import React, { useState, useEffect } from 'react';
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Button,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Alert
} from '@mui/material';
import SmartToyIcon from '@mui/icons-material/SmartToy';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CancelIcon from '@mui/icons-material/Cancel';

export interface ApprovalTicket {
  ticket_id: string;
  tenant_id: string;
  agent_id: string;
  target_bo_id: string;
  action_type: string;
  proposed_payload: any;
  compliance_validation_results: any;
  status: 'PENDING_CHECKER' | 'APPROVED' | 'REJECTED' | 'COMPLIANCE_FAILED';
  created_by_ai: boolean;
  checked_by?: string;
  checked_at?: string;
  created_at: string;
}

export const AgentApprovalInbox: React.FC = () => {
  const [tickets, setTickets] = useState<ApprovalTicket[]>([]);
  const [selectedTicket, setSelectedTicket] = useState<ApprovalTicket | null>(null);
  const [rejectReason, setRejectReason] = useState('');
  const [statusMsg, setStatusMsg] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const fetchTickets = async () => {
    try {
      const res = await fetch('/api/agentic/tickets');
      const data = await res.json();
      setTickets(data.tickets || []);
    } catch (err) {
      console.error('Failed to load agent tickets', err);
    }
  };

  useEffect(() => {
    fetchTickets();
  }, []);

  const handleReview = async (ticketId: string, decision: 'APPROVE' | 'REJECT') => {
    setLoading(true);
    try {
      const res = await fetch('/api/agentic/tickets/review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ticket_id: ticketId, decision, reason: rejectReason }),
      });
      if (res.ok) {
        setStatusMsg(`Ticket ${ticketId} successfully ${decision.toLowerCase()}d (Four-Eyes audit logged).`);
        setSelectedTicket(null);
        setRejectReason('');
        fetchTickets();
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <Paper sx={{ p: 3, bgcolor: '#1e293b', border: '1px solid #334155', color: '#f8fafc' }}>
      <Box display="flex" alignItems="center" gap={1.5} mb={2}>
        <SmartToyIcon sx={{ color: '#38bdf8', fontSize: 32 }} />
        <Typography variant="h5" fontWeight="700">
          Agentic Maker-Checker Approval Inbox (Four-Eyes Principle)
        </Typography>
      </Box>
      <Typography variant="body2" color="#94a3b8" mb={3}>
        Review and authorize operational actions generated by autonomous AI agents (bulk rebalancing, metadata overrides, schema extensions) before database execution.
      </Typography>

      {statusMsg && (
        <Alert severity="success" sx={{ mb: 2 }} onClose={() => setStatusMsg(null)}>
          {statusMsg}
        </Alert>
      )}

      <Table size="small">
        <TableHead sx={{ bgcolor: '#0f172a' }}>
          <TableRow>
            <TableCell sx={{ color: '#94a3b8' }}>Ticket ID</TableCell>
            <TableCell sx={{ color: '#94a3b8' }}>AI Agent</TableCell>
            <TableCell sx={{ color: '#94a3b8' }}>Target BO</TableCell>
            <TableCell sx={{ color: '#94a3b8' }}>Action Type</TableCell>
            <TableCell sx={{ color: '#94a3b8' }}>Status</TableCell>
            <TableCell sx={{ color: '#94a3b8' }}>Created</TableCell>
            <TableCell sx={{ color: '#94a3b8', textAlign: 'right' }}>Checker Action</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {tickets.map((t) => (
            <TableRow key={t.ticket_id}>
              <TableCell sx={{ color: '#38bdf8', fontWeight: 600 }}>{t.ticket_id}</TableCell>
              <TableCell sx={{ color: '#fff' }}>{t.agent_id}</TableCell>
              <TableCell sx={{ color: '#fff' }}>{t.target_bo_id}</TableCell>
              <TableCell sx={{ color: '#fff' }}>
                <Chip label={t.action_type} size="small" sx={{ bgcolor: '#0284c7', color: '#fff' }} />
              </TableCell>
              <TableCell>
                <Chip
                  label={t.status}
                  size="small"
                  color={t.status === 'PENDING_CHECKER' ? 'warning' : t.status === 'APPROVED' ? 'success' : 'error'}
                />
              </TableCell>
              <TableCell sx={{ color: '#94a3b8' }}>{new Date(t.created_at).toLocaleTimeString()}</TableCell>
              <TableCell align="right">
                {t.status === 'PENDING_CHECKER' ? (
                  <Box display="flex" justifyContent="flex-end" gap={1}>
                    <Button
                      variant="contained"
                      size="small"
                      startIcon={<CheckCircleIcon />}
                      onClick={() => handleReview(t.ticket_id, 'APPROVE')}
                      disabled={loading}
                      sx={{ bgcolor: '#16a34a', '&:hover': { bgcolor: '#15803d' } }}
                    >
                      Approve
                    </Button>
                    <Button
                      variant="outlined"
                      size="small"
                      color="error"
                      startIcon={<CancelIcon />}
                      onClick={() => setSelectedTicket(t)}
                      disabled={loading}
                    >
                      Reject
                    </Button>
                  </Box>
                ) : (
                  <Typography variant="caption" color="#94a3b8">
                    Reviewed by {t.checked_by || 'system'}
                  </Typography>
                )}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      {/* Reject Reason Dialog */}
      <Dialog open={!!selectedTicket} onClose={() => setSelectedTicket(null)} PaperProps={{ sx: { bgcolor: '#1e293b', color: '#fff' } }}>
        <DialogTitle>Reject AI Agent Proposal ({selectedTicket?.ticket_id})</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="#94a3b8" mb={2}>
            Provide an audit reason for rejecting this AI agent proposal. This will be logged in the immutable audit ledger.
          </Typography>
          <TextField
            label="Rejection Audit Reason"
            fullWidth
            multiline
            rows={3}
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
            sx={{ bgcolor: '#0f172a', input: { color: '#fff' }, textarea: { color: '#fff' } }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSelectedTicket(null)} sx={{ color: '#94a3b8' }}>
            Cancel
          </Button>
          <Button
            variant="contained"
            color="error"
            onClick={() => selectedTicket && handleReview(selectedTicket.ticket_id, 'REJECT')}
            disabled={!rejectReason || loading}
          >
            Confirm Rejection
          </Button>
        </DialogActions>
      </Dialog>
    </Paper>
  );
};
