#!/bin/bash

echo "📊 Generating Load Test Report"
echo "=============================="

RESULTS_DIR="k6/results"
mkdir -p "$RESULTS_DIR"

# Find latest test results
LATEST_LOAD_TEST=$(ls -t "$RESULTS_DIR"/load-test-*.json 2>/dev/null | head -1)
LATEST_RLS_TEST=$(ls -t "$RESULTS_DIR"/rls-test-*.json 2>/dev/null | head -1)

if [ -z "$LATEST_LOAD_TEST" ]; then
  echo "❌ No load test results found"
  exit 1
fi

# Generate summary
cat > "$RESULTS_DIR/test-summary.md" << EOF
# Load & RLS Stress Test Report

**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Test Configuration
- **Backend URL:** $BACKEND_URL
- **Test Duration:** $TEST_DURATION
- **Max VUs:** $VUS_MAX
- **Tenant Count:** $TENANT_COUNT

## Load Test Results

### Key Metrics
EOF

# Extract metrics from k6 JSON output
if command -v jq &> /dev/null; then
  cat "$LATEST_LOAD_TEST" | jq -r '
    select(.type == "Metric") |
    select(.data.name == "http_req_duration" or 
           .data.name == "errors" or 
           .data.name == "api_latency") |
    "\(.data.name): p(95)=\(.data.values[\"p(95)\"] | tostring)"
  ' >> "$RESULTS_DIR/test-summary.md"
fi

cat >> "$RESULTS_DIR/test-summary.md" << EOF

## RLS Validation Results

### Security Checks
EOF

if [ -n "$LATEST_RLS_TEST" ]; then
  cat "$LATEST_RLS_TEST" | jq -r '
    select(.type == "Metric") |
    select(.data.name == "rls_bypass_attempts" or 
           .data.name == "data_leak_detected") |
    "\(.data.name): rate=\(.data.values.rate | tostring)"
  ' >> "$RESULTS_DIR/test-summary.md"
fi

cat >> "$RESULTS_DIR/test-summary.md" << EOF

## Threshold Validation

| Threshold | Target | Actual | Status |
|-----------|--------|--------|--------|
| p95 Latency | <500ms | TBD | 🟡 |
| Error Rate | <1% | TBD | 🟡 |
| RLS Violations | 0% | TBD | 🟡 |
| Cache Hit Rate | >80% | TBD | 🟡 |

## Recommendations

- [ ] Review any RLS violations
- [ ] Optimize slow endpoints (p95 > 500ms)
- [ ] Increase cache TTL if hit rate < 80%
- [ ] Scale infrastructure if error rate > 1%

## Next Steps

1. Fix any RLS violations immediately (CRITICAL)
2. Optimize slow queries
3. Re-run tests after optimizations
4. Document baseline metrics

---
*Report generated by load testing automation*
EOF

echo "✅ Report generated: $RESULTS_DIR/test-summary.md"
echo ""
cat "$RESULTS_DIR/test-summary.md"
