package api

// ComplianceRegulatoryCalculationTemplates contains predefined templates for compliance and regulatory calculations
var ComplianceRegulatoryCalculationTemplates = []Template{
	// Banking/Basel III Category
	{
		NodeID:      "compliance_banking_lcr_calculation",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "banking_basel",
		Subcategory: "liquidity_risk",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Liquidity Coverage Ratio (LCR) under Basel III framework",
		Tags:        []string{"lcr", "basel_iii", "liquidity_risk", "regulatory"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                    "liquidity_coverage_ratio",
			HighQualityLiquidAssets: 500000000,
			NetCashOutflows:         400000000,
			RequiredLCR:             1.0,
		},
	},
	{
		NodeID:      "compliance_banking_nsfr_calculation",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "banking_basel",
		Subcategory: "funding_risk",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Net Stable Funding Ratio (NSFR) under Basel III framework",
		Tags:        []string{"nsfr", "basel_iii", "funding_risk", "regulatory"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                   "net_stable_funding_ratio",
			AvailableStableFunding: 800000000,
			RequiredStableFunding:  750000000,
			RequiredNSFR:           1.0,
		},
	},
	{
		NodeID:      "compliance_banking_leverage_ratio",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "banking_basel",
		Subcategory: "leverage_risk",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Leverage Ratio under Basel III supplementary framework",
		Tags:        []string{"leverage_ratio", "basel_iii", "capital_adequacy", "regulatory"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                  "leverage_ratio",
			Tier1Capital:          100000000,
			TotalExposures:        2000000000,
			RequiredLeverageRatio: 0.03,
		},
	},
	// Insurance/Solvency II Category
	{
		NodeID:      "compliance_insurance_scr_calculation",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "insurance_solvency",
		Subcategory: "solvency_capital",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Solvency Capital Requirement (SCR) under Solvency II framework",
		Tags:        []string{"scr", "solvency_ii", "capital_requirement", "regulatory"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:               "solvency_capital_requirement",
			MarketRiskSCR:      50000000,
			CreditRiskSCR:      20000000,
			OperationalRiskSCR: 15000000,
			InsuranceRiskSCR:   30000000,
			CorrelationMatrix: [][]float64{
				{1.0, 0.25, 0.15, 0.20},
				{0.25, 1.0, 0.10, 0.15},
				{0.15, 0.10, 1.0, 0.05},
				{0.20, 0.15, 0.05, 1.0},
			},
		},
	},
	{
		NodeID:      "compliance_insurance_mcr_calculation",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "insurance_solvency",
		Subcategory: "minimum_capital",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Minimum Capital Requirement (MCR) under Solvency II framework",
		Tags:        []string{"mcr", "solvency_ii", "minimum_capital", "regulatory"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                "minimum_capital_requirement",
			WrittenPremiums:     200000000,
			TechnicalProvisions: 180000000,
			MCRFloor:            0.025,
			MCRCap:              0.045,
		},
	},
	// AML/KYC Category
	{
		NodeID:      "compliance_aml_transaction_monitoring",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "aml_kyc",
		Subcategory: "transaction_monitoring",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Transaction Monitoring Risk Scores for AML compliance",
		Tags:        []string{"aml", "transaction_monitoring", "risk_scoring", "compliance"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                 "transaction_risk_scoring",
			TransactionAmount:    50000,
			TransactionFrequency: 15,
			CustomerRiskProfile:  "medium",
			GeographicRisk:       "low",
			ProductRisk:          "medium",
			RiskThresholds: map[string]float64{
				"low":    0.3,
				"medium": 0.6,
				"high":   0.8,
			},
		},
	},
	{
		NodeID:      "compliance_aml_customer_risk_rating",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "aml_kyc",
		Subcategory: "customer_risk",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Customer Risk Rating using weighted scoring methodology",
		Tags:        []string{"kyc", "customer_risk", "weighted_scoring", "compliance"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "customer_risk_rating",
			CustomerProfile: CustomerProfile{
				Jurisdiction:       "high_risk",
				CustomerType:       "individual",
				ProductType:        "investment_account",
				TransactionPattern: "frequent_large",
			},
			RiskWeights: map[string]float64{
				"jurisdiction":        0.3,
				"customer_type":       0.2,
				"product_type":        0.25,
				"transaction_pattern": 0.25,
			},
		},
	},
	// Market Conduct Category
	{
		NodeID:      "compliance_market_best_execution",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "market_conduct",
		Subcategory: "best_execution",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Best Execution Slippage analysis for market conduct compliance",
		Tags:        []string{"best_execution", "slippage", "market_conduct", "compliance"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:              "best_execution_slippage",
			ExecutionPrice:    100.50,
			BenchmarkPrice:    100.25,
			OrderSize:         10000,
			MarketVolatility:  0.02,
			SlippageThreshold: 0.005,
		},
	},
	{
		NodeID:      "compliance_market_trade_surveillance",
		NodeType:    "financial_calc",
		Domain:      "compliance_regulatory",
		Category:    "market_conduct",
		Subcategory: "trade_surveillance",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Trade Surveillance statistical alerts for unusual activity detection",
		Tags:        []string{"trade_surveillance", "statistical_alerts", "unusual_activity", "compliance"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:              "trade_surveillance_alerts",
			TradeVolume:       50000,
			AverageVolume:     25000,
			PriceMovement:     0.15,
			NormalPriceStdDev: 0.05,
			TimeWindow:        300, // seconds
			AlertThresholds: map[string]float64{
				"volume_spike":      2.0,
				"price_anomaly":     3.0,
				"frequency_anomaly": 5.0,
			},
		},
	},
}
