package api

// InsuranceCalculationTemplates contains predefined templates for insurance calculations
var InsuranceCalculationTemplates = []Template{
	// Underwriting Category
	{
		NodeID:      "insurance_loss_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "loss_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Measures the claims paid out by an insurer as a percentage of premiums earned.",
		Tags:        []string{"loss_ratio", "claims", "premiums"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(claim_amount)",
			Denominator: "SUM(premium_amount)",
		},
	},
	{
		NodeID:      "insurance_combined_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "combined_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Loss Ratio + Expense Ratio to measure underwriting profitability.",
		Tags:        []string{"combined_ratio", "loss_ratio", "expense_ratio"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "sum_of_ratios",
			Components: []RatioComponent{
				{Numerator: "SUM(claim_amount)", Denominator: "SUM(premium_amount)"},
				{Numerator: "SUM(expenses)", Denominator: "SUM(premium_amount)"},
			},
		},
	},
	{
		NodeID:      "insurance_reserve_adequacy",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "reserving",
		Subcategory: "reserve_adequacy",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Measures the sufficiency of funds set aside to pay for future claims.",
		Tags:        []string{"reserve", "adequacy"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(reserve_amount)",
			Denominator: "SUM(outstanding_claims)",
		},
	},
	{
		NodeID:      "insurance_expense_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "expense_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Operating expenses as a percentage of premiums earned.",
		Tags:        []string{"expenses", "premiums"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(expenses)",
			Denominator: "SUM(premium_amount)",
		},
	},
	{
		NodeID:      "insurance_operating_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "profitability",
		Subcategory: "operating_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Combined ratio adjusted for investment income.",
		Tags:        []string{"operating_ratio", "investment_income"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(claim_amount) + SUM(expenses) - SUM(investment_income)",
			Denominator: "SUM(premium_amount)",
		},
	},
	{
		NodeID:      "insurance_solvency_margin_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "solvency",
		Subcategory: "solvency_margin",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Available solvency margin / required solvency margin.",
		Tags:        []string{"solvency", "capital_adequacy"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(available_solvency_margin)",
			Denominator: "SUM(required_solvency_margin)",
		},
	},
	{
		NodeID:      "insurance_net_claims_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "net_claims_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Claims net of reinsurance as a percentage of net premiums.",
		Tags:        []string{"net_claims", "premiums"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(net_claims)",
			Denominator: "SUM(net_premiums)",
		},
	},
	{
		NodeID:      "insurance_reserve_development_ratio",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "reserving",
		Subcategory: "reserve_development",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Tracks how reserves evolve over time.",
		Tags:        []string{"reserve", "development"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(current_year_reserves)",
			Denominator: "SUM(prior_year_reserves)",
		},
	},
	{
		NodeID:      "insurance_loss_reserve_leverage",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "reserving",
		Subcategory: "reserve_leverage",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Loss reserves / policyholder surplus.",
		Tags:        []string{"reserve", "leverage"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(loss_reserves)",
			Denominator: "SUM(policyholder_surplus)",
		},
	},
	{
		NodeID:      "insurance_investment_yield",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "profitability",
		Subcategory: "investment_yield",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Investment income / invested assets.",
		Tags:        []string{"investment", "yield"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(investment_income)",
			Denominator: "SUM(invested_assets)",
		},
	},
	{
		NodeID:      "insurance_retention_rate",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "retention_rate",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Renewed policies / eligible renewals.",
		Tags:        []string{"retention", "renewals"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "COUNT(renewed_policies)",
			Denominator: "COUNT(eligible_renewals)",
		},
	},
	{
		NodeID:      "insurance_premium_growth_rate",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "profitability",
		Subcategory: "premium_growth",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Growth rate of premiums over prior period.",
		Tags:        []string{"premium", "growth"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "growth_rate",
			Numerator:   "SUM(current_premium_amount) - SUM(prior_premium_amount)",
			Denominator: "SUM(prior_premium_amount)",
		},
	},
	{
		NodeID:      "insurance_claim_frequency",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "claim_frequency",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Number of claims / number of policies.",
		Tags:        []string{"claims", "frequency"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "COUNT(claims)",
			Denominator: "COUNT(policies)",
		},
	},
	{
		NodeID:      "insurance_claim_severity",
		NodeType:    "calculation",
		Domain:      "insurance",
		Category:    "underwriting",
		Subcategory: "claim_severity",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Average cost per claim.",
		Tags:        []string{"claims", "severity"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(claim_amount)",
			Denominator: "COUNT(claims)",
		},
	},
}
