package api

// PrivateMarketsCalculationTemplates contains predefined templates for private markets calculations
var PrivateMarketsCalculationTemplates = []Template{
	// Performance Category
	{
		NodeID:      "private_markets_xirr",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "xirr",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Internal rate of return for irregular cash flows.",
		Tags:        []string{"xirr", "cash_flow", "time_weighted"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                "xirr",
			CashFlowsExpression: "ARRAY_AGG(cash_flow)",
			DatesExpression:     "ARRAY_AGG(transaction_date)",
		},
	},
	{
		NodeID:      "private_markets_irr",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "irr",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Discount rate that makes NPV = 0 for a series of cash flows.",
		Tags:        []string{"irr", "cash_flow"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                "irr",
			CashFlowsExpression: "ARRAY_AGG(cash_flow)",
		},
	},
	{
		NodeID:      "private_markets_tvpi",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "tvpi",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Total value to paid-in capital ratio (distributions + residual value).",
		Tags:        []string{"tvpi", "total_value"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(cumulative_distributions) + SUM(remaining_value)",
			Denominator: "SUM(paid_in_capital)",
		},
	},
	{
		NodeID:      "private_markets_rvpi",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "rvpi",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Residual value to paid-in capital ratio (unrealized NAV).",
		Tags:        []string{"rvpi", "residual_value"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(remaining_value)",
			Denominator: "SUM(paid_in_capital)",
		},
	},
	{
		NodeID:      "private_markets_pme",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "pme",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Public Market Equivalent vs benchmark index.",
		Tags:        []string{"pme", "benchmark"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                      "pme",
			CashFlowsExpression:       "ARRAY_AGG(cash_flow)",
			DatesExpression:           "ARRAY_AGG(transaction_date)",
			BenchmarkPricesExpression: "ARRAY_AGG(benchmark_price)",
		},
	},
	{
		NodeID:      "private_markets_pme_kaplan_schoar",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "pme_kaplan_schoar",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Kaplan–Schoar PME ratio (indexed distributions / indexed contributions).",
		Tags:        []string{"pme", "kaplan_schoar"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(distributions_indexed)",
			Denominator: "SUM(contributions_indexed)",
		},
	},
	{
		NodeID:      "private_markets_gross_irr",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "gross_irr",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Gross internal rate of return before fees and carry.",
		Tags:        []string{"gross_irr", "irr"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                "irr",
			CashFlowsExpression: "ARRAY_AGG(gross_cash_flow)",
		},
	},
	{
		NodeID:      "private_markets_net_irr",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "performance",
		Subcategory: "net_irr",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Net internal rate of return after fees and carry.",
		Tags:        []string{"net_irr", "irr"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:                "irr",
			CashFlowsExpression: "ARRAY_AGG(net_cash_flow)",
		},
	},

	// Multiples Category
	{
		NodeID:      "private_markets_moic",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "multiples",
		Subcategory: "moic",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Multiple of invested capital (total value returned / capital invested).",
		Tags:        []string{"moic", "multiple"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(total_distributions)",
			Denominator: "SUM(total_contributions)",
		},
	},
	{
		NodeID:      "private_markets_dpi",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "multiples",
		Subcategory: "dpi",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Distributed to Paid-In capital ratio.",
		Tags:        []string{"dpi", "distribution"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(cumulative_distributions)",
			Denominator: "SUM(paid_in_capital)",
		},
	},
	{
		NodeID:      "private_markets_equity_multiple",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "multiples",
		Subcategory: "equity_multiple",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Total value returned relative to equity invested.",
		Tags:        []string{"equity_multiple", "multiple"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(total_value)",
			Denominator: "SUM(equity_invested)",
		},
	},
	{
		NodeID:      "private_markets_gross_moic",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "multiples",
		Subcategory: "gross_moic",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Gross multiple of invested capital before fees.",
		Tags:        []string{"gross_moic", "multiple"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(gross_distributions) + SUM(remaining_value)",
			Denominator: "SUM(gross_contributions)",
		},
	},
	{
		NodeID:      "private_markets_net_moic",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "multiples",
		Subcategory: "net_moic",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Net multiple of invested capital after fees.",
		Tags:        []string{"net_moic", "multiple"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(net_distributions) + SUM(remaining_value)",
			Denominator: "SUM(net_contributions)",
		},
	},

	// Cash Flow Category
	{
		NodeID:      "private_markets_j_curve",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "cash_flow",
		Subcategory: "j_curve",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Cumulative net cash flow over time to visualize the J-curve effect.",
		Tags:        []string{"j_curve", "cumulative", "cash_flow"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:    "cumulative_sum",
			Series:  "net_cash_flow",
			OrderBy: "transaction_date",
		},
	},

	// Liquidity Category
	{
		NodeID:      "private_markets_capital_call_ratio",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "liquidity",
		Subcategory: "capital_call_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Capital called as a percentage of committed capital.",
		Tags:        []string{"capital_call", "liquidity"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(called_capital)",
			Denominator: "SUM(committed_capital)",
		},
	},
	{
		NodeID:      "private_markets_unfunded_commitment_ratio",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "liquidity",
		Subcategory: "unfunded_commitment_ratio",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Unfunded commitments relative to total committed capital.",
		Tags:        []string{"unfunded", "commitment", "liquidity"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "ratio",
			Numerator:   "SUM(unfunded_commitments)",
			Denominator: "SUM(committed_capital)",
		},
	},

	// Valuation Category
	{
		NodeID:      "private_markets_nav",
		NodeType:    "calculation",
		Domain:      "private_markets",
		Category:    "valuation",
		Subcategory: "nav",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Net asset value of portfolio holdings.",
		Tags:        []string{"nav", "valuation", "fair_value"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:       "sum",
			Expression: "current_fair_value",
		},
	},
}
