package api

// QuantFinanceCalculationTemplates contains predefined templates for quantitative finance calculations
var QuantFinanceCalculationTemplates = []Template{
	// Market Risk Category
	{
		NodeID:      "quant_market_var_historical",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "market_risk",
		Subcategory: "var_historical",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Historical simulation VaR at 99% confidence",
		Tags:        []string{"var", "historical", "risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:              "var_historical",
			ConfidenceLevel:   0.99,
			Returns:           []float64{-0.015, 0.002, -0.03, 0.01, -0.025},
			HoldingPeriodDays: 1,
		},
	},
	{
		NodeID:      "quant_market_var_parametric",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "market_risk",
		Subcategory: "var_parametric",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Variance-covariance VaR at 99% confidence",
		Tags:        []string{"var", "parametric", "risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:              "var_parametric",
			ConfidenceLevel:   0.99,
			AverageReturn:     0.001,
			StdDev:            0.02,
			HoldingPeriodDays: 1,
		},
	},
	{
		NodeID:      "quant_market_var_montecarlo",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "market_risk",
		Subcategory: "var_montecarlo",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Monte Carlo simulated VaR at 99% confidence",
		Tags:        []string{"var", "montecarlo", "risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:              "var_montecarlo",
			ConfidenceLevel:   0.99,
			NumSimulations:    100000,
			AverageReturn:     0.001,
			StdDev:            0.02,
			HoldingPeriodDays: 1,
		},
	},
	{
		NodeID:      "quant_market_cvar",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "market_risk",
		Subcategory: "cvar",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Conditional VaR at 99% confidence",
		Tags:        []string{"cvar", "tail_risk", "risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:            "cvar",
			ConfidenceLevel: 0.99,
			Returns:         []float64{-0.015, 0.002, -0.03, 0.01, -0.025},
		},
	},
	// Derivatives Pricing Category
	{
		NodeID:      "quant_derivatives_greeks",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "derivatives_pricing",
		Subcategory: "option_greeks",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Option Greeks for a European call",
		Tags:        []string{"options", "greeks", "risk_sensitivity"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:          "option_greeks",
			OptionType:    "call",
			S0:            []float64{100},
			StrikePrice:   105,
			TimeHorizon:   0.5,
			RiskFreeRate:  0.02,
			Volatilities:  []float64{0.25},
			DividendYield: 0.01,
		},
	},
	{
		NodeID:      "quant_pricing_black_scholes",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "derivatives_pricing",
		Subcategory: "black_scholes",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "European call option price via Black-Scholes",
		Tags:        []string{"options", "pricing", "black_scholes"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:          "black_scholes",
			OptionType:    "call",
			S0:            []float64{100},
			StrikePrice:   105,
			TimeHorizon:   0.5,
			RiskFreeRate:  0.02,
			Volatilities:  []float64{0.25},
			DividendYield: 0.01,
		},
	},
	{
		NodeID:      "quant_pricing_binomial",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "derivatives_pricing",
		Subcategory: "binomial",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "European call option price via binomial tree",
		Tags:        []string{"options", "pricing", "binomial"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:         "binomial_option",
			OptionType:   "call",
			S0:           []float64{100},
			StrikePrice:  105,
			TimeHorizon:  0.5,
			RiskFreeRate: 0.02,
			Volatilities: []float64{0.25},
			Steps:        100,
		},
	},
	{
		NodeID:      "quant_pricing_implied_vol",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "derivatives_pricing",
		Subcategory: "implied_volatility",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Implied volatility from market option price",
		Tags:        []string{"options", "implied_vol", "reverse_engineering"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:          "implied_volatility",
			OptionType:    "call",
			MarketPrice:   3.50,
			S0:            []float64{100},
			StrikePrice:   105,
			TimeHorizon:   0.5,
			RiskFreeRate:  0.02,
			DividendYield: 0.01,
		},
	},
	// Fixed Income Category
	{
		NodeID:      "quant_fixed_income_duration_convexity",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "fixed_income",
		Subcategory: "duration_convexity",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Macaulay duration, modified duration, and convexity",
		Tags:        []string{"bonds", "duration", "convexity"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "duration_convexity",
			CashFlows: []CashFlow{
				{Amount: 50, Period: 1},
				{Amount: 50, Period: 2},
				{Amount: 1050, Period: 3},
			},
			YieldToMaturity: 0.04,
			Frequency:       1,
		},
	},
	{
		NodeID:      "quant_fixed_income_yield_curve_bootstrap",
		NodeType:    "financial_calc",
		Domain:      "quant_finance",
		Category:    "fixed_income",
		Subcategory: "yield_curve_bootstrap",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Bootstraps spot rates from par yields to construct a zero-coupon yield curve",
		Tags:        []string{"yield_curve", "bootstrapping", "fixed_income"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "yield_curve_bootstrap",
			Instruments: []Instrument{
				{MaturityYears: 0.5, ParYield: 0.015},
				{MaturityYears: 1.0, ParYield: 0.017},
				{MaturityYears: 2.0, ParYield: 0.020},
				{MaturityYears: 3.0, ParYield: 0.022},
				{MaturityYears: 5.0, ParYield: 0.025},
			},
			Compounding: "semi_annual",
		},
	},
}
