package api

// RiskManagementCalculationTemplates contains predefined templates for risk management calculations
var RiskManagementCalculationTemplates = []Template{
	// Market Risk Category
	{
		NodeID:      "risk_market_stress_testing",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "market_risk",
		Subcategory: "stress_testing",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Scenario-based P&L impact analysis under stress conditions",
		Tags:        []string{"stress_testing", "scenario_analysis", "market_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "stress_testing",
			Scenarios: []Scenario{
				{Name: "Base Case", Shocks: map[string]float64{"equity": 0.0, "rates": 0.0}},
				{Name: "Equity Crash", Shocks: map[string]float64{"equity": -0.20, "rates": 0.01}},
				{Name: "Rate Shock", Shocks: map[string]float64{"equity": -0.05, "rates": 0.03}},
			},
			PortfolioValue: 1000000,
		},
	},
	{
		NodeID:      "risk_market_beta_coefficient",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "market_risk",
		Subcategory: "beta_analysis",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Beta coefficient measuring systematic risk relative to market",
		Tags:        []string{"beta", "systematic_risk", "market_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:         "beta_coefficient",
			AssetReturns: []float64{0.02, 0.015, 0.025, 0.01, 0.03},
			BenchReturns: []float64{0.015, 0.012, 0.02, 0.008, 0.025},
		},
	},
	{
		NodeID:      "risk_market_correlation_matrix",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "market_risk",
		Subcategory: "correlation_analysis",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Correlation matrix for portfolio risk diversification analysis",
		Tags:        []string{"correlation", "diversification", "market_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "correlation_matrix",
			AssetReturnsMatrix: [][]float64{
				{0.02, 0.015, 0.025},
				{0.015, 0.018, 0.022},
				{0.025, 0.022, 0.028},
			},
		},
	},
	// Credit Risk Category
	{
		NodeID:      "risk_credit_pd_calculation",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "credit_risk",
		Subcategory: "probability_of_default",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Probability of Default (PD) estimation using credit scoring",
		Tags:        []string{"pd", "credit_risk", "default_probability"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:        "probability_of_default",
			CreditScore: 650,
			PDModel:     "logistic_regression",
			RiskFactors: map[string]float64{
				"debt_to_income":     0.35,
				"credit_utilization": 0.45,
				"payment_history":    0.95,
			},
		},
	},
	{
		NodeID:      "risk_credit_lgd_calculation",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "credit_risk",
		Subcategory: "loss_given_default",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Loss Given Default (LGD) estimation for recovery analysis",
		Tags:        []string{"lgd", "credit_risk", "recovery_rate"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:            "loss_given_default",
			CollateralValue: 80000,
			ExposureAmount:  100000,
			RecoveryRate:    0.75,
			CollateralType:  "real_estate",
		},
	},
	{
		NodeID:      "risk_credit_ead_calculation",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "credit_risk",
		Subcategory: "exposure_at_default",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Exposure at Default (EAD) for credit risk measurement",
		Tags:        []string{"ead", "credit_risk", "exposure"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:              "exposure_at_default",
			CurrentExposure:   100000,
			CreditLimit:       150000,
			DrawnAmount:       80000,
			UndrawnCommitment: 20000,
		},
	},
	{
		NodeID:      "risk_credit_ecl_calculation",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "credit_risk",
		Subcategory: "expected_credit_loss",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Expected Credit Loss (ECL) under IFRS 9/CECL frameworks",
		Tags:        []string{"ecl", "ifrs9", "cecl", "credit_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:           "expected_credit_loss",
			PD:             0.02,
			LGD:            0.45,
			EAD:            100000,
			ExposurePeriod: 12,
		},
	},
	{
		NodeID:      "risk_credit_var_calculation",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "credit_risk",
		Subcategory: "credit_var",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Credit Value at Risk for portfolio credit loss distribution",
		Tags:        []string{"credit_var", "portfolio_risk", "credit_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type:            "credit_var",
			ConfidenceLevel: 0.99,
			NumSimulations:  10000,
			Exposures:       []float64{100000, 200000, 150000},
			PDs:             []float64{0.01, 0.02, 0.015},
			LGDs:            []float64{0.4, 0.5, 0.45},
		},
	},
	// Operational & Cyber Risk Category
	{
		NodeID:      "risk_operational_rcsa_scoring",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "operational_risk",
		Subcategory: "rcsa",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Risk Control Self-Assessment (RCSA) scoring methodology",
		Tags:        []string{"rcsa", "operational_risk", "risk_assessment"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "rcsa_scoring",
			RiskFactors: map[string]float64{
				"likelihood":            3.0,
				"impact":                4.0,
				"control_effectiveness": 2.5,
				"detectability":         3.5,
			},
			RiskCategory: "operational",
			BusinessUnit: "trading_desk",
		},
	},
	{
		NodeID:      "risk_operational_fair_quantification",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "operational_risk",
		Subcategory: "cyber_risk",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Factor Analysis of Information Risk (FAIR) cyber risk quantification",
		Tags:        []string{"fair", "cyber_risk", "quantitative_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "fair_quantification",
			PrimaryLossFactors: map[string]float64{
				"threat_event_frequency": 0.1,
				"vulnerability":          0.8,
				"primary_loss_magnitude": 500000,
			},
			SecondaryLossFactors: map[string]float64{
				"secondary_loss_frequency": 0.05,
				"secondary_loss_magnitude": 100000,
			},
		},
	},
	{
		NodeID:      "risk_operational_kri_monitoring",
		NodeType:    "financial_calc",
		Domain:      "risk_management",
		Category:    "operational_risk",
		Subcategory: "key_risk_indicators",
		Version:     "v1.0.0",
		Owner:       "patrick",
		Description: "Key Risk Indicators (KRIs) with threshold-based alerting",
		Tags:        []string{"kri", "monitoring", "thresholds", "operational_risk"},
		Governance: &Governance{
			Status: "draft",
		},
		Financial: FinancialCalc{
			Type: "kri_monitoring",
			KRIs: []KRI{
				{
					Name:      "Failed Transactions Rate",
					Value:     0.025,
					Threshold: 0.03,
					Severity:  "medium",
					Category:  "operational",
				},
				{
					Name:      "System Downtime Hours",
					Value:     2.5,
					Threshold: 4.0,
					Severity:  "high",
					Category:  "technology",
				},
			},
		},
	},
}
