package apistudio

import (
	"encoding/json"
	"fmt"
	"strings"
)

// GenerateTypeScriptSDK produces a TypeScript client for a set of API
// endpoints, generated from the same field/filter data GenerateOpenAPI uses
// so the two stay in sync.
//
// Auth: the runtime (APIRuntime.ServeHTTP) resolves env/tenant/roles from
// the caller's JWT via jwtmiddleware, not from request headers — so the
// generated client sends Authorization: Bearer <token>, not the X-Tenant-ID
// header the earlier version sent (which the runtime never read).
func GenerateTypeScriptSDK(env, tenantID string, endpoints []APIEndpoint) string {
	var sb strings.Builder

	sb.WriteString("/**\n")
	sb.WriteString(fmt.Sprintf(" * Governed API Client for %s (%s)\n", tenantID, env))
	sb.WriteString(" * Generated by API Studio — do not hand-edit, regenerate from /api-studio/sdk/typescript\n")
	sb.WriteString(" */\n\n")

	sb.WriteString("export class ApiClient {\n")
	sb.WriteString(fmt.Sprintf("  private baseUrl: string = %q;\n", APIRuntimeMountPrefixPlaceholder))
	sb.WriteString("  private token: string;\n\n")
	sb.WriteString("  constructor(token: string) {\n    this.token = token;\n  }\n\n")

	for _, ep := range endpoints {
		if ep.Type != "rest" {
			continue
		}

		fields := decodeStringList(ep.Fields)
		filterNames := decodeFilterNames(ep.Filters)

		funcName := operationID(ep)
		method := strings.ToUpper(ep.Method)

		responseType := "Record<string, any>"
		if len(fields) > 0 {
			var props []string
			for _, f := range fields {
				props = append(props, fmt.Sprintf("%s?: string", f))
			}
			responseType = fmt.Sprintf("{ %s }", strings.Join(props, "; "))
		}

		paramsType := "Record<string, string>"
		if len(filterNames) > 0 {
			var props []string
			for _, f := range filterNames {
				props = append(props, fmt.Sprintf("%s?: string", f))
			}
			paramsType = fmt.Sprintf("{ %s }", strings.Join(props, "; "))
		}

		sb.WriteString(fmt.Sprintf("  /**\n   * %s\n   * %s %s — Business Object: %s\n   */\n", ep.Name, method, ep.Path, ep.BOName))
		if method == "GET" {
			sb.WriteString(fmt.Sprintf("  async %s(params?: %s): Promise<%s[]> {\n", funcName, paramsType, responseType))
			sb.WriteString(fmt.Sprintf("    const url = `${this.baseUrl}%s`;\n", ep.Path))
			sb.WriteString("    const query = params ? '?' + new URLSearchParams(params as Record<string, string>) : '';\n")
			sb.WriteString("    const resp = await fetch(url + query, {\n")
			sb.WriteString("      method: 'GET',\n")
			sb.WriteString("      headers: { Authorization: `Bearer ${this.token}` }\n")
			sb.WriteString("    });\n")
			sb.WriteString("    if (!resp.ok) throw new Error(`API error ${resp.status}: ${await resp.text()}`);\n")
			sb.WriteString("    return resp.json();\n")
			sb.WriteString("  }\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("  async %s(body: Record<string, any>): Promise<%s[]> {\n", funcName, responseType))
			sb.WriteString(fmt.Sprintf("    const url = `${this.baseUrl}%s`;\n", ep.Path))
			sb.WriteString("    const resp = await fetch(url, {\n")
			sb.WriteString(fmt.Sprintf("      method: %q,\n", method))
			sb.WriteString("      headers: { Authorization: `Bearer ${this.token}`, 'Content-Type': 'application/json' },\n")
			sb.WriteString("      body: JSON.stringify(body)\n")
			sb.WriteString("    });\n")
			sb.WriteString("    if (!resp.ok) throw new Error(`API error ${resp.status}: ${await resp.text()}`);\n")
			sb.WriteString("    return resp.json();\n")
			sb.WriteString("  }\n\n")
		}
	}

	sb.WriteString("}\n")

	return sb.String()
}

// GeneratePythonSDK produces a Python client for a set of API endpoints,
// mirroring GenerateTypeScriptSDK's structure and auth model.
func GeneratePythonSDK(env, tenantID string, endpoints []APIEndpoint) string {
	var sb strings.Builder

	sb.WriteString("\"\"\"\n")
	sb.WriteString(fmt.Sprintf("Governed API Client for %s (%s)\n", tenantID, env))
	sb.WriteString("Generated by API Studio — do not hand-edit, regenerate from /api-studio/sdk/python\n")
	sb.WriteString("\"\"\"\n")
	sb.WriteString("import requests\n\n")
	sb.WriteString("class ApiClient:\n")
	sb.WriteString(fmt.Sprintf("    BASE_URL = %q\n\n", APIRuntimeMountPrefixPlaceholder))
	sb.WriteString("    def __init__(self, token: str):\n        self.token = token\n\n")
	sb.WriteString("    def _headers(self, json_body: bool = False) -> dict:\n")
	sb.WriteString("        headers = {\"Authorization\": f\"Bearer {self.token}\"}\n")
	sb.WriteString("        if json_body:\n            headers[\"Content-Type\"] = \"application/json\"\n")
	sb.WriteString("        return headers\n\n")

	for _, ep := range endpoints {
		if ep.Type != "rest" {
			continue
		}

		funcName := pythonMethodName(ep)
		method := strings.ToUpper(ep.Method)

		if method == "GET" {
			sb.WriteString(fmt.Sprintf("    def %s(self, params: dict | None = None) -> list[dict]:\n", funcName))
			sb.WriteString(fmt.Sprintf("        \"\"\"%s — GET %s over Business Object %s\"\"\"\n", ep.Name, ep.Path, ep.BOName))
			sb.WriteString(fmt.Sprintf("        resp = requests.get(self.BASE_URL + %q, params=params, headers=self._headers())\n", ep.Path))
			sb.WriteString("        resp.raise_for_status()\n")
			sb.WriteString("        return resp.json()\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("    def %s(self, body: dict) -> list[dict]:\n", funcName))
			sb.WriteString(fmt.Sprintf("        \"\"\"%s — %s %s over Business Object %s\"\"\"\n", ep.Name, method, ep.Path, ep.BOName))
			sb.WriteString(fmt.Sprintf("        resp = requests.request(%q, self.BASE_URL + %q, json=body, headers=self._headers(json_body=True))\n", method, ep.Path))
			sb.WriteString("        resp.raise_for_status()\n")
			sb.WriteString("        return resp.json()\n\n")
		}
	}

	return sb.String()
}

func decodeStringList(raw json.RawMessage) []string {
	var out []string
	_ = json.Unmarshal(raw, &out)
	return out
}

func decodeFilterNames(raw json.RawMessage) []string {
	var m map[string]interface{}
	if err := json.Unmarshal(raw, &m); err == nil {
		names := make([]string, 0, len(m))
		for k := range m {
			names = append(names, k)
		}
		return names
	}
	return decodeStringList(raw)
}

func pythonMethodName(ep APIEndpoint) string {
	name := strings.ToLower(strings.ReplaceAll(ep.Name, " ", "_"))
	return name
}
