package apistudio

import (
	"fmt"
	"strings"
	"github.com/hondyman/semlayer/libs/jwt-middleware"
)

// GenerateTypeScriptSDK produces a basic TypeScript client for a set of API endpoints
func GenerateTypeScriptSDK(env, tenantID string, endpoints []APIEndpoint) string {
	var sb strings.Builder

	sb.WriteString("/**\n")
	sb.WriteString(fmt.Sprintf(" * Governed API Client for %s (%s)\n", tenantID, env))
	sb.WriteString(" * Generated by API Studio\n")
	sb.WriteString(" */\n\n")

	sb.WriteString("export class ApiClient {\n")
	sb.WriteString("  private baseUrl: string = '/api/runtime';\n\n")

	for _, ep := range endpoints {
		if ep.Type != "rest" {
			continue
		}

		funcName := strings.ReplaceAll(ep.Name, " ", "")
		method := strings.ToLower(ep.Method)

		sb.WriteString(fmt.Sprintf("  /**\n   * %s\n   * Path: %s\n   */\n", ep.Name, ep.Path))
		sb.WriteString(fmt.Sprintf("  async %s(params?: any): Promise<any> {\n", funcName))
		sb.WriteString(fmt.Sprintf("    const url = `${this.baseUrl}%s`;\n", ep.Path))
		sb.WriteString("    const resp = await fetch(url + (params ? '?' + new URLSearchParams(params) : ''), {\n")
		sb.WriteString(fmt.Sprintf("      method: '%s',\n", strings.ToUpper(method)))
		sb.WriteString("      headers: { 'X-Env': 'production', 'X-Tenant-ID': '" + tenantID + "' }\n")
		sb.WriteString("    });\n")
		sb.WriteString("    return resp.json();\n")
		sb.WriteString("  }\n\n")
	}

	sb.WriteString("}\n")

	return sb.String()
}
