-- Generated by scripts/gen-tenant-ddl.py from the crims database. Do not edit by hand: change the
-- generator or regenerate. Schema only; no data. Row-level security is removed (see the generator).

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- Name: ref; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS ref;


--
