-- Generated by scripts/gen-tenant-ddl.py from the crims database. Do not edit by hand: change the
-- generator or regenerate. Schema only; no data. Row-level security is removed (see the generator).

-- Name: wlth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS wlth;


--
