-- Generated by scripts/gen-tenant-ddl.py from the crims database. Do not edit by hand: change the
-- generator or regenerate. Schema only; no data. Row-level security is removed (see the generator).

-- Name: cash_flow; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS cash_flow;


--

-- Name: settlement; Type: TABLE; Schema: cash_flow; Owner: -
--

CREATE TABLE cash_flow.settlement (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    account_id uuid NOT NULL,
    amount numeric(18,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    settlement_date date NOT NULL,
    settlement_status text DEFAULT 'SETTLED'::text NOT NULL,
    subtype_code text NOT NULL,
    ex_date date,
    record_date date,
    drip_reinvest_flag boolean,
    tax_withholding_amount numeric(18,2),
    coupon_period_start date,
    accrued_interest numeric(18,2),
    payment_frequency text,
    call_notice_id text,
    due_date date,
    management_fee_portion numeric(18,2),
    investment_portion numeric(18,2),
    return_of_capital numeric(18,2),
    preferred_return numeric(18,2),
    carried_interest_retained numeric(18,2),
    action_type_code text,
    cash_in_lieu_amount numeric(18,2),
    mandatory_flag boolean,
    fee_category text,
    invoice_reference_id text,
    vat_amount numeric(18,2),
    fund_order_id uuid,
    transaction_ref text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    valid_from timestamp with time zone DEFAULT now() NOT NULL,
    valid_to timestamp with time zone,
    CONSTRAINT ck_cash_flow_subtype CHECK ((subtype_code = ANY (ARRAY['dividend'::text, 'coupon_fixed_income'::text, 'capital_call'::text, 'lp_distribution'::text, 'corporate_action'::text, 'expense_fee'::text, 'dvp_securities'::text, 'free_of_payment'::text, 'fund_subscription'::text, 'fund_redemption'::text])))
);


--

-- Name: settlement settlement_pkey; Type: CONSTRAINT; Schema: cash_flow; Owner: -
--

ALTER TABLE ONLY cash_flow.settlement
    ADD CONSTRAINT settlement_pkey PRIMARY KEY (id);


--

-- Name: cash_flow_settlement_txn_ref_live; Type: INDEX; Schema: cash_flow; Owner: -
--

CREATE UNIQUE INDEX cash_flow_settlement_txn_ref_live ON cash_flow.settlement USING btree (tenant_id, transaction_ref) WHERE ((valid_to IS NULL) AND (transaction_ref IS NOT NULL));


--

-- Name: idx_cash_flow_settlement_account; Type: INDEX; Schema: cash_flow; Owner: -
--

CREATE INDEX idx_cash_flow_settlement_account ON cash_flow.settlement USING btree (tenant_id, account_id, settlement_date DESC) WHERE (valid_to IS NULL);


--

-- Name: idx_cash_flow_settlement_tenant; Type: INDEX; Schema: cash_flow; Owner: -
--

CREATE INDEX idx_cash_flow_settlement_tenant ON cash_flow.settlement USING btree (tenant_id, settlement_date DESC) WHERE (valid_to IS NULL);


--
