-- 003_seed_party_minimal.sql
-- Dev-only seed for crims.mdm.party + satellites (Option A 2026-09-23).
-- alpha.mdm.party is DROP'd; crims.mdm.party is the master extended with
-- alpha-only golden-record fields (see 002_crims_party_alter.sql).
-- Generated by gen_seed_party_minimal.py from information_schema so column
-- ordering stays in lockstep with the live schema.
-- Idempotent by id (uuid prefix aaaa9999-).

SET search_path = migration, crims, public;

BEGIN;

-- wipe prior seed
DELETE FROM crims.mdm.party_address WHERE party_id::text LIKE 'aaaa9999%';
DELETE FROM crims.mdm.party         WHERE id::text LIKE 'aaaa9999%';
DELETE FROM crims.mdm.xref          WHERE entity_type='party' AND entity_id::text LIKE 'aaaa9999%';

INSERT INTO crims.mdm.source_system
  (id, source_cd, name, system_type, vendor, connection_info, priority, is_active, custom_attributes, created_at, updated_at, tenant_id)
VALUES
  ('aaaa9999-9999-0000-0000-000000000099'::uuid,'SEED','seed_party_minimal.dev','SEED','uisce','{}'::jsonb,999,TRUE,'{"src":"seed_party_minimal"}'::jsonb,now(),now(),'99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid),
  ('aaaa9999-9999-0000-0000-00000000009a'::uuid,'SEED','seed_party_minimal.gold','SEED','uisce','{}'::jsonb,999,TRUE,'{"src":"seed_party_minimal"}'::jsonb,now(),now(),'00000000-0000-0000-0000-000000000001'::uuid)
ON CONFLICT (id) DO NOTHING;

-- ensure party_address exists (party satellite; the main copy handles full DDL later)
CREATE TABLE IF NOT EXISTS crims.mdm.party_address (
  id uuid PRIMARY KEY, party_id uuid NOT NULL, address_type varchar(30) NOT NULL,
  address_line_1 varchar(255), address_line_2 varchar(255), address_line_3 varchar(255),
  city varchar(100), state_province varchar(100), postal_code varchar(20), country_cd varchar(2),
  is_primary boolean NOT NULL DEFAULT false, is_verified boolean NOT NULL DEFAULT false,
  verified_at timestamptz, verified_method varchar(30),
  effective_from date NOT NULL DEFAULT CURRENT_DATE, effective_to date,
  is_current boolean NOT NULL DEFAULT true,
  custom_attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  tenant_id uuid NOT NULL);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='party_address_party_fkey') THEN
    ALTER TABLE crims.mdm.party_address
      ADD CONSTRAINT party_address_party_fkey FOREIGN KEY (party_id) REFERENCES crims.mdm.party(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_party_address_party ON crims.mdm.party_address (party_id);
CREATE INDEX IF NOT EXISTS idx_party_address_tenant ON crims.mdm.party_address (tenant_id);

INSERT INTO crims.mdm.party (id, party_cd, legal_name, party_type, segment, tax_id, domicile, custom_attributes, created_at, updated_at, tenant_id, client_group_id, client_since_date, country_of_risk_cd, date_of_birth, date_of_death, dq_score, giin, golden_record_id, incorporation_date, incorporation_jurisdiction, is_deceased, is_financial_institution, is_golden_record, is_individual, is_legal_entity, is_pep, is_regulated, is_restricted, is_sanctioned, is_us_person, last_reviewed_at, legal_form, lei, lifecycle_stage, merged_into_id, parent_party_id, party_sub_type, primary_currency, primary_nationality_cd, primary_residence_country_cd, primary_segment_id, primary_tax_country_cd, registration_number, relationship_end_date, relationship_manager_id, review_frequency_months, servicing_team_id, source_system_id, status, steward_id, ultimate_parent_party_id, valid_from, valid_to)
VALUES
('aaaa9999-0000-0000-0000-000000000001', 'IND-0001', 'Jane T. Doe', 'INDIVIDUAL', 'RETAIL', NULL, 'US', '{"src":"seed_party_minimal","comment":"dev individual"}'::jsonb, now(), now(), '99e99e99-99e9-49e9-89e9-99e99e99e999', NULL, '2024-01-01', 'US', NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, 'OPEN', NULL, NULL, 'HNI', 'USD', 'US', 'US', NULL, 'US', NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', NULL, NULL, '2024-01-01', NULL),
('aaaa9999-0000-0000-0000-000000000002', 'LEG-0001', 'Acme Capital LLC', 'LEGAL_ENTITY', 'INSTITUTIONAL', '12-3456789', 'US', '{"src":"seed_party_minimal","comment":"dev legal"}'::jsonb, now(), now(), '99e99e99-99e9-49e9-89e9-99e99e99e999', 'aaaa9999-0000-0000-0000-000000000007', '2024-01-15', 'US', NULL, NULL, NULL, NULL, NULL, '2000-06-15', 'DE', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, NULL, 'LIMITED_LIABILITY_CO', '549300ACMEUSCAPTLL', 'OPERATING', NULL, NULL, 'LIMITED_LIABILITY', 'USD', 'US', 'US', NULL, 'US', '123456789', NULL, NULL, 12, NULL, NULL, 'ACTIVE', NULL, 'aaaa9999-0000-0000-0000-000000000008', '2024-01-01', NULL),
('aaaa9999-0000-0000-0000-000000000003', 'FND-0001', 'Beta Holdings Trust', 'FUND', 'INSTITUTIONAL_FUND', '98-7654321', 'IE', '{"src":"seed_party_minimal","comment":"dev fund"}'::jsonb, now(), now(), '99e99e99-99e9-49e9-89e9-99e99e99e999', NULL, '2024-02-01', 'IE', NULL, NULL, NULL, NULL, NULL, '2010-03-22', 'IE', FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, NULL, 'UNIT_TRUST', '549300BETAHOLDIE', 'OPEN', NULL, NULL, 'INVESTMENT_FUND', 'EUR', 'IE', 'IE', NULL, 'IE', 'FUND-REG-001', NULL, NULL, 12, NULL, NULL, 'ACTIVE', NULL, NULL, '2024-02-01', NULL),
('aaaa9999-0000-0000-0000-000000000004', 'FI-0001', 'Gamma Securities Bank', 'FIN_INSTITUTION', 'BANK', '11-2233445', 'GB', '{"src":"seed_party_minimal","comment":"dev FI"}'::jsonb, now(), now(), '99e99e99-99e9-49e9-89e9-99e99e99e999', NULL, '2024-02-15', 'GB', NULL, NULL, NULL, NULL, NULL, '1985-11-30', 'GB', FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, NULL, 'PLC', '549300GAMMASEGB', 'OPEN', NULL, NULL, 'CORP', 'GBP', 'GB', 'GB', NULL, 'GB', 'FI-BANK-001', NULL, NULL, 12, NULL, NULL, 'ACTIVE', NULL, NULL, '2024-02-15', NULL),
('aaaa9999-0000-0000-0000-000000000005', 'PEP-0001', 'Hon. Quinton X. Politicus', 'INDIVIDUAL', 'RETAIL_PEP', NULL, 'KY', '{"src":"seed_party_minimal","comment":"dev PEP"}'::jsonb, now(), now(), '99e99e99-99e9-49e9-89e9-99e99e99e999', NULL, '2024-03-01', 'KY', '1965-04-12', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, 'OPEN', NULL, NULL, 'PEP', 'USD', 'KY', 'KY', NULL, 'KY', NULL, NULL, NULL, 6, NULL, NULL, 'ACTIVE', NULL, NULL, '2024-03-01', NULL),
('aaaa9999-0000-0000-0000-000000000006', 'SAN-0001', 'Doe Holdings S.A.', 'LEGAL_ENTITY', 'COMPLIANCE_TEST', '99-9999999', 'VG', '{"src":"seed_party_minimal","comment":"compliance test"}'::jsonb, now(), now(), '00000000-0000-0000-0000-000000000001', NULL, '2024-03-15', 'VG', NULL, NULL, 85.5, NULL, NULL, '2015-07-04', 'VG', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, NULL, 'CORPORATE', '549300DOEHOLDBVI', 'FROZEN', NULL, NULL, 'CORP', 'USD', 'VG', 'VG', NULL, 'VG', 'SAN-001', NULL, NULL, 12, NULL, NULL, 'RESTRICTED', NULL, NULL, '2024-03-15', NULL),
('aaaa9999-0000-0000-0000-000000000007', 'GRP-0001', 'Doe Family Office', 'CLIENT_GROUP', 'WEALTH_GROUP', NULL, 'US', '{"src":"seed_party_minimal","comment":"client_group anchor"}'::jsonb, now(), now(), '99e99e99-99e9-49e9-89e9-99e99e99e999', NULL, '2024-04-01', 'US', NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, 'OPEN', NULL, NULL, 'FAMILY_OFFICE', 'USD', 'US', 'US', NULL, 'US', NULL, NULL, NULL, 12, NULL, NULL, 'ACTIVE', NULL, NULL, '2024-04-01', NULL),
('aaaa9999-0000-0000-0000-000000000008', 'PAR-0001', 'Apex Holdings Global S.A.', 'ULTIMATE_PARENT', 'ULTIMATE_PARENT', NULL, 'LU', '{"src":"seed_party_minimal","comment":"ultimate parent"}'::jsonb, now(), now(), '00000000-0000-0000-0000-000000000001', NULL, '2024-04-15', 'LU', NULL, NULL, NULL, NULL, NULL, '1970-01-01', 'LU', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, NULL, 'SA', '549300APEXHOLDGLLU', 'OPERATING', NULL, NULL, 'SA', 'EUR', 'LU', 'LU', NULL, 'LU', 'PARENT-001', NULL, NULL, 12, NULL, NULL, 'ACTIVE', NULL, NULL, '2024-04-15', NULL)
ON CONFLICT (id) DO NOTHING;

-- xref rows linking each party to its id (entity_type='party')
INSERT INTO crims.mdm.xref
  (id, entity_type, entity_id, source_system_id, external_id, external_type,
   is_primary, valid_from, valid_to, custom_attributes, created_at, updated_at, tenant_id)
SELECT
  ('aaaa9999-1111-0000-0000-00000000' || lpad(row_number() OVER ()::text, 4, '0'))::uuid,
  'party', p.id,
  (SELECT id FROM crims.mdm.source_system WHERE source_cd='SEED' AND tenant_id=p.tenant_id LIMIT 1),
  p.party_cd, 'INTERNAL', TRUE,
  p.valid_from::timestamptz, p.valid_to, '{"src":"seed_party_minimal"}'::jsonb,
  now(), now(), p.tenant_id
FROM crims.mdm.party p WHERE p.id::text LIKE 'aaaa9999%';

-- minimal party_address (one per party)
INSERT INTO crims.mdm.party_address
  (id, tenant_id, party_id, address_type,
   address_line_1, city, country_cd, postal_code,
   is_primary, is_verified, is_current, effective_from, custom_attributes)
SELECT
  ('aaaa9999-2222-0000-0000-00000000' || lpad(row_number() OVER ()::text, 4, '0'))::uuid,
  p.tenant_id, p.id, 'BUSINESS',
  '1 Seed Street', 'Seedville', p.domicile, '00000',
  TRUE, FALSE, TRUE, CURRENT_DATE, '{"src":"seed_party_minimal"}'::jsonb
FROM crims.mdm.party p WHERE p.id::text LIKE 'aaaa9999%';

-- row #7 golden_record_id = self (client_group anchor)
UPDATE crims.mdm.party SET golden_record_id=id WHERE id='aaaa9999-0000-0000-0000-000000000007'::uuid;

-- mark migration.progress(party) done
DO $$
DECLARE pid bigint;
BEGIN
  SELECT id INTO pid FROM migration.plan WHERE source_schema='mdm' AND source_table='party';
  IF pid IS NOT NULL THEN
    INSERT INTO migration.progress (plan_id, status, rows_copied, started_at, finished_at, detail)
      VALUES (pid, 'done', 8, now(), now(), 'seed_party_minimal: 8 parties + 8 xref + 8 addresses')
    ON CONFLICT (plan_id) DO UPDATE SET status='done', rows_copied=8, finished_at=now(), detail=EXCLUDED.detail;
  END IF;
END $$;

COMMIT;

-- QA:
-- SELECT count(*) FROM crims.mdm.party         WHERE id::text LIKE 'aaaa9999%'; -- 8
-- SELECT count(*) FROM crims.mdm.party_address WHERE party_id::text LIKE 'aaaa9999%'; -- 8
-- SELECT count(*) FROM crims.mdm.xref          WHERE entity_type='party' AND entity_id::text LIKE 'aaaa9999%'; -- 8
