-- 005_fk_recreate.sql — Step 3b: re-add same-home FKs in crims.
-- Auto-generated by gen_fk_recreate.py. Idempotent: skips existing constraints.
-- DROP actions are intentionally absent (cross-DB / parent-gone FKs are
-- enforced by app logic + RLS, per FABRIC_FK_DROPPED blocker resolution).

DO $$
DECLARE r record; n int := 0;
BEGIN
  FOR r IN SELECT child_schema, child_table, fk_name, ddl FROM migration.fk_actions WHERE action='RECREATE' ORDER BY child_schema, child_table, fk_name
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace s ON s.oid = t.relnamespace
       WHERE c.conname = r.fk_name
         AND s.nspname = r.child_schema
         AND t.relname = r.child_table
         AND c.contype = 'f'
    ) THEN
      EXECUTE r.ddl; n := n + 1;
    END IF;
  END LOOP;
  RAISE NOTICE 'fk_recreate: % constraints added', n;
END $$;
