apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uisce.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uisce.labels" . | nindent 4 }}
{{/*
TODO: Wire up Infisical service account annotations when using Infisical Operator:
annotations:
  infisical.com/service-account: "true"
*/}}
