CREATE SCHEMA IF NOT EXISTS sml;

CREATE TABLE IF NOT EXISTS sml.abbreviation_lookup (
    id SERIAL PRIMARY KEY,
    abbreviation VARCHAR(50) NOT NULL UNIQUE,
    full_word TEXT NOT NULL,
    notes TEXT
);

INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes) VALUES
('abs', 'Asset-Backed Security', 'A financial security collateralized by a pool of assets.'),
('acct', 'Account', ''),
('accrd', 'Accrued', 'Accumulated or received but not yet paid or settled.'),
('act', 'Actual', ''),
('adj', 'Adjusted', ''),
('adp', 'Adapter / Automatic Data Processing', 'Could refer to a system adapter or the company ADP.'),
('adr', 'American Depositary Receipt', ''),
('agg', 'Aggregate', ''),
('alt', 'Alternate / Alternative', ''),
('amt', 'Amount', ''),
('amrtz', 'Amortize', ''),
('amrtzd', 'Amortized', ''),
('aum', 'Assets Under Management', ''),
('avg', 'Average', ''),
('bal', 'Balance', ''),
('bb', 'Bloomberg', 'A common financial data provider.'),
('bkr', 'Broker', ''),
('bps', 'Basis Points', '1/100th of a percentage point (0.01%).'),
('bus', 'Business', ''),
('bval', 'Bloomberg Valuation', 'Bloomberg''s pricing service.'),
('calc', 'Calculate / Calculation', ''),
('cap', 'Capital / Capitalization', ''),
('cd', 'Code', 'A very common suffix for columns that hold a category or type identifier.'),
('cds', 'Credit Default Swap', ''),
('chg', 'Change', ''),
('cnvrt', 'Convert / Convertible', ''),
('cnvx', 'Convexity', ''),
('collat', 'Collateral', ''),
('comp', 'Composite / Company', ''),
('cond', 'Condition', ''),
('corp', 'Corporate', ''),
('cpn', 'Coupon', ''),
('cpr', 'Conditional Prepayment Rate', ''),
('crrncy', 'Currency', ''),
('ctd', 'Cheapest to Deliver', ''),
('cust', 'Customer / Custodian', ''),
('cv', 'Convertible', ''),
('def', 'Default', ''),
('desc', 'Description', ''),
('dil', 'Diluted', ''),
('disc', 'Discount', ''),
('dist', 'Distribution', ''),
('div', 'Dividend', ''),
('doc', 'Document', ''),
('dom', 'Domicile', ''),
('dt', 'Date', ''),
('dur', 'Duration', ''),
('ebitda', 'Earnings Before Interest, Taxes, Depreciation, and Amortization', ''),
('eff', 'Effective', ''),
('eod', 'End of Day', ''),
('eom', 'End of Month', ''),
('eps', 'Earnings Per Share', ''),
('eq', 'Equity', ''),
('eqy', 'Equity', ''),
('esg', 'Environmental, Social, and Governance', ''),
('etf', 'Exchange-Traded Fund', ''),
('ev', 'Enterprise Value', ''),
('exch', 'Exchange', ''),
('exec', 'Execution', ''),
('exp', 'Expiration / Expense', ''),
('ext', 'Extension', ''),
('fd', 'From Date / Fund', 'Often paired with `td` (To Date) for date ranges.'),
('fi', 'Fixed Income', ''),
('figi', 'Financial Instrument Global Identifier', ''),
('fld', 'Field', ''),
('flt', 'Floating', 'As in a floating interest rate.'),
('freq', 'Frequency', ''),
('fwd', 'Forward', ''),
('fx', 'Foreign Exchange', ''),
('gl', 'General Ledger', ''),
('gldgr', 'General Ledger', ''),
('grp', 'Group', ''),
('gvt', 'Government', ''),
('hist', 'Historic / Historical', ''),
('id', 'Identifier', ''),
('idx', 'Index', ''),
('indx', 'Index', ''),
('inc', 'Income', ''),
('ind', 'Indicator', 'Typically a boolean (true/false) or flag (Y/N) column.'),
('int', 'Interest', ''),
('intvl', 'Interval', ''),
('inv', 'Investment / Inventory', ''),
('ipo', 'Initial Public Offering', ''),
('iss', 'Issuer', ''),
('isin', 'International Securities Identification Number', ''),
('krd', 'Key Rate Duration', ''),
('leg', 'Legal', ''),
('lei', 'Legal Entity Identifier', ''),
('liq', 'Liquidity', ''),
('ln', 'Loan', ''),
('loc', 'Local', ''),
('lsn', 'Log Sequence Number', 'Common in database replication.'),
('lt', 'Long Term', ''),
('ltd', 'Life to Date', ''),
('m', 'Month', ''),
('marg', 'Margin', ''),
('mat', 'Maturity', ''),
('max', 'Maximum', ''),
('mdfd', 'Modified', ''),
('mgmt', 'Management', ''),
('mid', 'Middle', 'The midpoint price between bid and ask.'),
('min', 'Minimum', ''),
('mkt', 'Market', ''),
('mod', 'Modified', ''),
('mort', 'Mortgage', ''),
('mtg', 'Mortgage', ''),
('mtd', 'Month to Date', ''),
('mtm', 'Mark to Market', ''),
('muni', 'Municipal', ''),
('nav', 'Net Asset Value', ''),
('net', 'Net', 'An amount after deductions.'),
('notl', 'Notional', ''),
('notnl', 'Notional', ''),
('num', 'Number', ''),
('nxt', 'Next', ''),
('oas', 'Option-Adjusted Spread', ''),
('oid', 'Object Identifier / Original Issue Discount', ''),
('oper', 'Operator', ''),
('opt', 'Option', ''),
('optn', 'Option', ''),
('orig', 'Original', ''),
('otc', 'Over-the-Counter', ''),
('outst', 'Outstanding', ''),
('pct', 'Percent', ''),
('perf', 'Performance', ''),
('phys', 'Physical', ''),
('pid', 'Process Identifier', ''),
('pos', 'Position', ''),
('prc', 'Price', ''),
('px', 'Price', ''),
('prev', 'Previous', ''),
('prin', 'Principal', ''),
('proc', 'Process / Procedure', ''),
('prod', 'Product', ''),
('proj', 'Projected', ''),
('prvdr', 'Provider', ''),
('pub', 'Publication', ''),
('pv', 'Present Value', ''),
('qty', 'Quantity', ''),
('qtd', 'Quarter to Date', ''),
('rcvry', 'Recovery', ''),
('recvd', 'Received', ''),
('ref', 'Reference', ''),
('reg', 'Regulation / Registered', ''),
('rel', 'Relative / Relation', ''),
('repo', 'Repurchase Agreement', ''),
('req', 'Required / Request', ''),
('ret', 'Return', ''),
('rgn', 'Region', ''),
('runno', 'Run Number', 'Identifier for a specific data processing job or batch run.'),
('sched', 'Schedule', ''),
('sec', 'Security / Second', ''),
('serv', 'Service', ''),
('sht', 'Short', ''),
('src', 'Source', ''),
('st', 'Short Term', ''),
('std', 'Standard', ''),
('strat', 'Strategy', ''),
('sub', 'Subsidiary / Subscription', ''),
('sys', 'System', ''),
('syst', 'System', ''),
('tca', 'Transaction Cost Analysis', ''),
('td', 'To Date', 'Often paired with `fd` (From Date).'),
('temp', 'Temporary', ''),
('term', 'Terminal / Term', ''),
('tot', 'Total', ''),
('trd', 'Trade', ''),
('txn', 'Transaction', ''),
('typ', 'Type', ''),
('udf', 'User-Defined Field', ''),
('ugl', 'Unrealized Gain/Loss', ''),
('ult', 'Ultimate', ''),
('upd', 'Update', ''),
('usr', 'User', ''),
('val', 'Value / Valuation', ''),
('var', 'Value at Risk / Variable', ''),
('vid', 'Version Identifier', ''),
('vol', 'Volume', ''),
('vwap', 'Volume-Weighted Average Price', ''),
('wac', 'Weighted Average Coupon', ''),
('wal', 'Write-Ahead Log / Weighted Average Life', ''),
('wam', 'Weighted Average Maturity', ''),
('wh', 'Warehouse', ''),
('wht', 'Withholding Tax', ''),
('wtd', 'Week to Date', ''),
('y', 'Year', ''),
('yr', 'Year', ''),
('yld', 'Yield', ''),
('ytd', 'Year to Date', ''),
('ytm', 'Yield to Maturity', ''),
('ytw', 'Yield to Worst', '');