-- Insert Part 3: Master Financial Services Abbreviations (150+ new items)
-- These abbreviations are drawn from real schemas across custody, trading, fund accounting, wealth, banking, payments, risk, and regulatory systems
-- Target: sml.abbreviation_lookup table

INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes) VALUES
-- Asset & Security Terms
('ABS', 'Asset Backed Security', 'Structured products backed by underlying assets'),
('ACCT_BAL', 'Account Balance', 'Current balance in banking or custody accounts'),
('ACCT_CLS', 'Account Class', 'Classification/segmentation of account types'),
('ADJ_NAV', 'Adjusted NAV', 'Net asset value adjusted for specific factors'),
('ADV', 'Advisory', 'Advisory fees and wealth advisory services'),
('AFFL', 'Affiliate', 'Entity relationships and affiliations'),
('AGG_RT', 'Aggregate Rate', 'Combined interest or fee rates'),
('AI', 'Accrued Interest', 'Interest accrued on fixed income securities'),
('ALT', 'Alternative', 'Alternative asset class (alts)'),
('ANN_RT', 'Annual Rate', 'Interest or return expressed as annual rate'),
('AP', 'Accounts Payable', 'Accounting - money owed to suppliers'),
('AR', 'Accounts Receivable', 'Accounting - money owed by customers'),
('ARR', 'Annual Recurring Revenue', 'SaaS finance metric for recurring revenue'),
('ASK', 'Ask Price', 'Market data - price at which seller offers security'),
('ATM', 'At The Money', 'Options terminology - strike price equals current price'),
('AUTH_CD', 'Authorization Code', 'Code for payment and ACH authorization'),
('AVG_COST', 'Average Cost', 'Tax lots - average cost basis calculation'),

-- Balance & Cash Flow
('BAL_FWD', 'Balance Forward', 'Statements - opening balance carried forward'),
('BBG', 'Bloomberg', 'Market data vendor identifier'),
('BBG_ID', 'Bloomberg Identifier', 'Security identifier in Bloomberg system'),
('BD', 'Business Day', 'Settlement term - business day convention'),
('BDRY', 'Boundary', 'Risk limits and boundary conditions'),
('BEN', 'Beneficiary', 'Trusts and account beneficiary designation'),
('BK_FEE', 'Bank Fee', 'Banking fees and charges'),
('BLK', 'Block', 'Block trades in securities'),
('BNF', 'Benefit', 'Insurance and retirement benefits'),
('BRCH', 'Branch', 'Bank branch locations'),
('BSKT', 'Basket', 'ETF creation/redemption baskets'),
('BTCH', 'Batch', 'Operations - batch processing'),

-- Calculation & Dates
('CALC_DT', 'Calculation Date', 'Valuation and calculation date'),
('CAP_EX', 'Capital Expenditure', 'Corporate finance - capital spending'),
('CAP_IN', 'Capital Inflow', 'Fund flows - money flowing in'),
('CAP_OUT', 'Capital Outflow', 'Fund flows - money flowing out'),
('CB', 'Central Bank', 'Macro data - central bank references'),
('CC', 'Cost Center', 'Accounting - cost center allocation'),
('CDS', 'Credit Default Swap', 'Derivatives - credit risk instrument'),
('CHG', 'Charge', 'Fees and charges'),
('CL', 'Closing Price', 'Market data - end of day price'),
('CLS_DT', 'Close Date', 'Account and loan close date'),
('CMNT', 'Comment', 'CRM and notes field'),
('CNF', 'Confirmation', 'Trade confirmations'),
('CNTR', 'Counterparty', 'Trading - counterparty identification'),
('CNTR_ID', 'Counterparty Identifier', 'KYC - counterparty identifier'),
('COLL', 'Collateral', 'Margin and repo collateral'),
('COMM_RT', 'Commission Rate', 'Trading fees and commission rates'),
('COMP_ID', 'Company Identifier', 'Legal entities identifier'),
('CONV', 'Conversion', 'FX and unit conversion'),
('CORP_ID', 'Corporate Identifier', 'Entity master data identifier'),
('CPN', 'Coupon', 'Fixed income - bond coupon'),
('CPN_RT', 'Coupon Rate', 'Bond terms and coupon rate'),
('CRV', 'Curve', 'Yield curve analysis'),
('CS', 'Common Stock', 'Equity asset class'),
('CTRY_CD', 'Country Code', 'ISO country codes'),
('CTRB', 'Contribution', 'Performance attribution calculations'),
('CUSTODY_ID', 'Custody Identifier', 'Custodian mapping identifier'),
('CV', 'Current Value', 'Position and valuation current value'),

-- Daily Operations
('D2D', 'Day To Day', 'Operational daily functions'),
('DBT', 'Debit', 'Banking debit transactions'),
('DCF', 'Discounted Cash Flow', 'Valuation - discounted cash flow method'),
('DD', 'Due Diligence', 'Compliance - due diligence process'),
('DDR', 'Data Record', 'ETL data record'),
('DEF', 'Deferred', 'Tax and revenue deferral'),
('DELV', 'Delivery', 'Settlement and delivery logistics'),
('DEP', 'Deposit', 'Banking deposits'),
('DERIV', 'Derivative', 'Trading - derivative instruments'),
('DISC_RT', 'Discount Rate', 'DCF discount rate calculation'),
('DLVRY_DT', 'Delivery Date', 'Settlement - delivery date'),
('DM', 'Data Management', 'Governance - data management'),
('DLY', 'Daily', 'Pricing and daily updates'),
('DNM', 'Denomination', 'Bond denomination and par value'),
('DPST', 'Deposit', 'Banking deposits (variant)'),
('DRVD', 'Derived', 'Computed and derived fields'),
('DSCLSR', 'Disclosure', 'Regulatory disclosure requirements'),
('DST', 'Distribution', 'Fund distributions and payouts'),
('DTL', 'Detail', 'Reporting detail level'),
('DUR_ADJ', 'Duration Adjusted', 'Risk - duration adjusted returns'),
('DV01', 'Dollar Value of 01', 'Fixed income risk metric - price change per basis point'),

-- Exchange & Economic
('ECN', 'Electronic Communication Network', 'Trading venues - ECN'),
('ED', 'Effective Duration', 'Fixed income risk duration'),
('EFF_YLD', 'Effective Yield', 'Bond yield metric'),
('ELIG_DT', 'Eligibility Date', 'Compliance eligibility dates'),
('ENT', 'Entity', 'Legal entity reference'),
('ENT_ID', 'Entity Identifier', 'Master data entity identifier'),
('EQ_WGT', 'Equal Weight', 'Portfolio model equal weighting'),
('EST_VAL', 'Estimated Value', 'NAV and pricing estimated values'),
('EVT', 'Event', 'Corporate actions and events'),
('EXC', 'Exchange', 'Market venues and exchanges'),
('EXC_CD', 'Exchange Code', 'MIC - market identifier code'),
('EXG', 'Exposure Group', 'Risk exposure grouping'),
('EXP_RT', 'Expense Rate', 'Fund expense ratios'),

-- Factors & Funds
('FCTR', 'Factor', 'Risk models and factor exposures'),
('FD', 'Fund', 'Fund accounting entity'),
('FD_ID', 'Fund Identifier', 'Fund master data identifier'),
('FEE_CD', 'Fee Code', 'Billing fee code'),
('FFO', 'Funds From Operations', 'REIT financial metric'),
('FIN_ID', 'Financial Identifier', 'Cross-system financial identifier'),
('FLT', 'Float', 'Interest rate floaters'),
('FND_FLW', 'Fund Flow', 'Inflows and outflows tracking'),
('FRCST', 'Forecast', 'Planning forecasts'),
('FRGN', 'Foreign', 'FX and foreign exposure'),
('FX_RT', 'FX Rate', 'Currency conversion rates'),

-- Goods to Glossary
('GDS', 'Goods', 'Commerce goods identifier'),
('GICS', 'Global Industry Classification Standard', 'Sector classification standard'),
('GLOSS', 'Glossary', 'Metadata glossary terms'),
('GRP', 'Group', 'Classification groupings'),
('GS', 'Government Security', 'Treasuries and government debt'),
('HAIR_RT', 'Haircut Rate', 'Collateral haircut percentage'),
('HEDG', 'Hedge', 'Risk management hedges'),
('HIST_DT', 'Historical Date', 'Time series historical dates'),
('HOLD_ID', 'Holding Identifier', 'Position holding identifier'),
('HRZN', 'Horizon', 'Risk and planning horizons'),

-- Index to Issuance
('IDX', 'Index', 'Benchmark indexes'),
('IDX_RT', 'Index Return', 'Index performance returns'),
('IMP_RT', 'Implied Rate', 'Options implied rates'),
('INC', 'Income', 'Performance and accounting income'),
('INIT', 'Initial', 'Initial margin and opening balances'),
('INST', 'Instrument', 'Security instrument master'),
('INV_ID', 'Investment Identifier', 'Portfolio system investment identifier'),
('INV_RT', 'Investment Return', 'Investment returns calculation'),
('IRR_ADJ', 'IRR Adjusted', 'Performance IRR adjusted returns'),
('ISDA', 'International Swaps and Derivatives Association', 'Legal documentation standard'),
('ISS_ID', 'Issuer Identifier', 'Security master issuer identifier'),
('ITM', 'In The Money', 'Options terminology - profitable position'),

-- Journal to KYC
('JRN', 'Journal', 'Accounting journal entries'),
('JRN_ID', 'Journal Identifier', 'Ledger journal identifier'),
('KPI', 'Key Performance Indicator', 'Business metrics and KPIs'),
('KYC', 'Know Your Customer', 'Compliance KYC procedures'),

-- Local to Liquid
('LCL', 'Local', 'Local currency and regional'),
('LCL_CCY', 'Local Currency', 'FX - local currency basis'),
('LIQ_RT', 'Liquidity Ratio', 'Risk liquidity ratios'),
('LMTD', 'Limited', 'Legal entity - limited liability'),
('LN', 'Loan', 'Banking loan products'),
('LN_ID', 'Loan Identifier', 'Loan system identifier'),
('LOC', 'Letter of Credit', 'Trade finance - letters of credit'),
('LTM', 'Last Twelve Months', 'Financial analysis LTM metrics'),
('LVL', 'Level', 'Pricing level tiers'),
('LVL1', 'Fair Value Level 1', 'ASC 820 - quoted prices'),
('LVL2', 'Fair Value Level 2', 'ASC 820 - observable inputs'),
('LVL3', 'Fair Value Level 3', 'ASC 820 - unobservable inputs'),

-- Market Cap to Margin
('MCAP', 'Market Capitalization', 'Equity market capitalization'),
('MGN_RT', 'Margin Rate', 'Trading and collateral margin rates'),

-- Additional Variants (Part 2 continuation)
('ADJ', 'Adjusted', 'Pricing and performance adjustments'),
('ADJ_PX', 'Adjusted Price', 'Price adjustments for splits/dividends'),
('AGG', 'Aggregate', 'Rollups and aggregate analytics'),
('ALLOC', 'Allocation', 'Portfolio models and sleeve accounting'),
('APPR', 'Approval', 'Workflow approval status'),
('ASOF', 'As Of Date', 'Backdated valuations'),
('AUTH', 'Authorization', 'Payments and ACH authorization'),
('BKNG', 'Booking', 'Trade booking entry'),
('BRKR', 'Broker', 'Custody and execution brokers'),
('CAP_GN', 'Capital Gain', 'Tax reporting capital gains'),
('CAP_LS', 'Capital Loss', 'Tax reporting capital losses'),
('CF', 'Cash Flow', 'Performance and planning cash flows'),
('CLRD', 'Cleared', 'Post-trade lifecycle cleared status'),
('CNCL', 'Cancel', 'Trade corrections and cancellation'),
('CRNCY', 'Currency', 'Currency variant of CCY'),
('CUST_ID', 'Custodian Identifier', 'Custody platform identifiers'),
('CVRD', 'Covered', 'Options covered positions and tax lots'),
('DISC', 'Discount', 'Bond discount pricing'),
('DIST', 'Distribution', 'Fund payouts and distributions'),
('DIV', 'Dividend', 'Equity income dividend'),
('DLR', 'Dollar', 'Currency shorthand dollar'),
('DUR', 'Duration', 'Fixed income risk duration'),
('EFF_RT', 'Effective Rate', 'Interest and credit effective rates'),
('ELIG', 'Eligible', 'Compliance eligibility status'),
('EQ', 'Equity', 'Asset class equity'),
('EST', 'Estimated', 'NAV and accruals estimated'),
('EX_DT', 'Ex Date', 'Dividend and corporate action ex-date'),
('EXP_DT', 'Expiration Date', 'Options and contracts expiration'),
('FAC', 'Factor', 'Risk models and factor analysis'),
('FEE_RT', 'Fee Rate', 'Advisory fee rates'),
('FIN', 'Financial', 'General finance field'),
('FRQ', 'Frequency', 'Interest and payout frequency'),
('GL', 'General Ledger', 'Accounting general ledger'),
('GL_ACCT', 'General Ledger Account', 'Chart of accounts'),
('GRS', 'Gross', 'Performance and fee gross amounts'),
('HAIRCUT', 'Collateral Haircut', 'Margin and repo haircut'),
('HIST', 'Historical', 'Time series historical data'),
('IMP', 'Implied', 'Options implied volatility'),
('INT', 'Interest', 'Income and accruals interest'),
('INTRADAY', 'Intra Day', 'Intraday market data'),
('IRR', 'Internal Rate of Return', 'Performance IRR metric'),
('ISS_DT', 'Issue Date', 'Bond and security issue dates'),
('LIQ', 'Liquidation', 'Position liquidation tracking'),
('LT', 'Long Term', 'Tax lots and long-term holdings'),
('MGN', 'Margin', 'Trading and collateral margin'),
('MIN_BAL', 'Minimum Balance', 'Banking compliance minimums'),
('MTM', 'Mark to Market', 'Daily valuation MTM'),
('NTNL', 'Notional', 'Derivatives notional amounts'),
('OBL', 'Obligation', 'Contracts and debt obligations'),
('OPT', 'Option', 'Derivatives option contracts'),
('ORIG', 'Original', 'Loan origination and cost basis'),
('OTH', 'Other', 'Miscellaneous categories'),
('PNL', 'Profit and Loss', 'Trading and performance PnL'),
('PRNCPL', 'Principal', 'Loans and bond principal'),
('PRV', 'Previous', 'Time series previous period'),
('RCNCL', 'Reconcile', 'Operations and accounting reconciliation'),
('REC', 'Received', 'Cash movement received'),
('REF_ID', 'Reference Identifier', 'Cross-system mapping reference'),
('REG', 'Regulatory', 'Regulatory compliance'),
('REPO', 'Repurchase Agreement', 'Repo financing arrangements'),
('REV', 'Revenue', 'Fees and accounting revenue'),
('RT', 'Rate', 'Interest and fee rates'),
('SCHD', 'Schedule', 'Payment schedules and reporting'),
('SHRT', 'Short', 'Short positions and tax lots'),
('SPRD', 'Spread', 'Fixed income and trading spreads'),
('STL', 'Settle', 'Trade settlement processing'),
('STL_DT', 'Settlement Date', 'T+1/T+2 settlement dates'),
('STRK', 'Strike', 'Options strike price'),
('SUBJ', 'Subject', 'CRM and note subjects'),
('SUPPL', 'Supplemental', 'Additional supplemental data'),
('TAX_RT', 'Tax Rate', 'Tax reporting rates'),
('TM', 'Time', 'Timestamp fields'),
('TOT_RT', 'Total Return', 'Performance total return'),
('TRD', 'Trade', 'Trading core entity'),
('TRD_DT', 'Trade Date', 'T-date trade lifecycle'),
('UNRLZD', 'Unrealized', 'Gains/losses unrealized'),
('VOL', 'Volatility', 'Options and risk volatility'),
('WDRWL', 'Withdrawal', 'Cash movement withdrawals')
ON CONFLICT (abbreviation) DO UPDATE SET 
  full_word = EXCLUDED.full_word,
  notes = EXCLUDED.notes;

-- Verification
SELECT COUNT(*) as total_abbreviations_after FROM sml.abbreviation_lookup;

-- Show newly added abbreviations (sample)
SELECT abbreviation, full_word, notes 
FROM sml.abbreviation_lookup 
WHERE abbreviation IN ('ABS', 'ACCT_BAL', 'ADJ_NAV', 'CDS', 'DV01', 'KYC', 'LVL1', 'LVL2', 'LVL3', 'NTNL')
ORDER BY abbreviation;
