-- Insert additional financial abbreviations into sml.abbreviation_lookup
-- This script adds comprehensive financial abbreviations organized by category

-- General Investing & Market Terms
INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes) VALUES
('AUM', 'Assets Under Management', 'Total value of assets managed by an investment firm'),
('BEP', 'Break-Even Point', 'Point where revenues equal costs'),
('BLUE CHIP', 'High-quality, low-risk stocks of large, well-established companies.', 'Premium stocks from reputable companies'),
('B/S', 'Balance Sheet', 'Financial statement showing assets, liabilities, and equity'),
('CFP', 'Certified Financial Planner', 'Professional certification for financial planning'),
('CFA', 'Chartered Financial Analyst', 'Professional certification for investment analysis'),
('CPA', 'Certified Public Accountant', 'Professional certification for accounting'),
('DCF', 'Discounted Cash Flow', 'Valuation method using future cash flows'),
('DPS', 'Dividend Per Share', 'Dividend amount per outstanding share'),
('EBIT', 'Earnings Before Interest and Taxes', 'Profit measure excluding interest and taxes'),
('EBITA', 'Earnings Before Interest, Taxes, and Amortization', 'Profit measure excluding interest, taxes, and amortization'),
('EBITDA', 'Earnings Before Interest, Taxes, Depreciation, and Amortization', 'Profit measure excluding interest, taxes, depreciation, and amortization'),
('EPS', 'Earnings Per Share', 'Company profit divided by outstanding shares'),
('ETF', 'Exchange-Traded Fund', 'Investment fund traded on stock exchanges'),
('ETN', 'Exchange-Traded Note', 'Unsecured debt security traded on exchanges'),
('FCF', 'Free Cash Flow', 'Cash available after capital expenditures'),
('FIFO', 'First In, First Out', 'Inventory valuation method'),
('FINOP', 'Financial and Operations Principal', 'Senior financial operations role'),
('FP&A', 'Financial Planning & Analysis', 'Department handling financial planning and analysis'),
('FV', 'Future Value', 'Value of investment at future date'),
('FX', 'Foreign Exchange', 'Currency trading and exchange rates'),
('FY', 'Fiscal Year', '12-month accounting period'),
('GDP', 'Gross Domestic Product', 'Total value of goods and services produced'),
('GDR', 'Global Depositary Receipt', 'Bank certificate representing shares in foreign company'),
('GTC', 'Good ''Til Canceled', 'Order type that remains active until executed or canceled'),
('HELOC', 'Home Equity Line of Credit', 'Revolving credit secured by home equity'),
('HSA', 'Health Savings Account', 'Tax-advantaged savings account for medical expenses'),
('IPO', 'Initial Public Offering', 'First sale of stock by private company to public'),
('IRA', 'Individual Retirement Account', 'Tax-advantaged retirement savings account'),
('LBO', 'Leveraged Buyout', 'Acquisition using significant debt financing'),
('LLC', 'Limited Liability Company', 'Business structure offering liability protection'),
('LTV', 'Loan-to-Value Ratio', 'Ratio of loan amount to property value'),
('MTM', 'Mark-to-Market', 'Valuation method using current market prices'),
('NAV', 'Net Asset Value', 'Value of fund assets minus liabilities'),
('NOPAT', 'Net Operating Profit After Tax', 'Profit after operating expenses and taxes'),
('NPV', 'Net Present Value', 'Present value of future cash flows minus initial investment'),
('OBA', 'Outside Business Activity', 'Business activities outside primary employment'),
('OTC', 'Over-the-Counter', 'Trading securities directly between parties'),
('P&L', 'Profit and Loss Statement', 'Financial statement showing revenues and expenses'),
('P/E', 'Price-to-Earnings Ratio', 'Stock valuation metric'),
('PEG', 'Price/Earnings-to-Growth Ratio', 'Stock valuation metric including growth'),
('PIPE', 'Private Investment in Public Equity', 'Private investment in publicly traded company'),
('POP', 'Public Offering Price', 'Price at which securities are offered to public'),
('PV', 'Present Value', 'Current value of future cash flows'),
('QoQ', 'Quarter-over-Quarter', 'Comparison between consecutive quarters'),
('QTD', 'Quarter-to-Date', 'Period from start of quarter to current date'),
('REIT', 'Real Estate Investment Trust', 'Company owning and operating income-generating real estate'),
('ROA', 'Return on Assets', 'Profitability ratio measuring asset efficiency'),
('ROE', 'Return on Equity', 'Profitability ratio measuring equity efficiency'),
('ROI', 'Return on Investment', 'Measure of investment profitability'),
('RMD', 'Required Minimum Distribution', 'Mandatory withdrawal from retirement accounts'),
('TBA', 'To Be Announced', 'Mortgage-backed securities trading system'),
('TNAV', 'Tangible Net Asset Value', 'Net asset value excluding intangible assets'),
('TOD', 'Transfer-on-Death', 'Beneficiary designation for accounts'),
('UMA', 'Unified Managed Account', 'Consolidated investment account'),
('WAM', 'Weighted Average Maturity', 'Average time to maturity weighted by value'),
('YTD', 'Year-to-Date', 'Period from start of year to current date'),

-- Equity & Stock Trading
('ADR', 'American Depositary Receipt', 'Certificate representing shares in foreign company'),
('AMT', 'Alternative Minimum Tax', 'Parallel tax system ensuring minimum tax payment'),
('BDC', 'Business Development Company', 'Company providing financing to small businesses'),
('BOM', 'Branch Office Manager', 'Manager overseeing branch office operations'),
('DMM', 'Designated Market Maker', 'Market maker providing liquidity in specific stocks'),
('ESPP', 'Employee Stock Purchase Plan', 'Program allowing employees to buy company stock'),
('ESOP', 'Employee Stock Ownership Plan', 'Retirement plan investing primarily in company stock'),
('FOK', 'Fill-or-Kill (order type)', 'Order that must be executed immediately or canceled'),
('IOC', 'Immediate-or-Cancel (order type)', 'Order executed immediately with any unfilled portion canceled'),
('ISO', 'Incentive Stock Option', 'Stock option with tax advantages'),
('LTCG', 'Long-Term Capital Gain', 'Profit from selling asset held over one year'),
('NBBO', 'National Best Bid and Offer', 'Best available bid and ask prices across exchanges'),
('NQSO', 'Non-Qualified Stock Option', 'Stock option without special tax treatment'),
('OSJ', 'Office of Supervisory Jurisdiction', 'FINRA office overseeing broker-dealers'),
('QIB', 'Qualified Institutional Buyer', 'Institutional investor meeting SEC requirements'),
('RIA', 'Registered Investment Advisor', 'Investment advisor registered with SEC'),
('RSU', 'Restricted Stock Unit', 'Compensation in form of company stock'),
('SIE', 'Securities Industry Essentials (exam)', 'Entry-level securities licensing exam'),

-- Fixed Income (Bonds)
('CDO', 'Collateralized Debt Obligation', 'Structured finance product backed by debt'),
('CLO', 'Collateralized Loan Obligation', 'CDO backed by leveraged loans'),
('CMO', 'Collateralized Mortgage Obligation', 'Mortgage-backed security with tranches'),
('FRN', 'Floating Rate Note', 'Bond with variable interest rate'),
('GO', 'General Obligation (bond)', 'Municipal bond backed by taxing power'),
('GSE', 'Government-Sponsored Enterprise (e.g., Fannie Mae, Freddie Mac)', 'Government-chartered financial services corporation'),
('LIBOR', 'London Interbank Offered Rate', 'Benchmark interest rate for dollar-denominated loans'),
('OID', 'Original Issue Discount', 'Bond sold below face value'),
('REMIC', 'Real Estate Mortgage Investment Conduit', 'Entity issuing mortgage-backed securities'),
('SOFR', 'Secured Overnight Financing Rate', 'Benchmark interest rate replacing LIBOR'),
('TIPS', 'Treasury Inflation-Protected Securities', 'Treasury securities adjusted for inflation'),

-- Derivatives (Options & Futures)
('CDSC', 'Contingent Deferred Sales Charge', 'Fee charged when mutual fund shares are sold'),
('CCP', 'Central Clearing Counterparty', 'Entity guaranteeing derivative trades'),
('CLOB', 'Centralized Limit Order Book', 'Electronic order book for trading'),
('CSA', 'Credit Support Annex', 'ISDA agreement governing collateral'),
('DCO', 'Derivatives Clearing Organization', 'Organization clearing derivative trades'),
('EFP', 'Exchange for Physicals', 'Transaction exchanging futures for physical commodity'),
('FCM', 'Futures Commission Merchant', 'Firm accepting orders for futures trading'),
('FRA', 'Forward Rate Agreement', 'Contract fixing interest rate for future period'),
('ISDA', 'International Swaps and Derivatives Association', 'Industry group for derivatives'),
('LEI', 'Legal Entity Identifier', 'Unique identifier for legal entities'),
('LSOC', 'Legally Segregated, Operationally Commingled', 'Regulatory structure for clearing'),
('SDR', 'Swaps Data Repository', 'Repository for OTC derivatives data'),

-- Regulatory & Compliance
('AML', 'Anti-Money Laundering', 'Regulations preventing money laundering'),
('BSA', 'Bank Secrecy Act', 'US law requiring financial institutions to report suspicious activities'),
('CFPB', 'Consumer Financial Protection Bureau', 'US agency protecting consumers in financial markets'),
('CFTC', 'Commodity Futures Trading Commission', 'US regulator of derivatives markets'),
('FASB', 'Financial Accounting Standards Board', 'Private organization setting accounting standards'),
('FATCA', 'Foreign Account Tax Compliance Act', 'US law requiring reporting of foreign assets'),
('FDIC', 'Federal Deposit Insurance Corporation', 'US agency insuring bank deposits'),
('FinCEN', 'Financial Crimes Enforcement Network', 'US bureau combating financial crime'),
('FINRA', 'Financial Industry Regulatory Authority', 'Self-regulatory organization for securities'),
('FSB', 'Financial Stability Board', 'International body promoting financial stability'),
('GAAP', 'Generally Accepted Accounting Principles', 'US accounting standards'),
('IASB', 'International Accounting Standards Board', 'International accounting standards setter'),
('IFRS', 'International Financial Reporting Standards', 'Global accounting standards'),
('IRS', 'Internal Revenue Service', 'US tax collection agency'),
('MiFID', 'Markets in Financial Instruments Directive', 'EU financial markets regulation'),
('NFA', 'National Futures Association', 'Self-regulatory organization for futures'),
('OCC', 'Office of the Comptroller of the Currency', 'US regulator of national banks'),
('OFAC', 'Office of Foreign Assets Control', 'US agency enforcing economic sanctions'),
('SAR', 'Suspicious Activity Report', 'Report of potentially suspicious financial activity'),
('SEC', 'Securities and Exchange Commission', 'US regulator of securities markets')

ON CONFLICT (abbreviation)
DO UPDATE SET
    full_word = EXCLUDED.full_word,
    notes = EXCLUDED.notes;

-- Verify the insertions
SELECT COUNT(*) as total_abbreviations FROM sml.abbreviation_lookup;
SELECT abbreviation, full_word FROM sml.abbreviation_lookup ORDER BY abbreviation LIMIT 10;