// Package builder provides CUE code generation from UI rule definitions
package builder

import (
	"fmt"
	"strings"
)

// UIRule represents a rule as defined in the visual builder UI
type UIRule struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Conditions  []Condition `json:"conditions"`
	Logic       string      `json:"logic"`  // "AND" or "OR"
	Action      string      `json:"action"` // "REJECT", "FLAG_FOR_REVIEW", "APPROVE", "LOG"
	Severity    string      `json:"severity"`
}

// Condition represents a single condition in the rule
type Condition struct {
	Field    string      `json:"field"`
	Operator string      `json:"operator"`
	Value    interface{} `json:"value"`
}

// CUEGenerationResult contains the generated CUE code and validation info
type CUEGenerationResult struct {
	CUECode string   `json:"cue_code"`
	Valid   bool     `json:"valid"`
	Errors  []string `json:"errors"`
}

// GenerateCUE converts a UIRule to valid CUE syntax
func GenerateCUE(rule UIRule) (*CUEGenerationResult, error) {
	if rule.Name == "" {
		return &CUEGenerationResult{
			Valid:  false,
			Errors: []string{"Rule name is required"},
		}, nil
	}

	// Sanitize rule name for CUE identifier
	safeName := sanitizeIdentifier(rule.Name)

	var sb strings.Builder

	// Write header comment
	sb.WriteString(fmt.Sprintf("// Auto-generated rule: %s\n", rule.Name))
	if rule.Description != "" {
		sb.WriteString(fmt.Sprintf("// Description: %s\n", rule.Description))
	}
	sb.WriteString(fmt.Sprintf("// Generated by Uisce Visual Builder\n\n"))

	// Start rule definition
	sb.WriteString(fmt.Sprintf("#%s: {\n", safeName))

	// Write the validation logic
	if len(rule.Conditions) > 0 {
		sb.WriteString("\t// Validation conditions\n")

		logic := strings.ToLower(rule.Logic)
		if logic == "" {
			logic = "and"
		}

		if logic == "and" {
			// All conditions must pass
			for i, cond := range rule.Conditions {
				cueExpr := conditionToCUE(cond)
				if i == 0 {
					sb.WriteString(fmt.Sprintf("\t_valid_%d: %s\n", i, cueExpr))
				} else {
					sb.WriteString(fmt.Sprintf("\t_valid_%d: %s\n", i, cueExpr))
				}
			}
			sb.WriteString("\n")
			sb.WriteString("\t// All conditions must be true\n")
			validRefs := make([]string, len(rule.Conditions))
			for i := range rule.Conditions {
				validRefs[i] = fmt.Sprintf("_valid_%d", i)
			}
			sb.WriteString(fmt.Sprintf("\t_all_valid: %s\n", strings.Join(validRefs, " & ")))
		} else {
			// Any condition passes
			for i, cond := range rule.Conditions {
				cueExpr := conditionToCUE(cond)
				sb.WriteString(fmt.Sprintf("\t_valid_%d: %s\n", i, cueExpr))
			}
			sb.WriteString("\n")
			sb.WriteString("\t// Any condition must be true\n")
			validRefs := make([]string, len(rule.Conditions))
			for i := range rule.Conditions {
				validRefs[i] = fmt.Sprintf("_valid_%d", i)
			}
			sb.WriteString(fmt.Sprintf("\t_any_valid: %s\n", strings.Join(validRefs, " | ")))
		}
	}

	sb.WriteString("\n")

	// Write action
	action := strings.ToUpper(rule.Action)
	if action == "" {
		action = "REJECT"
	}

	switch action {
	case "REJECT":
		sb.WriteString("\t// Rejection action\n")
		if rule.Logic == "AND" || rule.Logic == "" {
			sb.WriteString("\tif !_all_valid {\n")
		} else {
			sb.WriteString("\tif !_any_valid {\n")
		}
		sb.WriteString(fmt.Sprintf("\t\t_reject: true\n"))
		sb.WriteString(fmt.Sprintf("\t\t_reason: \"Violated rule: %s\"\n", rule.Name))
		sb.WriteString(fmt.Sprintf("\t\t_severity: \"%s\"\n", strings.ToLower(rule.Severity)))
		sb.WriteString("\t}\n")

	case "FLAG_FOR_REVIEW":
		sb.WriteString("\t// Flag for review action\n")
		if rule.Logic == "AND" || rule.Logic == "" {
			sb.WriteString("\tif !_all_valid {\n")
		} else {
			sb.WriteString("\tif !_any_valid {\n")
		}
		sb.WriteString("\t\t_flag_review: true\n")
		sb.WriteString(fmt.Sprintf("\t\t_reason: \"Review required: %s\"\n", rule.Name))
		sb.WriteString("\t}\n")

	case "APPROVE":
		sb.WriteString("\t// Auto-approve action\n")
		if rule.Logic == "AND" || rule.Logic == "" {
			sb.WriteString("\tif _all_valid {\n")
		} else {
			sb.WriteString("\tif _any_valid {\n")
		}
		sb.WriteString("\t\t_approved: true\n")
		sb.WriteString("\t}\n")

	case "LOG":
		sb.WriteString("\t// Logging action\n")
		if rule.Logic == "AND" || rule.Logic == "" {
			sb.WriteString("\tif !_all_valid {\n")
		} else {
			sb.WriteString("\tif !_any_valid {\n")
		}
		sb.WriteString(fmt.Sprintf("\t\t_log_message: \"Rule triggered: %s\"\n", rule.Name))
		sb.WriteString("\t}\n")
	}

	sb.WriteString("}\n")

	return &CUEGenerationResult{
		CUECode: sb.String(),
		Valid:   true,
		Errors:  []string{},
	}, nil
}

// conditionToCUE converts a single condition to CUE expression
func conditionToCUE(cond Condition) string {
	field := cond.Field
	op := cond.Operator
	value := cond.Value

	// Format value based on type
	var valueStr string
	switch v := value.(type) {
	case string:
		valueStr = fmt.Sprintf("\"%s\"", v)
	case float64:
		if v == float64(int(v)) {
			valueStr = fmt.Sprintf("%d", int(v))
		} else {
			valueStr = fmt.Sprintf("%f", v)
		}
	case int:
		valueStr = fmt.Sprintf("%d", v)
	case bool:
		valueStr = fmt.Sprintf("%t", v)
	case []interface{}:
		// Array for IN operator
		items := make([]string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				items[i] = fmt.Sprintf("\"%s\"", s)
			} else {
				items[i] = fmt.Sprintf("%v", item)
			}
		}
		valueStr = fmt.Sprintf("[%s]", strings.Join(items, ", "))
	default:
		valueStr = fmt.Sprintf("%v", v)
	}

	// Map operators to CUE syntax
	switch op {
	case ">", "<", ">=", "<=", "==", "!=":
		return fmt.Sprintf("%s %s %s", field, op, valueStr)
	case "IN":
		return fmt.Sprintf("list.Contains(%s, %s)", valueStr, field)
	case "NOT_IN":
		return fmt.Sprintf("!list.Contains(%s, %s)", valueStr, field)
	case "contains":
		return fmt.Sprintf("strings.Contains(%s, %s)", field, valueStr)
	case "startsWith":
		return fmt.Sprintf("strings.HasPrefix(%s, %s)", field, valueStr)
	case "endsWith":
		return fmt.Sprintf("strings.HasSuffix(%s, %s)", field, valueStr)
	default:
		return fmt.Sprintf("%s == %s", field, valueStr)
	}
}

// sanitizeIdentifier makes a string safe for use as a CUE identifier
func sanitizeIdentifier(name string) string {
	// Replace spaces and special chars with underscores
	safe := strings.ReplaceAll(name, " ", "_")
	safe = strings.ReplaceAll(safe, "-", "_")
	safe = strings.ReplaceAll(safe, ".", "_")

	// Remove any remaining non-alphanumeric chars
	var result strings.Builder
	for _, r := range safe {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			result.WriteRune(r)
		}
	}

	// Ensure it doesn't start with a number
	s := result.String()
	if len(s) > 0 && s[0] >= '0' && s[0] <= '9' {
		s = "_" + s
	}

	return s
}
