FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .
RUN go mod download

RUN go build -o stream_loader ./backend/cmd/stream_loader/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/stream_loader .

CMD ["./stream_loader"]
