package repository
package repository













































































































































































































































































































































































}	return metrics, nil	}		return nil, err	if err := tx.Commit(ctx); err != nil {	}		return nil, err	if err != nil {	)		&metrics.DaysSinceLastOfficialFeed, &metrics.LastOfficialFeedTimestamp, &metrics.CalculatedAt,		&metrics.MediumConfidenceCount, &metrics.LowConfidenceCount,		&metrics.CoveragePercentage, &metrics.ConflictCount, &metrics.HighConfidenceCount,		&metrics.ID, &metrics.TenantID, &metrics.TotalCalendarDays, &metrics.DaysWithGoldenRecords,	err = tx.QueryRow(ctx, metricsQuery, tenantID).Scan(	metrics := &domain.HealthMetrics{}	`		          days_since_last_official_feed, last_official_feed_timestamp, calculated_at		          conflict_count, high_confidence_count, medium_confidence_count, low_confidence_count,		RETURNING id, tenant_id, total_calendar_days, days_with_golden_records, coverage_percentage,			NOW()			(SELECT MAX(ingested_at) FROM mdm_calendar_source WHERE tenant_id = $1 AND is_official = TRUE),			COALESCE((SELECT EXTRACT(DAY FROM NOW() - MAX(ingested_at))::INT FROM mdm_calendar_source WHERE tenant_id = $1 AND is_official = TRUE), 999),			(SELECT COUNT(*) FROM mdm_calendar_golden WHERE tenant_id = $1 AND confidence_score < 50 AND is_deleted = FALSE),			(SELECT COUNT(*) FROM mdm_calendar_golden WHERE tenant_id = $1 AND confidence_score BETWEEN 50 AND 79 AND is_deleted = FALSE),			(SELECT COUNT(*) FROM mdm_calendar_golden WHERE tenant_id = $1 AND confidence_score >= 80 AND is_deleted = FALSE),			(SELECT COUNT(*) FROM mdm_calendar_conflicts WHERE tenant_id = $1 AND status IN ('open', 'in_review')),			ROUND(100.0 * (SELECT COUNT(DISTINCT calendar_date) FROM mdm_calendar_golden WHERE tenant_id = $1 AND is_deleted = FALSE) / NULLIF((SELECT COUNT(DISTINCT calendar_date) FROM mdm_calendar_golden WHERE tenant_id = $1 AND is_deleted = FALSE), 0), 2),			(SELECT COUNT(DISTINCT calendar_date) FROM mdm_calendar_golden WHERE tenant_id = $1 AND is_deleted = FALSE),			(SELECT COUNT(DISTINCT calendar_date) FROM mdm_calendar_golden WHERE tenant_id = $1 AND is_deleted = FALSE),			$1,			gen_random_uuid(),		SELECT		)			calculated_at			days_since_last_official_feed, last_official_feed_timestamp,			medium_confidence_count, low_confidence_count,			coverage_percentage, conflict_count, high_confidence_count,			id, tenant_id, total_calendar_days, days_with_golden_records,		INSERT INTO mdm_calendar_metrics (	metricsQuery := `	// Calculate metrics	defer tx.Rollback(ctx)	}		return nil, err	if err != nil {	tx, err := r.pool.Begin(ctx)func (r *CalendarRepository) CalculateAndStoreMetrics(ctx context.Context, tenantID uuid.UUID) (*domain.HealthMetrics, error) {// CalculateAndStoreMetrics computes and persists health metrics// ============================================================================// Health Metrics Operations// ============================================================================}	return records, rows.Err()	}		records = append(records, record)		}			return nil, err		); err != nil {			&record.EscalatedToStewardAt, &record.StewardID, &record.CreatedAt,			&record.ResolvedAt, &record.ResolvedBy, &record.ResolutionNotes,			&record.ConflictingSources, &record.Severity, &record.Status,			&record.ID, &record.TenantID, &record.GoldenRecordID, &record.ConflictType,		if err := rows.Scan(		var record domain.ConflictRecord	for rows.Next() {	var records []domain.ConflictRecord	defer rows.Close()	}		return nil, err	if err != nil {	rows, err := r.pool.Query(ctx, query, tenantID)	`		ORDER BY severity DESC, created_at ASC		WHERE tenant_id = $1 AND status IN ('open', 'in_review')		FROM mdm_calendar_conflicts		       escalated_to_steward_at, steward_id, created_at		       severity, status, resolved_at, resolved_by, resolution_notes,		SELECT id, tenant_id, golden_record_id, conflict_type, conflicting_sources,	query := `func (r *CalendarRepository) GetOpenConflicts(ctx context.Context, tenantID uuid.UUID) ([]domain.ConflictRecord, error) {// GetOpenConflicts retrieves unresolved conflicts}	return err	).Scan(&record.ID)		record.ConflictingSources, record.Severity, record.Status, record.CreatedAt,		record.ID, record.TenantID, record.GoldenRecordID, record.ConflictType,	err := r.pool.QueryRow(ctx, query,	record.CreatedAt = time.Now()	record.ID = uuid.New()	`		RETURNING id		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)			severity, status, created_at			id, tenant_id, golden_record_id, conflict_type, conflicting_sources,		INSERT INTO mdm_calendar_conflicts (	query := `func (r *CalendarRepository) RecordConflict(ctx context.Context, record *domain.ConflictRecord) error {// RecordConflict flags a conflict for stewardship// ============================================================================// Conflict Operations// ============================================================================}	return records, rows.Err()	}		records = append(records, record)		}			return nil, err		); err != nil {			&record.ExecutionTime, &record.ConflictingSources, &record.ConflictDetected,			&record.RuleApplied, &record.PriorityLevel, &record.WASMExecutionID,			&record.PreviousValue, &record.WinningValue, &record.WinningSourceID,			&record.ID, &record.TenantID, &record.GoldenRecordID, &record.SemanticTerm,		if err := rows.Scan(		var record domain.LineageRecord	for rows.Next() {	var records []domain.LineageRecord	defer rows.Close()	}		return nil, err	if err != nil {	rows, err := r.pool.Query(ctx, query, tenantID, goldenRecordID)	`		ORDER BY execution_timestamp DESC		WHERE tenant_id = $1 AND golden_record_id = $2		FROM mdm_calendar_lineage		       wasm_execution_id, execution_timestamp, conflicting_sources, conflict_detected		       winning_value, winning_source_id, rule_applied, priority_level,		SELECT id, tenant_id, golden_record_id, semantic_term, previous_value,	query := `func (r *CalendarRepository) GetLineage(ctx context.Context, tenantID uuid.UUID, goldenRecordID uuid.UUID) ([]domain.LineageRecord, error) {// GetLineage retrieves the lineage history for a record}	return err	).Scan(&record.ID)		record.ExecutionTime, record.ConflictingSources, record.ConflictDetected,		record.RuleApplied, record.PriorityLevel, record.WASMExecutionID,		record.PreviousValue, record.WinningValue, record.WinningSourceID,		record.ID, record.TenantID, record.GoldenRecordID, record.SemanticTerm,	err := r.pool.QueryRow(ctx, query,	record.ExecutionTime = time.Now()	record.ID = uuid.New()	`		RETURNING id		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)			wasm_execution_id, execution_timestamp, conflicting_sources, conflict_detected			winning_value, winning_source_id, rule_applied, priority_level,			id, tenant_id, golden_record_id, semantic_term, previous_value,		INSERT INTO mdm_calendar_lineage (	query := `func (r *CalendarRepository) RecordLineage(ctx context.Context, record *domain.LineageRecord) error {// RecordLineage creates a lineage record// ============================================================================// Lineage Operations// ============================================================================}	return records, rows.Err()	}		records = append(records, record)		}			return nil, err		); err != nil {			&record.IsOfficial, &record.IngestedAt, &record.IngestedBy, &record.RawPayload,			&record.SourceSystem, &record.ExternalID, &record.SourcePriority, &record.LatencyHours,			&record.IsBusinessDay, &record.RegionCode, &record.ExchangeCode, &record.HolidayName,			&record.ID, &record.TenantID, &record.GoldenRecordID, &record.CalendarDate,		if err := rows.Scan(		var record domain.SourceRecord	for rows.Next() {	var records []domain.SourceRecord	defer rows.Close()	}		return nil, err	if err != nil {	rows, err := r.pool.Query(ctx, query, tenantID, date, region, exchange)	`		ORDER BY source_priority ASC, ingested_at DESC		  AND exchange_code IS NOT DISTINCT FROM $4		  AND region_code = $3		  AND calendar_date = $2		WHERE tenant_id = $1		FROM mdm_calendar_source		       raw_payload		       source_priority, latency_hours, is_official, ingested_at, ingested_by,		       region_code, exchange_code, holiday_name, source_system, external_id,		SELECT id, tenant_id, golden_record_id, calendar_date, is_business_day, 	query := `func (r *CalendarRepository) GetSourceRecords(ctx context.Context, tenantID uuid.UUID, date time.Time, region string, exchange *string) ([]domain.SourceRecord, error) {// GetSourceRecords retrieves candidate source records for matching}	return err	).Scan(&record.ID)		record.IsOfficial, record.IngestedAt, record.IngestedBy, record.RawPayload,		record.SourceSystem, record.ExternalID, record.SourcePriority, record.LatencyHours,		record.IsBusinessDay, record.RegionCode, record.ExchangeCode, record.HolidayName,		record.ID, record.TenantID, record.GoldenRecordID, record.CalendarDate,	err := r.pool.QueryRow(ctx, query,	record.IngestedAt = time.Now()	record.ID = uuid.New()	`		RETURNING id		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)			raw_payload			source_priority, latency_hours, is_official, ingested_at, ingested_by,			region_code, exchange_code, holiday_name, source_system, external_id,			id, tenant_id, golden_record_id, calendar_date, is_business_day, 		INSERT INTO mdm_calendar_source (	query := `func (r *CalendarRepository) InsertSourceRecord(ctx context.Context, record *domain.SourceRecord) error {// InsertSourceRecord stores raw ingestion data// ============================================================================// Source Record Operations// ============================================================================}	return records, rows.Err()	}		records = append(records, record)		}			return nil, err		); err != nil {			&record.CreatedAt, &record.UpdatedAt, &record.CreatedBy, &record.UpdatedBy,			&record.ConfidenceScore, &record.VersionID, &record.IsDeleted,			&record.RegionCode, &record.ExchangeCode, &record.HolidayName, &record.SourceType,			&record.ID, &record.TenantID, &record.CalendarDate, &record.IsBusinessDay,		if err := rows.Scan(		var record domain.HolidaySchedule	for rows.Next() {	var records []domain.HolidaySchedule	defer rows.Close()	}		return nil, err	if err != nil {	rows, err := r.pool.Query(ctx, query, tenantID, start, end, region, exchange)	`		ORDER BY calendar_date ASC		  AND is_deleted = FALSE		  AND exchange_code IS NOT DISTINCT FROM $5		  AND region_code = $4		  AND calendar_date BETWEEN $2 AND $3		WHERE tenant_id = $1		FROM mdm_calendar_golden		       version_id, is_deleted, created_at, updated_at, created_by, updated_by		       exchange_code, holiday_name, source_type, confidence_score, 		SELECT id, tenant_id, calendar_date, is_business_day, region_code, 	query := `func (r *CalendarRepository) GetGoldenCalendar(ctx context.Context, tenantID uuid.UUID, start, end time.Time, region string, exchange *string) ([]domain.HolidaySchedule, error) {// GetGoldenCalendar retrieves calendar records for a date range}	return record, err	}		return nil, nil	if err == pgx.ErrNoRows {	)		&record.CreatedAt, &record.UpdatedAt, &record.CreatedBy, &record.UpdatedBy,		&record.ConfidenceScore, &record.VersionID, &record.IsDeleted,		&record.RegionCode, &record.ExchangeCode, &record.HolidayName, &record.SourceType,		&record.ID, &record.TenantID, &record.CalendarDate, &record.IsBusinessDay,	err := r.pool.QueryRow(ctx, query, tenantID, date, region, exchange).Scan(	record := &domain.HolidaySchedule{}	`		  AND is_deleted = FALSE		  AND exchange_code IS NOT DISTINCT FROM $4		  AND region_code = $3		  AND calendar_date = $2		WHERE tenant_id = $1		FROM mdm_calendar_golden		       version_id, is_deleted, created_at, updated_at, created_by, updated_by		       exchange_code, holiday_name, source_type, confidence_score, 		SELECT id, tenant_id, calendar_date, is_business_day, region_code, 	query := `func (r *CalendarRepository) GetGoldenRecord(ctx context.Context, tenantID uuid.UUID, date time.Time, region string, exchange *string) (*domain.HolidaySchedule, error) {// GetGoldenRecord retrieves a specific golden record}	return err	).Scan(&record.ID, &record.VersionID)		record.ConfidenceScore, record.VersionID, now, now, record.CreatedBy, record.UpdatedBy,		record.RegionCode, record.ExchangeCode, record.HolidayName, record.SourceType,		record.ID, record.TenantID, record.CalendarDate, record.IsBusinessDay,	err := r.pool.QueryRow(ctx, query,	now := time.Now()	`		RETURNING id, version_id			updated_by = EXCLUDED.updated_by			updated_at = NOW(),			version_id = version_id + 1,			confidence_score = EXCLUDED.confidence_score,			source_type = EXCLUDED.source_type,			holiday_name = EXCLUDED.holiday_name,			is_business_day = EXCLUDED.is_business_day,		DO UPDATE SET 		ON CONFLICT (tenant_id, calendar_date, region_code, exchange_code) 		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)			version_id, created_at, updated_at, created_by, updated_by			exchange_code, holiday_name, source_type, confidence_score, 			id, tenant_id, calendar_date, is_business_day, region_code, 		INSERT INTO mdm_calendar_golden (	query := `func (r *CalendarRepository) UpsertGoldenRecord(ctx context.Context, record *domain.HolidaySchedule) error {// UpsertGoldenRecord inserts or updates a golden record// ============================================================================// Golden Record Operations// ============================================================================}	return &CalendarRepository{pool: pool}func NewCalendarRepository(pool *pgxpool.Pool) *CalendarRepository {// NewCalendarRepository creates a new calendar repository}	pool *pgxpool.Pooltype CalendarRepository struct {// CalendarRepository handles all database operations for calendar MDM)	"github.com/hondyman/semlayer/mdm-service/internal/domain"	"github.com/jackc/pgx/v5/pgxpool"	"github.com/jackc/pgx/v5"	"github.com/google/uuid"	"time"	"context"import (