apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calendar-service
  namespace: calendar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calendar-service
subjects:
- kind: ServiceAccount
  name: calendar-service
  namespace: calendar
