package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hondyman/semlayer/backend/internal/graphql/models"
)

// CreateEntity is the resolver for the createEntity field.
func (r *mutationResolver) CreateEntity(ctx context.Context, input models.CreateEntityInput) (*models.CreateEntityPayload, error) {
	panic(fmt.Errorf("not implemented: CreateEntity - createEntity"))
}

// UpdateEntity is the resolver for the updateEntity field.
func (r *mutationResolver) UpdateEntity(ctx context.Context, id uuid.UUID, input models.UpdateEntityInput) (*models.UpdateEntityPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateEntity - updateEntity"))
}

// DeleteEntity is the resolver for the deleteEntity field.
func (r *mutationResolver) DeleteEntity(ctx context.Context, id uuid.UUID) (*models.DeleteEntityPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteEntity - deleteEntity"))
}

// CreatePosition is the resolver for the createPosition field.
func (r *mutationResolver) CreatePosition(ctx context.Context, input models.CreatePositionInput) (*models.CreatePositionPayload, error) {
	panic(fmt.Errorf("not implemented: CreatePosition - createPosition"))
}

// UpdatePosition is the resolver for the updatePosition field.
func (r *mutationResolver) UpdatePosition(ctx context.Context, id uuid.UUID, input models.UpdatePositionInput) (*models.UpdatePositionPayload, error) {
	panic(fmt.Errorf("not implemented: UpdatePosition - updatePosition"))
}

// ClosePosition is the resolver for the closePosition field.
func (r *mutationResolver) ClosePosition(ctx context.Context, id uuid.UUID, terminatingDate string) (*models.ClosePositionPayload, error) {
	panic(fmt.Errorf("not implemented: ClosePosition - closePosition"))
}

// ImportModelTypes is the resolver for the importModelTypes field.
func (r *mutationResolver) ImportModelTypes(ctx context.Context, input models.ImportModelTypesInput) (*models.ImportModelTypesPayload, error) {
	panic(fmt.Errorf("not implemented: ImportModelTypes - importModelTypes"))
}

// Entity is the resolver for the entity field.
func (r *queryResolver) Entity(ctx context.Context, id uuid.UUID) (*models.Entity, error) {
	panic(fmt.Errorf("not implemented: Entity - entity"))
}

// Entities is the resolver for the entities field.
func (r *queryResolver) Entities(ctx context.Context, where *models.EntityFilter, orderBy []*models.EntityOrderBy, limit *int32, offset *int32) ([]*models.Entity, error) {
	panic(fmt.Errorf("not implemented: Entities - entities"))
}

// EntitiesAggregate is the resolver for the entitiesAggregate field.
func (r *queryResolver) EntitiesAggregate(ctx context.Context, where *models.EntityFilter) (*models.EntityAggregate, error) {
	panic(fmt.Errorf("not implemented: EntitiesAggregate - entitiesAggregate"))
}

// OwnershipTree is the resolver for the ownershipTree field.
func (r *queryResolver) OwnershipTree(ctx context.Context, rootID uuid.UUID, depth *int32, includeAttributes *bool, asOf *string) (*models.OwnershipNode, error) {
	panic(fmt.Errorf("not implemented: OwnershipTree - ownershipTree"))
}

// OwnershipChain is the resolver for the ownershipChain field.
func (r *queryResolver) OwnershipChain(ctx context.Context, targetID uuid.UUID, depth *int32, asOf *string) ([]*models.OwnershipNode, error) {
	panic(fmt.Errorf("not implemented: OwnershipChain - ownershipChain"))
}

// ModelTypes is the resolver for the modelTypes field.
func (r *queryResolver) ModelTypes(ctx context.Context, hierarchyLevel *int32) ([]*models.ModelTypeDefinition, error) {
	panic(fmt.Errorf("not implemented: ModelTypes - modelTypes"))
}

// ModelType is the resolver for the modelType field.
func (r *queryResolver) ModelType(ctx context.Context, modelType string) (*models.ModelTypeDefinition, error) {
	panic(fmt.Errorf("not implemented: ModelType - modelType"))
}

// HierarchyRules is the resolver for the hierarchyRules field.
func (r *queryResolver) HierarchyRules(ctx context.Context, parentModelType string, childModelType string) ([]*models.HierarchyRule, error) {
	panic(fmt.Errorf("not implemented: HierarchyRules - hierarchyRules"))
}

// AllowedChildren is the resolver for the allowedChildren field.
func (r *queryResolver) AllowedChildren(ctx context.Context, parentModelType string) ([]*models.ModelTypeDefinition, error) {
	panic(fmt.Errorf("not implemented: AllowedChildren - allowedChildren"))
}

// AllowedParents is the resolver for the allowedParents field.
func (r *queryResolver) AllowedParents(ctx context.Context, childModelType string) ([]*models.ModelTypeDefinition, error) {
	panic(fmt.Errorf("not implemented: AllowedParents - allowedParents"))
}

// SearchEntities is the resolver for the searchEntities field.
func (r *queryResolver) SearchEntities(ctx context.Context, query string, modelTypes []string, limit *int32) ([]*models.Entity, error) {
	panic(fmt.Errorf("not implemented: SearchEntities - searchEntities"))
}

// PortfolioMetrics is the resolver for the portfolioMetrics field.
func (r *queryResolver) PortfolioMetrics(ctx context.Context, rootID uuid.UUID, asOf *string) (*models.PortfolioMetrics, error) {
	panic(fmt.Errorf("not implemented: PortfolioMetrics - portfolioMetrics"))
}

// EntityChanged is the resolver for the entityChanged field.
func (r *subscriptionResolver) EntityChanged(ctx context.Context, tenantID uuid.UUID, modelTypes []string) (<-chan *models.EntityChangedSubscription, error) {
	panic(fmt.Errorf("not implemented: EntityChanged - entityChanged"))
}

// PositionChanged is the resolver for the positionChanged field.
func (r *subscriptionResolver) PositionChanged(ctx context.Context, tenantID uuid.UUID) (<-chan *models.PositionChangedSubscription, error) {
	panic(fmt.Errorf("not implemented: PositionChanged - positionChanged"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
