package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/hondyman/semlayer/backend/internal/graphql/models"
)

// AiSuggestRule is the resolver for the aiSuggestRule field.
func (r *mutationResolver) AiSuggestRule(ctx context.Context, input models.AISuggestRuleInput) (*models.AISuggestedRule, error) {
	panic(fmt.Errorf("not implemented: AiSuggestRule - aiSuggestRule"))
}

// LogTermAISuggestionFeedback is the resolver for the logTermAISuggestionFeedback field.
func (r *mutationResolver) LogTermAISuggestionFeedback(ctx context.Context, input models.LogTermFeedbackInput) (string, error) {
	panic(fmt.Errorf("not implemented: LogTermAISuggestionFeedback - logTermAISuggestionFeedback"))
}
