package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"

	"github.com/google/uuid"
)

// CreateIPWhitelistEntry is the resolver for the createIpWhitelistEntry field.
func (r *mutationResolver) CreateIPWhitelistEntry(ctx context.Context, input IPWhitelistEntryInput) (*IPWhitelistEntry, error) {
	return r.Resolver.CreateIpWhitelistEntry(ctx, input)
}

// UpdateIPWhitelistEntry is the resolver for the updateIpWhitelistEntry field.
func (r *mutationResolver) UpdateIPWhitelistEntry(ctx context.Context, id uuid.UUID, input IPWhitelistEntryInput) (*IPWhitelistEntry, error) {
	return r.Resolver.UpdateIpWhitelistEntry(ctx, id, input)
}

// DeleteIPWhitelistEntry is the resolver for the deleteIpWhitelistEntry field.
func (r *mutationResolver) DeleteIPWhitelistEntry(ctx context.Context, id uuid.UUID) (bool, error) {
	return r.Resolver.DeleteIpWhitelistEntry(ctx, id)
}

// IPWhitelistEntries is the resolver for the ipWhitelistEntries field.
func (r *queryResolver) IPWhitelistEntries(ctx context.Context) ([]*IPWhitelistEntry, error) {
	return r.Resolver.IpWhitelistEntries(ctx)
}

// IPWhitelistEntry is the resolver for the ipWhitelistEntry field.
func (r *queryResolver) IPWhitelistEntry(ctx context.Context, id uuid.UUID) (*IPWhitelistEntry, error) {
	return r.Resolver.IpWhitelistEntry(ctx, id)
}

// IPWhitelistEntriesByTenant is the resolver for the ipWhitelistEntriesByTenant field.
func (r *queryResolver) IPWhitelistEntriesByTenant(ctx context.Context, tenantID uuid.UUID) ([]*IPWhitelistEntry, error) {
	return r.Resolver.IpWhitelistEntriesByTenant(ctx, tenantID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
