package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hondyman/semlayer/backend/internal/graphql/models"
)

// GenerateCoreModel is the resolver for the generateCoreModel field.
func (r *mutationResolver) GenerateCoreModel(ctx context.Context, input models.GenerateCoreModelInput) (*models.SemanticModel, error) {
	panic(fmt.Errorf("not implemented: GenerateCoreModel - generateCoreModel"))
}

// GenerateCoreView is the resolver for the generateCoreView field.
func (r *mutationResolver) GenerateCoreView(ctx context.Context, input models.GenerateCoreViewInput) (*models.SemanticView, error) {
	panic(fmt.Errorf("not implemented: GenerateCoreView - generateCoreView"))
}

// CreateCustomModel is the resolver for the createCustomModel field.
func (r *mutationResolver) CreateCustomModel(ctx context.Context, input models.CreateCustomModelInput) (*models.SemanticModel, error) {
	panic(fmt.Errorf("not implemented: CreateCustomModel - createCustomModel"))
}

// CreateCustomView is the resolver for the createCustomView field.
func (r *mutationResolver) CreateCustomView(ctx context.Context, input models.CreateCustomViewInput) (*models.SemanticView, error) {
	panic(fmt.Errorf("not implemented: CreateCustomView - createCustomView"))
}

// ApplyRelationshipSuggestion is the resolver for the applyRelationshipSuggestion field.
func (r *mutationResolver) ApplyRelationshipSuggestion(ctx context.Context, input models.ApplyRelationshipSuggestionInput) (*models.RelationshipSuggestion, error) {
	panic(fmt.Errorf("not implemented: ApplyRelationshipSuggestion - applyRelationshipSuggestion"))
}

// TraverseObjectGraph is the resolver for the traverseObjectGraph field.
func (r *mutationResolver) TraverseObjectGraph(ctx context.Context, input models.TraverseGraphInput) (*models.ObjectGraphPath, error) {
	panic(fmt.Errorf("not implemented: TraverseObjectGraph - traverseObjectGraph"))
}

// SemanticAssets is the resolver for the semanticAssets field.
func (r *queryResolver) SemanticAssets(ctx context.Context, entityID uuid.UUID) (*models.SemanticAsset, error) {
	panic(fmt.Errorf("not implemented: SemanticAssets - semanticAssets"))
}

// RelationshipSuggestions is the resolver for the relationshipSuggestions field.
func (r *queryResolver) RelationshipSuggestions(ctx context.Context, entityID uuid.UUID, limit *int32, minConfidence *float64) (*models.RelationshipSuggestionList, error) {
	panic(fmt.Errorf("not implemented: RelationshipSuggestions - relationshipSuggestions"))
}

// LinkedModels is the resolver for the linkedModels field.
func (r *queryResolver) LinkedModels(ctx context.Context, entityID uuid.UUID) ([]*models.SemanticModel, error) {
	panic(fmt.Errorf("not implemented: LinkedModels - linkedModels"))
}

// RelatedObjects is the resolver for the relatedObjects field.
func (r *queryResolver) RelatedObjects(ctx context.Context, entityID uuid.UUID) (*models.ObjectGraphNode, error) {
	panic(fmt.Errorf("not implemented: RelatedObjects - relatedObjects"))
}

// TraverseObjectGraph is the resolver for the traverseObjectGraph field.
func (r *queryResolver) TraverseObjectGraph(ctx context.Context, input models.TraverseGraphInput) (*models.ObjectGraphPath, error) {
	panic(fmt.Errorf("not implemented: TraverseObjectGraph - traverseObjectGraph"))
}
