package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hondyman/semlayer/backend/internal/graphql/models"
)

// CreateRuleScenario is the resolver for the createRuleScenario field.
func (r *mutationResolver) CreateRuleScenario(ctx context.Context, input models.CreateRuleScenarioInput) (*models.RuleScenario, error) {
	panic(fmt.Errorf("not implemented: CreateRuleScenario - createRuleScenario"))
}

// SaveScenarioVersion is the resolver for the saveScenarioVersion field.
func (r *mutationResolver) SaveScenarioVersion(ctx context.Context, input models.SaveScenarioVersionInput) (*models.RuleScenarioVersion, error) {
	panic(fmt.Errorf("not implemented: SaveScenarioVersion - saveScenarioVersion"))
}

// RunScenario is the resolver for the runScenario field.
func (r *mutationResolver) RunScenario(ctx context.Context, input models.RunScenarioInput) (*models.RuleTestRun, error) {
	panic(fmt.Errorf("not implemented: RunScenario - runScenario"))
}

// RuleScenarios is the resolver for the ruleScenarios field.
func (r *queryResolver) RuleScenarios(ctx context.Context, tenantID uuid.UUID, ruleID *uuid.UUID) ([]*models.RuleScenario, error) {
	panic(fmt.Errorf("not implemented: RuleScenarios - ruleScenarios"))
}

// RuleScenario is the resolver for the ruleScenario field.
func (r *queryResolver) RuleScenario(ctx context.Context, id uuid.UUID) (*models.RuleScenario, error) {
	panic(fmt.Errorf("not implemented: RuleScenario - ruleScenario"))
}
