package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"

	abacclient "github.com/hondyman/uisce/libs/abac-client"
	sharedtypes "github.com/hondyman/uisce/libs/shared-types"
	temporalclient "github.com/hondyman/uisce/libs/temporal-client"
	"github.com/hondyman/uisce/services/governance/internal/config"
	"github.com/hondyman/uisce/services/governance/internal/services"
)

func main() {
	// Load configuration from environment
	cfg, err := config.LoadFromEnv()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	log.Printf("Starting Governance service with config: Temporal=%s, Port=%d",
		cfg.TemporalHostPort, cfg.ServerPort)

	// Initialize shared clients
	abacClient := abacclient.NewClient()

	// Initialize PostgreSQL connection
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		log.Fatalf("DATABASE_URL environment variable is not set")
	}
	dbPool, err := pgxpool.New(context.Background(), dbURL)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer dbPool.Close()

	// Initialize temporal client (will be nil for now if not configured)
	var temporalClient *temporalclient.Client
	// TODO: Initialize actual temporal client.Client and wrap it when ready

	// Initialize governance service
	governanceService := services.NewGovernanceService(services.GovernanceServiceConfig{
		DB:             dbPool,
		ABACClient:     abacClient,
		TemporalClient: temporalClient,
	})

	// Setup Gin router
	r := gin.Default()

	// Health check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "healthy", "service": "governance"})
	})

	// API routes
	v1 := r.Group("/api/v1")
	{
		v1.POST("/policies/evaluate", func(c *gin.Context) {
			var req sharedtypes.AccessEvaluationRequest
			if err := c.ShouldBindJSON(&req); err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
				return
			}

			response, err := governanceService.EvaluateAccess(c.Request.Context(), req)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
				return
			}

			c.JSON(http.StatusOK, response)
		})

		v1.GET("/policies", func(c *gin.Context) {
			tenantID := getTenantID(c, cfg.DefaultTenantID)

			policies, err := governanceService.GetPolicies(c.Request.Context(), tenantID)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
				return
			}
			c.JSON(http.StatusOK, gin.H{"policies": policies})
		})

		v1.POST("/policies", func(c *gin.Context) {
			var req struct {
				TenantID    string                 `json:"tenant_id" binding:"required"`
				Name        string                 `json:"name" binding:"required"`
				Description string                 `json:"description"`
				Resource    string                 `json:"resource" binding:"required"`
				Actions     []string               `json:"actions" binding:"required"`
				Conditions  map[string]interface{} `json:"conditions"`
			}

			if err := c.ShouldBindJSON(&req); err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
				return
			}

			policy := sharedtypes.Policy{
				ID:          "", // Will be generated by service
				Name:        req.Name,
				Description: req.Description,
				Effect:      "allow", // Default effect
				Conditions:  req.Conditions,
				Actions:     req.Actions,
			}

			createdPolicy, err := governanceService.CreatePolicy(c.Request.Context(), policy)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
				return
			}

			c.JSON(http.StatusCreated, gin.H{"policy": createdPolicy, "message": "Policy created successfully"})
		})

		v1.GET("/audit", func(c *gin.Context) {
			tenantID := getTenantID(c, cfg.DefaultTenantID)

			limit := 100 // default limit
			if limitStr := c.Query("limit"); limitStr != "" {
				if parsedLimit, err := strconv.Atoi(limitStr); err == nil && parsedLimit > 0 {
					if parsedLimit > 1000 {
						limit = 1000 // max limit
					} else {
						limit = parsedLimit
					}
				}
			}

			auditLog, err := governanceService.GetAuditLog(c.Request.Context(), tenantID, limit)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
				return
			}
			c.JSON(http.StatusOK, gin.H{"audit_log": auditLog})
		})
	}

	serverAddr := fmt.Sprintf(":%d", cfg.ServerPort)
	log.Printf("Starting Governance service on port %d", cfg.ServerPort)
	log.Fatal(r.Run(serverAddr))
}

// getTenantID extracts tenant ID from context/header/query, fallback to default
func getTenantID(c *gin.Context, defaultTenantID string) string {
	// Try to get from header first (set by auth middleware)
	if tenantID := c.GetHeader("X-Tenant-ID"); tenantID != "" {
		return tenantID
	}

	// Try from query parameter
	if tenantID := c.Query("tenant_id"); tenantID != "" {
		return tenantID
	}

	// Try from auth context (if available)
	if tenantID, exists := c.Get("tenant_id"); exists {
		if tid, ok := tenantID.(string); ok && tid != "" {
			return tid
		}
	}

	return defaultTenantID
}
