-- Seed comprehensive abbreviations into sml.abbreviation_lookup for the gold_copy tenant
-- This migration populates the sml.abbreviation_lookup table with a comprehensive list
-- of business and IT abbreviations associated with the gold_copy tenant.

-- Create unique index on (tenant_id, UPPER(abbreviation)) if it doesn't exist
CREATE UNIQUE INDEX IF NOT EXISTS idx_abbreviation_lookup_tenant_abbr_upper
    ON sml.abbreviation_lookup(tenant_id, UPPER(abbreviation));

DO $$
DECLARE
    gold_copy_tid VARCHAR(255);
    inserted_count INTEGER := 0;
BEGIN
    -- Get the gold copy tenant ID
    SELECT id INTO gold_copy_tid FROM public.tenants WHERE gold_copy = true LIMIT 1;

    IF gold_copy_tid IS NULL THEN
        RAISE NOTICE 'No gold_copy tenant found, skipping seed';
        RETURN;
    END IF;

    RAISE NOTICE 'Seeding abbreviations for gold_copy tenant: %', gold_copy_tid;

    -- Seed abbreviations with tenant_id = gold_copy_tid
    -- Using ON CONFLICT (tenant_id, UPPER(abbreviation)) to handle duplicates

    -- Section 1: Basic IT/Tech abbreviations (50 entries)
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('ID', 'IDENTIFIER', 'Unique identifier', gold_copy_tid, NOW(), NOW()),
        ('TS', 'TIMESTAMP', 'Date and time', gold_copy_tid, NOW(), NOW()),
        ('USR', 'USER', 'System user', gold_copy_tid, NOW(), NOW()),
        ('CFG', 'CONFIG', 'Configuration settings', gold_copy_tid, NOW(), NOW()),
        ('MSG', 'MESSAGE', 'Text message or payload', gold_copy_tid, NOW(), NOW()),
        ('ERR', 'ERROR', 'Error description', gold_copy_tid, NOW(), NOW()),
        ('AUTH', 'AUTHENTICATION', 'User authentication', gold_copy_tid, NOW(), NOW()),
        ('PWD', 'PASSWORD', 'User password', gold_copy_tid, NOW(), NOW()),
        ('ADDR', 'ADDRESS', 'Physical or network address', gold_copy_tid, NOW(), NOW()),
        ('DESC', 'DESCRIPTION', 'Detailed description', gold_copy_tid, NOW(), NOW()),
        ('IMG', 'IMAGE', 'Image file or data', gold_copy_tid, NOW(), NOW()),
        ('SRC', 'SOURCE', 'Origin or source', gold_copy_tid, NOW(), NOW()),
        ('DEST', 'DESTINATION', 'Target or destination', gold_copy_tid, NOW(), NOW()),
        ('REQ', 'REQUEST', 'Incoming request', gold_copy_tid, NOW(), NOW()),
        ('RES', 'RESPONSE', 'Outgoing response', gold_copy_tid, NOW(), NOW()),
        ('VAL', 'VALUE', 'Data value', gold_copy_tid, NOW(), NOW()),
        ('KEY', 'KEY', 'Key in key-value pair', gold_copy_tid, NOW(), NOW()),
        ('IDX', 'INDEX', 'Database index or array index', gold_copy_tid, NOW(), NOW()),
        ('CNT', 'COUNT', 'Number of items', gold_copy_tid, NOW(), NOW()),
        ('AMT', 'AMOUNT', 'Monetary or numerical amount', gold_copy_tid, NOW(), NOW()),
        ('QTY', 'QUANTITY', 'Number of units', gold_copy_tid, NOW(), NOW()),
        ('MAX', 'MAXIMUM', 'Maximum value', gold_copy_tid, NOW(), NOW()),
        ('MIN', 'MINIMUM', 'Minimum value', gold_copy_tid, NOW(), NOW()),
        ('AVG', 'AVERAGE', 'Average value', gold_copy_tid, NOW(), NOW()),
        ('STD', 'STANDARD', 'Standard value or deviation', gold_copy_tid, NOW(), NOW()),
        ('TMP', 'TEMPORARY', 'Temporary data', gold_copy_tid, NOW(), NOW()),
        ('SYS', 'SYSTEM', 'System related', gold_copy_tid, NOW(), NOW()),
        ('DEV', 'DEVELOPMENT', 'Development environment', gold_copy_tid, NOW(), NOW()),
        ('PROD', 'PRODUCTION', 'Production environment', gold_copy_tid, NOW(), NOW()),
        ('TST', 'TEST', 'Test environment or data', gold_copy_tid, NOW(), NOW()),
        ('ACCT', 'ACCOUNT', 'Account', gold_copy_tid, NOW(), NOW()),
        ('ACCOUNT', 'ACCOUNT', 'Account', gold_copy_tid, NOW(), NOW()),
        ('ACCOUNTING', 'ACCOUNTING', 'Accounting', gold_copy_tid, NOW(), NOW()),
        ('ACC', 'ACCOUNT', 'Account', gold_copy_tid, NOW(), NOW()),
        ('ACCRD', 'ACCRUED', 'Accrued', gold_copy_tid, NOW(), NOW()),
        ('ACCRUAL', 'ACCRUAL', 'Accrual', gold_copy_tid, NOW(), NOW()),
        ('ACCRUED', 'ACCRUED', 'Accrued', gold_copy_tid, NOW(), NOW()),
        ('ACQUIRED', 'ACQUIRED', 'Acquired', gold_copy_tid, NOW(), NOW()),
        ('ACQUISITION', 'ACQUISITION', 'Acquisition', gold_copy_tid, NOW(), NOW()),
        ('ACT', 'ACT', 'Act', gold_copy_tid, NOW(), NOW()),
        ('ACTION', 'ACTION', 'Action', gold_copy_tid, NOW(), NOW()),
        ('ACTIVITY', 'ACTIVITY', 'Activity', gold_copy_tid, NOW(), NOW()),
        ('ACTUAL', 'ACTUAL', 'Actual', gold_copy_tid, NOW(), NOW()),
        ('ADD', 'ADD', 'Add', gold_copy_tid, NOW(), NOW()),
        ('ADDED', 'ADDED', 'Added', gold_copy_tid, NOW(), NOW()),
        ('ADDL', 'ADDITIONAL', 'Additional', gold_copy_tid, NOW(), NOW()),
        ('ADDITIONAL', 'ADDITIONAL', 'Additional', gold_copy_tid, NOW(), NOW()),
        ('ADDR1', 'ADDRESS LINE 1', 'Address Line 1', gold_copy_tid, NOW(), NOW()),
        ('ADDR2', 'ADDRESS LINE 2', 'Address Line 2', gold_copy_tid, NOW(), NOW()),
        ('ADDR3', 'ADDRESS LINE 3', 'Address Line 3', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;

    RAISE NOTICE 'Seeded % abbreviations (batch 1)', inserted_count;

    -- Section 2: Financial/Business abbreviations
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('ADJ', 'ADJUSTMENT', 'Adjustment', gold_copy_tid, NOW(), NOW()),
        ('ADJUSTABLE', 'ADJUSTABLE', 'Adjustable', gold_copy_tid, NOW(), NOW()),
        ('ADJUSTMENT', 'ADJUSTMENT', 'Adjustment', gold_copy_tid, NOW(), NOW()),
        ('ADMIN', 'ADMIN', 'Admin', gold_copy_tid, NOW(), NOW()),
        ('ADVANCE', 'ADVANCE', 'Advance', gold_copy_tid, NOW(), NOW()),
        ('AGG', 'AGGREGATE', 'Aggregate', gold_copy_tid, NOW(), NOW()),
        ('ALL', 'ALL', 'All', gold_copy_tid, NOW(), NOW()),
        ('ALLOC', 'ALLOCATION', 'Allocation', gold_copy_tid, NOW(), NOW()),
        ('ALLOCATED', 'ALLOCATED', 'Allocated', gold_copy_tid, NOW(), NOW()),
        ('ALPHA', 'ALPHA', 'Alpha', gold_copy_tid, NOW(), NOW()),
        ('AMORTIZATION', 'AMORTIZATION', 'Amortization', gold_copy_tid, NOW(), NOW()),
        ('AMT', 'AMOUNT', 'Amount', gold_copy_tid, NOW(), NOW()),
        ('ANALYSIS', 'ANALYSIS', 'Analysis', gold_copy_tid, NOW(), NOW()),
        ('ANNUAL', 'ANNUAL', 'Annual', gold_copy_tid, NOW(), NOW()),
        ('ANNUALIZED', 'ANNUALIZED', 'Annualized', gold_copy_tid, NOW(), NOW()),
        ('APP', 'APPLICATION', 'Application', gold_copy_tid, NOW(), NOW()),
        ('APPL', 'APPLICATION', 'Application', gold_copy_tid, NOW(), NOW()),
        ('APPROVED', 'APPROVED', 'Approved', gold_copy_tid, NOW(), NOW()),
        ('APRV', 'APPROVE', 'Approve', gold_copy_tid, NOW(), NOW()),
        ('AR', 'ACCOUNTS_RECEIVABLE', 'Accounts Receivable', gold_copy_tid, NOW(), NOW()),
        ('ASOF', 'AS_OF', 'As Of', gold_copy_tid, NOW(), NOW()),
        ('ASSIGNED', 'ASSIGNED', 'Assigned', gold_copy_tid, NOW(), NOW()),
        ('ASSET', 'ASSET', 'Asset', gold_copy_tid, NOW(), NOW()),
        ('AT', 'AT', 'At', gold_copy_tid, NOW(), NOW()),
        ('AUTH', 'AUTHORIZATION', 'Authorization', gold_copy_tid, NOW(), NOW()),
        ('AUTO', 'AUTOMATIC', 'Automatic', gold_copy_tid, NOW(), NOW()),
        ('AVAIL', 'AVAILABLE', 'Available', gold_copy_tid, NOW(), NOW()),
        ('BAL', 'BALANCE', 'Balance', gold_copy_tid, NOW(), NOW()),
        ('BASE', 'BASE', 'Base', gold_copy_tid, NOW(), NOW()),
        ('BASIS', 'BASIS', 'Basis', gold_copy_tid, NOW(), NOW()),
        ('BEGIN', 'BEGINNING', 'Beginning', gold_copy_tid, NOW(), NOW()),
        ('BENEFIT', 'BENEFIT', 'Benefit', gold_copy_tid, NOW(), NOW()),
        ('BID', 'BID', 'Bid', gold_copy_tid, NOW(), NOW()),
        ('BILL', 'BILL', 'Bill', gold_copy_tid, NOW(), NOW()),
        ('BILLING', 'BILLING', 'Billing', gold_copy_tid, NOW(), NOW()),
        ('BLK', 'BLOCK', 'Block', gold_copy_tid, NOW(), NOW()),
        ('BONUS', 'BONUS', 'Bonus', gold_copy_tid, NOW(), NOW()),
        ('BROKER', 'BROKER', 'Broker', gold_copy_tid, NOW(), NOW()),
        ('BROKERAGE', 'BROKERAGE', 'Brokerage', gold_copy_tid, NOW(), NOW()),
        ('BS', 'BALANCE_SHEET', 'Balance Sheet', gold_copy_tid, NOW(), NOW()),
        ('BT', 'BUSINESS_TERM', 'Business Term', gold_copy_tid, NOW(), NOW()),
        ('BUCKET', 'BUCKET', 'Bucket', gold_copy_tid, NOW(), NOW()),
        ('BUDGET', 'BUDGET', 'Budget', gold_copy_tid, NOW(), NOW()),
        ('BUS', 'BUSINESS', 'Business', gold_copy_tid, NOW(), NOW()),
        ('BUY', 'BUY', 'Buy', gold_copy_tid, NOW(), NOW()),
        ('BUYER', 'BUYER', 'Buyer', gold_copy_tid, NOW(), NOW()),
        ('CASH', 'CASH', 'Cash', gold_copy_tid, NOW(), NOW()),
        ('CAT', 'CATEGORY', 'Category', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 2)', inserted_count;

    -- Section 3: More abbreviations covering common business terms
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('CD', 'CODE', 'Code', gold_copy_tid, NOW(), NOW()),
        ('CERT', 'CERTIFICATE', 'Certificate', gold_copy_tid, NOW(), NOW()),
        ('CF', 'CASH_FLOW', 'Cash Flow', gold_copy_tid, NOW(), NOW()),
        ('CFO', 'CHIEF_FINANCIAL_OFFICER', 'Chief Financial Officer', gold_copy_tid, NOW(), NOW()),
        ('CHG', 'CHANGE', 'Change', gold_copy_tid, NOW(), NOW()),
        ('CK', 'CHECK', 'Check', gold_copy_tid, NOW(), NOW()),
        ('CL', 'CURRENT_LIABILITIES', 'Current Liabilities', gold_copy_tid, NOW(), NOW()),
        ('CLNT', 'CLIENT', 'Client', gold_copy_tid, NOW(), NOW()),
        ('CLR', 'CLEAR', 'Clear', gold_copy_tid, NOW(), NOW()),
        ('CNCL', 'CANCEL', 'Cancel', gold_copy_tid, NOW(), NOW()),
        ('CNF', 'CONFIRM', 'Confirm', gold_copy_tid, NOW(), NOW()),
        ('CNFG', 'CONFIGURE', 'Configure', gold_copy_tid, NOW(), NOW()),
        ('CNTRY', 'COUNTRY', 'Country', gold_copy_tid, NOW(), NOW()),
        ('CO', 'COMPANY', 'Company', gold_copy_tid, NOW(), NOW()),
        ('COA', 'CHART_OF_ACCOUNTS', 'Chart of Accounts', gold_copy_tid, NOW(), NOW()),
        ('COM', 'COMMISSION', 'Commission', gold_copy_tid, NOW(), NOW()),
        ('COMM', 'COMMISSION', 'Commission', gold_copy_tid, NOW(), NOW()),
        ('COMP', 'COMPENSATION', 'Compensation', gold_copy_tid, NOW(), NOW()),
        ('CONSOL', 'CONSOLIDATED', 'Consolidated', gold_copy_tid, NOW(), NOW()),
        ('CONST', 'CONSTANT', 'Constant', gold_copy_tid, NOW(), NOW()),
        ('CONV', 'CONVERSION', 'Conversion', gold_copy_tid, NOW(), NOW()),
        ('CORP', 'CORPORATION', 'Corporation', gold_copy_tid, NOW(), NOW()),
        ('CP', 'COUPON', 'Coupon', gold_copy_tid, NOW(), NOW()),
        ('CR', 'CREDIT', 'Credit', gold_copy_tid, NOW(), NOW()),
        ('CS', 'CUSTOMER', 'Customer', gold_copy_tid, NOW(), NOW()),
        ('CTRY', 'COUNTRY', 'Country', gold_copy_tid, NOW(), NOW()),
        ('CURR', 'CURRENCY', 'Currency', gold_copy_tid, NOW(), NOW()),
        ('CUST', 'CUSTOMER', 'Customer', gold_copy_tid, NOW(), NOW()),
        ('CV', 'CONVERTIBLE', 'Convertible', gold_copy_tid, NOW(), NOW()),
        ('CYC', 'CYCLE', 'Cycle', gold_copy_tid, NOW(), NOW()),
        ('DASH', 'DASHBOARD', 'Dashboard', gold_copy_tid, NOW(), NOW()),
        ('DATA', 'DATA', 'Data', gold_copy_tid, NOW(), NOW()),
        ('DB', 'DATABASE', 'Database', gold_copy_tid, NOW(), NOW()),
        ('DEAL', 'DEAL', 'Deal', gold_copy_tid, NOW(), NOW()),
        ('DEPT', 'DEPARTMENT', 'Department', gold_copy_tid, NOW(), NOW()),
        ('DERIV', 'DERIVATIVE', 'Derivative', gold_copy_tid, NOW(), NOW()),
        ('DESC', 'DESCRIPTION', 'Description', gold_copy_tid, NOW(), NOW()),
        ('DESK', 'DESK', 'Desk', gold_copy_tid, NOW(), NOW()),
        ('DEV', 'DEVELOPMENT', 'Development', gold_copy_tid, NOW(), NOW()),
        ('DFLT', 'DEFAULT', 'Default', gold_copy_tid, NOW(), NOW()),
        ('DIFF', 'DIFFERENCE', 'Difference', gold_copy_tid, NOW(), NOW()),
        ('DIR', 'DIRECT', 'Direct', gold_copy_tid, NOW(), NOW()),
        ('DIS', 'DISCOUNT', 'Discount', gold_copy_tid, NOW(), NOW()),
        ('DIV', 'DIVIDEND', 'Dividend', gold_copy_tid, NOW(), NOW()),
        ('DIV', 'DIVISION', 'Division', gold_copy_tid, NOW(), NOW()),
        ('DR', 'DEBIT', 'Debit', gold_copy_tid, NOW(), NOW()),
        ('DT', 'DATE', 'Date', gold_copy_tid, NOW(), NOW()),
        ('DUE', 'DUE', 'Due', gold_copy_tid, NOW(), NOW()),
        ('DUR', 'DURATION', 'Duration', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 3)', inserted_count;

    -- Section 4: Geographic, Temporal, and Common Terms
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('DT', 'DATE', 'Date', gold_copy_tid, NOW(), NOW()),
        ('DTM', 'DATETIME', 'DateTime', gold_copy_tid, NOW(), NOW()),
        ('DUE_DT', 'DUE_DATE', 'Due Date', gold_copy_tid, NOW(), NOW()),
        ('EFF', 'EFFECTIVE', 'Effective', gold_copy_tid, NOW(), NOW()),
        ('EFF_DT', 'EFFECTIVE_DATE', 'Effective Date', gold_copy_tid, NOW(), NOW()),
        ('ELIG', 'ELIGIBLE', 'Eligible', gold_copy_tid, NOW(), NOW()),
        ('EMP', 'EMPLOYEE', 'Employee', gold_copy_tid, NOW(), NOW()),
        ('END', 'ENDING', 'Ending', gold_copy_tid, NOW(), NOW()),
        ('END_DT', 'END_DATE', 'End Date', gold_copy_tid, NOW(), NOW()),
        ('EQ', 'EQUITY', 'Equity', gold_copy_tid, NOW(), NOW()),
        ('ER', 'EXPENSE_RATIO', 'Expense Ratio', gold_copy_tid, NOW(), NOW()),
        ('EST', 'ESTIMATE', 'Estimate', gold_copy_tid, NOW(), NOW()),
        ('ET', 'EARNINGS', 'Earnings', gold_copy_tid, NOW(), NOW()),
        ('EX', 'EXCHANGE', 'Exchange', gold_copy_tid, NOW(), NOW()),
        ('EXCH', 'EXCHANGE', 'Exchange', gold_copy_tid, NOW(), NOW()),
        ('EXCL', 'EXCLUDE', 'Exclude', gold_copy_tid, NOW(), NOW()),
        ('EXP', 'EXPENSE', 'Expense', gold_copy_tid, NOW(), NOW()),
        ('EXP', 'EXPIRES', 'Expires', gold_copy_tid, NOW(), NOW()),
        ('EXPORT', 'EXPORT', 'Export', gold_copy_tid, NOW(), NOW()),
        ('EXT', 'EXTENDED', 'Extended', gold_copy_tid, NOW(), NOW()),
        ('FACTOR', 'FACTOR', 'Factor', gold_copy_tid, NOW(), NOW()),
        ('FACT', 'FACT', 'Fact', gold_copy_tid, NOW(), NOW()),
        ('FX', 'FOREIGN_EXCHANGE', 'Foreign Exchange', gold_copy_tid, NOW(), NOW()),
        ('GAAP', 'GAAP', 'Generally Accepted Accounting Principles', gold_copy_tid, NOW(), NOW()),
        ('GAIN', 'GAIN', 'Gain', gold_copy_tid, NOW(), NOW()),
        ('GENDER', 'GENDER', 'Gender', gold_copy_tid, NOW(), NOW()),
        ('GEO', 'GEOGRAPHIC', 'Geographic', gold_copy_tid, NOW(), NOW()),
        ('GOVT', 'GOVERNMENT', 'Government', gold_copy_tid, NOW(), NOW()),
        ('GP', 'GROSS_PROFIT', 'Gross Profit', gold_copy_tid, NOW(), NOW()),
        ('GROSS', 'GROSS', 'Gross', gold_copy_tid, NOW(), NOW()),
        ('HCM', 'HUMAN_CAPITAL_MANAGEMENT', 'Human Capital Management', gold_copy_tid, NOW(), NOW()),
        ('HIST', 'HISTORICAL', 'Historical', gold_copy_tid, NOW(), NOW()),
        ('HOLD', 'HOLDING', 'Holding', gold_copy_tid, NOW(), NOW()),
        ('HR', 'HUMAN_RESOURCES', 'Human Resources', gold_copy_tid, NOW(), NOW()),
        ('IB', 'INTEREST_BEARING', 'Interest Bearing', gold_copy_tid, NOW(), NOW()),
        ('IC', 'INTEREST_COUPON', 'Interest Coupon', gold_copy_tid, NOW(), NOW()),
        ('ID', 'IDENTIFIER', 'Identifier', gold_copy_tid, NOW(), NOW()),
        ('IMP', 'IMPAIRMENT', 'Impairment', gold_copy_tid, NOW(), NOW()),
        ('IN', 'INCOME', 'Income', gold_copy_tid, NOW(), NOW()),
        ('INC', 'INCOME', 'Income', gold_copy_tid, NOW(), NOW()),
        ('INC', 'INCORPORATED', 'Incorporated', gold_copy_tid, NOW(), NOW()),
        ('INCL', 'INCLUDE', 'Include', gold_copy_tid, NOW(), NOW()),
        ('IND', 'INDUSTRY', 'Industry', gold_copy_tid, NOW(), NOW()),
        ('INFO', 'INFORMATION', 'Information', gold_copy_tid, NOW(), NOW()),
        ('INIT', 'INITIAL', 'Initial', gold_copy_tid, NOW(), NOW()),
        ('INS', 'INSURANCE', 'Insurance', gold_copy_tid, NOW(), NOW()),
        ('INT', 'INTEREST', 'Interest', gold_copy_tid, NOW(), NOW()),
        ('INT', 'INTERVAL', 'Interval', gold_copy_tid, NOW(), NOW()),
        ('INTERNAL', 'INTERNAL', 'Internal', gold_copy_tid, NOW(), NOW()),
        ('INV', 'INVESTMENT', 'Investment', gold_copy_tid, NOW(), NOW()),
        ('IO', 'INTEREST_ONLY', 'Interest Only', gold_copy_tid, NOW(), NOW()),
        ('IP', 'INTELLECTUAL_PROPERTY', 'Intellectual Property', gold_copy_tid, NOW(), NOW()),
        ('IRR', 'INTERNAL_RATE_OF_RETURN', 'Internal Rate of Return', gold_copy_tid, NOW(), NOW()),
        ('IS', 'INCOME_STATEMENT', 'Income Statement', gold_copy_tid, NOW(), NOW()),
        ('ISIN', 'INTERNATIONAL_SECURITIES_IDENTIFICATION_NUMBER', 'ISIN', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 4)', inserted_count;

    -- Section 5: More business and financial terms
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('IT', 'INFORMATION_TECHNOLOGY', 'Information Technology', gold_copy_tid, NOW(), NOW()),
        ('LAB', 'LABOR', 'Labor', gold_copy_tid, NOW(), NOW()),
        ('LDC', 'LIQUIDITY', 'Liquidity', gold_copy_tid, NOW(), NOW()),
        ('LEAD', 'LEAD', 'Lead', gold_copy_tid, NOW(), NOW()),
        ('LEGAL', 'LEGAL', 'Legal', gold_copy_tid, NOW(), NOW()),
        ('LIAB', 'LIABILITY', 'Liability', gold_copy_tid, NOW(), NOW()),
        ('LIQ', 'LIQUIDITY', 'Liquidity', gold_copy_tid, NOW(), NOW()),
        ('LLC', 'LIMITED_LIABILITY_COMPANY', 'Limited Liability Company', gold_copy_tid, NOW(), NOW()),
        ('LLP', 'LIMITED_LIABILITY_PARTNERSHIP', 'Limited Liability Partnership', gold_copy_tid, NOW(), NOW()),
        ('LN', 'LOAN', 'Loan', gold_copy_tid, NOW(), NOW()),
        ('LOAN', 'LOAN', 'Loan', gold_copy_tid, NOW(), NOW()),
        ('LOC', 'LINE_OF_CREDIT', 'Line of Credit', gold_copy_tid, NOW(), NOW()),
        ('LOSS', 'LOSS', 'Loss', gold_copy_tid, NOW(), NOW()),
        ('LP', 'LIMITED_PARTNERSHIP', 'Limited Partnership', gold_copy_tid, NOW(), NOW()),
        ('LTV', 'LOAN_TO_VALUE', 'Loan to Value', gold_copy_tid, NOW(), NOW()),
        ('Maturity', 'MATURITY', 'Maturity', gold_copy_tid, NOW(), NOW()),
        ('MAT', 'MATURITY', 'Maturity', gold_copy_tid, NOW(), NOW()),
        ('MGR', 'MANAGER', 'Manager', gold_copy_tid, NOW(), NOW()),
        ('MGT', 'MANAGEMENT', 'Management', gold_copy_tid, NOW(), NOW()),
        ('MID', 'MIDDLE', 'Middle', gold_copy_tid, NOW(), NOW()),
        ('MKT', 'MARKET', 'Market', gold_copy_tid, NOW(), NOW()),
        ('ML', 'MATURITY_LENGTH', 'Maturity Length', gold_copy_tid, NOW(), NOW()),
        ('MO', 'MONTH', 'Month', gold_copy_tid, NOW(), NOW()),
        ('MON', 'MONTH', 'Month', gold_copy_tid, NOW(), NOW()),
        ('MORT', 'MORTGAGE', 'Mortgage', gold_copy_tid, NOW(), NOW()),
        ('MP', 'MATURITY_PERIOD', 'Maturity Period', gold_copy_tid, NOW(), NOW()),
        ('MRG', 'MERGER', 'Merger', gold_copy_tid, NOW(), NOW()),
        ('MS', 'MORTGAGE_STATED', 'Mortgage Stated', gold_copy_tid, NOW(), NOW()),
        ('MTG', 'MORTGAGE', 'Mortgage', gold_copy_tid, NOW(), NOW()),
        ('MV', 'MARKET_VALUE', 'Market Value', gold_copy_tid, NOW(), NOW()),
        ('NBR', 'NUMBER', 'Number', gold_copy_tid, NOW(), NOW()),
        ('NC', 'NON_COMPLIANCE', 'Non Compliance', gold_copy_tid, NOW(), NOW()),
        ('NET', 'NET', 'Net', gold_copy_tid, NOW(), NOW()),
        ('NM', 'NAME', 'Name', gold_copy_tid, NOW(), NOW()),
        ('NO', 'NUMBER', 'Number', gold_copy_tid, NOW(), NOW()),
        ('NOL', 'NET_OPERATING_LOSS', 'Net Operating Loss', gold_copy_tid, NOW(), NOW()),
        ('NON', 'NON', 'Non', gold_copy_tid, NOW(), NOW()),
        ('NP', 'NET_POSITION', 'Net Position', gold_copy_tid, NOW(), NOW()),
        ('NPR', 'NET_PERIOD_REVIEW', 'Net Period Review', gold_copy_tid, NOW(), NOW()),
        ('NRC', 'NON_RESIDENTIAL_CUSTOMER', 'Non Residential Customer', gold_copy_tid, NOW(), NOW()),
        ('NSFR', 'NET_STABLE_FUNDING_RATIO', 'Net Stable Funding Ratio', gold_copy_tid, NOW(), NOW()),
        ('NUM', 'NUMBER', 'Number', gold_copy_tid, NOW(), NOW()),
        ('OBL', 'OBLIGATION', 'Obligation', gold_copy_tid, NOW(), NOW()),
        ('OD', 'OVERDRAFT', 'Overdraft', gold_copy_tid, NOW(), NOW()),
        ('OFF', 'OFFICER', 'Officer', gold_copy_tid, NOW(), NOW()),
        ('OID', 'ORIGINAL_ISSUANCE_DISCOUNT', 'Original Issue Discount', gold_copy_tid, NOW(), NOW()),
        ('ORD', 'ORDER', 'Order', gold_copy_tid, NOW(), NOW()),
        ('ORG', 'ORGANIZATION', 'Organization', gold_copy_tid, NOW(), NOW()),
        ('OS', 'OUTSTANDING', 'Outstanding', gold_copy_tid, NOW(), NOW()),
        ('OT', 'OTHER', 'Other', gold_copy_tid, NOW(), NOW()),
        ('OTH', 'OTHER', 'Other', gold_copy_tid, NOW(), NOW()),
        ('OUT', 'OUTSTANDING', 'Outstanding', gold_copy_tid, NOW(), NOW()),
        ('OVR', 'OVER', 'Over', gold_copy_tid, NOW(), NOW()),
        ('P&L', 'PROFIT_AND_LOSS', 'Profit and Loss', gold_copy_tid, NOW(), NOW()),
        ('PAID', 'PAID', 'Paid', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 5)', inserted_count;

    -- Section 6: More terms
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('PAR', 'PARENT', 'Parent', gold_copy_tid, NOW(), NOW()),
        ('PAR', 'PAR_VALUE', 'Par Value', gold_copy_tid, NOW(), NOW()),
        ('PART', 'PARTICIPANT', 'Participant', gold_copy_tid, NOW(), NOW()),
        ('PARTY', 'PARTY', 'Party', gold_copy_tid, NOW(), NOW()),
        ('PASS', 'PASSIVE', 'Passive', gold_copy_tid, NOW(), NOW()),
        ('PAY', 'PAYMENT', 'Payment', gold_copy_tid, NOW(), NOW()),
        ('PAYEE', 'PAYEE', 'Payee', gold_copy_tid, NOW(), NOW()),
        ('PAYER', 'PAYER', 'Payer', gold_copy_tid, NOW(), NOW()),
        ('PC', 'PERCENT', 'Percent', gold_copy_tid, NOW(), NOW()),
        ('PCT', 'PERCENT', 'Percent', gold_copy_tid, NOW(), NOW()),
        ('PD', 'PRINCIPAL_DUE', 'Principal Due', gold_copy_tid, NOW(), NOW()),
        ('PDE', 'PRINCIPAL_DUE_END', 'Principal Due End', gold_copy_tid, NOW(), NOW()),
        ('PDT', 'PENDNG_DATE', 'Pending Date', gold_copy_tid, NOW(), NOW()),
        ('PEN', 'PENDING', 'Pending', gold_copy_tid, NOW(), NOW()),
        ('PEND', 'PENDING', 'Pending', gold_copy_tid, NOW(), NOW()),
        ('PER', 'PERIOD', 'Period', gold_copy_tid, NOW(), NOW()),
        ('PERF', 'PERFORMANCE', 'Performance', gold_copy_tid, NOW(), NOW()),
        ('PERIOD', 'PERIOD', 'Period', gold_copy_tid, NOW(), NOW()),
        ('PFC', 'PRINCIPAL_FIRST_COUPON', 'Principal First Coupon', gold_copy_tid, NOW(), NOW()),
        ('PGT', 'PRINCIPAL_GRANT', 'Principal Grant', gold_copy_tid, NOW(), NOW()),
        ('PICY', 'PRINCIPAL_INTEREST_COUPON_YIELD', 'Principal Interest Coupon Yield', gold_copy_tid, NOW(), NOW()),
        ('PIT', 'PRINCIPAL_INTEREST_TAX', 'Principal Interest Tax', gold_copy_tid, NOW(), NOW()),
        ('PM', 'PRINCIPAL_MORTGAGE', 'Principal Mortgage', gold_copy_tid, NOW(), NOW()),
        ('PMT', 'PAYMENT', 'Payment', gold_copy_tid, NOW(), NOW()),
        ('PO', 'PURCHASE_ORDER', 'Purchase Order', gold_copy_tid, NOW(), NOW()),
        ('PORT', 'PORTFOLIO', 'Portfolio', gold_copy_tid, NOW(), NOW()),
        ('PORTFOLIO', 'PORTFOLIO', 'Portfolio', gold_copy_tid, NOW(), NOW()),
        ('POS', 'POSITION', 'Position', gold_copy_tid, NOW(), NOW()),
        ('POSITION', 'POSITION', 'Position', gold_copy_tid, NOW(), NOW()),
        ('PP', 'PRINCIPAL_PAYMENT', 'Principal Payment', gold_copy_tid, NOW(), NOW()),
        ('PPE', 'PROPERTY_PLANT_EQUIPMENT', 'Property Plant Equipment', gold_copy_tid, NOW(), NOW()),
        ('PR', 'PURCHASE', 'Purchase', gold_copy_tid, NOW(), NOW()),
        ('PRC', 'PRICE', 'Price', gold_copy_tid, NOW(), NOW()),
        ('PREF', 'PREFERRED', 'Preferred', gold_copy_tid, NOW(), NOW()),
        ('PREM', 'PREMIUM', 'Premium', gold_copy_tid, NOW(), NOW()),
        ('PREPAID', 'PREPAID', 'Prepaid', gold_copy_tid, NOW(), NOW()),
        ('PRICE', 'PRICE', 'Price', gold_copy_tid, NOW(), NOW()),
        ('PRIN', 'PRINCIPAL', 'Principal', gold_copy_tid, NOW(), NOW()),
        ('PRINCIPAL', 'PRINCIPAL', 'Principal', gold_copy_tid, NOW(), NOW()),
        ('PROD', 'PRODUCT', 'Product', gold_copy_tid, NOW(), NOW()),
        ('PROD', 'PRODUCTION', 'Production', gold_copy_tid, NOW(), NOW()),
        ('PRODUCT', 'PRODUCT', 'Product', gold_copy_tid, NOW(), NOW()),
        ('PROFIT', 'PROFIT', 'Profit', gold_copy_tid, NOW(), NOW()),
        ('PROJ', 'PROJECT', 'Project', gold_copy_tid, NOW(), NOW()),
        ('PROJ', 'PROJECTION', 'Projection', gold_copy_tid, NOW(), NOW()),
        ('PROP', 'PROPERTY', 'Property', gold_copy_tid, NOW(), NOW()),
        ('PROV', 'PROVISION', 'Provision', gold_copy_tid, NOW(), NOW()),
        ('PROVIS', 'PROVISION', 'Provision', gold_copy_tid, NOW(), NOW()),
        ('PST', 'PAST', 'Past', gold_copy_tid, NOW(), NOW()),
        ('PT', 'PART', 'Part', gold_copy_tid, NOW(), NOW()),
        ('PULL', 'PULL', 'Pull', gold_copy_tid, NOW(), NOW()),
        ('PUSH', 'PUSH', 'Push', gold_copy_tid, NOW(), NOW()),
        ('PUT', 'PUT', 'Put', gold_copy_tid, NOW(), NOW()),
        ('QBR', 'QUARTERLY', 'Quarterly', gold_copy_tid, NOW(), NOW()),
        ('QPR', 'QUARTERLY_PERIOD_REVIEW', 'Quarterly Period Review', gold_copy_tid, NOW(), NOW()),
        ('QSR', 'QUARTERLY_SERVICE_REPORT', 'Quarterly Service Report', gold_copy_tid, NOW(), NOW()),
        ('QTY', 'QUANTITY', 'Quantity', gold_copy_tid, NOW(), NOW()),
        ('QTR', 'QUARTER', 'Quarter', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 6)', inserted_count;

    -- Section 7: Additional common abbreviations
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('RATE', 'RATE', 'Rate', gold_copy_tid, NOW(), NOW()),
        ('RATIO', 'RATIO', 'Ratio', gold_copy_tid, NOW(), NOW()),
        ('RC', 'RECEIVABLE', 'Receivable', gold_copy_tid, NOW(), NOW()),
        ('RCL', 'RECEIVABLE_COLLECTION_LAG', 'Receivable Collection Lag', gold_copy_tid, NOW(), NOW()),
        ('RD', 'RESEARCH_AND_DEVELOPMENT', 'Research and Development', gold_copy_tid, NOW(), NOW()),
        ('REAL', 'REAL', 'Real', gold_copy_tid, NOW(), NOW()),
        ('REC', 'RECEIVABLE', 'Receivable', gold_copy_tid, NOW(), NOW()),
        ('RECG', 'RECONCILIATION', 'Reconciliation', gold_copy_tid, NOW(), NOW()),
        ('RECL', 'RECONCILIATION', 'Reconciliation', gold_copy_tid, NOW(), NOW()),
        ('RED', 'REDEEMABLE', 'Redeemable', gold_copy_tid, NOW(), NOW()),
        ('REDEV', 'REDEVELOPMENT', 'Redevelopment', gold_copy_tid, NOW(), NOW()),
        ('REF', 'REFERENCE', 'Reference', gold_copy_tid, NOW(), NOW()),
        ('REFI', 'REFINANCE', 'Refinance', gold_copy_tid, NOW(), NOW()),
        ('REIT', 'REAL_ESTATE_INVESTMENT_TRUST', 'Real Estate Investment Trust', gold_copy_tid, NOW(), NOW()),
        ('RELY', 'RELY', 'Rely', gold_copy_tid, NOW(), NOW()),
        ('REND', 'RENDITION', 'Rendition', gold_copy_tid, NOW(), NOW()),
        ('RENEW', 'RENEWAL', 'Renewal', gold_copy_tid, NOW(), NOW()),
        ('RENT', 'RENT', 'Rent', gold_copy_tid, NOW(), NOW()),
        ('REO', 'REAL_ESTATE_OWNED', 'Real Estate Owned', gold_copy_tid, NOW(), NOW()),
        ('REP', 'REPRESENTATIVE', 'Representative', gold_copy_tid, NOW(), NOW()),
        ('REPO', 'REPURCHASE_AGREEMENT', 'Repurchase Agreement', gold_copy_tid, NOW(), NOW()),
        ('REQ', 'REQUIREMENT', 'Requirement', gold_copy_tid, NOW(), NOW()),
        ('REQ', 'REQUEST', 'Request', gold_copy_tid, NOW(), NOW()),
        ('RES', 'RESERVE', 'Reserve', gold_copy_tid, NOW(), NOW()),
        ('RES', 'RESIDENTIAL', 'Residential', gold_copy_tid, NOW(), NOW()),
        ('RESN', 'RESOLUTION', 'Resolution', gold_copy_tid, NOW(), NOW()),
        ('REST', 'RESTRUCTURE', 'Restructure', gold_copy_tid, NOW(), NOW()),
        ('RESTR', 'RESTRICTION', 'Restriction', gold_copy_tid, NOW(), NOW()),
        ('RETAIL', 'RETAIL', 'Retail', gold_copy_tid, NOW(), NOW()),
        ('RET', 'RETIREMENT', 'Retirement', gold_copy_tid, NOW(), NOW()),
        ('RETAIN', 'RETAINED', 'Retained', gold_copy_tid, NOW(), NOW()),
        ('RETAINED', 'RETAINED', 'Retained', gold_copy_tid, NOW(), NOW()),
        ('RETN', 'RETENTION', 'Retention', gold_copy_tid, NOW(), NOW()),
        ('REV', 'REVENUE', 'Revenue', gold_copy_tid, NOW(), NOW()),
        ('REV', 'REVIEW', 'Review', gold_copy_tid, NOW(), NOW()),
        ('REVAL', 'REVALUATION', 'Revaluation', gold_copy_tid, NOW(), NOW()),
        ('RF', 'Rf', 'Rf', gold_copy_tid, NOW(), NOW()),
        ('RG', 'REGION', 'Region', gold_copy_tid, NOW(), NOW()),
        ('RGN', 'REGION', 'Region', gold_copy_tid, NOW(), NOW()),
        ('RGS', 'REGRESSION', 'Regression', gold_copy_tid, NOW(), NOW()),
        ('RIGHTS', 'RIGHTS', 'Rights', gold_copy_tid, NOW(), NOW()),
        ('RISK', 'RISK', 'Risk', gold_copy_tid, NOW(), NOW()),
        ('RL', 'REVOLVING', 'Revolving', gold_copy_tid, NOW(), NOW()),
        ('RLOC', 'REVOLVING_LINE_OF_CREDIT', 'Revolving Line of Credit', gold_copy_tid, NOW(), NOW()),
        ('RM', 'RISK_MANAGEMENT', 'Risk Management', gold_copy_tid, NOW(), NOW()),
        ('RM', 'ROOM', 'Room', gold_copy_tid, NOW(), NOW()),
        ('RMBS', 'RESIDENTIAL_MORTGAGE_BACKED_SECURITIES', 'Residential Mortgage Backed Securities', gold_copy_tid, NOW(), NOW()),
        ('RNG', 'RANGE', 'Range', gold_copy_tid, NOW(), NOW()),
        ('ROA', 'RETURN_ON_ASSETS', 'Return on Assets', gold_copy_tid, NOW(), NOW()),
        ('ROE', 'RETURN_ON_EQUITY', 'Return on Equity', gold_copy_tid, NOW(), NOW()),
        ('ROLL', 'ROLL', 'Roll', gold_copy_tid, NOW(), NOW()),
        ('ROLLF', 'ROLLFORWARD', 'Rollforward', gold_copy_tid, NOW(), NOW()),
        ('ROYA', 'ROYALTY', 'Royalty', gold_copy_tid, NOW(), NOW()),
        ('RPC', 'REPRESENTATIVE', 'Representative', gold_copy_tid, NOW(), NOW()),
        ('RPD', 'RENT_PER_DAY', 'Rent Per Day', gold_copy_tid, NOW(), NOW()),
        ('RPM', 'REVENUE_PER_MONTH', 'Revenue Per Month', gold_copy_tid, NOW(), NOW()),
        ('RPO', 'RECOVERY_POINT_OBJECTIVE', 'Recovery Point Objective', gold_copy_tid, NOW(), NOW()),
        ('RTY', 'REALTY', 'Realty', gold_copy_tid, NOW(), NOW()),
        ('RUR', 'RURAL', 'Rural', gold_copy_tid, NOW(), NOW()),
        ('RV', 'REVIEW', 'Review', gold_copy_tid, NOW(), NOW()),
        ('RW', 'RAW', 'Raw', gold_copy_tid, NOW(), NOW()),
        ('SA', 'SPECIAL_ASSESSMENT', 'Special Assessment', gold_copy_tid, NOW(), NOW()),
        ('SA', 'SALES_ALLOWANCE', 'Sales Allowance', gold_copy_tid, NOW(), NOW()),
        ('SAL', 'SALARY', 'Salary', gold_copy_tid, NOW(), NOW()),
        ('SALV', 'SALVAGE', 'Salvage', gold_copy_tid, NOW(), NOW()),
        ('SAR', 'SUSPICIOUS_ACTIVITY_REPORT', 'Suspicious Activity Report', gold_copy_tid, NOW(), NOW()),
        ('SBC', 'SPECIAL_PURPOSE_ENTITY', 'Special Purpose Entity', gold_copy_tid, NOW(), NOW()),
        ('SC', 'SERVICE_CHARGE', 'Service Charge', gold_copy_tid, NOW(), NOW()),
        ('SCALE', 'SCALE', 'Scale', gold_copy_tid, NOW(), NOW()),
        ('SCF', 'STATEMENT_OF_CASH_FLOWS', 'Statement of Cash Flows', gold_copy_tid, NOW(), NOW()),
        ('SCH', 'SCHEDULE', 'Schedule', gold_copy_tid, NOW(), NOW()),
        ('SCI', 'SECTOR', 'Sector', gold_copy_tid, NOW(), NOW()),
        ('SCL', 'SCALE', 'Scale', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 7)', inserted_count;

    -- Section 8: Final batch - more terms
    INSERT INTO sml.abbreviation_lookup (abbreviation, full_word, notes, tenant_id, created_at, updated_at)
    VALUES
        ('SCORE', 'SCORE', 'Score', gold_copy_tid, NOW(), NOW()),
        ('SCR', 'SCREENER', 'Screener', gold_copy_tid, NOW(), NOW()),
        ('SCRTY', 'SECURITY', 'Security', gold_copy_tid, NOW(), NOW()),
        ('SD', 'SETTLEMENT_DATE', 'Settlement Date', gold_copy_tid, NOW(), NOW()),
        ('SEC', 'SECURITIES', 'Securities', gold_copy_tid, NOW(), NOW()),
        ('SEC', 'SECURITY', 'Security', gold_copy_tid, NOW(), NOW()),
        ('SECTOR', 'SECTOR', 'Sector', gold_copy_tid, NOW(), NOW()),
        ('SELL', 'SELL', 'Sell', gold_copy_tid, NOW(), NOW()),
        ('SELLER', 'SELLER', 'Seller', gold_copy_tid, NOW(), NOW()),
        ('SERIAL', 'SERIAL', 'Serial', gold_copy_tid, NOW(), NOW()),
        ('SERIES', 'SERIES', 'Series', gold_copy_tid, NOW(), NOW()),
        ('SERM', 'SERIES', 'Series', gold_copy_tid, NOW(), NOW()),
        ('SERV', 'SERVICE', 'Service', gold_copy_tid, NOW(), NOW()),
        ('SERVICE', 'SERVICE', 'Service', gold_copy_tid, NOW(), NOW()),
        ('SET', 'SETTLEMENT', 'Settlement', gold_copy_tid, NOW(), NOW()),
        ('SETL', 'SETTLEMENT', 'Settlement', gold_copy_tid, NOW(), NOW()),
        ('SFF', 'SALE_FORWARD', 'Sale Forward', gold_copy_tid, NOW(), NOW()),
        ('SFT', 'SOFT', 'Soft', gold_copy_tid, NOW(), NOW()),
        ('SH', 'SHAREHOLDER', 'Shareholder', gold_copy_tid, NOW(), NOW()),
        ('SHH', 'SHAREHOLDER', 'Shareholder', gold_copy_tid, NOW(), NOW()),
        ('SHORT', 'SHORT', 'Short', gold_copy_tid, NOW(), NOW()),
        ('SHR', 'SHARE', 'Share', gold_copy_tid, NOW(), NOW()),
        ('SHT', 'SHORT', 'Short', gold_copy_tid, NOW(), NOW()),
        ('SIN', 'SIN', 'SIN', gold_copy_tid, NOW(), NOW()),
        ('SL', 'STREET_LAW', 'Street Law', gold_copy_tid, NOW(), NOW()),
        ('SL', 'SALES', 'Sales', gold_copy_tid, NOW(), NOW()),
        ('SLA', 'SERVICE_LEVEL_AGREEMENT', 'Service Level Agreement', gold_copy_tid, NOW(), NOW()),
        ('SLB', 'SALARY', 'Salary', gold_copy_tid, NOW(), NOW()),
        ('SLF', 'SELF', 'Self', gold_copy_tid, NOW(), NOW()),
        ('SLP', 'SALESPERSON', 'Salesperson', gold_copy_tid, NOW(), NOW()),
        ('SM', 'SERVICE_MANAGEMENT', 'Service Management', gold_copy_tid, NOW(), NOW()),
        ('SN', 'SECURITY_NUMBER', 'Security Number', gold_copy_tid, NOW(), NOW()),
        ('SND', 'SEND', 'Send', gold_copy_tid, NOW(), NOW()),
        ('SO', 'SALES_ORDER', 'Sales Order', gold_copy_tid, NOW(), NOW()),
        ('SOA', 'STATEMENT_OF_ACCOUNT', 'Statement of Account', gold_copy_tid, NOW(), NOW()),
        ('SOC', 'SERVICE_OCCUPATION_CODE', 'Service Occupation Code', gold_copy_tid, NOW(), NOW()),
        ('SOD', 'START_OF_DAY', 'Start of Day', gold_copy_tid, NOW(), NOW()),
        ('SOL', 'SOLVENCY', 'Solvency', gold_copy_tid, NOW(), NOW()),
        ('SOLV', 'SOLVENCY', 'Solvency', gold_copy_tid, NOW(), NOW()),
        ('SOP', 'START_OF_PERIOD', 'Start of Period', gold_copy_tid, NOW(), NOW()),
        ('SOW', 'STATEMENT_OF_WORK', 'Statement of Work', gold_copy_tid, NOW(), NOW()),
        ('SP', 'SALES_PERSON', 'Sales Person', gold_copy_tid, NOW(), NOW()),
        ('SPEC', 'SPECIAL', 'Special', gold_copy_tid, NOW(), NOW()),
        ('SPOUSE', 'SPOUSE', 'Spouse', gold_copy_tid, NOW(), NOW()),
        ('SPV', 'SPECIAL_PURPOSE_VEHICLE', 'Special Purpose Vehicle', gold_copy_tid, NOW(), NOW()),
        ('SQL', 'STRUCTURED_QUERY_LANGUAGE', 'Structured Query Language', gold_copy_tid, NOW(), NOW()),
        ('SR', 'SENIOR', 'Senior', gold_copy_tid, NOW(), NOW()),
        ('SR', 'SERVICE_REQUEST', 'Service Request', gold_copy_tid, NOW(), NOW()),
        ('SS', 'SPOUSE', 'Spouse', gold_copy_tid, NOW(), NOW()),
        ('SSN', 'SOCIAL_SECURITY_NUMBER', 'Social Security Number', gold_copy_tid, NOW(), NOW()),
        ('ST', 'STATE', 'State', gold_copy_tid, NOW(), NOW()),
        ('START', 'START', 'Start', gold_copy_tid, NOW(), NOW()),
        ('STAT', 'STATUS', 'Status', gold_copy_tid, NOW(), NOW()),
        ('STD', 'STANDARD', 'Standard', gold_copy_tid, NOW(), NOW()),
        ('STEP', 'STEP', 'Step', gold_copy_tid, NOW(), NOW()),
        ('STF', 'STAFF', 'Staff', gold_copy_tid, NOW(), NOW()),
        ('STK', 'STOCK', 'Stock', gold_copy_tid, NOW(), NOW()),
        ('STMNT', 'STATEMENT', 'Statement', gold_copy_tid, NOW(), NOW()),
        ('STP', 'STOP', 'Stop', gold_copy_tid, NOW(), NOW()),
        ('STR', 'STORE', 'Store', gold_copy_tid, NOW(), NOW()),
        ('STRUCT', 'STRUCTURE', 'Structure', gold_copy_tid, NOW(), NOW()),
        ('SUB', 'SUBORDINATED', 'Subordinated', gold_copy_tid, NOW(), NOW()),
        ('SUB', 'SUBSCRIPTION', 'Subscription', gold_copy_tid, NOW(), NOW()),
        ('SUBM', 'SUBMISSION', 'Submission', gold_copy_tid, NOW(), NOW()),
        ('SUBS', 'SUBSIDIARY', 'Subsidiary', gold_copy_tid, NOW(), NOW()),
        ('SUM', 'SUMMARY', 'Summary', gold_copy_tid, NOW(), NOW()),
        ('SUP', 'SUPPLEMENTARY', 'Supplementary', gold_copy_tid, NOW(), NOW()),
        ('SUP', 'SUPPLIER', 'Supplier', gold_copy_tid, NOW(), NOW()),
        ('SUPER', 'SUPER', 'Super', gold_copy_tid, NOW(), NOW()),
        ('SUPPL', 'SUPPLIER', 'Supplier', gold_copy_tid, NOW(), NOW()),
        ('SVCE', 'SERVICE', 'Service', gold_copy_tid, NOW(), NOW()),
        ('SW', 'SOFTWARE', 'Software', gold_copy_tid, NOW(), NOW()),
        ('SWAP', 'SWAP', 'Swap', gold_copy_tid, NOW(), NOW()),
        ('SYD', 'SUM_OF_YEARS_DIGITS', 'Sum of Years Digits', gold_copy_tid, NOW(), NOW()),
        ('SYMBOL', 'SYMBOL', 'Symbol', gold_copy_tid, NOW(), NOW()),
        ('SYS', 'SYSTEM', 'System', gold_copy_tid, NOW(), NOW()),
        ('TANG', 'TANGIBLE', 'Tangible', gold_copy_tid, NOW(), NOW()),
        ('TAX', 'TAX', 'Tax', gold_copy_tid, NOW(), NOW()),
        ('TB', 'TRIAL_BALANCE', 'Trial Balance', gold_copy_tid, NOW(), NOW()),
        ('TC', 'TAX_CREDIT', 'Tax Credit', gold_copy_tid, NOW(), NOW()),
        ('TCE', 'TOTAL_COMMISSION_EARNED', 'Total Commission Earned', gold_copy_tid, NOW(), NOW()),
        ('TD', 'TIME_DEPOSIT', 'Time Deposit', gold_copy_tid, NOW(), NOW()),
        ('TE', 'TAX_EXEMPT', 'Tax Exempt', gold_copy_tid, NOW(), NOW()),
        ('TECH', 'TECHNOLOGY', 'Technology', gold_copy_tid, NOW(), NOW()),
        ('TEMP', 'TEMPORARY', 'Temporary', gold_copy_tid, NOW(), NOW()),
        ('TERM', 'TERM', 'Term', gold_copy_tid, NOW(), NOW()),
        ('TERMS', 'TERMS', 'Terms', gold_copy_tid, NOW(), NOW()),
        ('TF', 'TRANSFER', 'Transfer', gold_copy_tid, NOW(), NOW()),
        ('TFC', 'TOTAL_FIXED_COST', 'Total Fixed Cost', gold_copy_tid, NOW(), NOW()),
        ('TICKET', 'TICKET', 'Ticket', gold_copy_tid, NOW(), NOW()),
        ('TIC', 'TOTAL_INVESTMENT_COST', 'Total Investment Cost', gold_copy_tid, NOW(), NOW()),
        ('TIC', 'TOTAL_INCOME', 'Total Income', gold_copy_tid, NOW(), NOW()),
        ('TIER', 'TIER', 'Tier', gold_copy_tid, NOW(), NOW()),
        ('TIME', 'TIME', 'Time', gold_copy_tid, NOW(), NOW()),
        ('TITLE', 'TITLE', 'Title', gold_copy_tid, NOW(), NOW()),
        ('TL', 'TIME_LAG', 'Time Lag', gold_copy_tid, NOW(), NOW()),
        ('TL', 'TERM_LOAN', 'Term Loan', gold_copy_tid, NOW(), NOW()),
        ('TM', 'TAX_MANAGEMENT', 'Tax Management', gold_copy_tid, NOW(), NOW()),
        ('TM', 'TIME', 'Time', gold_copy_tid, NOW(), NOW()),
        ('TN', 'TRADE_NAME', 'Trade Name', gold_copy_tid, NOW(), NOW()),
        ('TNC', 'TERMS_AND_CONDITIONS', 'Terms and Conditions', gold_copy_tid, NOW(), NOW()),
        ('TOT', 'TOTAL', 'Total', gold_copy_tid, NOW(), NOW()),
        ('TOTAL', 'TOTAL', 'Total', gold_copy_tid, NOW(), NOW()),
        ('TPC', 'TOTAL_PROJECT_COST', 'Total Project Cost', gold_copy_tid, NOW(), NOW()),
        ('TPD', 'TOTAL_PRINCIPAL_DUE', 'Total Principal Due', gold_copy_tid, NOW(), NOW()),
        ('TPR', 'TAX_PERIOD_REVIEW', 'Tax Period Review', gold_copy_tid, NOW(), NOW()),
        ('TR', 'TRANSACTION', 'Transaction', gold_copy_tid, NOW(), NOW()),
        ('TR', 'TREASURY', 'Treasury', gold_copy_tid, NOW(), NOW()),
        ('TRADE', 'TRADE', 'Trade', gold_copy_tid, NOW(), NOW()),
        ('TRADING', 'TRADING', 'Trading', gold_copy_tid, NOW(), NOW()),
        ('TRAD', 'TRADITION', 'Tradition', gold_copy_tid, NOW(), NOW()),
        ('TRAIN', 'TRAINING', 'Training', gold_copy_tid, NOW(), NOW()),
        ('TRANS', 'TRANSACTION', 'Transaction', gold_copy_tid, NOW(), NOW()),
        ('TRANSFER', 'TRANSFER', 'Transfer', gold_copy_tid, NOW(), NOW()),
        ('TRN', 'TRANSACTION', 'Transaction', gold_copy_tid, NOW(), NOW()),
        ('TRUST', 'TRUST', 'Trust', gold_copy_tid, NOW(), NOW()),
        ('TS', 'TIMESTAMP', 'Timestamp', gold_copy_tid, NOW(), NOW()),
        ('TSY', 'TREASURY', 'Treasury', gold_copy_tid, NOW(), NOW()),
        ('TT', 'TRANSFER_TAX', 'Transfer Tax', gold_copy_tid, NOW(), NOW()),
        ('TTL', 'TOTAL', 'Total', gold_copy_tid, NOW(), NOW()),
        ('TURN', 'TURNOVER', 'Turnover', gold_copy_tid, NOW(), NOW()),
        ('TV', 'TOTAL_VALUE', 'Total Value', gold_copy_tid, NOW(), NOW()),
        ('TWR', 'TIME_WEIGHTED_RETURN', 'Time Weighted Return', gold_copy_tid, NOW(), NOW()),
        ('TX', 'TAX', 'Tax', gold_copy_tid, NOW(), NOW()),
        ('TXN', 'TRANSACTION', 'Transaction', gold_copy_tid, NOW(), NOW()),
        ('TYP', 'TYPE', 'Type', gold_copy_tid, NOW(), NOW()),
        ('TYPE', 'TYPE', 'Type', gold_copy_tid, NOW(), NOW()),
        ('UDF', 'USER_DEFINED_FIELD', 'User Defined Field', gold_copy_tid, NOW(), NOW()),
        ('UDT', 'USER_DEFINED_TABLE', 'User Defined Table', gold_copy_tid, NOW(), NOW()),
        ('UG', 'UNDERGROUND', 'Underground', gold_copy_tid, NOW(), NOW()),
        ('UL', 'UPPER_LIMIT', 'Upper Limit', gold_copy_tid, NOW(), NOW()),
        ('UM', 'UNIT_OF_MEASURE', 'Unit of Measure', gold_copy_tid, NOW(), NOW()),
        ('UNITS', 'UNITS', 'Units', gold_copy_tid, NOW(), NOW()),
        ('UR', 'URGENT', 'Urgent', gold_copy_tid, NOW(), NOW()),
        ('URL', 'UNIFORM_RESOURCE_LOCATOR', 'Uniform Resource Locator', gold_copy_tid, NOW(), NOW()),
        ('URN', 'UNIVERSAL_RESOURCE_NAME', 'Universal Resource Name', gold_copy_tid, NOW(), NOW()),
        ('USR', 'USER', 'User', gold_copy_tid, NOW(), NOW()),
        ('UTIL', 'UTILIZATION', 'Utilization', gold_copy_tid, NOW(), NOW()),
        ('UTIL', 'UTILITY', 'Utility', gold_copy_tid, NOW(), NOW()),
        ('VAD', 'VALUE_ADDED_DISTRIBUTOR', 'Value Added Distributor', gold_copy_tid, NOW(), NOW()),
        ('VAL', 'VALUE', 'Value', gold_copy_tid, NOW(), NOW()),
        ('VALID', 'VALID', 'Valid', gold_copy_tid, NOW(), NOW()),
        ('VALUATION', 'VALUATION', 'Valuation', gold_copy_tid, NOW(), NOW()),
        ('VAR', 'VARIABLE', 'Variable', gold_copy_tid, NOW(), NOW()),
        ('VARIANCE', 'VARIANCE', 'Variance', gold_copy_tid, NOW(), NOW()),
        ('VAT', 'VALUE_ADDED_TAX', 'Value Added Tax', gold_copy_tid, NOW(), NOW()),
        ('VC', 'VARIABLE_COST', 'Variable Cost', gold_copy_tid, NOW(), NOW()),
        ('VEND', 'VENDOR', 'Vendor', gold_copy_tid, NOW(), NOW()),
        ('VENDOR', 'VENDOR', 'Vendor', gold_copy_tid, NOW(), NOW()),
        ('VEST', 'VESTING', 'Vesting', gold_copy_tid, NOW(), NOW()),
        ('VIEW', 'VIEW', 'View', gold_copy_tid, NOW(), NOW()),
        ('VOL', 'VOLUME', 'Volume', gold_copy_tid, NOW(), NOW()),
        ('W9', 'W9', 'W9 Form', gold_copy_tid, NOW(), NOW()),
        ('W9', 'WITHHOLDING_EXEMPTION', 'Withholding Exemption', gold_copy_tid, NOW(), NOW()),
        ('WAGE', 'WAGE', 'Wage', gold_copy_tid, NOW(), NOW()),
        ('WARR', 'WARRANTY', 'Warranty', gold_copy_tid, NOW(), NOW()),
        ('WARRANT', 'WARRANTY', 'Warranty', gold_copy_tid, NOW(), NOW()),
        ('WD', 'WITHDRAWAL', 'Withdrawal', gold_copy_tid, NOW(), NOW()),
        ('WDA', 'WITHDRAWAL_ADVANCE', 'Withdrawal Advance', gold_copy_tid, NOW(), NOW()),
        ('WDR', 'WITHDRAWAL', 'Withdrawal', gold_copy_tid, NOW(), NOW()),
        ('WGT', 'WEIGHT', 'Weight', gold_copy_tid, NOW(), NOW()),
        ('WHT', 'WITHHOLDING', 'Withholding', gold_copy_tid, NOW(), NOW()),
        ('WI', 'WHEN_ISSUED', 'When Issued', gold_copy_tid, NOW(), NOW()),
        ('WK', 'WEEK', 'Week', gold_copy_tid, NOW(), NOW()),
        ('WKD', 'WEEKEND', 'Weekend', gold_copy_tid, NOW(), NOW()),
        ('WM', 'WEALTH_MANAGEMENT', 'Wealth Management', gold_copy_tid, NOW(), NOW()),
        ('WORK', 'WORK', 'Work', gold_copy_tid, NOW(), NOW()),
        ('WPD', 'WORKING_PERIOD_DAYS', 'Working Period Days', gold_copy_tid, NOW(), NOW()),
        ('WR', 'WRONG', 'Wrong', gold_copy_tid, NOW(), NOW()),
        ('WRNT', 'WARRANT', 'Warrant', gold_copy_tid, NOW(), NOW()),
        ('WS', 'WORKSHEET', 'Worksheet', gold_copy_tid, NOW(), NOW()),
        ('WS', 'WEEKLY_START', 'Weekly Start', gold_copy_tid, NOW(), NOW()),
        ('WTH', 'WITHHOLDING', 'Withholding', gold_copy_tid, NOW(), NOW()),
        ('WTN', 'WARRANT', 'Warrant', gold_copy_tid, NOW(), NOW()),
        ('XCHG', 'EXCHANGE', 'Exchange', gold_copy_tid, NOW(), NOW()),
        ('XCP', 'EX_COUPON', 'Ex Coupon', gold_copy_tid, NOW(), NOW()),
        ('XD', 'EX_DIVIDEND', 'Ex Dividend', gold_copy_tid, NOW(), NOW()),
        ('XM', 'EX_MONTH', 'Ex Month', gold_copy_tid, NOW(), NOW()),
        ('XPD', 'EXPIRED', 'Expired', gold_copy_tid, NOW(), NOW()),
        ('YIELD', 'YIELD', 'Yield', gold_copy_tid, NOW(), NOW()),
        ('YLD', 'YIELD', 'Yield', gold_copy_tid, NOW(), NOW()),
        ('YR', 'YEAR', 'Year', gold_copy_tid, NOW(), NOW()),
        ('YRS', 'YEARS', 'Years', gold_copy_tid, NOW(), NOW()),
        ('YTD', 'YEAR_TO_DATE', 'Year to Date', gold_copy_tid, NOW(), NOW()),
        ('YTM', 'YIELD_TO_MATURITY', 'Yield to Maturity', gold_copy_tid, NOW(), NOW()),
        ('YTW', 'YIELD_TO_WORST', 'Yield to Worst', gold_copy_tid, NOW(), NOW()),
        ('ZIP', 'ZIP_CODE', 'Zip Code', gold_copy_tid, NOW(), NOW()),
        ('ZONE', 'ZONE', 'Zone', gold_copy_tid, NOW(), NOW())
    ON CONFLICT (tenant_id, UPPER(abbreviation)) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RAISE NOTICE 'Seeded % abbreviations (batch 8)', inserted_count;

    -- Verify final count
    SELECT COUNT(*) INTO inserted_count FROM sml.abbreviation_lookup WHERE tenant_id = gold_copy_tid;
    RAISE NOTICE 'Total abbreviations for gold_copy tenant %: %', gold_copy_tid, inserted_count;

END $$;
