package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"

	"github.com/hondyman/semlayer/backend/internal/catalogsync"
)

type serviceConfig struct {
	PostgresDSN       string
	KafkaBrokers      []string
	KafkaTopic        string
	SchemaRegistryURL string
	SchemaSubject     string
	SourceName        string
	Port              string
	CDMRepoDir        string
	TenantID          *uuid.UUID
	TenantDatasource  *uuid.UUID
}

type syncRequest struct {
	Nodes []catalogsync.NodeInput `json:"nodes"`
	Edges []catalogsync.EdgeInput `json:"edges"`
}

func main() {
	cfg := loadConfig()

	db, err := sqlx.Open("postgres", cfg.PostgresDSN)
	if err != nil {
		log.Fatalf("failed to open postgres: %v", err)
	}
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(time.Hour)

	tenantID, err := resolveGoldCopyTenant(context.Background(), db, cfg.TenantID)
	if err != nil {
		log.Fatalf("resolve gold_copy tenant: %v", err)
	}

	var publisher catalogsync.EventPublisher
	publisher, err = catalogsync.NewAvroPublisher(cfg.KafkaBrokers, cfg.KafkaTopic, cfg.SchemaRegistryURL, cfg.SchemaSubject)
	if err != nil {
		log.Printf("Warning: failed to init avro publisher (Kafka/SchemaRegistry might be down): %v", err)
		log.Println("Falling back to NoopPublisher. Events will not be published to Kafka.")
		publisher = &catalogsync.NoopPublisher{}
	}
	defer publisher.Close(context.Background())

	svc := &catalogsync.SyncService{
		Nodes:      catalogsync.NewNodeRepository(db),
		Edges:      catalogsync.NewEdgeRepository(db),
		Publisher:  publisher,
		SourceName: cfg.SourceName,
	}

	http.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})

	http.HandleFunc("/sync", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}
		var req syncRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			w.WriteHeader(http.StatusBadRequest)
			_, _ = w.Write([]byte("invalid json"))
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
		defer cancel()

		if err := svc.UpsertNodes(ctx, req.Nodes); err != nil {
			log.Printf("sync nodes error: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			_, _ = w.Write([]byte("failed syncing nodes"))
			return
		}
		if err := svc.UpsertEdges(ctx, req.Edges); err != nil {
			log.Printf("sync edges error: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			_, _ = w.Write([]byte("failed syncing edges"))
			return
		}

		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("synced"))
	})

	http.HandleFunc("/sync/finos", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 2*time.Minute)
		defer cancel()

		cdmClassTypeID, err := ensureNodeType(ctx, db, tenantID, "CDMClass")
		if err != nil {
			log.Printf("ensure node type CDMClass: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		cdmFieldTypeID, err := ensureNodeType(ctx, db, tenantID, "CDMField")
		if err != nil {
			log.Printf("ensure node type CDMField: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		cdmEnumTypeID, err := ensureNodeType(ctx, db, tenantID, "CDMEnum")
		if err != nil {
			log.Printf("ensure node type CDMEnum: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		cdmEnumValueTypeID, err := ensureNodeType(ctx, db, tenantID, "CDMEnumValue")
		if err != nil {
			log.Printf("ensure node type CDMEnumValue: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		// Check for local catalog.json first (generated by cdm-generator)
		const localCatalogPath = "./catalog.json"
		var nodes []catalogsync.NodeInput
		var edgeSpecs []catalogsync.CDMEdgeSpec
		var classesLoaded int

		if _, err := os.Stat(localCatalogPath); err == nil {
			log.Printf("Found local %s, loading from generated catalog...", localCatalogPath)
			cat, err := catalogsync.LoadCatalogJSON(localCatalogPath)
			if err != nil {
				log.Printf("failed to load local catalog: %v", err)
				w.WriteHeader(http.StatusInternalServerError)
				_, _ = w.Write([]byte("failed loading local catalog"))
				return
			}
			nodes, edgeSpecs = catalogsync.BuildGraphFromCatalogJSON(cat, catalogsync.CDMTypeIDs{
				Class:     cdmClassTypeID,
				Field:     cdmFieldTypeID,
				Enum:      cdmEnumTypeID,
				EnumValue: cdmEnumValueTypeID,
			}, tenantID, cfg.TenantDatasource)
			log.Printf("Loaded %d products and generated graph from catalog.json", len(cat.Products))

		} else {
			log.Printf("Local %s not found, falling back to git fetch...", localCatalogPath)
			classes, err := catalogsync.FetchAndParseCDM(cfg.CDMRepoDir)
			if err != nil {
				log.Printf("fetch CDM schemas: %v", err)
				w.WriteHeader(http.StatusBadGateway)
				return
			}
			classesLoaded = len(classes)
			nodes, edgeSpecs = catalogsync.BuildCDMGraph(classes, catalogsync.CDMTypeIDs{
				Class:     cdmClassTypeID,
				Field:     cdmFieldTypeID,
				Enum:      cdmEnumTypeID,
				EnumValue: cdmEnumValueTypeID,
			}, tenantID, cfg.TenantDatasource)
		}

		if err := svc.UpsertNodes(ctx, nodes); err != nil {
			log.Printf("sync CDM nodes: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		edges := make([]catalogsync.EdgeInput, 0, len(edgeSpecs))
		for _, es := range edgeSpecs {
			srcID, err := svc.Nodes.ResolveNodeID(ctx, cfg.TenantDatasource, es.SourceType, es.SourcePath)
			if err != nil {
				log.Printf("resolve source node %s: %v", es.SourcePath, err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
			tgtID, err := svc.Nodes.ResolveNodeID(ctx, cfg.TenantDatasource, es.TargetType, es.TargetPath)
			if err != nil {
				log.Printf("resolve target node %s: %v", es.TargetPath, err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}

			edges = append(edges, catalogsync.EdgeInput{
				SourceNodeID:       srcID,
				TargetNodeID:       tgtID,
				EdgeType:           es.Type,
				EdgeTypeID:         uuid.Nil,
				RelationshipType:   nil,
				Properties:         es.Props,
				TenantID:           tenantID,
				TenantDatasourceID: cfg.TenantDatasource,
			})
		}

		if err := svc.UpsertEdges(ctx, edges); err != nil {
			log.Printf("sync CDM edges: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		resp := map[string]any{
			"status":         "ok",
			"classes_loaded": classesLoaded,
			"nodes_synced":   len(nodes),
			"edges_synced":   len(edges),
			"cdm_types": map[string]string{
				"class":      cdmClassTypeID.String(),
				"field":      cdmFieldTypeID.String(),
				"enum":       cdmEnumTypeID.String(),
				"enum_value": cdmEnumValueTypeID.String(),
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	})

	log.Printf("catalog-sync listening on %s", cfg.Port)
	if err := http.ListenAndServe(cfg.Port, nil); err != nil {
		log.Fatalf("server error: %v", err)
	}
}

func loadConfig() serviceConfig {
	get := func(key, def string) string {
		v := strings.TrimSpace(os.Getenv(key))
		if v == "" {
			return def
		}
		return v
	}

	brokers := strings.Split(get("KAFKA_BROKERS", "localhost:9092"), ",")
	for i := range brokers {
		brokers[i] = strings.TrimSpace(brokers[i])
	}

	return serviceConfig{
		PostgresDSN:       get("POSTGRES_DSN", "host=localhost port=5432 user=postgres password=postgres dbname=alpha sslmode=disable"),
		KafkaBrokers:      brokers,
		KafkaTopic:        get("KAFKA_TOPIC", "catalog-change-events"),
		SchemaRegistryURL: get("SCHEMA_REGISTRY_URL", "http://localhost:8081"),
		SchemaSubject:     get("SCHEMA_SUBJECT", "catalog-change-event-value"),
		SourceName:        get("SOURCE_NAME", "catalog-sync"),
		Port:              ensurePort(get("PORT", ":8090")),
		CDMRepoDir:        get("CDM_REPO_DIR", "/tmp/cdm"),
		TenantID:          parseOptionalUUID(get("TENANT_ID", "")),
		TenantDatasource:  parseOptionalUUID(get("TENANT_DATASOURCE_ID", "")),
	}
}

func ensurePort(port string) string {
	if !strings.HasPrefix(port, ":") {
		return ":" + port
	}
	return port
}

func parseOptionalUUID(v string) *uuid.UUID {
	if strings.TrimSpace(v) == "" {
		return nil
	}
	id, err := uuid.Parse(v)
	if err != nil {
		log.Fatalf("invalid TENANT_DATASOURCE_ID: %v", err)
	}
	return &id
}

func ensureNodeType(ctx context.Context, db *sqlx.DB, tenantID uuid.UUID, name string) (uuid.UUID, error) {
	var id uuid.UUID
	err := db.GetContext(ctx, &id, `SELECT id FROM catalog_node_type WHERE catalog_type_name = $1 AND tenant_id IS NOT DISTINCT FROM $2 LIMIT 1`, name, tenantID)
	if err == nil {
		return id, nil
	}
	if !errors.Is(err, sql.ErrNoRows) {
		return uuid.Nil, err
	}

	id = uuid.New()
	_, err = db.ExecContext(ctx, `
		INSERT INTO catalog_node_type (id, catalog_type_name, tenant_id, created_at, updated_at)
		VALUES ($1, $2, $3, now(), now())
	`, id, name, tenantID)
	if err != nil {
		return uuid.Nil, fmt.Errorf("insert node type %s: %w", name, err)
	}
	return id, nil
}

func resolveGoldCopyTenant(ctx context.Context, db *sqlx.DB, requested *uuid.UUID) (uuid.UUID, error) {
	var id uuid.UUID
	if requested != nil {
		err := db.GetContext(ctx, &id, `SELECT id FROM public.tenants WHERE id = $1 AND gold_copy = true`, *requested)
		if err != nil {
			return uuid.Nil, fmt.Errorf("tenant %s not gold_copy or missing: %w", requested.String(), err)
		}
		return id, nil
	}

	err := db.GetContext(ctx, &id, `SELECT id FROM public.tenants WHERE gold_copy = true LIMIT 1`)
	if err != nil {
		return uuid.Nil, fmt.Errorf("no gold_copy tenant found: %w", err)
	}
	return id, nil
}

// ensureUnused prevents compiler errors when structs are referenced by JSON unmarshal only.
var _ = uuid.Nil
