/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpgradeArtifactsData {
  /**
   * Semantic version of this schema definition, e.g., '1.0.0'.
   */
  schema_version: string;
  /**
   * Optional history of schema changes for this artifact.
   */
  changelog?: {
    version: string;
    date: string;
    description: string;
    [k: string]: unknown;
  }[];
  report: DiffReport;
  aliases: AliasMap;
  [k: string]: unknown;
}
export interface DiffReport {
  core_version: string;
  previous_version: string;
  generated_at: string;
  schema_hash: string;
  summary: DiffSummary;
  cubes: CubeDiff[];
  views: ViewDiff[];
  governance: GovernanceDiff[];
  pre_aggregations: PreAggregationDiff[];
  warnings: string[];
  [k: string]: unknown;
}
export interface DiffSummary {
  cubes_added: number;
  cubes_removed: number;
  cubes_changed: number;
  views_added: number;
  views_removed: number;
  views_changed: number;
  breaking_changes: number;
  warnings: number;
  [k: string]: unknown;
}
export interface CubeDiff {
  name: string;
  status: 'added' | 'removed' | 'changed';
  changes: Change[];
  [k: string]: unknown;
}
export interface Change {
  type: string;
  name?: string;
  join_path?: string;
  member?: string;
  old?: unknown;
  new?: unknown;
  details?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ViewDiff {
  name: string;
  status: 'added' | 'removed' | 'changed';
  changes: Change[];
  [k: string]: unknown;
}
export interface GovernanceDiff {
  scope: 'cube' | 'view';
  name: string;
  changes: Change[];
  [k: string]: unknown;
}
export interface PreAggregationDiff {
  cube: string;
  name: string;
  status: 'rebuild_required' | 'unchanged' | 'removed' | 'added';
  reason?: string;
  [k: string]: unknown;
}
export interface AliasMap {
  core_version: string;
  previous_version: string;
  generated_at: string;
  aliases: AliasEntry[];
  [k: string]: unknown;
}
export interface AliasEntry {
  scope: 'cube' | 'view';
  name: string;
  member_type: 'dimension' | 'measure' | 'segment';
  old_name: string;
  new_name?: string;
  status: 'renamed' | 'deprecated' | 'removed';
  meta?: AliasMeta;
  [k: string]: unknown;
}
export interface AliasMeta {
  reason: string;
  auto_rewrite: boolean;
  suggested_replacement?: string;
  breaking_change?: boolean;
  [k: string]: unknown;
}

// Compatibility alias: some code expects `UpgradeArtifacts` name
export type UpgradeArtifacts = UpgradeArtifactsData;
