package rules
package rules

import (
























































































































































































































































































































}	}		ConflictFlag:   result.ConflictDetected,		Winner:         *result.WinningCandidate,		CandidatesEvaluated: len(candidates),		RulesApplied:   []string{result.RuleApplied},		Timestamp:      time.Now(),		ExecutionID:    result.ExecID,	return &ExecutionTrace{func (re *RulesEngine) TraceExecution(result *RuleResult, candidates []Candidate) *ExecutionTrace {// TraceExecution records the full audit trail}	ConflictFlag   bool	Winner         Candidate	CandidatesEvaluated int	RulesApplied   []string	Timestamp      time.Time	ExecutionID    uuid.UUIDtype ExecutionTrace struct {// ExecutionTrace records the full execution path for audit// ============================================================================// Audit & Trace// ============================================================================}	return nil	fmt.Printf("TODO: Implement DSL parsing and WASM compilation for rule: %s\n", name)	// 4. Register rule in externalRulesDB	// 3. Load the WASM sandbox	// 2. Compile to WASM	// 1. Parse the DSL (survivorship_calendar_policy.asl)	// In production, this would:	// Placeholder for parsing DSL/WASM rulesfunc (re *RulesEngine) LoadRuleFromDSL(name string, dslContent string) error {// LoadRuleFromDSL loads a rule definition (placeholder for future WASM support)// ============================================================================// Rule Loading (for external DSL support)// ============================================================================}	return lineage	}		}			lineage.ConflictingSources = data		if data, err := json.Marshal(ruleResult.AlternativeCandidates); err == nil {	if ruleResult.ConflictDetected && len(ruleResult.AlternativeCandidates) > 0 {	// Serialize conflicting sources	}		lineage.WinningSourceID = &ruleResult.WinningCandidate.SourceID		lineage.WinningValue = winningValue		winningValue := fmt.Sprintf("%v", ruleResult.WinningCandidate.Value)	if ruleResult.WinningCandidate != nil {	// Set winning value and source	}		ConflictDetected: ruleResult.ConflictDetected,		WASMExecutionID: &ruleResult.ExecID,		PriorityLevel: ruleResult.WinningCandidate.Priority,		RuleApplied:   ruleResult.RuleApplied,		SemanticTerm:  ruleResult.SemanticTerm,		TenantID:       execCtx.TenantID,	lineage := &domain.LineageRecord{func (re *RulesEngine) ConstructLineage(execCtx ExecutionContext, ruleResult *RuleResult) *domain.LineageRecord {// ConstructLineage creates a lineage record from a rule result// ============================================================================// Lineage Construction// ============================================================================}	return &Score{Value: score, Reasoning: reasoning}	}		reasoning = "Unknown source - default fallback"		score = 50	default:		reasoning = "Internal steward override"		score = 85	case "ManualSteward":		}			reasoning = "Refinitiv with delayed data (>24h)"			score = 70		if candidate.Latency != nil && *candidate.Latency > 24 {		reasoning = "Premium vendor (Refinitiv)"		score = 90	case "Refinitiv":		}			reasoning = "Bloomberg with delayed data (>24h)"			score = 70		if candidate.Latency != nil && *candidate.Latency > 24 {		reasoning = "Premium vendor (Bloomberg)"		score = 90	case "Bloomberg":		}			reasoning = "Exchange data (non-official derivative)"			score = 80		if !candidate.IsOfficial {		reasoning = "Official exchange data"		score = 100	case "ExchangeFeed":	switch candidate.System {	// Base score by system	reasoning := ""	score := 0func (re *RulesEngine) CalculateConfidenceScore(candidate *Candidate) *Score {// CalculateConfidenceScore computes the confidence for a candidate}	Reasoning string	Value    inttype Score struct {// Score represents a confidence score for a candidate// ============================================================================// Scoring System// ============================================================================}	return true	}		}			return false		if c.System == "ExchangeFeed" && c.IsOfficial {	for _, c := range candidates {func (re *RulesEngine) DetectMissingOfficialFeed(candidates []Candidate) bool {// DetectMissingOfficialFeed flags when no official exchange data exists// ============================================================================// Conflict Detection Rules// ============================================================================}	return false, nil	}		}			}				return true, alternatives				}					}						alternatives = append(alternatives, c)					if c.SourceID != winner.SourceID {				for _, c := range candidates {				var alternatives []Candidate				// Collect alternatives (all non-winners)			if highConfidenceCandidates[i].Value != highConfidenceCandidates[i+1].Value {		for i := 0; i < len(highConfidenceCandidates)-1; i++ {		// Check variance in values	if len(highConfidenceCandidates) > 1 {	// Conflict exists if multiple high-confidence sources have different values	}		}			highConfidenceCandidates = append(highConfidenceCandidates, c)		if c.Confidence > 90 {	for _, c := range candidates {	var highConfidenceCandidates []Candidate	// Flag if multiple high-confidence sources disagree on business day statusfunc (re *RulesEngine) detectConflicts(candidates []Candidate, winner *Candidate) (bool, []Candidate) {// detectConflicts identifies high-priority disagreements}	return fmt.Sprintf("Priority 4: Default Source %s", candidate.System)	}		return fmt.Sprintf("Priority 3: StewardOverride (Confidence %d)", candidate.Confidence)	if candidate.System == "ManualSteward" {	}		return fmt.Sprintf("Priority 2: MajorVendor %s (Confidence %d)%s", candidate.System, candidate.Confidence, latencyStr)		}			latencyStr = fmt.Sprintf(" - Latency: %dh", *candidate.Latency)		if candidate.Latency != nil && *candidate.Latency < 24 {		var latencyStr string	if candidate.System == "Bloomberg" || candidate.System == "Refinitiv" {	}		return "Priority 1: ExchangeOfficial (Confidence 100)"	if candidate.System == "ExchangeFeed" && candidate.IsOfficial {func (re *RulesEngine) getRuleApplied(candidate *Candidate) string {// getRuleApplied returns the rule name that was applied}	return best	}		}			best = &candidates[i]			(candidates[i].Priority == best.Priority && candidates[i].TimeIngested.After(best.TimeIngested)) {		if candidates[i].Priority < best.Priority ||	for i := range candidates {	best := &candidates[0]	// Priority 4: Remaining (ordered by priority score and recency)	}		}			return &candidates[i]		if candidates[i].System == "ManualSteward" && candidates[i].Priority < 50 {	for i := range candidates {	// Priority 3: Internal Steward Override (via source_priority < 50)	}		}			return &candidates[i]			(candidates[i].Latency == nil || *candidates[i].Latency < 24) {		if (candidates[i].System == "Bloomberg" || candidates[i].System == "Refinitiv") &&	for i := range candidates {	// Priority 2: Premium Vendor (Bloomberg/Refinitiv) with low latency	}		}			return &candidates[i]		if candidates[i].System == "ExchangeFeed" && candidates[i].IsOfficial {	for i := range candidates {	// Priority 1: Official Exchange Data (Highest Trust)func (re *RulesEngine) applyPriorityHierarchy(candidates []Candidate) *Candidate {// applyPriorityHierarchy implements the priority selection logic}	return result, nil	result.ConflictDetected, result.AlternativeCandidates = re.detectConflicts(execCtx.Candidates, winner)	// Detect conflicts	result.RuleApplied = re.getRuleApplied(winner)	result.WinningCandidate = winner	winner := re.applyPriorityHierarchy(execCtx.Candidates)	// Apply priority hierarchy	}		return result, fmt.Errorf("no candidates available for survivorship")	if len(execCtx.Candidates) == 0 {	}		ExecID:       uuid.New(),		SemanticTerm: "IsBusinessDay",	result := &RuleResult{func (re *RulesEngine) ExecuteCalendarSurvivorship(ctx context.Context, execCtx ExecutionContext) (*RuleResult, error) {// ExecuteCalendarSurvivorship executes survivorship rules for IsBusinessDay// ============================================================================// Priority-Based Survivorship Rules// ============================================================================}	}		externalRulesDB: make(map[string]*RuleDef),	return &RulesEngine{func NewRulesEngine() *RulesEngine {// NewRulesEngine creates a new rules engine}	Score    func(*Candidate) int	Conditions func(*ExecutionContext, *Candidate) bool	Priority int	Name     stringtype RuleDef struct {// RuleDef defines a rule with priority, conditions, and scoring}	externalRulesDB map[string]*RuleDef // Allow loading rules from external sourcetype RulesEngine struct {// RulesEngine implements survivorship logic}	AlternativeCandidates []Candidate	ConflictDetected   bool	ExecID             uuid.UUID	RuleApplied        string	WinningCandidate   *Candidate	SemanticTerm       stringtype RuleResult struct {// RuleResult represents the outcome of rule execution}	TimeIngested time.Time	Confidence  int	Latency     *int // Hours	IsOfficial  bool	Priority    int	Value       bool	System      string	SourceID    uuid.UUIDtype Candidate struct {// Candidate represents a potential source for the semantic term}	Candidates     []Candidate	ExchangeCode   *string	RegionCode     string	DateKey        time.Time	BusinessObject string	TenantID       uuid.UUIDtype ExecutionContext struct {// ExecutionContext holds the context for rule execution// ============================================================================// Survivorship Rules Engine// ============================================================================)	"github.com/hondyman/semlayer/mdm-service/internal/domain"	"github.com/google/uuid"	"time"	"fmt"	"encoding/json"	"context"