import React, { useState, useEffect, useRef } from 'react';
import {
  Box,
  Typography,
  TextField,
  Select,
  MenuItem,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Button,
  IconButton,
  Stack,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  useTheme,
  alpha,
  Checkbox,
  Menu,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  CircularProgress,
  Alert,
} from '@mui/material';
import {
  Search as SearchIcon,
  FilterList as FilterListIcon,
  Code as CodeIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Error as ErrorIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  Download as DownloadIcon,
  History as HistoryIcon,
  Settings as SettingsIcon,
  ExpandMore as ExpandMoreIcon,
  MoreVert as MoreVertIcon,
} from '@mui/icons-material';
import { useTenant } from '../../../contexts/TenantContext';
import { useNotification } from '../../../hooks/useNotification';
import { devLog, devError } from '../../../utils/devLogger';
import AuditLogDialog from '../dialogs/AuditLogDialog';
import SettingsDialog, { ValidationSettings } from '../dialogs/SettingsDialog';
import ExpressionBuilder from '../../../components/ExpressionBuilder/ExpressionBuilder';
import { ConditionGroup } from '../../../components/ExpressionBuilder/AdvancedConditionBuilder';

// Helper to convert ConditionGroup to CUE string
const conditionGroupToCue = (group: ConditionGroup): string => {
  if (!group.conditions || group.conditions.length === 0) return 'true';

  const parts = group.conditions.map((node: any) => {
    if (node.type === 'group') {
      return `(${conditionGroupToCue(node)})`;
    } else {
      // Condition
      const field = node.field;
      const val = isNaN(Number(node.value)) ? `"${node.value}"` : node.value;
      
      switch (node.operator) {
        case 'equals': return `${field} == ${val}`;
        case 'not_equals': return `${field} != ${val}`;
        case 'greater_than': return `${field} > ${val}`;
        case 'less_than': return `${field} < ${val}`;
        case 'greater_equal': return `${field} >= ${val}`;
        case 'less_equal': return `${field} <= ${val}`;
        case 'contains': return `strings.Contains(${field}, ${val})`;
        case 'starts_with': return `strings.HasPrefix(${field}, ${val})`;
        case 'ends_with': return `strings.HasSuffix(${field}, ${val})`;
        case 'is_empty': return `${field} == "" || ${field} == null`;
        case 'is_not_empty': return `${field} != "" && ${field} != null`;
        case 'is_true': return `${field} == true`;
        case 'is_false': return `${field} == false`;
        // Date operators (simplistic mapping for CUE)
        case 'before': return `${field} < ${val}`;
        case 'after': return `${field} > ${val}`;
        default: return `${field} == ${val}`;
      }
    }
  });

  const joinOp = group.operator === 'AND' ? ' && ' : ' || ';
  return parts.join(joinOp);
};

// Helper to attempt parsing CUE string back to ConditionGroup (Basic implementation)
// Note: This is a heuristic parser and only works for simple expressions generated by the builder.
// Complex CUE manually written will likely fail to parse perfectly and should default to Code mode.
const cueToConditionGroup = (cue: string): ConditionGroup | null => {
  try {
    if (!cue || cue.trim() === '') return null;
    
    // Very basic check if it looks like a builder expression
    // If it contains advanced CUE syntax not generated by builder, return null
    if (cue.includes('{') || cue.includes('for ') || cue.includes('if ')) return null;

    // This is a placeholder. Implementing a full CUE parser is complex.
    // For now, we only initialize the builder if logic matches a known pattern or is empty.
    // If we can't parse it, we return null, confusing the user less than a wrong tree.
    return null; 
  } catch (e) {
    return null;
  }
};

interface ValidationRule {
  id: string;
  name: string;
  description: string;
  type: 'expression' | 'regex' | 'lookup';
  severity: 'error' | 'warning' | 'info';
  status: 'active' | 'inactive';
  logic?: string;
  appliedFields?: string[];
}

interface SemanticField {
  key: string;
  name: string;
  displayName?: string;
  technicalName?: string;
  type: string;
  semanticTerms?: string[];
  semanticId?: string;
  description?: string;
  group?: string;
}

interface ValidationRulesPageProps {
  businessObjectId?: string;
  businessObjectName?: string;
  selectedNodeType?: 'root' | 'subtype' | 'field' | 'group';
  selectedNodeName?: string;
  fields?: SemanticField[];
  rules?: ValidationRule[];
  onRulesUpdate?: (rules: ValidationRule[]) => void;
  onAddRule?: () => void;
  onEditRule?: (rule: any) => void;
}

const ValidationRulesPage: React.FC<ValidationRulesPageProps> = ({ 
  businessObjectId, 
  businessObjectName,
  selectedNodeType,
  selectedNodeName,
  fields = [],
  rules: externalRules,
  onRulesUpdate,
  onAddRule,
  onEditRule
}) => {
  const theme = useTheme();
  const notification = useNotification();
  const { tenant, datasource } = useTenant();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [rules, setRules] = useState<ValidationRule[]>([]);

  const [searchQuery, setSearchQuery] = useState('');
  const [severityFilter, setSeverityFilter] = useState<string>('');
  const [typeFilter, setTypeFilter] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('');
  const [visibleCount, setVisibleCount] = useState(20);
  const observerTarget = useRef(null);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [viewLogicOpen, setViewLogicOpen] = useState(false);
  const [auditLogOpen, setAuditLogOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [selectedRule, setSelectedRule] = useState<ValidationRule | null>(null);
  const [deleteConfirm, setDeleteConfirm] = useState<ValidationRule | null>(null);
  const [formData, setFormData] = useState<Partial<ValidationRule>>({});
  const [selectedRules, setSelectedRules] = useState<Set<string>>(new Set());
  const [bulkActionAnchor, setBulkActionAnchor] = useState<null | HTMLElement>(null);
  const [exportMenuAnchor, setExportMenuAnchor] = useState<null | HTMLElement>(null);
  const [advancedFiltersExpanded, setAdvancedFiltersExpanded] = useState(false);
  const [availableFields, setAvailableFields] = useState<SemanticField[]>([]);
  const [validationSettings, setValidationSettings] = useState<ValidationSettings>({
    stopOnFirstError: true,
    notifyOnFailures: true,
    emailDigest: false,
    cacheResults: true,
    cacheDurationMinutes: 5,
    logAllValidations: true,
    maxRulesPerObject: 100,
    timeoutSeconds: 30,
  });
  
  // Visual Builder State
  const [isVisualMode, setIsVisualMode] = useState(true);
  const [visualTree, setVisualTree] = useState<ConditionGroup>({
    id: 'root',
    type: 'group',
    operator: 'AND',
    conditions: []
  });

  const tenantId = tenant?.id || '';
  const datasourceId = datasource?.id || datasource?.alpha_tenant_instance_id || '';

  // Sync fields from parent component
  useEffect(() => {
    if (fields && fields.length > 0) {
      setAvailableFields(fields);
      devLog('Available semantic fields:', fields.length);
    }
  }, [fields]);

  // Sync rules from external prop if provided - avoid loop by checking identity
  useEffect(() => {
    if (externalRules && externalRules !== rules) {
      // Normalize external rules to match ValidationRule interface
      const normalized = externalRules.map((rule: any) => ({
        id: rule.id || rule.key || rule.rule_id,
        name: rule.name || rule.rule_name || 'Untitled Rule',
        description: rule.description || '',
        type: (rule.type || rule.rule_type || 'expression').toLowerCase() as 'expression' | 'regex' | 'lookup',
        severity: (rule.severity || 'error').toLowerCase() as 'error' | 'warning' | 'info',
        status: rule.status === 'inactive' || rule.status === false || rule.is_inactive ? 'inactive' : 'active',
        logic: rule.logic || rule.rule_definition || '',
      })) as ValidationRule[];
      
      setRules(normalized);
      setLoading(false); // Stop loading if rules are provided
    }
  }, [externalRules]);

  // Fetch validation rules from backend
  const fetchRules = async () => {
      if (externalRules) return; // Skip if parent is managing rules
      if (!tenantId || !datasourceId) {
        // No tenant/datasource context - show sample data
        devLog('No tenant/datasource context, using sample data');
        setRules([
          {
            id: '1',
            name: 'check_invoice_total_positive',
            description: 'Ensures total is > 0',
            type: 'expression',
            severity: 'error',
            status: 'active',
            logic: 'total > 0',
          },
          {
            id: '2',
            name: 'validate_vendor_tax_id',
            description: 'Checks format of Tax ID',
            type: 'regex',
            severity: 'warning',
            status: 'active',
            logic: '^[0-9]{9}$',
          },
          {
            id: '3',
            name: 'cross_reference_po',
            description: 'Matches against PO table',
            type: 'lookup',
            severity: 'error',
            status: 'inactive',
            logic: 'SELECT * FROM po_table WHERE po_id = @po_id',
          },
          {
            id: '4',
            name: 'check_due_date_future',
            description: 'Due date must be > today',
            type: 'expression',
            severity: 'warning',
            status: 'active',
            logic: 'due_date > TODAY()',
          },
        ]);
        setLoading(false);
        return;
      }

      setLoading(true);
      setError(null);

      try {
        const params = new URLSearchParams({
          tenant_id: tenantId,
          datasource_id: datasourceId,
          page: '1',
          limit: '100',
        });

        if (businessObjectName) {
          // If a subtype is selected, filter by subtype, otherwise filter by business object
          const targetEntity = selectedNodeType === 'subtype' && selectedNodeName ? selectedNodeName : businessObjectName;
          params.append('target_entity', targetEntity);
        }

        const response = await fetch(`/api/validation-rules?${params.toString()}`, {
          headers: {
            'X-Tenant-ID': tenantId,
            'X-Tenant-Datasource-ID': datasourceId,
          },
        });

        if (!response.ok) {
          throw new Error('Failed to fetch validation rules');
        }

        const data = await response.json();
        const rulesData = Array.isArray(data) ? data : (data.rules || []);
        
        console.log('[ValidationRulesPage] Raw rulesData from API:', rulesData);
        
        // Transform backend data to local ValidationRule format
        const transformedRules: ValidationRule[] = rulesData.map((rule: any) => {
          console.log('[ValidationRulesPage] Transforming rule:', rule.rule_name || rule.name);
          console.log('[ValidationRulesPage] - script_content:', rule.script_content);
          console.log('[ValidationRulesPage] - rule_definition:', rule.rule_definition);
          console.log('[ValidationRulesPage] - logic:', rule.logic);
          
          const transformed = {
            id: rule.id || rule.key,
            name: rule.rule_name || rule.name,
            description: rule.description || '',
            type: (rule.rule_type || 'expression').toLowerCase() as 'expression' | 'regex' | 'lookup',
            severity: (rule.severity || 'error').toLowerCase() as 'error' | 'warning' | 'info',
            status: rule.is_active === false ? 'inactive' : 'active',
            logic: rule.script_content || rule.rule_definition || rule.logic || '',
          };
          
          console.log('[ValidationRulesPage] - transformed.logic:', transformed.logic);
          return transformed;
        });

        setRules(transformedRules);
        devLog('Loaded validation rules:', transformedRules.length);
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Failed to load validation rules';
        devError('Error fetching validation rules:', err);
        setError(msg);
        // Fall back to sample data
        setRules([
          {
            id: '1',
            name: 'check_invoice_total_positive',
            description: 'Ensures total is > 0',
            type: 'expression',
            severity: 'error',
            status: 'active',
            logic: 'total > 0',
          },
          {
            id: '2',
            name: 'validate_vendor_tax_id',
            description: 'Checks format of Tax ID',
            type: 'regex',
            severity: 'warning',
            status: 'active',
            logic: '^[0-9]{9}$',
          },
        ]);
      } finally {
        setLoading(false);
      }
    };


  useEffect(() => {
    fetchRules();
  }, [tenantId, datasourceId, businessObjectId, businessObjectName, selectedNodeType, selectedNodeName]);

  // Reset visibleCount when filters change
  useEffect(() => {
    setVisibleCount(20);
  }, [searchQuery, severityFilter, typeFilter, statusFilter]);

  // Lazy loading IntersectionObserver
  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => {
        if (entries[0].isIntersecting) {
          setVisibleCount(prev => prev + 20);
        }
      },
      { threshold: 0.1 }
    );

    if (observerTarget.current) {
      observer.observe(observerTarget.current);
    }

    return () => {
      if (observerTarget.current) {
        observer.unobserve(observerTarget.current);
      }
    };
  }, []);

  // No longer notify parent via useEffect to avoid circular loops

  const filteredRules = rules.filter(rule => {
    const matchesSearch = searchQuery === '' || 
      rule.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      rule.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesSeverity = severityFilter === '' || rule.severity === severityFilter;
    const matchesType = typeFilter === '' || rule.type === typeFilter;
    const matchesStatus = statusFilter === '' || rule.status === statusFilter;
    return matchesSearch && matchesSeverity && matchesType && matchesStatus;
  });

  const lazyLoadedRules = filteredRules.slice(0, visibleCount);

  const handleCreateRule = () => {
    if (onAddRule) {
      onAddRule();
      return;
    }
    setFormData({ name: '', description: '', type: 'expression', severity: 'error', status: 'active' });
    setIsVisualMode(true);
    setVisualTree({ id: 'root', type: 'group', operator: 'AND', conditions: [] });
    setCreateDialogOpen(true);
  };

  const handleSaveRule = async () => {
    if (!formData.name?.trim() || (!formData.description?.trim() && !formData.logic?.trim() && !isVisualMode)) {
      notification.error('Please fill in required fields');
      return;
    }

    // Determine payload
    const payload: any = {
      rule_name: formData.name,
      description: formData.description || '',
      rule_type: formData.type || 'business_logic',
      severity: formData.severity || 'error',
      target_entity: selectedNodeType === 'subtype' && selectedNodeName ? selectedNodeName : businessObjectName,
      datasource_id: datasourceId,
      is_active: formData.status !== 'inactive',
      is_core: false // Pending logic for core rules
    };

    // Handle Logic/Condition
    if (isVisualMode && formData.type === 'expression') {
      // Send Visual Tree as condition_json
      payload.condition_json = visualTree;
      // Also generate CUE for script_content as fallback/backend usage
      payload.script_content = conditionGroupToCue(visualTree);
    } else {
      // Code mode
      payload.script_content = formData.logic;
      // Clear condition_json if switching to code to avoid ambiguity or keep it? 
      // Safest to send what we have.
    }

    try {
      if (editDialogOpen && selectedRule) {
        // Update
        const response = await fetch(`/api/validation-rules/${selectedRule.id}?tenant_id=${tenantId}`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'X-Tenant-ID': tenantId,
            'X-Tenant-Datasource-ID': datasourceId
          },
          body: JSON.stringify(payload)
        });

        if (!response.ok) throw new Error('Failed to update rule');
        
        notification.success('Rule updated successfully');
        setEditDialogOpen(false);
      } else {
        // Create
        const response = await fetch(`/api/validation-rules?tenant_id=${tenantId}&datasource_id=${datasourceId}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-Tenant-ID': tenantId,
            'X-Tenant-Datasource-ID': datasourceId
          },
          body: JSON.stringify(payload)
        });

        if (!response.ok) {
           const errData = await response.json();
           throw new Error(errData.details || errData.error || 'Failed to create rule');
        }

        notification.success('Rule created successfully');
        setCreateDialogOpen(false);
      }

      setFormData({});
      // Refresh list
      fetchRules();

    } catch (err: any) {
      console.error('Save rule error:', err);
      notification.error(err.message || 'Failed to save rule');
    }
  };

  const handleEditRule = (rule: ValidationRule) => {
    if (onEditRule) {
      onEditRule(rule);
      return;
    }
    setSelectedRule(rule);
    setFormData(rule);
    
    // Attempt to parse logic to visual tree, else switch to code mode
    const parsedTree = cueToConditionGroup(rule.logic || '');
    if (parsedTree) {
      setVisualTree(parsedTree);
      setIsVisualMode(true);
    } else {
      setIsVisualMode(false);
      // setVisualTree empty/default
      setVisualTree({ id: 'root', type: 'group', operator: 'AND', conditions: [] });
    }
    setEditDialogOpen(true);
  };

  const handleDeleteRule = async (rule: ValidationRule) => {
    try {
      // Call the backend API to delete the rule
      const response = await fetch(`/api/validation-rules/${rule.id}`, {
        method: 'DELETE',
        headers: {
          'X-Tenant-ID': tenantId,
          'X-Tenant-Datasource-ID': datasourceId,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to delete rule');
      }

      // Update local state after successful deletion
      const updatedRules = rules.filter(r => r.id !== rule.id);
      setRules(updatedRules);
      if (onRulesUpdate) onRulesUpdate(updatedRules);
      notification.success('Rule deleted successfully');
      setDeleteConfirm(null);
    } catch (err) {
      notification.error(err instanceof Error ? err.message : 'Failed to delete rule');
    }
  };

  const handleSelectRule = (ruleId: string) => {
    const newSelected = new Set(selectedRules);
    if (newSelected.has(ruleId)) {
      newSelected.delete(ruleId);
    } else {
      newSelected.add(ruleId);
    }
    setSelectedRules(newSelected);
  };

  const handleSelectAll = () => {
    if (selectedRules.size === lazyLoadedRules.length) {
      setSelectedRules(new Set());
    } else {
      setSelectedRules(new Set(lazyLoadedRules.map(r => r.id)));
    }
  };

  const handleBulkToggleStatus = () => {
    const updatedRules = rules.map(r => {
      if (selectedRules.has(r.id)) {
        return { ...r, status: r.status === 'active' ? 'inactive' : 'active' as 'active' | 'inactive' };
      }
      return r;
    });
    setRules(updatedRules as ValidationRule[]);
    if (onRulesUpdate) onRulesUpdate(updatedRules as ValidationRule[]);
    setSelectedRules(new Set());
    notification.success(`${selectedRules.size} rule(s) updated successfully`);
    setBulkActionAnchor(null);
  };

  const handleBulkDelete = () => {
    const updatedRules = rules.filter(r => !selectedRules.has(r.id));
    setRules(updatedRules);
    if (onRulesUpdate) onRulesUpdate(updatedRules);
    setSelectedRules(new Set());
    notification.success(`${selectedRules.size} rule(s) deleted successfully`);
    setBulkActionAnchor(null);
  };

  const handleExport = (format: 'csv' | 'json') => {
    const dataToExport = selectedRules.size > 0 
      ? rules.filter(r => selectedRules.has(r.id))
      : filteredRules;

    if (format === 'csv') {
      const headers = ['Rule Name', 'Description', 'Type', 'Severity', 'Status'];
      const csvContent = [
        headers.join(','),
        ...dataToExport.map(rule =>
          [rule.name, rule.description, rule.type, rule.severity, rule.status].map(v => `"${v}"`).join(',')
        )
      ].join('\n');
      downloadFile(csvContent, `validation-rules-${new Date().toISOString().split('T')[0]}.csv`, 'text/csv');
    } else {
      const jsonContent = JSON.stringify(dataToExport, null, 2);
      downloadFile(jsonContent, `validation-rules-${new Date().toISOString().split('T')[0]}.json`, 'application/json');
    }
    notification.success(`Exported ${dataToExport.length} rule(s) successfully`);
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'error':
        return <ErrorIcon sx={{ color: '#dc2626', fontSize: '18px' }} />;
      case 'warning':
        return <WarningIcon sx={{ color: '#f59e0b', fontSize: '18px' }} />;
      case 'info':
        return <InfoIcon sx={{ color: '#3b82f6', fontSize: '18px' }} />;
      default:
        return null;
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'expression':
        return 'primary';
      case 'regex':
        return 'secondary';
      case 'lookup':
        return 'warning';
      default:
        return 'default';
    }
  };

  return (
    <Box sx={{ width: '100%', bgcolor: theme.palette.mode === 'dark' ? '#101922' : '#f5f7f8' }}>
      {error && (
        <Alert severity="error" sx={{ mx: 2, my: 2 }}>
          {error}
        </Alert>
      )}

      {loading && (
        <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', py: 6 }}>
          <CircularProgress />
        </Box>
      )}

      {!loading && (
        <>
          {/* Header */}
          <Box sx={{ px: 2, py: 2, borderBottom: '1px solid', borderColor: 'divider' }}>
            <Typography variant="subtitle1" sx={{ fontWeight: 500 }}>
              Validation Rules for: <strong>{selectedNodeType === 'subtype' ? selectedNodeName : businessObjectName}</strong>
              {selectedNodeType === 'subtype' && (
                <Chip label="Subtype" size="small" sx={{ ml: 1 }} />
              )}
            </Typography>
          </Box>

          {/* Search and Filters */}
          <Box sx={{ px: 2, py: 2 }}>
            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} alignItems="center">
              <TextField
                size="small"
                placeholder="Search by rule name or description..."
                InputProps={{
                  startAdornment: <SearchIcon sx={{ mr: 1, color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a' }} />,
                }}
                value={searchQuery}
                onChange={(e) => {
                  setSearchQuery(e.target.value);
                  setVisibleCount(20);
                }}
                sx={{
                  flex: 1,
                  '& .MuiOutlinedInput-root': {
                    bgcolor: theme.palette.mode === 'dark' ? '#1a2632' : '#ffffff',
                    color: theme.palette.mode === 'dark' ? '#fff' : '#111418',
                    '& fieldset': { borderColor: theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6' },
                    '&:hover fieldset': { borderColor: theme.palette.mode === 'dark' ? '#4a5b6c' : '#bbc1c9' }
                  }
                }}
              />
              <IconButton
                size="small"
                onClick={() => setAdvancedFiltersExpanded(!advancedFiltersExpanded)}
                sx={{ color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a' }}
              >
                <FilterListIcon />
              </IconButton>
              <Button
                variant="contained"
                startIcon={<AddIcon />}
                onClick={handleCreateRule}
                sx={{
                  bgcolor: '#0d7ff2',
                  color: '#fff',
                  '&:hover': { bgcolor: '#0a5fb8' }
                }}
              >
                Add Rule
              </Button>
            </Stack>

            {/* Advanced Filters */}
            {advancedFiltersExpanded && (
              <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ mt: 2 }}>
                <Select
                  size="small"
                  value={severityFilter}
                  onChange={(e) => {
                    setSeverityFilter(e.target.value);
                    setVisibleCount(20);
                  }}
                  displayEmpty
                  sx={{
                    flex: 1,
                    bgcolor: theme.palette.mode === 'dark' ? '#1a2632' : '#ffffff',
                    color: theme.palette.mode === 'dark' ? '#fff' : '#111418',
                    '& .MuiOutlinedInput-notchedOutline': { borderColor: theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6' }
                  }}
                >
                  <MenuItem value="">All Severities</MenuItem>
                  <MenuItem value="error">Error</MenuItem>
                  <MenuItem value="warning">Warning</MenuItem>
                  <MenuItem value="info">Info</MenuItem>
                </Select>

                <Select
                  size="small"
                  value={typeFilter}
                  onChange={(e) => {
                    setTypeFilter(e.target.value);
                    setVisibleCount(20);
                  }}
                  displayEmpty
                  sx={{
                    flex: 1,
                    bgcolor: theme.palette.mode === 'dark' ? '#1a2632' : '#ffffff',
                    color: theme.palette.mode === 'dark' ? '#fff' : '#111418',
                    '& .MuiOutlinedInput-notchedOutline': { borderColor: theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6' }
                  }}
                >
                  <MenuItem value="">All Types</MenuItem>
                  <MenuItem value="expression">Expression</MenuItem>
                  <MenuItem value="regex">Regex</MenuItem>
                  <MenuItem value="lookup">SQL Lookup</MenuItem>
                </Select>

                <Select
                  size="small"
                  value={statusFilter}
                  onChange={(e) => {
                    setStatusFilter(e.target.value);
                    setVisibleCount(20);
                  }}
                  displayEmpty
                  sx={{
                    flex: 1,
                    bgcolor: theme.palette.mode === 'dark' ? '#1a2632' : '#ffffff',
                    color: theme.palette.mode === 'dark' ? '#fff' : '#111418',
                    '& .MuiOutlinedInput-notchedOutline': { borderColor: theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6' }
                  }}
                >
                  <MenuItem value="">All Statuses</MenuItem>
                  <MenuItem value="active">Active</MenuItem>
                  <MenuItem value="inactive">Inactive</MenuItem>
                </Select>
              </Stack>
            )}

            {/* Bulk Actions */}
            {selectedRules.size > 0 && (
              <Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 2, p: 2, bgcolor: theme.palette.mode === 'dark' ? '#202b38' : '#f3f4f6', borderRadius: '0.5rem' }}>
                <Typography variant="body2" sx={{ flex: 1, color: theme.palette.mode === 'dark' ? '#fff' : '#111418', fontWeight: 500 }}>
                  {selectedRules.size} rule{selectedRules.size > 1 ? 's' : ''} selected
                </Typography>
                <Stack direction="row" spacing={1}>
                  <Button
                    size="small"
                    onClick={handleBulkToggleStatus}
                    sx={{
                      color: '#0d7ff2',
                      '&:hover': { bgcolor: alpha('#0d7ff2', 0.1) }
                    }}
                  >
                    Toggle Status
                  </Button>
                  <Button
                    size="small"
                    startIcon={<DownloadIcon />}
                    onClick={(e) => setExportMenuAnchor(e.currentTarget)}
                    sx={{
                      color: '#0d7ff2',
                      '&:hover': { bgcolor: alpha('#0d7ff2', 0.1) }
                    }}
                  >
                    Export
                  </Button>
                  <Button
                    size="small"
                    onClick={handleBulkDelete}
                    sx={{
                      color: '#dc2626',
                      '&:hover': { bgcolor: alpha('#dc2626', 0.1) }
                    }}
                  >
                    Delete
                  </Button>
                </Stack>
              </Stack>
            )}

            {/* Export Menu */}
            <Menu
              anchorEl={exportMenuAnchor}
              open={Boolean(exportMenuAnchor)}
              onClose={() => setExportMenuAnchor(null)}
            >
              <MenuItem onClick={() => handleExport('csv')}>Export as CSV</MenuItem>
              <MenuItem onClick={() => handleExport('json')}>Export as JSON</MenuItem>
            </Menu>
          </Box>

          {/* Table */}
          <Box sx={{ px: 2, pb: 2 }}>
            <TableContainer sx={{
              borderRadius: '0.75rem',
              border: `1px solid ${theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6'}`,
              bgcolor: theme.palette.mode === 'dark' ? '#1a2632' : '#ffffff',
              boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)'
            }}>
              <Table>
                <TableHead>
                  <TableRow sx={{ bgcolor: theme.palette.mode === 'dark' ? '#202b38' : '#f9fafb' }}>
                    <TableCell padding="checkbox">
                      <Checkbox
                        checked={selectedRules.size === lazyLoadedRules.length && lazyLoadedRules.length > 0}
                        indeterminate={selectedRules.size > 0 && selectedRules.size < lazyLoadedRules.length}
                        onChange={handleSelectAll}
                      />
                    </TableCell>
                    <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a', width: '25%' }}>Rule Name</TableCell>
                    <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a', width: '15%' }}>Type</TableCell>
                    <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a', width: '15%' }}>Severity</TableCell>
                    <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a', width: '15%' }}>Status</TableCell>
                    <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a', textAlign: 'right', width: '30%' }}>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody sx={{ '& tr': { borderBottomColor: theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6' } }}>
                  {lazyLoadedRules.length > 0 ? (
                    lazyLoadedRules.map((rule) => (
                      <TableRow
                        key={rule.id}
                        hover
                        selected={selectedRules.has(rule.id)}
                        sx={{
                          '&:hover': {
                            bgcolor: theme.palette.mode === 'dark' ? '#202b38' : '#f9fafb'
                          },
                          '&:hover .action-buttons': {
                            opacity: 1,
                          }
                        }}
                      >
                        <TableCell padding="checkbox">
                          <Checkbox
                            checked={selectedRules.has(rule.id)}
                            onChange={() => handleSelectRule(rule.id)}
                          />
                        </TableCell>
                        <TableCell sx={{ py: 2 }}>
                          <Box>
                            <Typography variant="body2" fontWeight={600} sx={{ color: theme.palette.mode === 'dark' ? '#fff' : '#111418' }}>
                              {rule.name}
                            </Typography>
                            <Typography variant="caption" sx={{ color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a' }}>
                              {rule.description}
                            </Typography>
                          </Box>
                        </TableCell>
                        <TableCell sx={{ py: 2 }}>
                          <Box sx={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            px: '10px',
                            py: '4px',
                            borderRadius: '0.25rem',
                            fontSize: '0.75rem',
                            fontWeight: 500,
                            bgcolor: rule.type === 'expression' ? '#dbeafe' : rule.type === 'regex' ? '#e9d5ff' : '#fef3c7',
                            color: rule.type === 'expression' ? '#1e40af' : rule.type === 'regex' ? '#6b21a8' : '#92400e'
                          }}>
                            {rule.type ? rule.type.charAt(0).toUpperCase() + rule.type.slice(1) : '-'}
                          </Box>
                        </TableCell>
                        <TableCell sx={{ py: 2 }}>
                          <Stack direction="row" spacing={1} alignItems="center">
                            {getSeverityIcon(rule.severity)}
                            <Typography variant="body2" fontWeight={500} sx={{ color: theme.palette.mode === 'dark' ? '#fff' : '#111418' }}>
                              {rule.severity ? rule.severity.charAt(0).toUpperCase() + rule.severity.slice(1) : '-'}
                            </Typography>
                          </Stack>
                        </TableCell>
                        <TableCell sx={{ py: 2 }}>
                          <Stack direction="row" spacing={1} alignItems="center">
                            <Box sx={{
                              width: 8,
                              height: 8,
                              borderRadius: '50%',
                              bgcolor: rule.status === 'active' ? '#22c55e' : theme.palette.mode === 'dark' ? '#4b5563' : '#d1d5db'
                            }} />
                            <Typography variant="body2" sx={{ color: rule.status === 'active' ? (theme.palette.mode === 'dark' ? '#fff' : '#111418') : (theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a') }}>
                              {rule.status ? rule.status.charAt(0).toUpperCase() + rule.status.slice(1) : '-'}
                            </Typography>
                          </Stack>
                        </TableCell>
                        <TableCell align="right" sx={{ py: 2 }}>
                          <Stack
                            direction="row"
                            spacing={0.5}
                            justifyContent="flex-end"
                            className="action-buttons"
                            sx={{ opacity: { xs: 1, md: 0 }, transition: 'opacity 0.2s' }}
                          >
                            <IconButton
                              size="small"
                              onClick={() => {
                                console.log('[ValidationRulesPage] View Logic clicked for rule:', rule);
                                console.log('[ValidationRulesPage] rule.logic:', rule.logic);
                                setSelectedRule(rule);
                                setViewLogicOpen(true);
                              }}
                              title="View Logic"
                              sx={{
                                p: 1,
                                color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a',
                                '&:hover': {
                                  color: 'primary.main',
                                  bgcolor: theme.palette.mode === 'dark' ? '#2a3845' : '#f3f4f6'
                                }
                              }}
                            >
                              <CodeIcon fontSize="small" />
                            </IconButton>
                            <IconButton
                              size="small"
                              onClick={() => handleEditRule(rule)}
                              title="Edit Rule"
                              sx={{
                                p: 1,
                                color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a',
                                '&:hover': {
                                  color: 'primary.main',
                                  bgcolor: theme.palette.mode === 'dark' ? '#2a3845' : '#f3f4f6'
                                }
                              }}
                            >
                              <EditIcon fontSize="small" />
                            </IconButton>
                            <IconButton
                              size="small"
                              onClick={() => setDeleteConfirm(rule)}
                              title="Delete"
                              sx={{
                                p: 1,
                                color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a',
                                '&:hover': {
                                  color: '#dc2626',
                                  bgcolor: theme.palette.mode === 'dark' ? '#7f1d1d' : '#fee2e2'
                                }
                              }}
                            >
                              <DeleteIcon fontSize="small" />
                            </IconButton>
                          </Stack>
                        </TableCell>
                      </TableRow>
                    ))
                  ) : (
                    <TableRow>
                      <TableCell colSpan={6} align="center" sx={{ py: 4 }}>
                        <Typography color="text.secondary">
                          {filteredRules.length === 0 ? 'No validation rules found' : 'No results to display'}
                        </Typography>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </TableContainer>

            {/* Lazy Loading Sentinel and Footer */}
            <Box sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              px: 3,
              py: 2,
              bgcolor: theme.palette.mode === 'dark' ? '#202b38' : '#f9fafb',
              borderTop: `1px solid ${theme.palette.mode === 'dark' ? '#3a4b5c' : '#dbe0e6'}`,
              borderBottomLeftRadius: '0.75rem',
              borderBottomRightRadius: '0.75rem'
            }}>
              <Typography variant="body2" sx={{ color: theme.palette.mode === 'dark' ? '#9aaab9' : '#60758a' }}>
                Showing <Typography component="span" fontWeight={600} sx={{ color: theme.palette.mode === 'dark' ? '#fff' : '#111418' }}>
                  {Math.min(lazyLoadedRules.length, filteredRules.length)}
                </Typography> of <Typography component="span" fontWeight={600} sx={{ color: theme.palette.mode === 'dark' ? '#fff' : '#111418' }}>
                  {filteredRules.length}
                </Typography> results
              </Typography>
              
              {/* Observer Sentinel */}
              <div ref={observerTarget} style={{ height: '10px', width: '100%', position: 'absolute', bottom: 0 }} />
            </Box>
          </Box>
        </>
      )}

      {/* Create/Edit Rule Dialog */}
      <Dialog open={createDialogOpen || editDialogOpen} onClose={() => { setCreateDialogOpen(false); setEditDialogOpen(false); }} maxWidth="sm" fullWidth>
        <DialogTitle>
          {editDialogOpen ? 'Edit Validation Rule' : 'Create New Validation Rule'}
        </DialogTitle>
        <DialogContent sx={{ pt: 2 }}>
          <Stack spacing={2}>
            <TextField
              fullWidth
              label="Rule Name"
              value={formData.name || ''}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="e.g., check_invoice_total"
              size="small"
            />
            <TextField
              fullWidth
              label="Description"
              value={formData.description || ''}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="What this rule validates"
              size="small"
            />
            {availableFields.length > 0 && (
              <Box>
                <Typography variant="subtitle2" sx={{ mb: 1 }}>Apply to Fields (Optional)</Typography>
                <Stack direction="row" spacing={1} sx={{ flexWrap: 'wrap', gap: 1 }}>
                  {availableFields.map((field) => (
                    <Chip
                      key={field.key}
                      label={field.displayName || field.name}
                      onClick={() => {
                        const appliedFields = formData.appliedFields || [];
                        const index = appliedFields.indexOf(field.key);
                        if (index > -1) {
                          appliedFields.splice(index, 1);
                        } else {
                          appliedFields.push(field.key);
                        }
                        setFormData({ ...formData, appliedFields: [...appliedFields] });
                      }}
                      variant={formData.appliedFields?.includes(field.key) ? 'filled' : 'outlined'}
                      color={formData.appliedFields?.includes(field.key) ? 'primary' : 'default'}
                      size="small"
                    />
                  ))}
                </Stack>
              </Box>
            )}
            <Select
              fullWidth
              value={formData.type || 'expression'}
              onChange={(e) => setFormData({ ...formData, type: e.target.value as any })}
              size="small"
            >
              <MenuItem value="expression">Expression</MenuItem>
              <MenuItem value="regex">Regex</MenuItem>
              <MenuItem value="lookup">SQL Lookup</MenuItem>
            </Select>
            <Select
              fullWidth
              value={formData.severity || 'error'}
              onChange={(e) => setFormData({ ...formData, severity: e.target.value as any })}
              size="small"
            >
              <MenuItem value="error">Error</MenuItem>
              <MenuItem value="warning">Warning</MenuItem>
              <MenuItem value="info">Info</MenuItem>
            </Select>

            {/* Toggle between Visual and Code */}
            {formData.type === 'expression' && (
               <Stack direction="row" spacing={1} alignItems="center" justifyContent="flex-end">
                 <Typography variant="caption" color="text.secondary">Mode:</Typography>
                 <Button 
                   size="small" 
                   variant={isVisualMode ? 'contained' : 'outlined'} 
                   onClick={() => setIsVisualMode(true)}
                   sx={{ fontSize: '0.7rem', py: 0.5, minWidth: 'auto' }}
                 >
                   Visual
                 </Button>
                 <Button 
                   size="small" 
                   variant={!isVisualMode ? 'contained' : 'outlined'} 
                   onClick={() => setIsVisualMode(false)}
                   sx={{ fontSize: '0.7rem', py: 0.5, minWidth: 'auto' }}
                 >
                   Code (CUE)
                 </Button>
               </Stack>
            )}

            {isVisualMode && formData.type === 'expression' ? (
              <Box sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1, p: 1 }}>
                <ExpressionBuilder
                  availableFields={availableFields.map(f => ({
                    name: f.name,
                    label: f.displayName || f.name,
                    type: f.type || 'string'
                  }))}
                  onChange={(tree: ConditionGroup) => {
                    setVisualTree(tree);
                    const cue = conditionGroupToCue(tree);
                    setFormData({ ...formData, logic: cue });
                  }}
                  autosave={false}
                />
                <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
                  Generated Logic: <code>{formData.logic}</code>
                </Typography>
              </Box>
            ) : (
              <TextField
                fullWidth
                label="Logic / Formula"
                value={formData.logic || ''}
                onChange={(e) => setFormData({ ...formData, logic: e.target.value })}
                multiline
                rows={4}
                placeholder="Enter the validation logic (CUE expression)"
                size="small"
                inputProps={{ style: { fontFamily: 'monospace', fontSize: '0.875rem' } }}
              />
            )}
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setCreateDialogOpen(false); setEditDialogOpen(false); }}>Cancel</Button>
          <Button onClick={handleSaveRule} variant="contained">
            {editDialogOpen ? 'Update Rule' : 'Create Rule'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* View Logic Dialog */}
      <Dialog open={viewLogicOpen} onClose={() => setViewLogicOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>Rule Logic: {selectedRule?.name}</DialogTitle>
        <DialogContent sx={{ pt: 2 }}>
          <Stack spacing={2}>
            {selectedRule && (
              <>
                {/* CUE Code Section */}
                <Box>
                  <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 600 }}>
                    CUE Validation Code
                  </Typography>
                  <Box sx={{ 
                    p: 2, 
                    bgcolor: theme.palette.mode === 'dark' ? 'grey.900' : 'grey.100', 
                    borderRadius: 1, 
                    fontFamily: 'monospace', 
                    whiteSpace: 'pre-wrap', 
                    wordBreak: 'break-word',
                    fontSize: '0.875rem',
                    border: `1px solid ${theme.palette.mode === 'dark' ? 'grey.800' : 'grey.300'}`
                  }}>
                    {selectedRule?.logic || 'No CUE code available for this rule'}
                  </Box>
                  <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
                    This is the CUE validation code that will be executed against your data.
                  </Typography>
                </Box>
                
                {/* Raw Logic/Metadata Section */}
                <Box>
                  <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 600 }}>
                    Rule Details
                  </Typography>
                  <Box sx={{ 
                    p: 2, 
                    bgcolor: theme.palette.mode === 'dark' ? '#1a1a1a' : '#f9f9f9', 
                    borderRadius: 1, 
                    fontSize: '0.875rem',
                    border: `1px solid ${theme.palette.mode === 'dark' ? 'grey.800' : 'grey.300'}`
                  }}>
                    <Stack spacing={1}>
                      <Box>
                        <Typography variant="caption" color="text.secondary">Type:</Typography>
                        <Typography variant="body2">{selectedRule.type}</Typography>
                      </Box>
                      <Box>
                        <Typography variant="caption" color="text.secondary">Severity:</Typography>
                        <Typography variant="body2">{selectedRule.severity}</Typography>
                      </Box>
                      <Box>
                        <Typography variant="caption" color="text.secondary">Status:</Typography>
                        <Typography variant="body2">{selectedRule.status}</Typography>
                      </Box>
                    </Stack>
                  </Box>
                </Box>
              </>
            )}
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setViewLogicOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={Boolean(deleteConfirm)} onClose={() => setDeleteConfirm(null)}>
        <DialogTitle>Delete Validation Rule</DialogTitle>
        <DialogContent>
          <Typography>
            Are you sure you want to delete <strong>{deleteConfirm?.name}</strong>?
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteConfirm(null)}>Cancel</Button>
          <Button onClick={() => deleteConfirm && handleDeleteRule(deleteConfirm)} color="error" variant="contained">
            Delete
          </Button>
        </DialogActions>
      </Dialog>

      {/* Bulk Actions Menu */}
      <Menu
        anchorEl={bulkActionAnchor}
        open={Boolean(bulkActionAnchor)}
        onClose={() => setBulkActionAnchor(null)}
      >
        <MenuItem onClick={handleBulkToggleStatus}>
          {rules.some(r => selectedRules.has(r.id) && r.status === 'active') ? 'Deactivate Selected' : 'Activate Selected'}
        </MenuItem>
        <MenuItem onClick={() => handleExport('csv')}>Export Selected as CSV</MenuItem>
        <MenuItem onClick={() => handleExport('json')}>Export Selected as JSON</MenuItem>
        <MenuItem onClick={handleBulkDelete} sx={{ color: 'error.main' }}>Delete Selected</MenuItem>
      </Menu>

      {/* Audit Log Dialog */}
      <AuditLogDialog open={auditLogOpen} onClose={() => setAuditLogOpen(false)} />

      {/* Settings Dialog */}
      <SettingsDialog
        open={settingsOpen}
        onClose={() => setSettingsOpen(false)}
        initialSettings={validationSettings}
        onSave={(newSettings) => {
          setValidationSettings(newSettings);
          notification.success('Settings saved successfully');
        }}
      />
    </Box>
  );
};

export default ValidationRulesPage;
