package domain
package domain

































































































































































































































































}	Status                    string     `json:"status"` // "healthy", "warning", "critical"	DaysSinceLastOfficialFeed int        `json:"days_since_last_official_feed"`	HighConfidencePercentage  float64    `json:"high_confidence_percentage"`	ConflictCount             int        `json:"conflict_count"`	CoveragePercentage        float64    `json:"coverage_percentage"`	TenantID                  uuid.UUID  `json:"tenant_id"`type HealthCheckResponse struct {// HealthCheckResponse provides operational metrics}	SourceStats    json.RawMessage  `json:"source_stats"`	History        []LineageRecord  `json:"history"`	GoldenRecordID uuid.UUID        `json:"golden_record_id"`type LineageResponse struct {// LineageResponse provides the lineage audit trail}	Conflicts      []ConflictRecord   `json:"conflicts,omitempty"`	CoveragePercentage float64       `json:"coverage_percentage"`	Records        []HolidaySchedule `json:"records"`type GetGoldenCalendarResponse struct {// GetGoldenCalendarResponse is the API response}	Exchange  *string   `json:"exchange"`	Region    string    `json:"region" validate:"required"`	EndDate   time.Time `json:"end_date" validate:"required"`	StartDate time.Time `json:"start_date" validate:"required"`type GetGoldenCalendarRequest struct {// GetGoldenCalendarRequest is the API request for fetching golden records}	RawPayload    interface{} `json:"raw_payload"`	HolidayName   *string   `json:"holiday_name"`	IsBusinessDay bool      `json:"is_business_day"`	Exchange      *string   `json:"exchange"`	Region        string    `json:"region" validate:"required,len=2"`	Date          time.Time `json:"date" validate:"required"`type CalendarRaw struct {// CalendarRaw represents a single calendar record from source}	Data         []CalendarRaw `json:"data" validate:"required,min=1"`	IsOfficial   bool          `json:"is_official"`	ExternalID   *string       `json:"external_id"`	SourceSystem string        `json:"source_system" validate:"required"`type IngestRequest struct {// IngestRequest is the API request for ingesting source data// ============================================================================// Request/Response Models// ============================================================================}	CalculatedAt               time.Time `db:"calculated_at"`	LastOfficialFeedTimestamp  *time.Time `db:"last_official_feed_timestamp"`	DaysSinceLastOfficialFeed  int       `db:"days_since_last_official_feed"`	LowConfidenceCount         int       `db:"low_confidence_count"`	MediumConfidenceCount      int       `db:"medium_confidence_count"`	HighConfidenceCount        int       `db:"high_confidence_count"`	ConflictCount              int       `db:"conflict_count"`	CoveragePercentage         float64   `db:"coverage_percentage"`	DaysWithGoldenRecords      int       `db:"days_with_golden_records"`	TotalCalendarDays          int       `db:"total_calendar_days"`	TenantID                   uuid.UUID `db:"tenant_id"`	ID                         uuid.UUID `db:"id"`type HealthMetrics struct {// HealthMetrics provides operational intelligence// ============================================================================// Health Metrics// ============================================================================}	ChangeTime      time.Time  `db:"change_timestamp"`	ChangedBy       *uuid.UUID `db:"changed_by"`	ChangeReason    *string    `db:"change_reason"`	ConfidenceScore int        `db:"confidence_score"`	SourceType      string     `db:"source_type"`	HolidayName     *string    `db:"holiday_name"`	ExchangeCode    *string    `db:"exchange_code"`	RegionCode      string     `db:"region_code"`	IsBusinessDay   bool       `db:"is_business_day"`	CalendarDate    time.Time  `db:"calendar_date"`	VersionTime     time.Time  `db:"version_timestamp"`	VersionID       int        `db:"version_id"`	GoldenRecordID  uuid.UUID  `db:"golden_record_id"`	TenantID        uuid.UUID  `db:"tenant_id"`	ID              uuid.UUID  `db:"id"`type VersionRecord struct {// VersionRecord maintains historical snapshots for audit and replay// ============================================================================// Version Record (Time Travel)// ============================================================================}	CreatedAt            time.Time        `db:"created_at"`	StewardID            *uuid.UUID       `db:"steward_id"`	EscalatedToStewardAt *time.Time       `db:"escalated_to_steward_at"`	ResolutionNotes      *string          `db:"resolution_notes"`	ResolvedBy           *uuid.UUID       `db:"resolved_by"`	ResolvedAt           *time.Time       `db:"resolved_at"`	Status               string           `db:"status"`	Severity             string           `db:"severity"`	ConflictingSources   json.RawMessage  `db:"conflicting_sources"`	ConflictType         string           `db:"conflict_type"`	GoldenRecordID       uuid.UUID        `db:"golden_record_id"`	TenantID             uuid.UUID        `db:"tenant_id"`	ID                   uuid.UUID        `db:"id"`type ConflictRecord struct {// ConflictRecord represents a conflict that needs stewardship)	ConflictSeverityCritical ConflictSeverity = "critical"	ConflictSeverityHigh     ConflictSeverity = "high"	ConflictSeverityMedium   ConflictSeverity = "medium"	ConflictSeverityLow      ConflictSeverity = "low"const (type ConflictSeverity string)	ConflictStatusRejected  ConflictStatus = "rejected"	ConflictStatusResolved  ConflictStatus = "resolved"	ConflictStatusInReview  ConflictStatus = "in_review"	ConflictStatusOpen      ConflictStatus = "open"const (type ConflictStatus string)	ConflictTypeDataQualityIssue         ConflictType = "DataQualityIssue"	ConflictTypeMissingOfficial          ConflictType = "MissingOfficial"	ConflictTypeHighPriorityDisagreement ConflictType = "HighPriorityDisagreement"const (type ConflictType string// ============================================================================// Conflict Record (Stewardship Queue)// ============================================================================}	ConflictDetected bool            `db:"conflict_detected"`	ConflictingSources json.RawMessage `db:"conflicting_sources"`	ExecutionTime    time.Time       `db:"execution_timestamp"`	WASMExecutionID  *uuid.UUID      `db:"wasm_execution_id"`	PriorityLevel    int             `db:"priority_level"`	RuleApplied      string          `db:"rule_applied"`	WinningSourceID  *uuid.UUID      `db:"winning_source_id"`	WinningValue     string          `db:"winning_value"`	PreviousValue    *string         `db:"previous_value"`	SemanticTerm     string          `db:"semantic_term"`	GoldenRecordID   uuid.UUID       `db:"golden_record_id"`	TenantID         uuid.UUID       `db:"tenant_id"`	ID               uuid.UUID       `db:"id"`type LineageRecord struct {// LineageRecord tracks how each semantic term was resolved// ============================================================================// Lineage Record (Audit Trail)// ============================================================================}	RawPayload      json.RawMessage    `db:"raw_payload"`	IngestedBy      *uuid.UUID         `db:"ingested_by"`	IngestedAt      time.Time          `db:"ingested_at"`	IsOfficial      bool               `db:"is_official"`	LatencyHours    *int               `db:"latency_hours"`	SourcePriority  int                `db:"source_priority"`	ExternalID      *string            `db:"external_id"`	SourceSystem    string             `db:"source_system"`	HolidayName     *string            `db:"holiday_name"`	ExchangeCode    *string            `db:"exchange_code"`	RegionCode      string             `db:"region_code"`	IsBusinessDay   bool               `db:"is_business_day"`	CalendarDate    time.Time          `db:"calendar_date"`	GoldenRecordID  *uuid.UUID         `db:"golden_record_id"`	TenantID        uuid.UUID          `db:"tenant_id"`	ID              uuid.UUID          `db:"id"`type SourceRecord struct {// SourceRecord represents raw data from ingestion sources// ============================================================================// Source Record (Ingestion Staging)// ============================================================================}	UpdatedBy       *uuid.UUID     `db:"updated_by"`	CreatedBy       *uuid.UUID     `db:"created_by"`	UpdatedAt       time.Time      `db:"updated_at"`	CreatedAt       time.Time      `db:"created_at"`	IsDeleted       bool           `db:"is_deleted"`	VersionID       int            `db:"version_id"`	ConfidenceScore int            `db:"confidence_score"`	SourceType      string         `db:"source_type"`	HolidayName     *string        `db:"holiday_name"`	ExchangeCode    *string        `db:"exchange_code"`	RegionCode      string         `db:"region_code"`	IsBusinessDay   bool           `db:"is_business_day"`	CalendarDate    time.Time      `db:"calendar_date"`	TenantID        uuid.UUID      `db:"tenant_id"`	ID              uuid.UUID      `db:"id"`type HolidaySchedule struct {// HolidaySchedule is the primary business object for calendar data// ============================================================================// Business Object: HolidaySchedule// ============================================================================}	return cs >= 0 && cs <= 100func (cs ConfidenceScore) Valid() bool {type ConfidenceScore int// ConfidenceScore is 0-100 based on survivorship rules)	SourceTypeRegionalDefault SourceType = "RegionalDefault"	SourceTypeManualSteward SourceType = "ManualSteward"	SourceTypeRefinitiv     SourceType = "Refinitiv"	SourceTypeBloomberg     SourceType = "Bloomberg"	SourceTypeExchangeFeed  SourceType = "ExchangeFeed"const (type SourceType string// SourceType indicates the origin of datatype HolidayName string// HolidayName is the human-readable nametype ExchangeCode string// ExchangeCode is the ISO-10383 MIC Code (e.g., "XNYS", "XLON")type RegionCode string// RegionCode is the ISO-3166 Country Codetype IsBusinessDay bool// IsBusinessDay indicates whether markets/offices are opentype CalendarDate time.Time// CalendarDate represents the specific day being defined// ============================================================================// Semantic Terms (Atomic Meanings)// ============================================================================)	"github.com/google/uuid"	"time"	"encoding/json"	"database/sql/driver"import (