package service
package service












































































































































































































































































































































































































































































}	}, nil		Status:                    status,		DaysSinceLastOfficialFeed: metrics.DaysSinceLastOfficialFeed,		HighConfidencePercentage:  highConfPercent,		ConflictCount:             metrics.ConflictCount,		CoveragePercentage:        metrics.CoveragePercentage,		TenantID:                  tenantID,	return &domain.HealthCheckResponse{	}		highConfPercent = float64(metrics.HighConfidenceCount) / float64(totalRecords) * 100	if totalRecords > 0 {	totalRecords := metrics.HighConfidenceCount + metrics.MediumConfidenceCount + metrics.LowConfidenceCount	highConfPercent := 0.0	}		status = "critical"	if metrics.DaysSinceLastOfficialFeed > 7 || metrics.ConflictCount > 50 {	}		status = "warning"	if metrics.ConflictCount > 10 {	status := "healthy"	}		return nil, fmt.Errorf("failed to calculate metrics: %w", err)	if err != nil {	metrics, err := s.repo.CalculateAndStoreMetrics(ctx, tenantID)) (*domain.HealthCheckResponse, error) {	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) GetHealthMetrics(// GetHealthMetrics calculates operational health}	}, nil		SourceStats:    statsJSON,		History:        history,		GoldenRecordID: goldenRecordID,	return &domain.LineageResponse{	statsJSON, _ := json.Marshal(sourceStats)	}		"last_updated":      time.Now(),		"sources_evaluated": len(history),	sourceStats := map[string]interface{}{	// Build response with source stats	}		return nil, fmt.Errorf("failed to fetch lineage: %w", err)	if err != nil {	history, err := s.repo.GetLineage(ctx, tenantID, goldenRecordID)) (*domain.LineageResponse, error) {	goldenRecordID uuid.UUID,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) GetLineageForRecord(// GetLineageForRecord returns the full audit trail for a golden record}	return record.IsBusinessDay, nil	}		return true, nil	if record == nil {	// Default to true if no record (open/no data)	}		return true, fmt.Errorf("failed to check business day: %w", err)	if err != nil {	record, err := s.repo.GetGoldenRecord(ctx, tenantID, date, region, exchange)) (bool, error) {	exchange *string,	region string,	date time.Time,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) IsBusinessDay(// IsBusinessDay is a helper for calendar module to check a specific date}	return response, nil	}		Conflicts:            conflicts,		CoveragePercentage:   coveragePercentage,		Records:               records,	response := &domain.GetGoldenCalendarResponse{	}		conflicts = []domain.ConflictRecord{}		s.logger.Warn("failed to fetch conflicts", zap.Error(err))	if err != nil {	conflicts, err := s.repo.GetOpenConflicts(ctx, tenantID)	// Get open conflicts	}		}			coveragePercentage = float64(len(records)) / float64(totalDays) * 100		if totalDays > 0 {		totalDays := int(request.EndDate.Sub(request.StartDate).Hours() / 24)	if len(records) > 0 {	coveragePercentage := 0.0	// Calculate coverage	}		return nil, fmt.Errorf("failed to fetch golden calendar: %w", err)	if err != nil {		request.Region, request.Exchange)		request.StartDate, request.EndDate,	records, err := s.repo.GetGoldenCalendar(ctx, tenantID,) (*domain.GetGoldenCalendarResponse, error) {	request *domain.GetGoldenCalendarRequest,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) GetGoldenCalendar(// GetGoldenCalendar returns the trusted calendar for consumption// ============================================================================// Query APIs// ============================================================================}	return s.repo.RecordConflict(ctx, conflict)	}		CreatedAt:          time.Now(),		Status:             "open",		Severity:           "medium",		ConflictingSources: json.RawMessage("[]"),		ConflictType:       "MissingOfficial",		GoldenRecordID:     golden.ID,		TenantID:           tenantID,	conflict := &domain.ConflictRecord{) error {	golden *domain.HolidaySchedule,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) flagMissingOfficialFeed(// flagMissingOfficialFeed creates a conflict for missing official data}	return s.repo.RecordConflict(ctx, conflict)	}		CreatedAt:          time.Now(),		Status:             "open",		Severity:           "high",		ConflictingSources: conflictingSources,		ConflictType:       "HighPriorityDisagreement",		GoldenRecordID:     golden.ID,		TenantID:           tenantID,	conflict := &domain.ConflictRecord{	conflictingSources, _ := json.Marshal(ruleResult.AlternativeCandidates)) error {	ruleResult *rules.RuleResult,	golden *domain.HolidaySchedule,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) flagConflict(// flagConflict creates a conflict record for stewardship review}	return golden	golden.UpdatedAt = time.Now()	}		golden.CreatedAt = time.Now()		golden.VersionID = 1		golden.ID = uuid.New()	} else {		golden.VersionID = existing.VersionID + 1		golden.CreatedAt = existing.CreatedAt		golden.ID = existing.ID	if existing != nil {	// If updating existing, preserve metadata	}		IsDeleted:      false,		ConfidenceScore: ruleResult.WinningCandidate.Confidence,		SourceType:     ruleResult.WinningCandidate.System,		HolidayName:    raw.HolidayName,		ExchangeCode:   raw.Exchange,		RegionCode:     raw.Region,		IsBusinessDay:  ruleResult.WinningCandidate.Value,		CalendarDate:   raw.Date,		TenantID:       tenantID,	golden := &domain.HolidaySchedule{) *domain.HolidaySchedule {	existing *domain.HolidaySchedule,	ruleResult *rules.RuleResult,	raw domain.CalendarRaw,	tenantID uuid.UUID,func (s *CalendarIngestionService) buildGoldenRecord(// buildGoldenRecord constructs the golden record from the rule result}	return candidates	}		}				zap.Int("confidence", score.Value))				zap.String("source_system", otherSource.SourceSystem),			s.logger.Debug("added historical source as candidate",			candidates = append(candidates, otherCandidate)			otherCandidate.Confidence = score.Value			score := s.engine.CalculateConfidenceScore(&otherCandidate)			}				TimeIngested: otherSource.IngestedAt,				Latency:      otherSource.LatencyHours,				IsOfficial:   otherSource.IsOfficial,				Priority:     otherSource.SourcePriority,				Value:        otherSource.IsBusinessDay,				System:       otherSource.SourceSystem,				SourceID:     otherSource.ID,			otherCandidate := rules.Candidate{			}				continue			if otherSource.ID == newSource.ID {			// Skip the one we just inserted		for _, otherSource := range otherSources {	if err == nil {	otherSources, err := s.repo.GetSourceRecords(ctx, tenantID, raw.Date, raw.Region, raw.Exchange)	// Fetch other recent sources for the same date/region/exchange	}			zap.Int("confidence", existing.ConfidenceScore))			zap.String("golden_id", existing.ID.String()),		s.logger.Debug("added existing golden record as candidate",		candidates = append(candidates, existingCandidate)		}			TimeIngested: existing.UpdatedAt,			Confidence:   existing.ConfidenceScore,			IsOfficial:   false, // Mark as not official refresh			Priority:     100, // Lower priority than fresh data			Value:        existing.IsBusinessDay,			System:       existing.SourceType,			SourceID:     uuid.New(), // Synthetic ID for existing		existingCandidate := rules.Candidate{	if existing != nil && !existing.IsDeleted {	// If an existing golden record exists, add it as a candidate (for continuity)	candidates = append(candidates, newCandidate)	newCandidate.Confidence = score.Value	score := s.engine.CalculateConfidenceScore(&newCandidate)	// Calculate confidence for new candidate	}		TimeIngested: newSource.IngestedAt,		Latency:      newSource.LatencyHours,		IsOfficial:   newSource.IsOfficial,		Priority:     newSource.SourcePriority,		Value:        raw.IsBusinessDay,		System:       newSource.SourceSystem,		SourceID:     newSource.ID,	newCandidate := rules.Candidate{	// Add the new incoming source as a candidate	candidates := []rules.Candidate{}) []rules.Candidate {	existing *domain.HolidaySchedule,	newSource *domain.SourceRecord,	raw domain.CalendarRaw,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) buildCandidates(// buildCandidates constructs the list of candidates for survivorship}	return goldenRecord.ID, nil		zap.Int("confidence_score", goldenRecord.ConfidenceScore))		zap.String("date", raw.Date.String()),		zap.String("golden_id", goldenRecord.ID.String()),	s.logger.Info("record processing complete",	}		}				zap.Error(err))				zap.String("golden_id", goldenRecord.ID.String()),			s.logger.Warn("failed to flag missing official feed",		if err := s.flagMissingOfficialFeed(ctx, tenantID, goldenRecord); err != nil {	if s.engine.DetectMissingOfficialFeed(candidates) && len(candidates) > 1 {	// 8. Check for missing official data	}		}				zap.Error(err))				zap.String("golden_id", goldenRecord.ID.String()),			s.logger.Warn("failed to flag conflict",		if err := s.flagConflict(ctx, tenantID, goldenRecord, ruleResult); err != nil {	if ruleResult.ConflictDetected {	// 7. Flag Conflicts (if detected)	}			zap.Error(err))			zap.String("golden_id", goldenRecord.ID.String()),		s.logger.Warn("failed to record lineage",	if err := s.repo.RecordLineage(ctx, lineage); err != nil {	lineage.GoldenRecordID = goldenRecord.ID	}, ruleResult)		BusinessObject: "HolidaySchedule",		TenantID:       tenantID,	lineage := s.engine.ConstructLineage(rules.ExecutionContext{	// 6. Record Lineage	sourceRecord.GoldenRecordID = &goldenRecord.ID	}		return uuid.Nil, fmt.Errorf("failed to upsert golden record: %w", err)	if err := s.repo.UpsertGoldenRecord(ctx, goldenRecord); err != nil {	)		existingGolden,		ruleResult,		raw,		tenantID,	goldenRecord := s.buildGoldenRecord(	// 5. Upsert Golden Record		zap.Bool("conflict_detected", ruleResult.ConflictDetected))		zap.String("rule_applied", ruleResult.RuleApplied),	s.logger.Debug("survivorship rules executed",	}		return uuid.Nil, fmt.Errorf("survivorship rules failed: %w", err)	if err != nil {	})		Candidates:     candidates,		ExchangeCode:   raw.Exchange,		RegionCode:     raw.Region,		DateKey:        raw.Date,		BusinessObject: "HolidaySchedule",		TenantID:       tenantID,	ruleResult, err := s.engine.ExecuteCalendarSurvivorship(ctx, rules.ExecutionContext{	// 4. Execute Survivorship Rules	candidates := s.buildCandidates(ctx, tenantID, raw, sourceRecord, existingGolden)	// 3. Prepare candidates for survivorship rules	}		return uuid.Nil, fmt.Errorf("failed to find golden record: %w", err)	if err != nil {	existingGolden, err := s.repo.GetGoldenRecord(ctx, tenantID, raw.Date, raw.Region, raw.Exchange)	// 2. Find Existing Golden Record (Matching)		zap.String("source_system", sourceData.SourceSystem))		zap.String("source_id", sourceRecord.ID.String()),	s.logger.Debug("source record stored",	}		return uuid.Nil, fmt.Errorf("failed to store source record: %w", err)	if err := s.repo.InsertSourceRecord(ctx, sourceRecord); err != nil {	}		}			sourceRecord.RawPayload = payload		if payload, err := json.Marshal(raw.RawPayload); err == nil {	if raw.RawPayload != nil {	// Serialize raw payload	}		SourcePriority: int(domain.SourceType(sourceData.SourceSystem).toPriority()),		IsOfficial:     sourceData.IsOfficial,		ExternalID:     sourceData.ExternalID,		SourceSystem:   sourceData.SourceSystem,		HolidayName:    raw.HolidayName,		ExchangeCode:   raw.Exchange,		RegionCode:     raw.Region,		IsBusinessDay:  raw.IsBusinessDay,		CalendarDate:   raw.Date,		TenantID:       tenantID,	sourceRecord := &domain.SourceRecord{	// 1. Store Source Record) (uuid.UUID, error) {	raw domain.CalendarRaw,	sourceData *domain.IngestRequest,	tenantID uuid.UUID,	ctx context.Context,func (s *CalendarIngestionService) processCalendarRecord(// processCalendarRecord handles a single calendar entry through the full pipeline}	return goldenRecordIDs, nil		zap.Int("attempted", len(sourceData.Data)))		zap.Int("processed", len(goldenRecordIDs)),	s.logger.Info("ingestion complete",	}		goldenRecordIDs = append(goldenRecordIDs, recordID)		}			continue				zap.Error(err))				zap.String("region", raw.Region),				zap.String("date", raw.Date.String()),			s.logger.Error("failed to process record",		if err != nil {		recordID, err := s.processCalendarRecord(ctx, tenantID, sourceData, raw)	for _, raw := range sourceData.Data {	// Process each record in the ingestion	var goldenRecordIDs []uuid.UUID		zap.String("tenant_id", tenantID.String()))		zap.Int("record_count", len(sourceData.Data)),		zap.String("source_system", sourceData.SourceSystem),	s.logger.Info("starting calendar ingestion", func (s *CalendarIngestionService) IngestSource(ctx context.Context, tenantID uuid.UUID, sourceData *domain.IngestRequest) ([]uuid.UUID, error) {// IngestSource receives data from external providers and runs the survivorship pipeline// ============================================================================// Ingestion Pipeline// ============================================================================}	}		logger: logger,		engine: engine,		repo:   repo,	return &CalendarIngestionService{func NewCalendarIngestionService(repo *repository.CalendarRepository, engine *rules.RulesEngine, logger *zap.Logger) *CalendarIngestionService {// NewCalendarIngestionService creates a new ingestion service}	logger    *zap.Logger	engine    *rules.RulesEngine	repo      *repository.CalendarRepositorytype CalendarIngestionService struct {// CalendarIngestionService orchestrates the MDM ingestion pipeline)	"go.uber.org/zap"	"github.com/hondyman/semlayer/mdm-service/internal/rules"	"github.com/hondyman/semlayer/mdm-service/internal/repository"	"github.com/hondyman/semlayer/mdm-service/internal/domain"	"github.com/google/uuid"	"time"	"fmt"	"encoding/json"	"context"import (