// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: calendar/events/v1/calendar_events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CalendarEvent represents a change to calendar data
// Published to Redpanda topics for downstream consumption
type CalendarEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EventId               string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                              // UUID unique to this event
	EventType             string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                        // CALENDAR_UPDATE, HOLIDAY_ADDED, CONFLICT_DETECTED, INGESTION_STARTED, INGESTION_COMPLETED
	TenantId              string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                           // Multi-tenant isolation - partition key
	Region                string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                                                               // Region affected (US, GB, CA, etc)
	Exchange              string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`                                                           // Exchange code (NYSE, LSE, etc) - optional
	CalendarDate          string                 `protobuf:"bytes,6,opt,name=calendar_date,json=calendarDate,proto3" json:"calendar_date,omitempty"`                               // ISO 8601 date string: YYYY-MM-DD
	IsBusinessDay         bool                   `protobuf:"varint,7,opt,name=is_business_day,json=isBusinessDay,proto3" json:"is_business_day,omitempty"`                         // True if market/office open
	HolidayName           string                 `protobuf:"bytes,8,opt,name=holiday_name,json=holidayName,proto3" json:"holiday_name,omitempty"`                                  // Human-readable holiday name (e.g., "Christmas")
	SourceSystem          string                 `protobuf:"bytes,9,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"`                               // Where data came from (Workalendar, TradingHours, NagerDate, OpenHolidays, etc)
	ConfidenceScore       int32                  `protobuf:"varint,10,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`                    // 0-100 confidence in this data point
	Operation             string                 `protobuf:"bytes,11,opt,name=operation,proto3" json:"operation,omitempty"`                                                        // CREATE, UPDATE, DELETE
	RuleApplied           string                 `protobuf:"bytes,12,opt,name=rule_applied,json=ruleApplied,proto3" json:"rule_applied,omitempty"`                                 // Which survivorship rule won (e.g., "highest_confidence", "most_recent")
	SemanticTermVersion   string                 `protobuf:"bytes,13,opt,name=semantic_term_version,json=semanticTermVersion,proto3" json:"semantic_term_version,omitempty"`       // Schema version for semantic terms
	BusinessObjectVersion string                 `protobuf:"bytes,14,opt,name=business_object_version,json=businessObjectVersion,proto3" json:"business_object_version,omitempty"` // Schema version for business objects
	Timestamp             int64                  `protobuf:"varint,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                       // Unix milliseconds when event was created
	WasmExecutionId       string                 `protobuf:"bytes,16,opt,name=wasm_execution_id,json=wasmExecutionId,proto3" json:"wasm_execution_id,omitempty"`                   // Traceable to WASM rules engine execution - for debugging
	AttemptNumber         int32                  `protobuf:"varint,17,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`                          // If retried, which attempt (1-based)
	IsRetry               bool                   `protobuf:"varint,18,opt,name=is_retry,json=isRetry,proto3" json:"is_retry,omitempty"`                                            // Whether this is a retry of a previous failed publish
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CalendarEvent) Reset() {
	*x = CalendarEvent{}
	mi := &file_calendar_events_v1_calendar_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarEvent) ProtoMessage() {}

func (x *CalendarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_events_v1_calendar_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarEvent.ProtoReflect.Descriptor instead.
func (*CalendarEvent) Descriptor() ([]byte, []int) {
	return file_calendar_events_v1_calendar_events_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CalendarEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CalendarEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CalendarEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CalendarEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CalendarEvent) GetCalendarDate() string {
	if x != nil {
		return x.CalendarDate
	}
	return ""
}

func (x *CalendarEvent) GetIsBusinessDay() bool {
	if x != nil {
		return x.IsBusinessDay
	}
	return false
}

func (x *CalendarEvent) GetHolidayName() string {
	if x != nil {
		return x.HolidayName
	}
	return ""
}

func (x *CalendarEvent) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *CalendarEvent) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *CalendarEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CalendarEvent) GetRuleApplied() string {
	if x != nil {
		return x.RuleApplied
	}
	return ""
}

func (x *CalendarEvent) GetSemanticTermVersion() string {
	if x != nil {
		return x.SemanticTermVersion
	}
	return ""
}

func (x *CalendarEvent) GetBusinessObjectVersion() string {
	if x != nil {
		return x.BusinessObjectVersion
	}
	return ""
}

func (x *CalendarEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CalendarEvent) GetWasmExecutionId() string {
	if x != nil {
		return x.WasmExecutionId
	}
	return ""
}

func (x *CalendarEvent) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *CalendarEvent) GetIsRetry() bool {
	if x != nil {
		return x.IsRetry
	}
	return false
}

// CalendarConflict represents a discrepancy between sources
// Published to calendar-conflicts topic for stewardship queue
type CalendarConflict struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConflictId        string                 `protobuf:"bytes,1,opt,name=conflict_id,json=conflictId,proto3" json:"conflict_id,omitempty"`                      // UUID
	TenantId          string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                            // Multi-tenant isolation
	Region            string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                                                // Region where conflict occurred
	CalendarDate      string                 `protobuf:"bytes,4,opt,name=calendar_date,json=calendarDate,proto3" json:"calendar_date,omitempty"`                // Date with conflicting data
	FieldName         string                 `protobuf:"bytes,5,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`                         // Which field had conflict (is_business_day, holiday_name, etc)
	ConflictingValues []string               `protobuf:"bytes,6,rep,name=conflicting_values,json=conflictingValues,proto3" json:"conflicting_values,omitempty"` // Values that disagreed ("true", "false", "Christmas", "Xmas", etc)
	SourceSystems     []string               `protobuf:"bytes,7,rep,name=source_systems,json=sourceSystems,proto3" json:"source_systems,omitempty"`             // Systems that disagreed (Workalendar, TradingHours, etc)
	Severity          int32                  `protobuf:"varint,8,opt,name=severity,proto3" json:"severity,omitempty"`                                           // 1=LOW, 2=MEDIUM, 3=HIGH, 4=CRITICAL
	Reason            string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`                                                // Why conflict occurred (e.g., "source_disagreement", "stale_data", "partial_coverage")
	Resolved          bool                   `protobuf:"varint,10,opt,name=resolved,proto3" json:"resolved,omitempty"`                                          // Whether conflict was resolved by survivorship rules
	ResolutionRule    string                 `protobuf:"bytes,11,opt,name=resolution_rule,json=resolutionRule,proto3" json:"resolution_rule,omitempty"`         // Which rule resolved it
	ResolvedValue     string                 `protobuf:"bytes,12,opt,name=resolved_value,json=resolvedValue,proto3" json:"resolved_value,omitempty"`            // The winning value
	CreatedAt         int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                       // Milliseconds since epoch
	ResolvedAt        int64                  `protobuf:"varint,14,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`                    // Milliseconds since epoch
	EscalationStatus  string                 `protobuf:"bytes,15,opt,name=escalation_status,json=escalationStatus,proto3" json:"escalation_status,omitempty"`   // NONE, PENDING, ESCALATED, MANUAL_REVIEW_REQUIRED
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalendarConflict) Reset() {
	*x = CalendarConflict{}
	mi := &file_calendar_events_v1_calendar_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarConflict) ProtoMessage() {}

func (x *CalendarConflict) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_events_v1_calendar_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarConflict.ProtoReflect.Descriptor instead.
func (*CalendarConflict) Descriptor() ([]byte, []int) {
	return file_calendar_events_v1_calendar_events_proto_rawDescGZIP(), []int{1}
}

func (x *CalendarConflict) GetConflictId() string {
	if x != nil {
		return x.ConflictId
	}
	return ""
}

func (x *CalendarConflict) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CalendarConflict) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CalendarConflict) GetCalendarDate() string {
	if x != nil {
		return x.CalendarDate
	}
	return ""
}

func (x *CalendarConflict) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *CalendarConflict) GetConflictingValues() []string {
	if x != nil {
		return x.ConflictingValues
	}
	return nil
}

func (x *CalendarConflict) GetSourceSystems() []string {
	if x != nil {
		return x.SourceSystems
	}
	return nil
}

func (x *CalendarConflict) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *CalendarConflict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CalendarConflict) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *CalendarConflict) GetResolutionRule() string {
	if x != nil {
		return x.ResolutionRule
	}
	return ""
}

func (x *CalendarConflict) GetResolvedValue() string {
	if x != nil {
		return x.ResolvedValue
	}
	return ""
}

func (x *CalendarConflict) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CalendarConflict) GetResolvedAt() int64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

func (x *CalendarConflict) GetEscalationStatus() string {
	if x != nil {
		return x.EscalationStatus
	}
	return ""
}

// IngestionEvent represents lifecycle events during data ingestion
type IngestionEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IngestionId        string                 `protobuf:"bytes,1,opt,name=ingestion_id,json=ingestionId,proto3" json:"ingestion_id,omitempty"`                        // UUID for this ingestion run
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                 // Multi-tenant isolation
	EventType          string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                              // STARTED, IN_PROGRESS, COMPLETED, FAILED
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                                     // QUEUED, RUNNING, SUCCESS, PARTIAL_SUCCESS, FAILURE
	Regions            []string               `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`                                                   // Regions being ingested
	TargetYear         int32                  `protobuf:"varint,6,opt,name=target_year,json=targetYear,proto3" json:"target_year,omitempty"`                          // Year being ingested
	ForceRefresh       bool                   `protobuf:"varint,7,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`                    // Force overwrite of existing data
	RecordsIngested    int32                  `protobuf:"varint,8,opt,name=records_ingested,json=recordsIngested,proto3" json:"records_ingested,omitempty"`           // Total records processed
	RecordsCreated     int32                  `protobuf:"varint,9,opt,name=records_created,json=recordsCreated,proto3" json:"records_created,omitempty"`              // New records added
	RecordsUpdated     int32                  `protobuf:"varint,10,opt,name=records_updated,json=recordsUpdated,proto3" json:"records_updated,omitempty"`             // Existing records updated
	RecordsDeleted     int32                  `protobuf:"varint,11,opt,name=records_deleted,json=recordsDeleted,proto3" json:"records_deleted,omitempty"`             // Records marked as deleted
	ConflictsDetected  int32                  `protobuf:"varint,12,opt,name=conflicts_detected,json=conflictsDetected,proto3" json:"conflicts_detected,omitempty"`    // Number of conflicts found
	ConflictsResolved  int32                  `protobuf:"varint,13,opt,name=conflicts_resolved,json=conflictsResolved,proto3" json:"conflicts_resolved,omitempty"`    // Number of conflicts automatically resolved
	ConflictsEscalated int32                  `protobuf:"varint,14,opt,name=conflicts_escalated,json=conflictsEscalated,proto3" json:"conflicts_escalated,omitempty"` // Conflicts requiring manual review
	SourcesQueried     int32                  `protobuf:"varint,15,opt,name=sources_queried,json=sourcesQueried,proto3" json:"sources_queried,omitempty"`             // Number of data sources queried
	SourcesSucceeded   int32                  `protobuf:"varint,16,opt,name=sources_succeeded,json=sourcesSucceeded,proto3" json:"sources_succeeded,omitempty"`       // Number of sources that succeeded
	SourcesFailed      int32                  `protobuf:"varint,17,opt,name=sources_failed,json=sourcesFailed,proto3" json:"sources_failed,omitempty"`                // Number of sources that failed
	ErrorMessages      []string               `protobuf:"bytes,18,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`                 // If failed, error details
	StartedAt          int64                  `protobuf:"varint,19,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                            // Milliseconds since epoch
	CompletedAt        int64                  `protobuf:"varint,20,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`                      // Milliseconds since epoch
	DurationMs         int64                  `protobuf:"varint,21,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                         // Total execution time
	TriggeredBy        string                 `protobuf:"bytes,22,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`                       // User ID or system name that triggered
	WasmRulesVersion   string                 `protobuf:"bytes,23,opt,name=wasm_rules_version,json=wasmRulesVersion,proto3" json:"wasm_rules_version,omitempty"`      // Version of WASM rules engine used
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IngestionEvent) Reset() {
	*x = IngestionEvent{}
	mi := &file_calendar_events_v1_calendar_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionEvent) ProtoMessage() {}

func (x *IngestionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_events_v1_calendar_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionEvent.ProtoReflect.Descriptor instead.
func (*IngestionEvent) Descriptor() ([]byte, []int) {
	return file_calendar_events_v1_calendar_events_proto_rawDescGZIP(), []int{2}
}

func (x *IngestionEvent) GetIngestionId() string {
	if x != nil {
		return x.IngestionId
	}
	return ""
}

func (x *IngestionEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IngestionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IngestionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestionEvent) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *IngestionEvent) GetTargetYear() int32 {
	if x != nil {
		return x.TargetYear
	}
	return 0
}

func (x *IngestionEvent) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *IngestionEvent) GetRecordsIngested() int32 {
	if x != nil {
		return x.RecordsIngested
	}
	return 0
}

func (x *IngestionEvent) GetRecordsCreated() int32 {
	if x != nil {
		return x.RecordsCreated
	}
	return 0
}

func (x *IngestionEvent) GetRecordsUpdated() int32 {
	if x != nil {
		return x.RecordsUpdated
	}
	return 0
}

func (x *IngestionEvent) GetRecordsDeleted() int32 {
	if x != nil {
		return x.RecordsDeleted
	}
	return 0
}

func (x *IngestionEvent) GetConflictsDetected() int32 {
	if x != nil {
		return x.ConflictsDetected
	}
	return 0
}

func (x *IngestionEvent) GetConflictsResolved() int32 {
	if x != nil {
		return x.ConflictsResolved
	}
	return 0
}

func (x *IngestionEvent) GetConflictsEscalated() int32 {
	if x != nil {
		return x.ConflictsEscalated
	}
	return 0
}

func (x *IngestionEvent) GetSourcesQueried() int32 {
	if x != nil {
		return x.SourcesQueried
	}
	return 0
}

func (x *IngestionEvent) GetSourcesSucceeded() int32 {
	if x != nil {
		return x.SourcesSucceeded
	}
	return 0
}

func (x *IngestionEvent) GetSourcesFailed() int32 {
	if x != nil {
		return x.SourcesFailed
	}
	return 0
}

func (x *IngestionEvent) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

func (x *IngestionEvent) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *IngestionEvent) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *IngestionEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *IngestionEvent) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *IngestionEvent) GetWasmRulesVersion() string {
	if x != nil {
		return x.WasmRulesVersion
	}
	return ""
}

var File_calendar_events_v1_calendar_events_proto protoreflect.FileDescriptor

const file_calendar_events_v1_calendar_events_proto_rawDesc = "" +
	"\n" +
	"(calendar/events/v1/calendar_events.proto\x12\x12calendar.events.v1\"\x93\x05\n" +
	"\rCalendarEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12#\n" +
	"\rcalendar_date\x18\x06 \x01(\tR\fcalendarDate\x12&\n" +
	"\x0fis_business_day\x18\a \x01(\bR\risBusinessDay\x12!\n" +
	"\fholiday_name\x18\b \x01(\tR\vholidayName\x12#\n" +
	"\rsource_system\x18\t \x01(\tR\fsourceSystem\x12)\n" +
	"\x10confidence_score\x18\n" +
	" \x01(\x05R\x0fconfidenceScore\x12\x1c\n" +
	"\toperation\x18\v \x01(\tR\toperation\x12!\n" +
	"\frule_applied\x18\f \x01(\tR\vruleApplied\x122\n" +
	"\x15semantic_term_version\x18\r \x01(\tR\x13semanticTermVersion\x126\n" +
	"\x17business_object_version\x18\x0e \x01(\tR\x15businessObjectVersion\x12\x1c\n" +
	"\ttimestamp\x18\x0f \x01(\x03R\ttimestamp\x12*\n" +
	"\x11wasm_execution_id\x18\x10 \x01(\tR\x0fwasmExecutionId\x12%\n" +
	"\x0eattempt_number\x18\x11 \x01(\x05R\rattemptNumber\x12\x19\n" +
	"\bis_retry\x18\x12 \x01(\bR\aisRetry\"\x8f\x04\n" +
	"\x10CalendarConflict\x12\x1f\n" +
	"\vconflict_id\x18\x01 \x01(\tR\n" +
	"conflictId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12#\n" +
	"\rcalendar_date\x18\x04 \x01(\tR\fcalendarDate\x12\x1d\n" +
	"\n" +
	"field_name\x18\x05 \x01(\tR\tfieldName\x12-\n" +
	"\x12conflicting_values\x18\x06 \x03(\tR\x11conflictingValues\x12%\n" +
	"\x0esource_systems\x18\a \x03(\tR\rsourceSystems\x12\x1a\n" +
	"\bseverity\x18\b \x01(\x05R\bseverity\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1a\n" +
	"\bresolved\x18\n" +
	" \x01(\bR\bresolved\x12'\n" +
	"\x0fresolution_rule\x18\v \x01(\tR\x0eresolutionRule\x12%\n" +
	"\x0eresolved_value\x18\f \x01(\tR\rresolvedValue\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vresolved_at\x18\x0e \x01(\x03R\n" +
	"resolvedAt\x12+\n" +
	"\x11escalation_status\x18\x0f \x01(\tR\x10escalationStatus\"\xf4\x06\n" +
	"\x0eIngestionEvent\x12!\n" +
	"\fingestion_id\x18\x01 \x01(\tR\vingestionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aregions\x18\x05 \x03(\tR\aregions\x12\x1f\n" +
	"\vtarget_year\x18\x06 \x01(\x05R\n" +
	"targetYear\x12#\n" +
	"\rforce_refresh\x18\a \x01(\bR\fforceRefresh\x12)\n" +
	"\x10records_ingested\x18\b \x01(\x05R\x0frecordsIngested\x12'\n" +
	"\x0frecords_created\x18\t \x01(\x05R\x0erecordsCreated\x12'\n" +
	"\x0frecords_updated\x18\n" +
	" \x01(\x05R\x0erecordsUpdated\x12'\n" +
	"\x0frecords_deleted\x18\v \x01(\x05R\x0erecordsDeleted\x12-\n" +
	"\x12conflicts_detected\x18\f \x01(\x05R\x11conflictsDetected\x12-\n" +
	"\x12conflicts_resolved\x18\r \x01(\x05R\x11conflictsResolved\x12/\n" +
	"\x13conflicts_escalated\x18\x0e \x01(\x05R\x12conflictsEscalated\x12'\n" +
	"\x0fsources_queried\x18\x0f \x01(\x05R\x0esourcesQueried\x12+\n" +
	"\x11sources_succeeded\x18\x10 \x01(\x05R\x10sourcesSucceeded\x12%\n" +
	"\x0esources_failed\x18\x11 \x01(\x05R\rsourcesFailed\x12%\n" +
	"\x0eerror_messages\x18\x12 \x03(\tR\rerrorMessages\x12\x1d\n" +
	"\n" +
	"started_at\x18\x13 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x14 \x01(\x03R\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\x15 \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\ftriggered_by\x18\x16 \x01(\tR\vtriggeredBy\x12,\n" +
	"\x12wasm_rules_version\x18\x17 \x01(\tR\x10wasmRulesVersionBb\n" +
	"\x1ccom.usice.calendar.events.v1B\x13CalendarEventsProtoZ-calendar-service/pkg/proto/calendar/events/v1b\x06proto3"

var (
	file_calendar_events_v1_calendar_events_proto_rawDescOnce sync.Once
	file_calendar_events_v1_calendar_events_proto_rawDescData []byte
)

func file_calendar_events_v1_calendar_events_proto_rawDescGZIP() []byte {
	file_calendar_events_v1_calendar_events_proto_rawDescOnce.Do(func() {
		file_calendar_events_v1_calendar_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_events_v1_calendar_events_proto_rawDesc), len(file_calendar_events_v1_calendar_events_proto_rawDesc)))
	})
	return file_calendar_events_v1_calendar_events_proto_rawDescData
}

var file_calendar_events_v1_calendar_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_calendar_events_v1_calendar_events_proto_goTypes = []any{
	(*CalendarEvent)(nil),    // 0: calendar.events.v1.CalendarEvent
	(*CalendarConflict)(nil), // 1: calendar.events.v1.CalendarConflict
	(*IngestionEvent)(nil),   // 2: calendar.events.v1.IngestionEvent
}
var file_calendar_events_v1_calendar_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calendar_events_v1_calendar_events_proto_init() }
func file_calendar_events_v1_calendar_events_proto_init() {
	if File_calendar_events_v1_calendar_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_events_v1_calendar_events_proto_rawDesc), len(file_calendar_events_v1_calendar_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calendar_events_v1_calendar_events_proto_goTypes,
		DependencyIndexes: file_calendar_events_v1_calendar_events_proto_depIdxs,
		MessageInfos:      file_calendar_events_v1_calendar_events_proto_msgTypes,
	}.Build()
	File_calendar_events_v1_calendar_events_proto = out.File
	file_calendar_events_v1_calendar_events_proto_goTypes = nil
	file_calendar_events_v1_calendar_events_proto_depIdxs = nil
}
