-- Core calendars owned by the gold-copy tenant (decision D5): NYSE (XNYS),
-- London Stock Exchange (XLON) and TARGET2, 2024-01-01 .. 2030-12-31.
-- GENERATED by gen_0002_core_calendars.py - edit the generator, not this file.
--
-- Tenants inherit these; a tenant's own items go in a child calendar linked
-- through mdm.calendar_hierarchy (ADDITIVE by default; INHERIT_EXCEPT and
-- OVERRIDE through an approved mdm.calendar_change_request).
--
-- Holidays are derived from each market's published rules, plus listed
-- one-off closures, so days are seeded is_official = false until reconciled
-- with the exchange's own calendar. Idempotent: reruns add only what is
-- missing and never overwrite an edited day.
BEGIN;

CREATE TEMP TABLE core_cal_def (
    calendar_cd text, name text, short_name text, type_cd text, tz text, country_cd text,
    mic text, currency_cd text, open_time time, close_time time, cutoff_time time
) ON COMMIT DROP;
INSERT INTO core_cal_def VALUES
    ('XNYS', 'New York Stock Exchange', 'NYSE', 'EXCHANGE_TRADING', 'America/New_York', 'US', 'XNYS', 'USD', '09:30', '16:00', NULL),
    ('XLON', 'London Stock Exchange', 'LSE', 'EXCHANGE_TRADING', 'Europe/London', 'GB', 'XLON', 'GBP', '08:00', '16:30', NULL),
    ('TARGET2', 'TARGET2 (T2) euro payments', 'TARGET2', 'TARGET2', 'Europe/Frankfurt', NULL, NULL, 'EUR', '07:00', '18:00', '18:00');

INSERT INTO mdm.calendar_master (tenant_id, calendar_cd, name, short_name, calendar_type_id, primary_time_zone_id,
                                 country_cd, mic, currency_cd, effective_from, is_golden_record, custom_attributes)
SELECT '99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid, d.calendar_cd, d.name, d.short_name,
       (SELECT id FROM mdm.calendar_type WHERE calendar_type_cd = d.type_cd ORDER BY (tenant_id = '99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid) DESC LIMIT 1),
       (SELECT id FROM mdm.time_zone WHERE tz_name = d.tz ORDER BY (tenant_id = '99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid) DESC LIMIT 1),
       d.country_cd, d.mic, d.currency_cd, DATE '2024-01-01', true,
       jsonb_build_object('seed', 'core-calendars-v1', 'coverage', '2024-2030', 'rule_derived', true, 'core', true)
FROM core_cal_def d
ON CONFLICT (tenant_id, calendar_cd) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM mdm.calendar_master WHERE tenant_id = '99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid
               AND calendar_cd IN ('XNYS', 'XLON', 'TARGET2') AND (calendar_type_id IS NULL OR primary_time_zone_id IS NULL)) THEN
        RAISE EXCEPTION 'core calendar seed: a calendar type or time zone reference row is missing';
    END IF;
END $$;

INSERT INTO mdm.calendar_identifier (tenant_id, calendar_id, id_type, id_value, is_primary, effective_from, source)
SELECT m.tenant_id, m.id, 'MIC', m.mic, true, DATE '2024-01-01', 'ISO 10383'
FROM mdm.calendar_master m
WHERE m.tenant_id = '99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid AND m.mic IS NOT NULL AND m.calendar_cd IN ('XNYS', 'XLON')
  AND NOT EXISTS (SELECT 1 FROM mdm.calendar_identifier i WHERE i.calendar_id = m.id AND i.id_type = 'MIC');

CREATE TEMP TABLE core_cal_holiday (calendar_cd text, d date, code text, name text, kind text, close_time time) ON COMMIT DROP;
INSERT INTO core_cal_holiday VALUES
('XNYS', DATE '2024-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XNYS', DATE '2024-01-15', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2024-02-19', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2024-03-29', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2024-05-27', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2024-06-19', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2024-07-04', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2024-09-02', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2024-11-28', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2024-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2024-07-03', 'INDEPENDENCE_EVE', 'Day before Independence Day', 'HALF', TIME '13:00'),
('XNYS', DATE '2024-11-29', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2024-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '13:00'),
('XNYS', DATE '2025-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XNYS', DATE '2025-01-20', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2025-02-17', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2025-04-18', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2025-05-26', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2025-06-19', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2025-07-04', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2025-09-01', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2025-11-27', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2025-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2025-07-03', 'INDEPENDENCE_EVE', 'Day before Independence Day', 'HALF', TIME '13:00'),
('XNYS', DATE '2025-11-28', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2025-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '13:00'),
('XNYS', DATE '2026-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XNYS', DATE '2026-01-19', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2026-02-16', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2026-04-03', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2026-05-25', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2026-06-19', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2026-07-03', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2026-09-07', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2026-11-26', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2026-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2026-11-27', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2026-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '13:00'),
('XNYS', DATE '2027-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XNYS', DATE '2027-01-18', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2027-02-15', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2027-03-26', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2027-05-31', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2027-06-18', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2027-07-05', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2027-09-06', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2027-11-25', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2027-12-24', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2027-11-26', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2028-01-17', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2028-02-21', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2028-04-14', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2028-05-29', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2028-06-19', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2028-07-04', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2028-09-04', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2028-11-23', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2028-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2028-07-03', 'INDEPENDENCE_EVE', 'Day before Independence Day', 'HALF', TIME '13:00'),
('XNYS', DATE '2028-11-24', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2029-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XNYS', DATE '2029-01-15', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2029-02-19', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2029-03-30', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2029-05-28', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2029-06-19', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2029-07-04', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2029-09-03', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2029-11-22', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2029-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2029-07-03', 'INDEPENDENCE_EVE', 'Day before Independence Day', 'HALF', TIME '13:00'),
('XNYS', DATE '2029-11-23', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2029-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '13:00'),
('XNYS', DATE '2030-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XNYS', DATE '2030-01-21', 'MLK_DAY', 'Martin Luther King Jr. Day', 'CLOSED', NULL),
('XNYS', DATE '2030-02-18', 'WASHINGTONS_BIRTHDAY', 'Washington''s Birthday', 'CLOSED', NULL),
('XNYS', DATE '2030-04-19', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XNYS', DATE '2030-05-27', 'MEMORIAL_DAY', 'Memorial Day', 'CLOSED', NULL),
('XNYS', DATE '2030-06-19', 'JUNETEENTH', 'Juneteenth National Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2030-07-04', 'INDEPENDENCE_DAY', 'Independence Day', 'CLOSED', NULL),
('XNYS', DATE '2030-09-02', 'LABOR_DAY', 'Labor Day', 'CLOSED', NULL),
('XNYS', DATE '2030-11-28', 'THANKSGIVING', 'Thanksgiving Day', 'CLOSED', NULL),
('XNYS', DATE '2030-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XNYS', DATE '2030-07-03', 'INDEPENDENCE_EVE', 'Day before Independence Day', 'HALF', TIME '13:00'),
('XNYS', DATE '2030-11-29', 'DAY_AFTER_THANKSGIVING', 'Day after Thanksgiving', 'HALF', TIME '13:00'),
('XNYS', DATE '2030-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '13:00'),
('XLON', DATE '2024-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2024-03-29', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2024-04-01', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2024-05-06', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2024-05-27', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2024-08-26', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2024-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2024-12-26', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2024-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2024-12-31', 'NEW_YEARS_EVE', 'New Year''s Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2025-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2025-04-18', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2025-04-21', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2025-05-05', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2025-05-26', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2025-08-25', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2025-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2025-12-26', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2025-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2025-12-31', 'NEW_YEARS_EVE', 'New Year''s Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2026-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2026-04-03', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2026-04-06', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2026-05-04', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2026-05-25', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2026-08-31', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2026-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2026-12-28', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2026-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2026-12-31', 'NEW_YEARS_EVE', 'New Year''s Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2027-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2027-03-26', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2027-03-29', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2027-05-03', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2027-05-31', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2027-08-30', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2027-12-27', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2027-12-28', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2027-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2027-12-31', 'NEW_YEARS_EVE', 'New Year''s Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2028-01-03', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2028-04-14', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2028-04-17', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2028-05-01', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2028-05-29', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2028-08-28', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2028-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2028-12-26', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2029-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2029-03-30', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2029-04-02', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2029-05-07', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2029-05-28', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2029-08-27', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2029-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2029-12-26', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2029-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2029-12-31', 'NEW_YEARS_EVE', 'New Year''s Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2030-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('XLON', DATE '2030-04-19', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('XLON', DATE '2030-04-22', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('XLON', DATE '2030-05-06', 'EARLY_MAY', 'Early May bank holiday', 'CLOSED', NULL),
('XLON', DATE '2030-05-27', 'SPRING_BANK', 'Spring bank holiday', 'CLOSED', NULL),
('XLON', DATE '2030-08-26', 'SUMMER_BANK', 'Summer bank holiday', 'CLOSED', NULL),
('XLON', DATE '2030-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('XLON', DATE '2030-12-26', 'BOXING_DAY', 'Boxing Day', 'CLOSED', NULL),
('XLON', DATE '2030-12-24', 'CHRISTMAS_EVE', 'Christmas Eve', 'HALF', TIME '12:30'),
('XLON', DATE '2030-12-31', 'NEW_YEARS_EVE', 'New Year''s Eve', 'HALF', TIME '12:30'),
('TARGET2', DATE '2024-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2024-03-29', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2024-04-01', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2024-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2024-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2024-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('TARGET2', DATE '2025-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2025-04-18', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2025-04-21', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2025-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2025-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2025-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('TARGET2', DATE '2026-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2026-04-03', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2026-04-06', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2026-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2026-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2026-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('TARGET2', DATE '2027-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2027-03-26', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2027-03-29', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2027-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2027-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2027-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('TARGET2', DATE '2028-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2028-04-14', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2028-04-17', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2028-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2028-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2028-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('TARGET2', DATE '2029-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2029-03-30', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2029-04-02', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2029-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2029-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2029-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('TARGET2', DATE '2030-01-01', 'NEW_YEARS_DAY', 'New Year''s Day', 'CLOSED', NULL),
('TARGET2', DATE '2030-04-19', 'GOOD_FRIDAY', 'Good Friday', 'CLOSED', NULL),
('TARGET2', DATE '2030-04-22', 'EASTER_MONDAY', 'Easter Monday', 'CLOSED', NULL),
('TARGET2', DATE '2030-05-01', 'LABOUR_DAY', 'Labour Day', 'CLOSED', NULL),
('TARGET2', DATE '2030-12-25', 'CHRISTMAS', 'Christmas Day', 'CLOSED', NULL),
('TARGET2', DATE '2030-12-26', 'BOXING_DAY', 'Christmas Holiday', 'CLOSED', NULL),
('XNYS', DATE '2025-01-09', 'NATIONAL_DAY_OF_MOURNING', 'National Day of Mourning for President Jimmy Carter', 'CLOSED', NULL);

INSERT INTO mdm.calendar_day (
    tenant_id, calendar_id, calendar_date, day_of_week, is_weekend,
    is_business_day, is_trading_day, is_settlement_day, is_payment_day, is_dealing_day, is_valuation_day,
    is_half_day, session_open_time, session_close_time, settlement_cutoff_time,
    is_month_end, is_quarter_end, is_year_end,
    is_last_business_day_of_month, is_first_business_day_of_month,
    business_day_of_month, business_day_of_quarter, business_day_of_year,
    additional_holidays, is_materialized, materialization_source, is_official, custom_attributes)
SELECT tenant_id, calendar_id, dt, dow, weekend,
       open, open, open, open, open, open,
       half, CASE WHEN open THEN open_time END, CASE WHEN open THEN COALESCE(half_close, close_time) END,
       CASE WHEN open THEN cutoff_time END,
       dt = (date_trunc('month', dt) + interval '1 month - 1 day')::date,
       dt = (date_trunc('quarter', dt) + interval '3 months - 1 day')::date,
       extract(month FROM dt) = 12 AND extract(day FROM dt) = 31,
       open AND dt = max(dt) FILTER (WHERE open) OVER (PARTITION BY calendar_id, date_trunc('month', dt)),
       open AND dt = min(dt) FILTER (WHERE open) OVER (PARTITION BY calendar_id, date_trunc('month', dt)),
       CASE WHEN open THEN count(*) FILTER (WHERE open) OVER (PARTITION BY calendar_id, date_trunc('month', dt) ORDER BY dt) END,
       CASE WHEN open THEN count(*) FILTER (WHERE open) OVER (PARTITION BY calendar_id, date_trunc('quarter', dt) ORDER BY dt) END,
       CASE WHEN open THEN count(*) FILTER (WHERE open) OVER (PARTITION BY calendar_id, date_trunc('year', dt) ORDER BY dt) END,
       holidays, true, 'core-calendars-v1', false,
       jsonb_build_object('rule_derived', true)
FROM (
    SELECT m.tenant_id, m.id AS calendar_id, g.d::date AS dt,
           extract(isodow FROM g.d)::int AS dow,
           extract(isodow FROM g.d) IN (6, 7) AS weekend,
           NOT (extract(isodow FROM g.d) IN (6, 7))
             AND NOT EXISTS (SELECT 1 FROM core_cal_holiday h WHERE h.calendar_cd = m.calendar_cd AND h.d = g.d::date AND h.kind = 'CLOSED') AS open,
           EXISTS (SELECT 1 FROM core_cal_holiday h WHERE h.calendar_cd = m.calendar_cd AND h.d = g.d::date AND h.kind = 'HALF') AS half,
           (SELECT min(h.close_time) FROM core_cal_holiday h WHERE h.calendar_cd = m.calendar_cd AND h.d = g.d::date AND h.kind = 'HALF') AS half_close,
           (SELECT jsonb_agg(jsonb_build_object('code', h.code, 'name', h.name, 'kind', h.kind) ORDER BY h.code)
              FROM core_cal_holiday h WHERE h.calendar_cd = m.calendar_cd AND h.d = g.d::date) AS holidays,
           c.open_time, c.close_time, c.cutoff_time
    FROM mdm.calendar_master m
    JOIN core_cal_def c ON c.calendar_cd = m.calendar_cd
    CROSS JOIN generate_series(DATE '2024-01-01', DATE '2030-12-31', interval '1 day') AS g(d)
    WHERE m.tenant_id = '99e99e99-99e9-49e9-89e9-99e99e99e999'::uuid
) days
ON CONFLICT (tenant_id, calendar_id, calendar_date) DO NOTHING;

COMMIT;
