ALTER TABLE mdm.party
    DROP CONSTRAINT IF EXISTS chk_party_status,
    DROP CONSTRAINT IF EXISTS chk_party_lifecycle;

DROP INDEX IF EXISTS mdm.idx_party_tenant;
DROP INDEX IF EXISTS mdm.idx_party_status;
DROP INDEX IF EXISTS mdm.idx_party_sub_type;
DROP INDEX IF EXISTS mdm.idx_party_client_group;
DROP INDEX IF EXISTS mdm.idx_party_parent;
DROP INDEX IF EXISTS mdm.idx_party_lei;
DROP INDEX IF EXISTS mdm.idx_party_dob;
DROP INDEX IF EXISTS mdm.idx_party_pep;
DROP INDEX IF EXISTS mdm.idx_party_sanctioned;
DROP INDEX IF EXISTS mdm.idx_party_individual;

ALTER TABLE mdm.party
    DROP COLUMN IF EXISTS party_sub_type,
    DROP COLUMN IF EXISTS status,
    DROP COLUMN IF EXISTS lifecycle_stage,
    DROP COLUMN IF EXISTS is_individual,
    DROP COLUMN IF EXISTS is_legal_entity,
    DROP COLUMN IF EXISTS is_financial_institution,
    DROP COLUMN IF EXISTS is_regulated,
    DROP COLUMN IF EXISTS is_pep,
    DROP COLUMN IF EXISTS is_sanctioned,
    DROP COLUMN IF EXISTS is_restricted,
    DROP COLUMN IF EXISTS is_us_person,
    DROP COLUMN IF EXISTS primary_segment_id,
    DROP COLUMN IF EXISTS parent_party_id,
    DROP COLUMN IF EXISTS ultimate_parent_party_id,
    DROP COLUMN IF EXISTS client_group_id,
    DROP COLUMN IF EXISTS primary_tax_country_cd,
    DROP COLUMN IF EXISTS primary_residence_country_cd,
    DROP COLUMN IF EXISTS primary_nationality_cd,
    DROP COLUMN IF EXISTS country_of_risk_cd,
    DROP COLUMN IF EXISTS lei,
    DROP COLUMN IF EXISTS giin,
    DROP COLUMN IF EXISTS registration_number,
    DROP COLUMN IF EXISTS incorporation_date,
    DROP COLUMN IF EXISTS incorporation_jurisdiction,
    DROP COLUMN IF EXISTS legal_form,
    DROP COLUMN IF EXISTS date_of_birth,
    DROP COLUMN IF EXISTS is_deceased,
    DROP COLUMN IF EXISTS date_of_death,
    DROP COLUMN IF EXISTS client_since_date,
    DROP COLUMN IF EXISTS relationship_end_date,
    DROP COLUMN IF EXISTS relationship_manager_id,
    DROP COLUMN IF EXISTS servicing_team_id,
    DROP COLUMN IF EXISTS primary_currency,
    DROP COLUMN IF EXISTS source_system_id,
    DROP COLUMN IF EXISTS golden_record_id,
    DROP COLUMN IF EXISTS is_golden_record,
    DROP COLUMN IF EXISTS merged_into_id,
    DROP COLUMN IF EXISTS dq_score,
    DROP COLUMN IF EXISTS steward_id,
    DROP COLUMN IF EXISTS last_reviewed_at,
    DROP COLUMN IF EXISTS review_frequency_months;
