-- Message set 9300: staging bindings (internal/stagingbind errors.go), en/es/fr.
INSERT INTO public.message_sets (set_nbr, set_name, module, set_type, description)
VALUES (9300, 'Staging bindings', 'stagingbind', 'core', 'Staging binding messages')
ON CONFLICT (set_nbr) DO NOTHING;

INSERT INTO public.message_catalog (set_nbr, message_nbr, language_cd, severity, message_text, description, user_action) VALUES
  (9300, 1, 'en', 'Error', 'There is no business object %1.', NULL, NULL),
  (9300, 1, 'es', 'Error', 'No existe el objeto de negocio %1.', NULL, NULL),
  (9300, 1, 'fr', 'Error', 'Il n''existe pas d''objet métier %1.', NULL, NULL),
  (9300, 2, 'en', 'Error', '%1 is not a staging table. Use staging.<name>.', NULL, NULL),
  (9300, 2, 'es', 'Error', '%1 no es una tabla de staging. Use staging.<nombre>.', NULL, NULL),
  (9300, 2, 'fr', 'Error', '%1 n''est pas une table de staging. Utilisez staging.<nom>.', NULL, NULL),
  (9300, 3, 'en', 'Error', '%1 has no field %2.', NULL, NULL),
  (9300, 3, 'es', 'Error', '%1 no tiene el campo %2.', NULL, NULL),
  (9300, 3, 'fr', 'Error', '%1 n''a pas de champ %2.', NULL, NULL),
  (9300, 4, 'en', 'Error', '%1 has no column %2.', NULL, NULL),
  (9300, 4, 'es', 'Error', '%1 no tiene la columna %2.', NULL, NULL),
  (9300, 4, 'fr', 'Error', '%1 n''a pas de colonne %2.', NULL, NULL),
  (9300, 5, 'en', 'Error', 'Bind at least one field.', NULL, NULL),
  (9300, 5, 'es', 'Error', 'Vincule al menos un campo.', NULL, NULL),
  (9300, 5, 'fr', 'Error', 'Liez au moins un champ.', NULL, NULL),
  (9300, 6, 'en', 'Error', 'You cannot approve your own change; another person must.', NULL, NULL),
  (9300, 6, 'es', 'Error', 'No puede aprobar su propio cambio; debe hacerlo otra persona.', NULL, NULL),
  (9300, 6, 'fr', 'Error', 'Vous ne pouvez pas approuver votre propre modification ; une autre personne doit le faire.', NULL, NULL),
  (9300, 7, 'en', 'Error', 'Change %1 was not found.', NULL, NULL),
  (9300, 7, 'es', 'Error', 'No se encontró el cambio %1.', NULL, NULL),
  (9300, 7, 'fr', 'Error', 'La modification %1 est introuvable.', NULL, NULL),
  (9300, 8, 'en', 'Error', 'This change has already been decided.', NULL, NULL),
  (9300, 8, 'es', 'Error', 'Este cambio ya se ha decidido.', NULL, NULL),
  (9300, 8, 'fr', 'Error', 'Cette modification a déjà été traitée.', NULL, NULL),
  (9300, 9, 'en', 'Error', 'Only the person who proposed a change can withdraw it.', NULL, NULL),
  (9300, 9, 'es', 'Error', 'Solo quien propuso un cambio puede retirarlo.', NULL, NULL),
  (9300, 9, 'fr', 'Error', 'Seule la personne qui a proposé une modification peut la retirer.', NULL, NULL),
  (9300, 10, 'en', 'Error', 'You are not allowed to change staging bindings here.', NULL, NULL),
  (9300, 10, 'es', 'Error', 'No tiene permiso para cambiar vínculos de staging aquí.', NULL, NULL),
  (9300, 10, 'fr', 'Error', 'Vous n''êtes pas autorisé à modifier les liaisons de staging ici.', NULL, NULL),
  (9300, 11, 'en', 'Error', 'The binding changed after this change was proposed. Propose it again.', NULL, NULL),
  (9300, 11, 'es', 'Error', 'El vínculo cambió después de proponer este cambio. Propóngalo de nuevo.', NULL, NULL),
  (9300, 11, 'fr', 'Error', 'La liaison a changé après la proposition de cette modification. Proposez-la à nouveau.', NULL, NULL),
  (9300, 12, 'en', 'Error', '%1 has no approved binding to %2.', NULL, NULL),
  (9300, 12, 'es', 'Error', '%1 no tiene un vínculo aprobado con %2.', NULL, NULL),
  (9300, 12, 'fr', 'Error', '%1 n''a pas de liaison approuvée avec %2.', NULL, NULL),
  (9300, 13, 'en', 'Error', 'The staging database is not configured for this environment.', NULL, NULL),
  (9300, 13, 'es', 'Error', 'La base de datos de staging no está configurada en este entorno.', NULL, NULL),
  (9300, 13, 'fr', 'Error', 'La base de données de staging n''est pas configurée pour cet environnement.', NULL, NULL),
  (9300, 14, 'en', 'Error', 'Choose a tenant to work in.', NULL, NULL),
  (9300, 14, 'es', 'Error', 'Elija un inquilino con el que trabajar.', NULL, NULL),
  (9300, 14, 'fr', 'Error', 'Choisissez un locataire dans lequel travailler.', NULL, NULL)
ON CONFLICT (set_nbr, message_nbr, language_cd) DO NOTHING;
