-- Message set 9200: the scheduler (internal/schedule errors.go), en/es/fr.
INSERT INTO public.message_sets (set_nbr, set_name, module, set_type, description)
VALUES (9200, 'Scheduler', 'schedule', 'core', 'Scheduler messages')
ON CONFLICT (set_nbr) DO NOTHING;

INSERT INTO public.message_catalog (set_nbr, message_nbr, language_cd, severity, message_text, description, user_action) VALUES
  (9200, 1, 'en', 'Error', 'Schedule %1 was not found.', 'schedule id unknown or deleted for the tenant', NULL),
  (9200, 1, 'es', 'Error', 'No se encontró la programación %1.', NULL, NULL),
  (9200, 1, 'fr', 'Error', 'La planification %1 est introuvable.', NULL, NULL),
  (9200, 2, 'en', 'Error', '''%1'' is not a valid timetable. Use 5 fields: minute hour day month weekday, e.g. 0 18 * * 1-5.', 'cron failed to parse', NULL),
  (9200, 2, 'es', 'Error', '''%1'' no es un horario válido. Use 5 campos: minuto hora día mes día-de-la-semana, p. ej. 0 18 * * 1-5.', NULL, NULL),
  (9200, 2, 'fr', 'Error', '« %1 » n''est pas un horaire valide. Utilisez 5 champs : minute heure jour mois jour-de-semaine, p. ex. 0 18 * * 1-5.', NULL, NULL),
  (9200, 3, 'en', 'Error', 'A schedule can run at most every 5 minutes.', 'cron fires more often than MinInterval', NULL),
  (9200, 3, 'es', 'Error', 'Una programación puede ejecutarse como máximo cada 5 minutos.', NULL, NULL),
  (9200, 3, 'fr', 'Error', 'Une planification peut s''exécuter au plus toutes les 5 minutes.', NULL, NULL),
  (9200, 4, 'en', 'Error', 'Unknown time zone %1.', NULL, NULL),
  (9200, 4, 'es', 'Error', 'Zona horaria desconocida: %1.', NULL, NULL),
  (9200, 4, 'fr', 'Error', 'Fuseau horaire inconnu : %1.', NULL, NULL),
  (9200, 5, 'en', 'Error', 'Calendar %1 was not found.', 'calendar_cd not in mdm.calendar_master for tenant or gold copy', NULL),
  (9200, 5, 'es', 'Error', 'No se encontró el calendario %1.', NULL, NULL),
  (9200, 5, 'fr', 'Error', 'Le calendrier %1 est introuvable.', NULL, NULL),
  (9200, 6, 'en', 'Error', 'Choose a business calendar for this calendar rule.', NULL, NULL),
  (9200, 6, 'es', 'Error', 'Elija un calendario laboral para esta regla de calendario.', NULL, NULL),
  (9200, 6, 'fr', 'Error', 'Choisissez un calendrier ouvré pour cette règle de calendrier.', NULL, NULL),
  (9200, 7, 'en', 'Error', 'The business day must be 1 to 23, or -1 to -23 counting back from the month end.', NULL, NULL),
  (9200, 7, 'es', 'Error', 'El día hábil debe estar entre 1 y 23, o entre -1 y -23 contando desde el final del mes.', NULL, NULL),
  (9200, 7, 'fr', 'Error', 'Le jour ouvré doit être compris entre 1 et 23, ou entre -1 et -23 en partant de la fin du mois.', NULL, NULL),
  (9200, 8, 'en', 'Error', 'Nothing of kind %1 can be scheduled.', NULL, NULL),
  (9200, 8, 'es', 'Error', 'No se puede programar nada del tipo %1.', NULL, NULL),
  (9200, 8, 'fr', 'Error', 'Rien du type %1 ne peut être planifié.', NULL, NULL),
  (9200, 9, 'en', 'Error', '%1 %2 was not found, or you can''t run it.', 'runner Check/Run: target missing or not visible to the owner', NULL),
  (9200, 9, 'es', 'Error', 'No se encontró %1 %2 o no puede ejecutarlo.', NULL, NULL),
  (9200, 9, 'fr', 'Error', '%1 %2 est introuvable ou vous ne pouvez pas l''exécuter.', NULL, NULL),
  (9200, 10, 'en', 'Error', 'The end date must be after the start date.', NULL, NULL),
  (9200, 10, 'es', 'Error', 'La fecha de fin debe ser posterior a la de inicio.', NULL, NULL),
  (9200, 10, 'fr', 'Error', 'La date de fin doit être postérieure à la date de début.', NULL, NULL),
  (9200, 11, 'en', 'Error', 'Calendar %1 has no days for %2, so the run could not be judged.', 'Decide found a date outside mdm.calendar_day coverage - never a silent run', 'Extend the calendar''s coverage, then run the schedule again.'),
  (9200, 11, 'es', 'Error', 'El calendario %1 no tiene días para %2, por lo que no se pudo evaluar la ejecución.', NULL, 'Amplíe la cobertura del calendario y vuelva a ejecutar la programación.'),
  (9200, 11, 'fr', 'Error', 'Le calendrier %1 n''a pas de jours pour %2 ; l''exécution n''a pas pu être évaluée.', NULL, 'Étendez la couverture du calendrier, puis relancez la planification.'),
  (9200, 12, 'en', 'Error', 'The scheduler is not available right now.', 'Temporal unreachable or rejected the schedule', 'Try again shortly. If it keeps happening, contact support with the reference.'),
  (9200, 12, 'es', 'Error', 'El programador no está disponible en este momento.', NULL, 'Vuelva a intentarlo en breve. Si continúa, contacte con el soporte indicando la referencia.'),
  (9200, 12, 'fr', 'Error', 'Le planificateur n''est pas disponible pour le moment.', NULL, 'Réessayez sous peu. Si le problème persiste, contactez le support en indiquant la référence.'),
  (9200, 13, 'en', 'Error', 'Run %1 has no output file.', NULL, NULL),
  (9200, 13, 'es', 'Error', 'La ejecución %1 no tiene archivo de salida.', NULL, NULL),
  (9200, 13, 'fr', 'Error', 'L''exécution %1 n''a pas de fichier de sortie.', NULL, NULL),
  (9200, 14, 'en', 'Error', 'A schedule needs a name.', NULL, NULL),
  (9200, 14, 'es', 'Error', 'La programación necesita un nombre.', NULL, NULL),
  (9200, 14, 'fr', 'Error', 'La planification doit avoir un nom.', NULL, NULL),
  (9200, 15, 'en', 'Error', 'Run %1 was not found.', NULL, NULL),
  (9200, 15, 'es', 'Error', 'No se encontró la ejecución %1.', NULL, NULL),
  (9200, 15, 'fr', 'Error', 'L''exécution %1 est introuvable.', NULL, NULL),
  (9200, 16, 'en', 'Error', 'Unknown calendar rule %1.', NULL, NULL),
  (9200, 16, 'es', 'Error', 'Regla de calendario desconocida: %1.', NULL, NULL),
  (9200, 16, 'fr', 'Error', 'Règle de calendrier inconnue : %1.', NULL, NULL)
ON CONFLICT (set_nbr, message_nbr, language_cd) DO NOTHING;
