-- Migration: Polyglot CRUD and Bi-Temporal Mapping Layer Schema
-- Date: 2026-07-30
-- Purpose: Extend Business Object bindings for dual OLTP CRUD (writeable) and Bi-Temporal OLAP (datalake analytical) modes.
--
-- RETIRED 2026-09-12: this file's business_object_bindings definition (binding_id,
-- binding_mode, physical_table_name, ...) never matches the table that actually
-- exists in any environment. The real business_object_bindings table (id, tenant_id,
-- bo_id, backend_id, backend_type, driving_node_id, ...) is defined in
-- 20261002_business_object_studio_engine.up.sql, recovered from an unmerged branch
-- (commit c9e9ac74a4) where the application code that queries this table
-- (backend/internal/api/business_object_handlers.go, backend/internal/models/
-- businessobjects.go, backend/internal/cbo/cbo_types.go) was already merged
-- independently. On a fresh build, this file's earlier date prefix (20260730 <
-- 20261002) meant it would run first and silently win the CREATE TABLE IF NOT
-- EXISTS race, leaving the wrong schema in place — the same collision pattern
-- documented in FAILURES_LEDGER.md Arc 7. binding_service.go still queries the
-- old (this file's) column names and is confirmed broken against the real schema
-- as of this date; that is a separate, pre-existing bug, not something retiring
-- this DDL introduces.
