-- Message Catalog seed.
--
-- 1. Legacy language code ENG -> en (the app's locale codes). Two messages
--    exist as both ENG and en with identical text; the en copy (no
--    description) is dropped. If a pair ever differs, the UPDATE hits the
--    primary key and this migration fails rather than lose either text.
-- 2. The existing core messages, so fresh environments get the same
--    catalog (ON CONFLICT DO NOTHING: edits made through the catalog win).
-- 3. Set 9100 (the catalog's own messages) and Spanish/French for set 1
--    (the generic messages every unmapped error falls back to).

DELETE FROM public.message_catalog e
 WHERE e.language_cd = 'en'
   AND EXISTS (SELECT 1 FROM public.message_catalog g
                WHERE g.language_cd = 'ENG' AND g.set_nbr = e.set_nbr
                  AND g.message_nbr = e.message_nbr AND g.message_text = e.message_text);
UPDATE public.message_catalog SET language_cd = 'en' WHERE language_cd = 'ENG';
UPDATE public.tenant_message_catalog SET language_cd = 'en' WHERE language_cd = 'ENG';

ALTER TABLE public.message_catalog ALTER COLUMN language_cd SET DEFAULT 'en';
ALTER TABLE public.tenant_message_catalog ALTER COLUMN language_cd SET DEFAULT 'en';

INSERT INTO public.message_sets (set_nbr, set_name, module, set_type, description) VALUES
  (1, 'System', 'platform', 'core', 'Core platform system messages (auth, tenant, validation)'),
  (1000, 'Compliance', 'compliance', 'core', 'Compliance module messages'),
  (2000, 'Risk', 'risk', 'core', 'Risk module messages'),
  (3000, 'ETL', 'etl', 'core', 'ETL pipeline messages'),
  (4000, 'WASM', 'wasm', 'core', 'WASM module management messages'),
  (5000, 'Delivery', 'delivery', 'core', 'Delivery, export, and secure link messages'),
  (6000, 'Lineage', 'lineage', 'core', 'Lineage and audit trail messages'),
  (7000, 'Reports', 'reports', 'core', 'Reports and scheduler messages'),
  (8000, 'Notification', 'notification', 'core', 'Notification delivery messages'),
  (9100, 'Message Catalog', 'msgcat', 'core', 'Message catalog editing and approval messages'),
  (10000, 'CoreCustom', 'platform', 'custom', 'Core custom message range for implementer extensions'),
  (20000, 'ClientCustom', 'platform', 'client', 'Client and tenant custom message range')
ON CONFLICT (set_nbr) DO NOTHING;

INSERT INTO public.message_catalog (set_nbr, message_nbr, language_cd, severity, message_text, description, user_action) VALUES
  (1, 1, 'en', 'Error', 'Tenant ID is required.', 'tenant_id query parameter or header is missing', NULL),
  (1, 1, 'es', 'Error', 'Falta el identificador de la organización.', NULL, NULL),
  (1, 1, 'fr', 'Error', 'L''identifiant de l''organisation est manquant.', NULL, NULL),
  (1, 2, 'en', 'Error', 'Tenant %1 not found or access denied.', 'Tenant lookup failed or RLS rejected', NULL),
  (1, 2, 'es', 'Error', 'La organización %1 no existe o el acceso está denegado.', NULL, NULL),
  (1, 2, 'fr', 'Error', 'L''organisation %1 est introuvable ou l''accès est refusé.', NULL, NULL),
  (1, 3, 'en', 'Error', 'Unauthorized — authentication is required.', 'JWT absent or invalid', NULL),
  (1, 3, 'es', 'Error', 'No autorizado: se requiere autenticación.', NULL, NULL),
  (1, 3, 'fr', 'Error', 'Non autorisé : une authentification est requise.', NULL, NULL),
  (1, 4, 'en', 'Fatal', 'An internal error occurred (ref: %1). Please contact support.', 'Unhandled internal server error with reference ID', 'Quote the reference when you contact support; it identifies the exact failure.'),
  (1, 4, 'es', 'Fatal', 'Se produjo un error interno (ref.: %1). Póngase en contacto con el soporte.', NULL, 'Indique la referencia al contactar con el soporte; identifica el fallo exacto.'),
  (1, 4, 'fr', 'Fatal', 'Une erreur interne s''est produite (réf. : %1). Veuillez contacter le support.', NULL, 'Indiquez la référence lorsque vous contactez le support ; elle identifie l''erreur exacte.'),
  (1, 5, 'en', 'Error', 'Invalid input: %1.', 'Generic input validation failure', NULL),
  (1, 5, 'es', 'Error', 'Entrada no válida: %1.', NULL, NULL),
  (1, 5, 'fr', 'Error', 'Saisie non valide : %1.', NULL, NULL),
  (1, 6, 'en', 'Error', '%1 was not found.', 'Generic not-found with resource name', NULL),
  (1, 6, 'es', 'Error', 'No se encontró %1.', NULL, NULL),
  (1, 6, 'fr', 'Error', '%1 est introuvable.', NULL, NULL),
  (1, 7, 'en', 'Error', 'Validation failed: %1.', 'Structured validation error detail', NULL),
  (1, 7, 'es', 'Error', 'La validación falló: %1.', NULL, NULL),
  (1, 7, 'fr', 'Error', 'La validation a échoué : %1.', NULL, NULL),
  (1, 8, 'en', 'Warning', 'Rate limit exceeded. Retry after %1 seconds.', 'API rate limit hit', NULL),
  (1, 8, 'es', 'Warning', 'Se superó el límite de solicitudes. Vuelva a intentarlo en %1 segundos.', NULL, NULL),
  (1, 8, 'fr', 'Warning', 'Limite de requêtes dépassée. Réessayez dans %1 secondes.', NULL, NULL),
  (1, 9, 'en', 'Error', 'Request parameter %1 is required.', 'Specific query/body parameter missing', NULL),
  (1, 9, 'es', 'Error', 'El parámetro %1 es obligatorio.', NULL, NULL),
  (1, 9, 'fr', 'Error', 'Le paramètre %1 est obligatoire.', NULL, NULL),
  (1, 10, 'en', 'Error', 'Operation not permitted: %1.', 'RBAC/ABAC authorization denial', NULL),
  (1, 10, 'es', 'Error', 'Operación no permitida: %1.', NULL, NULL),
  (1, 10, 'fr', 'Error', 'Opération non autorisée : %1.', NULL, NULL),
  (1, 11, 'en', 'Error', 'Resource %1 is locked and cannot be modified.', 'Optimistic locking conflict', NULL),
  (1, 11, 'es', 'Error', 'El recurso %1 está bloqueado y no se puede modificar.', NULL, NULL),
  (1, 11, 'fr', 'Error', 'La ressource %1 est verrouillée et ne peut pas être modifiée.', NULL, NULL),
  (1, 12, 'en', 'Warning', 'Service %1 is temporarily unavailable. Please try again shortly.', 'Downstream service unreachable', NULL),
  (1, 12, 'es', 'Warning', 'El servicio %1 no está disponible temporalmente. Vuelva a intentarlo en unos momentos.', NULL, NULL),
  (1, 12, 'fr', 'Warning', 'Le service %1 est temporairement indisponible. Veuillez réessayer dans quelques instants.', NULL, NULL),
  (1, 13, 'en', 'Error', 'Request body is malformed or not valid JSON.', 'JSON decode failure', NULL),
  (1, 13, 'es', 'Error', 'El cuerpo de la solicitud está mal formado o no es JSON válido.', NULL, NULL),
  (1, 13, 'fr', 'Error', 'Le corps de la requête est mal formé ou n''est pas un JSON valide.', NULL, NULL),
  (1, 14, 'en', 'Error', 'Pagination parameter %1 must be a positive integer.', 'Bad page/limit parameter', NULL),
  (1, 14, 'es', 'Error', 'El parámetro de paginación %1 debe ser un entero positivo.', NULL, NULL),
  (1, 14, 'fr', 'Error', 'Le paramètre de pagination %1 doit être un entier positif.', NULL, NULL),
  (1, 15, 'en', 'Message', 'Operation completed successfully.', 'Generic success message', NULL),
  (1, 15, 'es', 'Message', 'La operación se completó correctamente.', NULL, NULL),
  (1, 15, 'fr', 'Message', 'L''opération s''est terminée avec succès.', NULL, NULL),
  (1000, 1, 'en', 'Error', 'Failed to retrieve compliance summary for tenant %1.', 'DB error fetching compliance_results', NULL),
  (1000, 2, 'en', 'Error', 'Failed to retrieve compliance alerts.', 'DB error fetching compliance_breaches', NULL),
  (1000, 3, 'en', 'Error', 'Compliance rule %1 could not be processed.', 'Rule engine processing error', NULL),
  (1000, 4, 'en', 'Warning', 'No completed ETL run found for valuation date %1.', 'compliance summary returned pending because no ETL run', NULL),
  (1000, 5, 'en', 'Error', 'Compliance breach %1 was not found.', 'breach_id lookup returned no rows', NULL),
  (1000, 6, 'en', 'Error', 'Failed to activate compliance rule %1.', 'rule activation DB update failed', NULL),
  (1000, 7, 'en', 'Error', 'Rule %1 evaluation failed: %2.', 'Specific rule evaluation error', NULL),
  (1000, 8, 'en', 'Warning', 'Compliance status breakdown is temporarily unavailable.', 'status breakdown query failed', NULL),
  (1000, 9, 'en', 'Error', 'Failed to retrieve rule lineage for rule %1.', 'lineage DB query failed', NULL),
  (1000, 10, 'en', 'Error', 'Compliance score calculation failed for ETL run %1.', 'division by zero or null data in pass rate calc', NULL),
  (1000, 102, 'en', 'Error', 'Hire date cannot be less than birthdate', NULL, NULL),
  (1000, 103, 'en', 'Error', 'Cant be "hired" before they were 14 (Child labor laws)', NULL, NULL),
  (1000, 104, 'en', 'Error', 'Self-Reporting Violation: Employee {0} cannot be assigned as their own manager.', NULL, NULL),
  (1000, 105, 'en', 'Error', 'Reference Error: The manager with ID ''{0}'' does not exist in the Employee directory.', NULL, NULL),
  (1000, 106, 'en', 'Warning', 'Seniority Alert: Manager (hired {0:D}) has less tenure than the employee (hired {1:D}).', NULL, NULL),
  (1000, 107, 'en', 'Error', 'Territory Description cannot be null', NULL, NULL),
  (2000, 1, 'en', 'Error', 'Failed to retrieve risk summary for tenant %1.', 'DB error fetching risk_metrics', NULL),
  (2000, 2, 'en', 'Error', 'Risk scenario %1 was not found.', 'scenario_id lookup returned no rows', NULL),
  (2000, 3, 'en', 'Error', 'Failed to calculate VaR metrics for ETL run %1.', 'VaR query failed or returned null', NULL),
  (2000, 4, 'en', 'Warning', 'Exposure breakdown is unavailable for ETL run %1.', 'exposure_breakdown query returned no rows', NULL),
  (2000, 5, 'en', 'Error', 'Worst-case scenario determination failed for ETL run %1.', 'scenario_pnl query failed', NULL),
  (2000, 6, 'en', 'Error', 'Risk aggregate score calculation failed.', 'null/missing var95 or var99 values', NULL),
  (2000, 7, 'en', 'Error', 'Failed to retrieve scenario lineage for scenario %1.', 'scenario_results lineage query failed', NULL),
  (2000, 8, 'en', 'Warning', 'No risk data is available for ETL run %1.', 'risk_metrics returned empty for the given ETL run', NULL),
  (2000, 9, 'en', 'Error', 'Portfolio %1 risk assessment failed.', 'per-portfolio risk calc error', NULL),
  (2000, 10, 'en', 'Warning', 'Risk threshold %1 was exceeded.', 'VaR or volatility above configured threshold', NULL),
  (3000, 1, 'en', 'Error', 'Failed to retrieve ETL health metrics.', 'etl_runs health query failed', NULL),
  (3000, 2, 'en', 'Error', 'ETL run %1 was not found.', 'etl_run_id lookup returned no rows', NULL),
  (3000, 3, 'en', 'Error', 'Failed to retrieve ETL run history.', 'listETLRuns query failed', NULL),
  (3000, 4, 'en', 'Warning', 'No completed ETL run for valuation date %1.', 'etl_runs returned ErrNoRows for the date', NULL),
  (3000, 5, 'en', 'Warning', 'ETL run %1 is still in progress.', 'status = in_progress, downstream query blocked', NULL),
  (3000, 6, 'en', 'Error', 'ETL run %1 failed: %2.', 'ETL run completed with status=failed and error message', NULL),
  (3000, 7, 'en', 'Warning', 'ETL health status is temporarily unavailable.', 'etl_runs query failed gracefully', NULL),
  (3000, 8, 'en', 'Error', 'Failed to process portfolios in ETL run %1.', 'portfolio ETL batch processing error', NULL),
  (3000, 9, 'en', 'Warning', 'ETL run %1 duration (%2 s) exceeded the configured threshold.', 'long-running ETL performance warning', NULL),
  (3000, 10, 'en', 'Error', 'ETL schedule conflict detected for valuation date %1.', 'overlapping ETL runs for same date', NULL),
  (4000, 1, 'en', 'Error', 'Failed to retrieve WASM versions for module %1.', 'wasm_versions query failed', NULL),
  (4000, 2, 'en', 'Error', 'WASM version %1 was not found.', 'version_id lookup returned no rows', NULL),
  (4000, 3, 'en', 'Error', 'Activation failed for WASM module %1.', 'is_active update transaction failed', NULL),
  (4000, 4, 'en', 'Error', 'WASM module %1 is not compatible with the current platform version.', 'version incompatibility check failed', NULL),
  (4000, 5, 'en', 'Warning', 'No active WASM version found for module %1.', 'wasm_versions returned no active version', NULL),
  (5000, 1, 'en', 'Error', 'Failed to generate a secure download link for %1.', 'Secure link token generation failed', NULL),
  (5000, 2, 'en', 'Error', 'The secure link for %1 has expired.', 'HMAC token TTL exceeded', NULL),
  (5000, 3, 'en', 'Error', 'The secure link token is invalid.', 'HMAC signature verification failed', NULL),
  (5000, 4, 'en', 'Error', 'Export %1 was not found.', 'export_id lookup returned no rows', NULL),
  (5000, 5, 'en', 'Error', 'Failed to share %1 with the specified recipients.', 'Email delivery or sharing API error', NULL),
  (5000, 6, 'en', 'Error', 'Report execution %1 was not found.', 'report execution ID lookup returned no rows', NULL),
  (5000, 7, 'en', 'Error', 'Export generation failed for request %1.', 'export job processing error', NULL),
  (5000, 8, 'en', 'Warning', 'Download limit exceeded for export %1.', 'Per-token or per-export download count threshold hit', NULL),
  (5000, 9, 'en', 'Error', 'PDF generation failed for household report %1.', 'PDF renderer error', NULL),
  (5000, 10, 'en', 'Error', 'Delivery to %1 failed: %2.', 'General delivery failure with recipient and reason', NULL),
  (6000, 1, 'en', 'Error', 'Failed to retrieve the lineage graph.', 'Lineage graph query failed', NULL),
  (6000, 2, 'en', 'Warning', 'Lineage metrics are unavailable for module %1.', 'lineage metrics query returned no rows or error', NULL),
  (6000, 3, 'en', 'Error', 'Audit trail not found for %1.', 'Audit record lookup returned no rows', NULL),
  (6000, 4, 'en', 'Fatal', 'Failed to record audit event: %1.', 'Audit write failure - critical platform issue', NULL),
  (6000, 5, 'en', 'Warning', 'Lineage data for node %1 is incomplete.', 'Orphaned or partially-processed lineage node', NULL),
  (7000, 1, 'en', 'Error', 'Report %1 was not found.', 'report_id lookup returned no rows', NULL),
  (7000, 2, 'en', 'Error', 'Report execution %1 failed.', 'Scheduler reported execution failure', NULL),
  (7000, 3, 'en', 'Warning', 'Scheduler conflict detected for report %1.', 'Duplicate/overlapping schedule detected', NULL),
  (7000, 4, 'en', 'Warning', 'Report %1 generation timed out after %2 seconds.', 'Report rendering exceeded the configured timeout', NULL),
  (7000, 5, 'en', 'Error', 'Invalid parameters for report %1: %2.', 'Report parameter validation failure', NULL),
  (8000, 1, 'en', 'Error', 'Failed to deliver notification to %1.', 'Notification send failure for recipient(s)', NULL),
  (8000, 2, 'en', 'Error', 'Notification template %1 was not found.', 'template_id lookup returned no rows', NULL),
  (8000, 3, 'en', 'Warning', 'Notification channel %1 is currently unavailable.', 'Channel (email/SMS/push) unreachable', NULL),
  (8000, 4, 'en', 'Warning', 'Notification rate limit exceeded for tenant %1.', 'Per-tenant notification throttle hit', NULL),
  (8000, 5, 'en', 'Error', 'Failed to process notification batch %1.', 'Batch notification processing error', NULL),
  (9100, 1, 'en', 'Error', 'Language %1 is not supported.', 'language_cd is not one of the app locales', NULL),
  (9100, 1, 'es', 'Error', 'El idioma %1 no es compatible.', NULL, NULL),
  (9100, 1, 'fr', 'Error', 'La langue %1 n''est pas prise en charge.', NULL, NULL),
  (9100, 2, 'en', 'Error', 'Severity %1 is not valid. Use Message, Warning, Error or Fatal.', 'severity outside the four catalog severities', NULL),
  (9100, 2, 'es', 'Error', 'La gravedad %1 no es válida. Use Message, Warning, Error o Fatal.', NULL, NULL),
  (9100, 2, 'fr', 'Error', 'La gravité %1 n''est pas valide. Utilisez Message, Warning, Error ou Fatal.', NULL, NULL),
  (9100, 3, 'en', 'Error', 'The message text is required.', 'empty message_text on upsert', NULL),
  (9100, 3, 'es', 'Error', 'El texto del mensaje es obligatorio.', NULL, NULL),
  (9100, 3, 'fr', 'Error', 'Le texte du message est obligatoire.', NULL, NULL),
  (9100, 4, 'en', 'Error', 'The text is too long (maximum %1 characters).', 'message_text, description or user_action over its length limit', NULL),
  (9100, 4, 'es', 'Error', 'El texto es demasiado largo (máximo %1 caracteres).', NULL, NULL),
  (9100, 4, 'fr', 'Error', 'Le texte est trop long (%1 caractères maximum).', NULL, NULL),
  (9100, 5, 'en', 'Error', 'This translation must use exactly the parameters in the English text: %1.', 'placeholder set (%1..%9) differs from the en text', NULL),
  (9100, 5, 'es', 'Error', 'Esta traducción debe usar exactamente los parámetros del texto en inglés: %1.', NULL, NULL),
  (9100, 5, 'fr', 'Error', 'Cette traduction doit utiliser exactement les paramètres du texte anglais : %1.', NULL, NULL),
  (9100, 6, 'en', 'Error', 'Add the English text first; it is the fallback for every other language.', 'non-en translation for a message with no en text in scope', NULL),
  (9100, 6, 'es', 'Error', 'Añada primero el texto en inglés; es el respaldo de todos los demás idiomas.', NULL, NULL),
  (9100, 6, 'fr', 'Error', 'Ajoutez d''abord le texte anglais ; il sert de repli pour toutes les autres langues.', NULL, NULL),
  (9100, 7, 'en', 'Error', 'Message set %1 was not found.', 'set_nbr not in message_sets', NULL),
  (9100, 7, 'es', 'Error', 'No se encontró el conjunto de mensajes %1.', NULL, NULL),
  (9100, 7, 'fr', 'Error', 'Le jeu de messages %1 est introuvable.', NULL, NULL),
  (9100, 8, 'en', 'Error', 'Message %1 was not found.', 'no core or tenant row for set/number', NULL),
  (9100, 8, 'es', 'Error', 'No se encontró el mensaje %1.', NULL, NULL),
  (9100, 8, 'fr', 'Error', 'Le message %1 est introuvable.', NULL, NULL),
  (9100, 9, 'en', 'Error', 'Message numbers must be between 1 and 99999.', 'message_nbr out of range', NULL),
  (9100, 9, 'es', 'Error', 'Los números de mensaje deben estar entre 1 y 99999.', NULL, NULL),
  (9100, 9, 'fr', 'Error', 'Les numéros de message doivent être compris entre 1 et 99999.', NULL, NULL),
  (9100, 10, 'en', 'Error', 'New messages for your organization can only be added to client message sets; set %1 is a %2 set.', 'tenant tried to create a message (no core row) outside a client set', NULL),
  (9100, 10, 'es', 'Error', 'Los mensajes nuevos de su organización solo pueden añadirse a conjuntos de mensajes de cliente; el conjunto %1 es de tipo %2.', NULL, NULL),
  (9100, 10, 'fr', 'Error', 'Les nouveaux messages de votre organisation ne peuvent être ajoutés qu''aux jeux de messages client ; le jeu %1 est de type %2.', NULL, NULL),
  (9100, 11, 'en', 'Error', 'Only platform administrators can change the core catalog.', 'core-scope change without global_admin', NULL),
  (9100, 11, 'es', 'Error', 'Solo los administradores de la plataforma pueden modificar el catálogo principal.', NULL, NULL),
  (9100, 11, 'fr', 'Error', 'Seuls les administrateurs de la plateforme peuvent modifier le catalogue principal.', NULL, NULL),
  (9100, 12, 'en', 'Error', 'Only your organization''s administrators can change its messages.', 'tenant-scope change without tenant_admin or global_admin', NULL),
  (9100, 12, 'es', 'Error', 'Solo los administradores de su organización pueden modificar sus mensajes.', NULL, NULL),
  (9100, 12, 'fr', 'Error', 'Seuls les administrateurs de votre organisation peuvent modifier ses messages.', NULL, NULL),
  (9100, 13, 'en', 'Error', 'The English text of a core message can''t be deleted; it is the message of record.', 'core delete of the en row', NULL),
  (9100, 13, 'es', 'Error', 'El texto en inglés de un mensaje principal no se puede eliminar; es el mensaje de referencia.', NULL, NULL),
  (9100, 13, 'fr', 'Error', 'Le texte anglais d''un message principal ne peut pas être supprimé ; c''est le message de référence.', NULL, NULL),
  (9100, 14, 'en', 'Error', 'Change %1 was not found.', 'change id unknown or not visible to the caller', NULL),
  (9100, 14, 'es', 'Error', 'No se encontró el cambio %1.', NULL, NULL),
  (9100, 14, 'fr', 'Error', 'La modification %1 est introuvable.', NULL, NULL),
  (9100, 15, 'en', 'Error', 'This change is no longer pending.', 'approve/reject/withdraw on a decided change', NULL),
  (9100, 15, 'es', 'Error', 'Este cambio ya no está pendiente.', NULL, NULL),
  (9100, 15, 'fr', 'Error', 'Cette modification n''est plus en attente.', NULL, NULL),
  (9100, 16, 'en', 'Error', 'You can''t approve or reject your own change; another approver must review it.', 'maker-checker: reviewer is the requester', NULL),
  (9100, 16, 'es', 'Error', 'No puede aprobar ni rechazar su propio cambio; debe revisarlo otro aprobador.', NULL, NULL),
  (9100, 16, 'fr', 'Error', 'Vous ne pouvez pas approuver ou rejeter votre propre modification ; un autre approbateur doit l''examiner.', NULL, NULL),
  (9100, 17, 'en', 'Error', 'The message was changed after this change was proposed. Propose it again against the current text.', 'optimistic concurrency: row differs from the change''s before image', NULL),
  (9100, 17, 'es', 'Error', 'El mensaje se modificó después de proponer este cambio. Vuelva a proponerlo sobre el texto actual.', NULL, NULL),
  (9100, 17, 'fr', 'Error', 'Le message a été modifié après la proposition de cette modification. Proposez-la de nouveau à partir du texte actuel.', NULL, NULL),
  (9100, 18, 'en', 'Error', 'Only the person who proposed a change can withdraw it.', 'withdraw by someone other than requested_by', NULL),
  (9100, 18, 'es', 'Error', 'Solo quien propuso un cambio puede retirarlo.', NULL, NULL),
  (9100, 18, 'fr', 'Error', 'Seule la personne qui a proposé une modification peut la retirer.', NULL, NULL),
  (9100, 19, 'en', 'Error', 'There is no message to delete.', 'delete of a row that does not exist in scope', NULL),
  (9100, 19, 'es', 'Error', 'No hay ningún mensaje que eliminar.', NULL, NULL),
  (9100, 19, 'fr', 'Error', 'Il n''y a aucun message à supprimer.', NULL, NULL),
  (9100, 20, 'en', 'Error', 'A change to this message is already waiting for approval.', 'second pending change for the same scope/key/language', NULL),
  (9100, 20, 'es', 'Error', 'Ya hay un cambio de este mensaje pendiente de aprobación.', NULL, NULL),
  (9100, 20, 'fr', 'Error', 'Une modification de ce message est déjà en attente d''approbation.', NULL, NULL),
  (9100, 21, 'en', 'Error', 'Delete the other translations first; English is their fallback.', 'tenant delete of en for its own message while translations remain', NULL),
  (9100, 21, 'es', 'Error', 'Elimine primero las demás traducciones; el inglés es su respaldo.', NULL, NULL),
  (9100, 21, 'fr', 'Error', 'Supprimez d''abord les autres traductions ; l''anglais leur sert de repli.', NULL, NULL)
ON CONFLICT (set_nbr, message_nbr, language_cd) DO NOTHING;

UPDATE public.message_catalog SET user_action = 'Quote the reference when you contact support; it identifies the exact failure.' WHERE set_nbr = 1 AND message_nbr = 4 AND language_cd = 'en' AND user_action IS NULL;
