-- Message set 9400 (mastering): overrides and their policy.
INSERT INTO public.message_catalog (set_nbr, message_nbr, language_cd, severity, message_text, description, user_action) VALUES
  (9400, 16, 'en', 'Error', 'The override policy is not valid: the mode is APPROVAL or DIRECT, and 1 to 5 approvals are required.', NULL, NULL),
  (9400, 16, 'es', 'Error', 'La política de anulación no es válida: el modo es APPROVAL o DIRECT y se requieren de 1 a 5 aprobaciones.', NULL, NULL),
  (9400, 16, 'fr', 'Error', 'La politique de dérogation n''est pas valide : le mode est APPROVAL ou DIRECT, et 1 à 5 approbations sont requises.', NULL, NULL),
  (9400, 17, 'en', 'Error', '%1 is not an attribute this entity masters.', NULL, NULL),
  (9400, 17, 'es', 'Error', '%1 no es un atributo que esta entidad maestriza.', NULL, NULL),
  (9400, 17, 'fr', 'Error', '%1 n''est pas un attribut traité par cette entité.', NULL, NULL),
  (9400, 18, 'en', 'Error', 'Give a reason for the override - it is kept in the audit trail.', NULL, NULL),
  (9400, 18, 'es', 'Error', 'Indique un motivo para la anulación; se conserva en la auditoría.', NULL, NULL),
  (9400, 18, 'fr', 'Error', 'Indiquez un motif pour la dérogation ; il est conservé dans la piste d''audit.', NULL, NULL),
  (9400, 19, 'en', 'Error', 'Enter a valid value for %1.', NULL, NULL),
  (9400, 19, 'es', 'Error', 'Introduzca un valor válido para %1.', NULL, NULL),
  (9400, 19, 'fr', 'Error', 'Saisissez une valeur valide pour %1.', NULL, NULL),
  (9400, 20, 'en', 'Error', '%1 is not a valid code for %2.', NULL, NULL),
  (9400, 20, 'es', 'Error', '%1 no es un código válido para %2.', NULL, NULL),
  (9400, 20, 'fr', 'Error', '%1 n''est pas un code valide pour %2.', NULL, NULL),
  (9400, 21, 'en', 'Error', '%1 has no active override to clear.', NULL, NULL),
  (9400, 21, 'es', 'Error', '%1 no tiene ninguna anulación activa que quitar.', NULL, NULL),
  (9400, 21, 'fr', 'Error', '%1 n''a aucune dérogation active à retirer.', NULL, NULL),
  (9400, 22, 'en', 'Error', '%1 already has an override waiting for approval.', NULL, NULL),
  (9400, 22, 'es', 'Error', '%1 ya tiene una anulación pendiente de aprobación.', NULL, NULL),
  (9400, 22, 'fr', 'Error', '%1 a déjà une dérogation en attente d''approbation.', NULL, NULL),
  (9400, 23, 'en', 'Error', 'Override %1 was not found.', NULL, NULL),
  (9400, 23, 'es', 'Error', 'No se encontró la anulación %1.', NULL, NULL),
  (9400, 23, 'fr', 'Error', 'La dérogation %1 est introuvable.', NULL, NULL),
  (9400, 24, 'en', 'Error', 'This override has already been decided (%1).', NULL, NULL),
  (9400, 24, 'es', 'Error', 'Esta anulación ya se decidió (%1).', NULL, NULL),
  (9400, 24, 'fr', 'Error', 'Cette dérogation a déjà été traitée (%1).', NULL, NULL),
  (9400, 25, 'en', 'Error', 'You cannot approve or reject your own override; another person must.', NULL, NULL),
  (9400, 25, 'es', 'Error', 'No puede aprobar ni rechazar su propia anulación; debe hacerlo otra persona.', NULL, NULL),
  (9400, 25, 'fr', 'Error', 'Vous ne pouvez pas approuver ni rejeter votre propre dérogation ; une autre personne doit le faire.', NULL, NULL),
  (9400, 26, 'en', 'Error', 'You have already decided on this override.', NULL, NULL),
  (9400, 26, 'es', 'Error', 'Ya ha decidido sobre esta anulación.', NULL, NULL),
  (9400, 26, 'fr', 'Error', 'Vous avez déjà statué sur cette dérogation.', NULL, NULL),
  (9400, 27, 'en', 'Error', 'Only the person who proposed a pending override can withdraw it.', NULL, NULL),
  (9400, 27, 'es', 'Error', 'Solo quien propuso una anulación pendiente puede retirarla.', NULL, NULL),
  (9400, 27, 'fr', 'Error', 'Seule la personne qui a proposé une dérogation en attente peut la retirer.', NULL, NULL),
  (9400, 28, 'en', 'Error', 'Only administrators can change the override policy.', NULL, NULL),
  (9400, 28, 'es', 'Error', 'Solo los administradores pueden cambiar la política de anulación.', NULL, NULL),
  (9400, 28, 'fr', 'Error', 'Seuls les administrateurs peuvent modifier la politique de dérogation.', NULL, NULL)
ON CONFLICT (set_nbr, message_nbr, language_cd) DO NOTHING;
