package archguard

// openerInventory classifies every non-test file that opens a database connection (see
// tenant_connection_guard_test.go). Kinds are decided by reading each opener's DSN source, not
// by path. The tenant-datasource entries are the work list for moving tenant data access behind
// internal/tenantdb.
var openerInventory = map[string]opener{
	"internal/sourceconn/sourceconn.go":                          {Kind: kindSourceConnector, Max: 2, Reason: "the audited opener of tenant source databases: a pgxpool per authorized datasource (credentials from the secrets store, ownership under an explicit policy, bounded) and the ad hoc open used to test an unsaved connection"},
	"cmd/admin_audit_check/main.go":                              {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/admin_http_check/main.go":                               {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/apikeygen/main.go":                                      {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/apply_enhancements/main.go":                             {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/apply_migration_scan/main.go":                           {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/bo-service/main.go":                                     {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/catalog-admin/main.go":                                  {Kind: kindControlPlane, Max: 2, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/catalog-sync/main.go":                                   {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/catalog-worker/main.go":                                 {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/check_ddl_regression/main.go":                           {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/cleanup_stale_terms/main.go":                            {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/debug-categories/main.go":                               {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/debug_impact/main.go":                                   {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/demo.go":                                                {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/demo/preaggregation/preaggregation_demo.go":             {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/demo_xirr_execution/main.go":                            {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/e2e/db.go":                                              {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/e2e_bo_check/main.go":                                   {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/e2e_bo_check2/main.go":                                  {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/event-router/main.go":                                   {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/fix_driver_table/main.go":                               {Kind: kindTool, Max: 2, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/fix_tables/main.go":                                     {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/generate-embeddings/main.go":                            {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/generate_dynamic_measures.go":                           {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/inspect_node_ids/main.go":                               {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/inspect_schema/main.go":                                 {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/ledger-demo/main.go":                                    {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/mdm-friction-importer/main.go":                          {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/migrate-datasource-creds/main.go":                       {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/migrate-db/main.go":                                     {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/migrate-report-schedules/main.go":                       {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/migrate/main.go":                                        {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/migrate_validation_rules/main.go":                       {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/notifications-service/main.go":                          {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/outbox-processor/main.go":                               {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/populate_bo_fields/main.go":                             {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/preaggregation/main.go":                                 {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/profiler/main.go":                                       {Kind: kindTenantDatasource, Max: 2, Reason: "opens alpha (alphaPool) and the source DSN of a datasource", Until: "4a follow-up with the scanner"},
	"cmd/register_oms_preagg/main.go":                            {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/report-smoke-test/main.go":                              {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/run_quick_migration/main.go":                            {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/scan_ownership_exposure/main.go":                        {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/screen-builder-service/main.go":                         {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/security-api/main.go":                                   {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/security-event-worker/main.go":                          {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/security-sync-worker/main.go":                           {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/seed-calculations/main.go":                              {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed-notifications/main.go":                             {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed-orm-bos/main.go":                                   {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed-wealth/main.go":                                    {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed_data_values/main.go":                               {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed_data_values_v2/main.go":                            {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed_iso_codes/main.go":                                 {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed_mdm_rules/main.go":                                 {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed_northwind_bos/main.go":                             {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/seed_xirr_catalog/main.go":                              {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/semanticmatch/main.go":                                  {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/server/main.go":                                         {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/simulate/main.go":                                       {Kind: kindTool, Max: 3, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/stream_loader/main.go":                                  {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/sync-graph/main.go":                                     {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/temporal-worker/main.go":                                {Kind: kindControlPlane, Max: 2, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/test-create-semantic-term/main.go":                      {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/triggers/main.go":                                       {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"cmd/verify/verify_engagement_notifications.go":              {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_calc_measure/main.go":                            {Kind: kindTool, Max: 2, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_collection_aggregation/main.go":                  {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_compliance_domain/main.go":                       {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_mdm_e2e/main.go":                                 {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_oms_validations/main.go":                         {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_oracle_rule/main.go":                             {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_order_validations/main.go":                       {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_second_binding/main.go":                          {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_shadow_context/main.go":                          {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_stats_measure/main.go":                           {Kind: kindTool, Max: 3, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/verify_three_domains/main.go":                           {Kind: kindTool, Max: 1, Reason: "a one-off command-line tool (seed, verify, demo, fix, migrate): not served, opens the database it is pointed at"},
	"cmd/worker/main.go":                                         {Kind: kindControlPlane, Max: 1, Reason: "a served command: opens alpha from DATABASE_URL-style configuration"},
	"db.go":                                                      {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"integration/docker_helper.go":                               {Kind: kindTool, Max: 1, Reason: "test support: starts and connects to a throwaway database"},
	"internal/analytics/pre_aggregation_service.go":              {Kind: kindWarehouse, Max: 1, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/analytics/service.go":                              {Kind: kindWarehouse, Max: 1, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/analytics/starrocks_client.go":                     {Kind: kindWarehouse, Max: 2, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/api/admin_report_handlers.go":                      {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/api/api.go":                                        {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/api/data_pipeline_wiring.go":                       {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/api/schedule_wiring.go":                            {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/bundles/handler.go":                                {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/calcengine/multi_source_engine.go":                 {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/calcengine/starrocks.go":                           {Kind: kindWarehouse, Max: 1, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/calcengine/unified_engine.go":                      {Kind: kindWarehouse, Max: 1, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/db/connection.go":                                  {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/db/mcp_role_db.go":                                 {Kind: kindControlPlane, Max: 2, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/deployment/container.go":                           {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/lakehouse/infra/starrocks.go":                      {Kind: kindWarehouse, Max: 1, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/metadata/catalog_scan_service.go":                  {Kind: kindTenantDatasource, Max: 1, Reason: "opens a datasource's connection from hydrated config; the business-object service reaches tenant datasources through it. These are tenant SOURCE databases of several types, so Postgres-only tenantdb is not the whole answer", Until: "4a follow-up: Postgres datasources behind tenantdb, other types behind a source-connector sibling"},
	"internal/observability/slo_report_generator.go":             {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/planner/test_fixtures.go":                          {Kind: kindTool, Max: 1, Reason: "test fixtures"},
	"internal/profiler/profiler.go":                              {Kind: kindTenantDatasource, Max: 1, Reason: "opens the source DSN it is handed for a datasource", Until: "4a follow-up with the scanner"},
	"internal/sync/starrocks_worker.go":                          {Kind: kindWarehouse, Max: 1, Reason: "opens StarRocks (MySQL protocol) from configuration"},
	"internal/temporal/activities/tenant_database_activities.go": {Kind: kindProvisioning, Max: 2, Reason: "administrator connection to the shared cluster to create roles, grants and run tenant migrations, plus the isolation check that connects AS the tenant role to other databases to prove it is denied (the saga)"},
	"internal/temporal/activities/tenant_instance_activities.go": {Kind: kindProvisioning, Max: 2, Reason: "administrator connection to the shared cluster to CREATE and DROP tenant databases (the saga)"},
	"internal/tenantauto/provisioner.go":                         {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/tenantauto/reconciler.go":                          {Kind: kindControlPlane, Max: 1, Reason: "opens alpha or another platform database from the process's own configuration"},
	"internal/tenantdb/tenantdb.go":                              {Kind: kindTenantDB, Max: 1, Reason: "the router: the only package allowed to open a tenant database for data access"},
	"internal/trading/persist.go":                                {Kind: kindTenantDatasource, Max: 1, Reason: "the ORM database, opened from CRIMS_ORM_DSN (or DATABASE_URL with the name swapped to crims): ONE shared database, not one per tenant", Until: "4b: ORM data move, then behind tenantdb"},
	"migrations/cmd/migrate.go":                                  {Kind: kindTool, Max: 1, Reason: "migration command for alpha"},
	"services/uma-rebalance/main.go":                             {Kind: kindControlPlane, Max: 1, Reason: "standalone service that opens DATABASE_URL"},
}
