#!/bin/bash
set -euo pipefail

INFISICAL_PROJECT="${INFISICAL_PROJECT:-uisce}"
INFISICAL_ENV="${INFISICAL_ENV:-dev}"
INFISICAL_TOKEN="${INFISICAL_TOKEN:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Bootstrap secrets from Infisical for local development.

OPTIONS:
  -e, --env ENV         Environment: dev, staging, prod (default: dev)
  -p, --project PROJECT Infisical project name (default: uisce)
  -t, --token TOKEN     Infisical service token (or set INFISICAL_TOKEN env var)
  --dry-run             Show what would be generated without writing files
  -h, --help            Show this help message

EXAMPLES:
  # Use default (dev environment)
  ./infisical-bootstrap.sh

  # Generate for staging
  ./infisical-bootstrap.sh -e staging

  # Use a specific token
  ./infisical-bootstrap.sh -t ifs_xxxxx

ENVIRONMENT VARIABLES:
  INFISICAL_TOKEN    Infisical service token (required)
  INFISICAL_PROJECT  Project name (default: uisce)
  INFISICAL_ENV      Environment (default: dev)

INFISICAL SETUP:
  1. Install Infisical CLI: brew install infisical
  2. Run: infisical login
  3. Create a service token at: https://app.infisical.com
  4. Export: export INFISICAL_TOKEN=ifs_xxxxx

EOF
    exit 1
}

log() { echo "[bootstrap] $*"; }
warn() { echo "[bootstrap] WARNING: $*" >&2; }
die() { echo "[bootstrap] ERROR: $*" >&2; exit 1; }

check_infisical() {
    if ! command -v infisical &> /dev/null; then
        die "Infisical CLI not found. Install: brew install infisical"
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -e|--env) INFISICAL_ENV="$2"; shift 2 ;;
            -p|--project) INFISICAL_PROJECT="$2"; shift 2 ;;
            -t|--token) INFISICAL_TOKEN="$2"; shift 2 ;;
            --dry-run) DRY_RUN=true; shift ;;
            -h|--help) usage ;;
            *) die "Unknown option: $1" ;;
        esac
    done
}

pull_secrets_at_path() {
    local path="$1"
    local domain_arg="--domain=http://100.84.50.65:8085/api"
    local proj_arg="--projectId=9af25976-bafc-4895-a057-2effec13c620"
    local output=""

    # Run non-interactively with /dev/null stdin so infisical will not prompt
    if [ -n "$INFISICAL_TOKEN" ]; then
        output=$(infisical secrets $domain_arg $proj_arg --env="$INFISICAL_ENV" --path="$path" --recursive -o json --token="$INFISICAL_TOKEN" --silent </dev/null 2>/dev/null || true)
    else
        output=$(infisical secrets $domain_arg $proj_arg --env="$INFISICAL_ENV" --path="$path" --recursive -o json --silent </dev/null 2>/dev/null || true)
    fi

    if [ -z "$output" ] || ! echo "$output" | jq . >/dev/null 2>&1; then
        output="{}"
    fi
    echo "$output"
}

# Merges two Infisical JSON secret payloads (each may be an array of
# {secretKey, secretValue} or an object) into a single deduped array,
# with entries from $2 winning over $1 on key collisions.
merge_secrets_json() {
    local a b
    a=$(echo "$1" | jq 'if type=="array" then . elif type=="object" and length>0 then (to_entries | map({secretKey:.key, secretValue:.value})) else [] end' 2>/dev/null) || a='[]'
    b=$(echo "$2" | jq 'if type=="array" then . elif type=="object" and length>0 then (to_entries | map({secretKey:.key, secretValue:.value})) else [] end' 2>/dev/null) || b='[]'
    jq -n --argjson a "$a" --argjson b "$b" '
        ($a + $b) as $all
        | reduce $all[] as $item ({}; if $item.secretKey != null and $item.secretKey != "" then .[$item.secretKey] = $item.secretValue else . end)
        | to_entries | map({secretKey: .key, secretValue: .value})
    '
}

pull_secrets() {
    # Secrets live both at the project root and inside a "core" folder
    # (e.g. KEYCLOAK_JWKS_URL, DATABASE_URL). --recursive from "/" is
    # supposed to cover both, but fetch /core explicitly too so a
    # folder-scoped token or a CLI version that doesn't honor --recursive
    # for nested folders still picks these up.
    local root_output core_output
    root_output=$(pull_secrets_at_path "/")
    core_output=$(pull_secrets_at_path "/core")

    if [ "$root_output" = "{}" ] && [ "$core_output" = "{}" ]; then
        warn "Could not fetch valid JSON secrets from Infisical (not logged in or server unreachable). Using default/existing environment settings."
    fi

    merge_secrets_json "$root_output" "$core_output"
}

generate_env_file() {
    local secrets_json="$1"
    local output_path="$2"
    local section="$3"

    if [ -n "${DRY_RUN:-}" ]; then
        log "[DRY-RUN] Would generate $output_path"
        return
    fi

    log "Generating $output_path ($section)"

    {
        echo "# Generated by scripts/infisical-bootstrap.sh"
        echo "# Environment: $INFISICAL_ENV | Project: $INFISICAL_PROJECT"
        echo "# DO NOT COMMIT THIS FILE"
        echo ""
    } > "$output_path"

    if [ -z "$secrets_json" ] || [ "$secrets_json" = "null" ]; then
        warn "No secrets returned for $section"
        return
    fi

    echo "$secrets_json" | jq -r '
        if type == "array" then
            .[] | select(.secretKey != null and .secretKey != "") | "\(.secretKey)=\"\(.secretValue)\""
        elif type == "object" then
            to_entries[] | "\(.key)=\"\(.value)\""
        end
    ' >> "$output_path" 2>/dev/null || warn "Failed to parse JSON for $section"
}

generate_composite_secrets() {
    local output_path="$1"
    local prev_database_url="$2"
    local prev_postgres_dsn="$3"
    local db_pass="${POSTGRES_PASSWORD:-postgres}"
    local db_user="${POSTGRES_USER:-postgres}"
    local db_host="${DB_HOST:-100.84.50.65}"
    local db_port="${DB_PORT:-5432}"
    local db_name="${DB_NAME:-alpha}"

    if [ -n "${DRY_RUN:-}" ]; then
        log "[DRY-RUN] Would generate composite secrets in $output_path"
        return
    fi

    # generate_env_file truncates $output_path on every run and only
    # repopulates DATABASE_URL/POSTGRES_DSN from Infisical when the pull
    # succeeds. Before this guard existed, an unreachable Infisical server
    # silently clobbered a working TLS-configured DSN (sslmode=verify-full
    # plus client certs) with a plaintext sslmode=disable default on every
    # single run - see backend/docs/INCIDENT_REPORT_20260906.md. Prefer
    # whatever DSN was already in this file before this run truncated it;
    # only fall back to the plaintext default, loudly, if there was
    # nothing to preserve (e.g. a genuinely first-time bootstrap).
    if ! grep -q "^DATABASE_URL=" "$output_path"; then
        if [ -n "$prev_database_url" ]; then
            # Quoted: the DSN contains "&", which an unquoted assignment
            # in a sourced .env file hands to the shell as a job-control
            # operator, silently truncating the value to empty the moment
            # anything sources this file with plain `source`/`. `.
            echo "DATABASE_URL=\"${prev_database_url}\"" >> "$output_path"
        else
            warn "No DATABASE_URL from Infisical or a prior $output_path - writing an insecure sslmode=disable default. This should only happen on a genuine first-time bootstrap."
            echo "DATABASE_URL=postgres://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}?sslmode=disable" >> "$output_path"
        fi
    fi
    if ! grep -q "^POSTGRES_DSN=" "$output_path"; then
        if [ -n "$prev_postgres_dsn" ]; then
            echo "POSTGRES_DSN=\"${prev_postgres_dsn}\"" >> "$output_path"
        else
            warn "No POSTGRES_DSN from Infisical or a prior $output_path - writing an insecure sslmode=disable default. This should only happen on a genuine first-time bootstrap."
            echo "POSTGRES_DSN=postgresql://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}?sslmode=disable" >> "$output_path"
        fi
    fi
    if ! grep -q "^REDIS_URL=" "$output_path"; then
        echo "REDIS_URL=redis://${db_host}:6379" >> "$output_path"
    fi
    if ! grep -q "^API_TOKEN_ENCRYPTION_KEY_DEV_FALLBACK=" "$output_path"; then
        echo "API_TOKEN_ENCRYPTION_KEY_DEV_FALLBACK=true" >> "$output_path"
    fi
    if ! grep -q "^API_TOKEN_ENCRYPTION_KEY=" "$output_path"; then
        echo "API_TOKEN_ENCRYPTION_KEY=D+1O956T8t9zZ+w/FqK1lS9b8jJ2vR7mX4kY0uP3oN8=" >> "$output_path"
    fi

    # Keycloak JWKS/issuer defaults. These are not currently stored as
    # Infisical secrets, so without this fallback the backend silently
    # ends up with no RSA public key configured and rejects every
    # user-issued JWT with "missing or invalid JWT token" (401s across
    # the app). Prefer real Infisical secrets when present; only fill in
    # gaps here.
    local kc_host="${KEYCLOAK_HOST:-100.84.50.65}"
    local kc_port="${KEYCLOAK_PORT:-8443}"
    local kc_realm="${KEYCLOAK_REALM:-uisce}"
    if ! grep -q "^KEYCLOAK_HOST=" "$output_path"; then
        echo "KEYCLOAK_HOST=${kc_host}" >> "$output_path"
    fi
    if ! grep -q "^KEYCLOAK_PORT=" "$output_path"; then
        echo "KEYCLOAK_PORT=${kc_port}" >> "$output_path"
    fi
    if ! grep -q "^KEYCLOAK_REALM=" "$output_path"; then
        echo "KEYCLOAK_REALM=${kc_realm}" >> "$output_path"
    fi
    if ! grep -q "^KEYCLOAK_JWKS_URL=" "$output_path"; then
        echo "KEYCLOAK_JWKS_URL=https://${kc_host}:${kc_port}/realms/${kc_realm}/protocol/openid-connect/certs" >> "$output_path"
    fi
    if ! grep -q "^KEYCLOAK_ISSUER=" "$output_path"; then
        echo "KEYCLOAK_ISSUER=https://${kc_host}:${kc_port}/realms/${kc_realm}" >> "$output_path"
    fi
    if ! grep -q "^KEYCLOAK_INSECURE_SKIP_VERIFY=" "$output_path"; then
        echo "KEYCLOAK_INSECURE_SKIP_VERIFY=true" >> "$output_path"
    fi
}

# capture_env_value prints the current value of KEY from a .env file
# before generate_env_file truncates it, so generate_composite_secrets can
# preserve it instead of clobbering it with an insecure default. Strips a
# surrounding pair of double quotes if present (generate_env_file writes
# values quoted; hand-edited files may not be).
capture_env_value() {
    local path="$1"
    local key="$2"
    [ -f "$path" ] || return 0
    local line
    line=$(grep "^${key}=" "$path" | tail -n1)
    [ -n "$line" ] || return 0
    line="${line#${key}=}"
    line="${line%\"}"
    line="${line#\"}"
    echo "$line"
}

main() {
    parse_args "$@"
    check_infisical

    log "Pulling secrets for project=$INFISICAL_PROJECT env=$INFISICAL_ENV"

    local all_secrets
    all_secrets=$(pull_secrets)

    local root_env="$ROOT_DIR/.env"
    local backend_env="$ROOT_DIR/backend/.env"
    local frontend_env="$ROOT_DIR/frontend/.env.local"
    local calendar_env="$ROOT_DIR/calendar-service/.env"
    local rebalancing_env="$ROOT_DIR/rebalancing/.env"


    local env_vars
    env_vars=$(echo "$all_secrets" | jq -r 'if type == "array" then .[] | "\(.key)=\(.value)" elif type == "object" and length > 0 then to_entries[] | "\(.key)=\(.value)" else empty end' 2>/dev/null) || true
    if [ -n "$env_vars" ]; then
        eval "$(echo "$env_vars" | while read -r line; do [ -n "$line" ] && echo "export $line"; done)"
    fi

    local prev_db_url prev_dsn
    prev_db_url=$(capture_env_value "$root_env" "DATABASE_URL")
    prev_dsn=$(capture_env_value "$root_env" "POSTGRES_DSN")
    generate_env_file "$all_secrets" "$root_env" "root"
    generate_composite_secrets "$root_env" "$prev_db_url" "$prev_dsn"

    if [ -d "$ROOT_DIR/backend" ]; then
        prev_db_url=$(capture_env_value "$backend_env" "DATABASE_URL")
        prev_dsn=$(capture_env_value "$backend_env" "POSTGRES_DSN")
        generate_env_file "$all_secrets" "$backend_env" "backend"
        generate_composite_secrets "$backend_env" "$prev_db_url" "$prev_dsn"
    fi

    if [ -d "$ROOT_DIR/frontend" ]; then
        generate_env_file "$all_secrets" "$frontend_env" "frontend"
    fi

    if [ -d "$ROOT_DIR/calendar-service" ]; then
        prev_db_url=$(capture_env_value "$calendar_env" "DATABASE_URL")
        prev_dsn=$(capture_env_value "$calendar_env" "POSTGRES_DSN")
        generate_env_file "$all_secrets" "$calendar_env" "calendar-service"
        generate_composite_secrets "$calendar_env" "$prev_db_url" "$prev_dsn"
    fi

    if [ -d "$ROOT_DIR/rebalancing" ]; then
        prev_db_url=$(capture_env_value "$rebalancing_env" "DATABASE_URL")
        prev_dsn=$(capture_env_value "$rebalancing_env" "POSTGRES_DSN")
        generate_env_file "$all_secrets" "$rebalancing_env" "rebalancing"
        generate_composite_secrets "$rebalancing_env" "$prev_db_url" "$prev_dsn"
    fi

    log "Done. Generated .env files:"
    [ -f "$root_env" ] && echo "  - $root_env"
    [ -f "$backend_env" ] && echo "  - $backend_env"
    [ -f "$frontend_env" ] && echo "  - $frontend_env"
    [ -f "$calendar_env" ] && echo "  - $calendar_env"
    [ -f "$rebalancing_env" ] && echo "  - $rebalancing_env"

    echo ""
    log "Next steps:"
    echo "  1. Review generated .env files (they contain secrets)"
    echo "  2. Add .env files to .gitignore if not already present"
    echo "  3. Run: docker-compose up -d"
}

main "$@"
