#!/bin/bash
set -euo pipefail

INFISICAL_PROJECT="${INFISICAL_PROJECT:-uisce}"
INFISICAL_ENV="${INFISICAL_ENV:-dev}"
INFISICAL_TOKEN="${INFISICAL_TOKEN:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Bootstrap secrets from Infisical for local development.

OPTIONS:
  -e, --env ENV         Environment: dev, staging, prod (default: dev)
  -p, --project PROJECT Infisical project name (default: uisce)
  -t, --token TOKEN     Infisical service token (or set INFISICAL_TOKEN env var)
  --dry-run             Show what would be generated without writing files
  -h, --help            Show this help message

EXAMPLES:
  # Use default (dev environment)
  ./infisical-bootstrap.sh

  # Generate for staging
  ./infisical-bootstrap.sh -e staging

  # Use a specific token
  ./infisical-bootstrap.sh -t ifs_xxxxx

ENVIRONMENT VARIABLES:
  INFISICAL_TOKEN    Infisical service token (required)
  INFISICAL_PROJECT  Project name (default: uisce)
  INFISICAL_ENV      Environment (default: dev)

INFISICAL SETUP:
  1. Install Infisical CLI: brew install infisical
  2. Run: infisical login
  3. Create a service token at: https://app.infisical.com
  4. Export: export INFISICAL_TOKEN=ifs_xxxxx

EOF
    exit 1
}

log() { echo "[bootstrap] $*"; }
warn() { echo "[bootstrap] WARNING: $*" >&2; }
die() { echo "[bootstrap] ERROR: $*" >&2; exit 1; }

check_infisical() {
    if ! command -v infisical &> /dev/null; then
        die "Infisical CLI not found. Install: brew install infisical"
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -e|--env) INFISICAL_ENV="$2"; shift 2 ;;
            -p|--project) INFISICAL_PROJECT="$2"; shift 2 ;;
            -t|--token) INFISICAL_TOKEN="$2"; shift 2 ;;
            --dry-run) DRY_RUN=true; shift ;;
            -h|--help) usage ;;
            *) die "Unknown option: $1" ;;
        esac
    done
}

pull_secrets() {
    local output=""
    local domain_arg="--domain=http://100.84.50.65:8085/api"
    local proj_arg="--projectId=9af25976-bafc-4895-a057-2effec13c620"
    
    # Run non-interactively with /dev/null stdin so infisical will not prompt
    if [ -n "$INFISICAL_TOKEN" ]; then
        output=$(infisical secrets $domain_arg $proj_arg --env="$INFISICAL_ENV" --recursive -o json --token="$INFISICAL_TOKEN" --silent </dev/null 2>/dev/null || true)
    else
        output=$(infisical secrets $domain_arg $proj_arg --env="$INFISICAL_ENV" --recursive -o json --silent </dev/null 2>/dev/null || true)
    fi
    
    if [ -z "$output" ] || ! echo "$output" | jq . >/dev/null 2>&1; then
        warn "Could not fetch valid JSON secrets from Infisical (not logged in or server unreachable). Using default/existing environment settings."
        output="{}"
    fi
    echo "$output"
}

generate_env_file() {
    local secrets_json="$1"
    local output_path="$2"
    local section="$3"

    if [ -n "${DRY_RUN:-}" ]; then
        log "[DRY-RUN] Would generate $output_path"
        return
    fi

    log "Generating $output_path ($section)"

    {
        echo "# Generated by scripts/infisical-bootstrap.sh"
        echo "# Environment: $INFISICAL_ENV | Project: $INFISICAL_PROJECT"
        echo "# DO NOT COMMIT THIS FILE"
        echo ""
    } > "$output_path"

    if [ -z "$secrets_json" ] || [ "$secrets_json" = "null" ]; then
        warn "No secrets returned for $section"
        return
    fi

    echo "$secrets_json" | jq -r '
        if type == "array" then
            .[] | select(.secretKey != null and .secretKey != "") | "\(.secretKey)=\"\(.secretValue)\""
        elif type == "object" then
            to_entries[] | "\(.key)=\"\(.value)\""
        end
    ' >> "$output_path" 2>/dev/null || warn "Failed to parse JSON for $section"
}

generate_composite_secrets() {
    local output_path="$1"
    local db_pass="${POSTGRES_PASSWORD:-postgres}"
    local db_user="${POSTGRES_USER:-postgres}"
    local db_host="${DB_HOST:-100.84.50.65}"
    local db_port="${DB_PORT:-5432}"
    local db_name="${DB_NAME:-alpha}"

    if [ -n "${DRY_RUN:-}" ]; then
        log "[DRY-RUN] Would generate composite secrets in $output_path"
        return
    fi

    if ! grep -q "^DATABASE_URL=" "$output_path"; then
        echo "DATABASE_URL=postgres://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}?sslmode=disable" >> "$output_path"
    fi
    if ! grep -q "^POSTGRES_DSN=" "$output_path"; then
        echo "POSTGRES_DSN=postgresql://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}?sslmode=disable" >> "$output_path"
    fi
    if ! grep -q "^REDIS_URL=" "$output_path"; then
        echo "REDIS_URL=redis://${db_host}:6379" >> "$output_path"
    fi
    if ! grep -q "^API_TOKEN_ENCRYPTION_KEY_DEV_FALLBACK=" "$output_path"; then
        echo "API_TOKEN_ENCRYPTION_KEY_DEV_FALLBACK=true" >> "$output_path"
    fi
    if ! grep -q "^API_TOKEN_ENCRYPTION_KEY=" "$output_path"; then
        echo "API_TOKEN_ENCRYPTION_KEY=D+1O956T8t9zZ+w/FqK1lS9b8jJ2vR7mX4kY0uP3oN8=" >> "$output_path"
    fi
}

main() {
    parse_args "$@"
    check_infisical

    log "Pulling secrets for project=$INFISICAL_PROJECT env=$INFISICAL_ENV"

    local all_secrets
    all_secrets=$(pull_secrets)

    local root_env="$ROOT_DIR/.env"
    local backend_env="$ROOT_DIR/backend/.env"
    local frontend_env="$ROOT_DIR/frontend/.env.local"
    local calendar_env="$ROOT_DIR/calendar-service/.env"
    local rebalancing_env="$ROOT_DIR/rebalancing/.env"


    local env_vars
    env_vars=$(echo "$all_secrets" | jq -r 'if type == "array" then .[] | "\(.key)=\(.value)" elif type == "object" and length > 0 then to_entries[] | "\(.key)=\(.value)" else empty end' 2>/dev/null) || true
    if [ -n "$env_vars" ]; then
        eval "$(echo "$env_vars" | while read -r line; do [ -n "$line" ] && echo "export $line"; done)"
    fi

    generate_env_file "$all_secrets" "$root_env" "root"
    generate_composite_secrets "$root_env"

    if [ -d "$ROOT_DIR/backend" ]; then
        generate_env_file "$all_secrets" "$backend_env" "backend"
        generate_composite_secrets "$backend_env"
    fi

    if [ -d "$ROOT_DIR/frontend" ]; then
        generate_env_file "$all_secrets" "$frontend_env" "frontend"
    fi

    if [ -d "$ROOT_DIR/calendar-service" ]; then
        generate_env_file "$all_secrets" "$calendar_env" "calendar-service"
        generate_composite_secrets "$calendar_env"
    fi

    if [ -d "$ROOT_DIR/rebalancing" ]; then
        generate_env_file "$all_secrets" "$rebalancing_env" "rebalancing"
        generate_composite_secrets "$rebalancing_env"
    fi

    log "Done. Generated .env files:"
    [ -f "$root_env" ] && echo "  - $root_env"
    [ -f "$backend_env" ] && echo "  - $backend_env"
    [ -f "$frontend_env" ] && echo "  - $frontend_env"
    [ -f "$calendar_env" ] && echo "  - $calendar_env"
    [ -f "$rebalancing_env" ] && echo "  - $rebalancing_env"

    echo ""
    log "Next steps:"
    echo "  1. Review generated .env files (they contain secrets)"
    echo "  2. Add .env files to .gitignore if not already present"
    echo "  3. Run: docker-compose up -d"
}

main "$@"
