#!/bin/bash

# Test Hasura Multi-Tenant Security
# This script tests that tenant isolation and global admin access work correctly

set -e

BACKEND_URL="${BACKEND_URL:-http://localhost:8080}"
HASURA_URL="${HASURA_URL:-http://localhost:8080}"

echo "🧪 Testing Hasura Multi-Tenant Security"
echo "Backend URL: $BACKEND_URL"
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test 1: Login as standard user
echo "Test 1: Login as standard user"
echo "================================"

# You'll need to create test users first
# For now, we'll show the commands

echo -e "${YELLOW}To test, first create test users:${NC}"
echo ""
echo "-- Create tenant A"
echo "INSERT INTO tenants (id, name) VALUES ('00000000-0000-0000-0000-000000000001', 'tenant-a');"
echo ""
echo "-- Create tenant B"
echo "INSERT INTO tenants (id, name) VALUES ('00000000-0000-0000-0000-000000000002', 'tenant-b');"
echo ""
echo "-- Create user in tenant A"
echo "INSERT INTO users (id, email, password_hash, name, role, organization, tenant_id, is_core_admin)"
echo "VALUES ("
echo "  '10000000-0000-0000-0000-000000000001',"
echo "  'user-a@tenant-a.com',"
echo "  '\$2a\$10\$...',"  # bcrypt hash of 'password123'
echo "  'User A',"
echo "  'user',"
echo "  'tenant-a',"
echo "  '00000000-0000-0000-0000-000000000001',"
echo "  false"
echo ");"
echo ""
echo "-- Create user in tenant B"
echo "INSERT INTO users (id, email, password_hash, name, role, organization, tenant_id, is_core_admin)"
echo "VALUES ("
echo "  '20000000-0000-0000-0000-000000000001',"
echo "  'user-b@tenant-b.com',"
echo "  '\$2a\$10\$...',"  # bcrypt hash of 'password123'
echo "  'User B',"
echo "  'user',"
echo "  'tenant-b',"
echo "  '00000000-0000-0000-0000-000000000002',"
echo "  false"
echo ");"
echo ""
echo "-- Create global admin (Uisce organization)"
echo "INSERT INTO users (id, email, password_hash, name, role, organization, tenant_id, is_core_admin)"
echo "VALUES ("
echo "  '99000000-0000-0000-0000-000000000001',"
echo "  'admin@uisce.com',"
echo "  '\$2a\$10\$...',"  # bcrypt hash of 'password123'
echo "  'Global Admin',"
echo "  'admin',"
echo "  'uisce',"
echo "  NULL,"
echo "  true"
echo ");"
echo ""

# Test 2: Verify JWT claims
echo "Test 2: Verify JWT Token Claims"
echo "================================"
echo ""
echo "Login and inspect JWT token:"
echo ""
echo "curl -X POST $BACKEND_URL/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\": \"user-a@tenant-a.com\", \"password\": \"password123\"}' | jq ."
echo ""
echo -e "${YELLOW}Expected JWT claims:${NC}"
echo "{"
echo "  \"https://hasura.io/jwt/claims\": {"
echo "    \"x-hasura-allowed-roles\": [\"user\"],"
echo "    \"x-hasura-default-role\": \"user\","
echo "    \"x-hasura-user-id\": \"10000000-0000-0000-0000-000000000001\","
echo "    \"x-hasura-tenant-id\": \"00000000-0000-0000-0000-000000000001\""
echo "  }"
echo "}"
echo ""

# Test 3: Test tenant isolation
echo "Test 3: Test Tenant Isolation"
echo "=============================="
echo ""
echo "1. Create test data in each tenant:"
echo ""
echo "-- Tenant A data"
echo "INSERT INTO business_objects (id, name, display_name, fields, tenant_id)"
echo "VALUES ("
echo "  '11111111-0000-0000-0000-000000000001',"
echo "  'client_a',"
echo "  'Client A',"
echo "  '[]'::jsonb,"
echo "  '00000000-0000-0000-0000-000000000001'"
echo ");"
echo ""
echo "-- Tenant B data"
echo "INSERT INTO business_objects (id, name, display_name, fields, tenant_id)"
echo "VALUES ("
echo "  '22222222-0000-0000-0000-000000000001',"
echo "  'client_b',"
echo "  'Client B',"
echo "  '[]'::jsonb,"
echo "  '00000000-0000-0000-0000-000000000002'"
echo ");"
echo ""
echo "2. Query as Tenant A user (should only see Tenant A data):"
echo ""
echo "TOKEN_A=\$(curl -s -X POST $BACKEND_URL/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\": \"user-a@tenant-a.com\", \"password\": \"password123\"}' | jq -r '.access_token')"
echo ""
echo "curl -X POST $HASURA_URL/v1/graphql \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H \"Authorization: Bearer \$TOKEN_A\" \\"
echo "  -d '{"
echo "    \"query\": \"{ business_objects { id name tenant_id } }\""
echo "  }' | jq ."
echo ""
echo -e "${GREEN}Expected: Only returns business_objects with tenant_id = '00000000-0000-0000-0000-000000000001'${NC}"
echo ""

# Test 4: Test global admin access
echo "Test 4: Test Global Admin Access"
echo "================================="
echo ""
echo "Query as Global Admin (should see ALL tenants' data):"
echo ""
echo "TOKEN_ADMIN=\$(curl -s -X POST $BACKEND_URL/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\": \"admin@uisce.com\", \"password\": \"password123\"}' | jq -r '.access_token')"
echo ""
echo "curl -X POST $HASURA_URL/v1/graphql \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H \"Authorization: Bearer \$TOKEN_ADMIN\" \\"
echo "  -d '{"
echo "    \"query\": \"{ business_objects { id name tenant_id } }\""
echo "  }' | jq ."
echo ""
echo -e "${GREEN}Expected: Returns business_objects from BOTH tenants${NC}"
echo ""

# Test 5: Test unauthorized access
echo "Test 5: Test Unauthorized Access Prevention"
echo "============================================"
echo ""
echo "Try to query without authentication:"
echo ""
echo "curl -X POST $HASURA_URL/v1/graphql \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"query\": \"{ business_objects { id name } }\""
echo "  }' | jq ."
echo ""
echo -e "${GREEN}Expected: Error - missing or invalid authorization${NC}"
echo ""

# Summary
echo "========================================="
echo "Test Summary"
echo "========================================="
echo ""
echo -e "${YELLOW}Manual Testing Steps:${NC}"
echo "1. Create test users and tenants (SQL above)"
echo "2. Login as each user and verify JWT claims"
echo "3. Query GraphQL and verify tenant isolation"
echo "4. Login as global admin and verify full access"
echo ""
echo -e "${GREEN}Security Checklist:${NC}"
echo "✓ JWT tokens include tenant_id and role"
echo "✓ Hasura permissions configured for user and global_admin roles"
echo "✓ Tenant users can only see their tenant's data"
echo "✓ Global admins can see all tenants' data"
echo "✓ Unauthenticated requests are rejected"
echo ""
