-- ============================================================================
-- 0004_oms_orders.sql
-- Core order tables: orders, order_slice, order_link.
-- Run after 0003_mds.sql
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- oms.orders
-- Primary order table — parent orders only. Child slices go in order_slice.
-- state machine driven by ref.order_status; transitions logged in order_event.
-- --------------------------------------------------------------------------
CREATE TABLE oms.orders (
    id                        UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id                 UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',

    -- external / correlation identifiers
    client_order_id           VARCHAR(100) NOT NULL,   -- firm's own order ref
    venue_order_id           VARCHAR(100),             -- venue's order ref (filled post-routing)
    alt_venue_order_id        VARCHAR(100),            -- backup venue ref
    alt_client_order_id       VARCHAR(100),            -- secondary firm ref

    -- routing context
    portfolio_id              UUID        NOT NULL REFERENCES mds.portfolio(id),
    account_id               UUID        NOT NULL REFERENCES mds.account(id),
    security_id              UUID        NOT NULL REFERENCES mds.security_master(id),
    venue_id                 UUID        REFERENCES mds.venue(id),  -- preferred venue; routing engine may override

    -- order specification
    side                      VARCHAR(20) NOT NULL REFERENCES ref.side(code),
    order_type_id            INTEGER     NOT NULL REFERENCES ref.order_type(id),
    time_in_force_id         INTEGER     NOT NULL REFERENCES ref.time_in_force(id),
    asset_class              VARCHAR(30) NOT NULL REFERENCES ref.asset_class(code),

    quantity                  NUMERIC(20,6) NOT NULL,
    limit_price              NUMERIC(20,8),
    stop_price               NUMERIC(20,8),
    stop_limit_price         NUMERIC(20,8),           -- for STOP_LIMIT
    algo_params              JSONB       DEFAULT '{}', -- TWAP slices, VWAP POV, etc.

    -- currency / settlement
    settlement_ccy           CHAR(3)     REFERENCES ref.currency(iso3_code),
    currency_id              INTEGER     REFERENCES ref.currency(id),

    -- state
    status_id                INTEGER,
    filled_qty               NUMERIC(20,6) DEFAULT 0,
    avg_fill_price           NUMERIC(20,8) DEFAULT 0,
    leaves_qty               NUMERIC(20,6) GENERATED ALWAYS AS (quantity - filled_qty) STORED,

    -- timestamps
    tif_expire_at            TIMESTAMPTZ,
    effective_at             TIMESTAMPTZ,
    last_update_at          TIMESTAMPTZ DEFAULT now(),

    -- risk / compliance
    risk_score               NUMERIC(10,4),
    risk_reason              TEXT,
    risk_approver_id         UUID,

    -- cross-DB linkage to uisce rebalancing (independent — no FK)
    external_proposed_trade_id  TEXT,   -- links to proposed_trades.id in central uisce DB
    source_workflow_id       TEXT,       -- workflow that originated this order

    -- book-building / auction
    is_auction_only         BOOLEAN     DEFAULT false,
    auction_start           TIMESTAMPTZ,
    auction_end             TIMESTAMPTZ,

    -- metadata
    created_by               VARCHAR(100),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                  INTEGER     NOT NULL DEFAULT 1,

    CONSTRAINT uq_orders_client_order_id UNIQUE (tenant_id, client_order_id),
    CONSTRAINT chk_orders_filled_qty    CHECK (filled_qty <= quantity AND filled_qty >= 0)
);

CREATE INDEX idx_orders_tenant          ON oms.orders (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_orders_portfolio       ON oms.orders (portfolio_id);
CREATE INDEX idx_orders_account         ON oms.orders (account_id);
CREATE INDEX idx_orders_security        ON oms.orders (security_id);
CREATE INDEX idx_orders_venue           ON oms.orders (venue_id) WHERE venue_id IS NOT NULL;
CREATE INDEX idx_orders_status         ON oms.orders (status_id);
CREATE INDEX idx_orders_created         ON oms.orders (tenant_id, created_at DESC);
CREATE INDEX idx_orders_client_oid      ON oms.orders (tenant_id, client_order_id);
CREATE INDEX idx_orders_external_prop  ON oms.orders (tenant_id, external_proposed_trade_id) WHERE external_proposed_trade_id IS NOT NULL;
CREATE INDEX idx_orders_portfolio_status ON oms.orders (portfolio_id, status_id);

-- --------------------------------------------------------------------------
-- oms.order_slice
-- Child orders generated by algos, slicers, or order-management systems.
-- A slice belongs to exactly one parent order.
-- --------------------------------------------------------------------------
CREATE TABLE oms.order_slice (
    id                        UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id                 UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    parent_order_id           UUID        NOT NULL REFERENCES oms.orders(id),

    venue_id                  UUID        REFERENCES mds.venue(id),
    venue_order_id            VARCHAR(100),
    venue_slice_id            VARCHAR(100),   -- venue's internal slice ID

    algo_strategy             VARCHAR(50),    -- 'TWAP','VWAP','POV','IS','ArrivalPrice'
    routing_venue_id         UUID        REFERENCES mds.venue(id),  -- actual routed venue

    quantity                  NUMERIC(20,6) NOT NULL,
    limit_price               NUMERIC(20,8),
    filled_qty                NUMERIC(20,6) DEFAULT 0,
    avg_fill_price            NUMERIC(20,8) DEFAULT 0,
    leaves_qty                NUMERIC(20,6) GENERATED ALWAYS AS (quantity - filled_qty) STORED,

    status_id                 INTEGER,
    algo_slice_params         JSONB       DEFAULT '{}',

    effective_at              TIMESTAMPTZ,
    expire_at                 TIMESTAMPTZ,

    created_by                VARCHAR(100),
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                   INTEGER     NOT NULL DEFAULT 1,

    CONSTRAINT uq_slice_venue UNIQUE (tenant_id, venue_order_id)
);

CREATE INDEX idx_slice_parent          ON oms.order_slice (parent_order_id);
CREATE INDEX idx_slice_venue           ON oms.order_slice (venue_id) WHERE venue_id IS NOT NULL;
CREATE INDEX idx_slice_status          ON oms.order_slice (status_id);
CREATE INDEX idx_slice_tenant          ON oms.order_slice (tenant_id);
CREATE UNIQUE INDEX idx_slice_venue_oid_uniq ON oms.order_slice (tenant_id, venue_order_id) WHERE venue_order_id IS NOT NULL;

-- --------------------------------------------------------------------------
-- oms.order_link
-- Explicit parent↔child relationships (SLICE_OF, REPLACES, HEDGED_BY, PAIR_OF, LEG, CLONE)
-- --------------------------------------------------------------------------
CREATE TABLE oms.order_link (
    id                      UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id               UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    link_type_id            INTEGER     NOT NULL REFERENCES ref.order_link_type(id),

    parent_order_id         UUID        NOT NULL REFERENCES oms.orders(id),
    child_order_id          UUID        NOT NULL REFERENCES oms.orders(id),

    ratio_numerator         NUMERIC(18,8) DEFAULT 1,
    ratio_denominator       NUMERIC(18,8) DEFAULT 1,

    is_active               BOOLEAN     DEFAULT true,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_order_link_pair UNIQUE (parent_order_id, child_order_id, link_type_id),
    CONSTRAINT chk_order_link_diff CHECK (parent_order_id != child_order_id)
);

CREATE INDEX idx_order_link_parent  ON oms.order_link (parent_order_id);
CREATE INDEX idx_order_link_child   ON oms.order_link (child_order_id);
CREATE INDEX idx_order_link_type   ON oms.order_link (link_type_id);

-- Trigger to default status_id on orders / order_slice if not supplied
CREATE OR REPLACE FUNCTION oms.default_order_status()
RETURNS TRIGGER AS $$
DECLARE
    limit_order_codes TEXT[] := ARRAY['LIMIT','STOP_LIMIT','LOC','LOO','HYBRID'];
    stop_order_codes  TEXT[] := ARRAY['STOP','STOP_LIMIT'];
    ot_code TEXT;
BEGIN
    IF TG_TABLE_NAME = 'orders' THEN
        IF NEW.status_id IS NULL THEN
            SELECT id INTO NEW.status_id FROM ref.order_status WHERE code = 'NEW';
        END IF;
        -- Validate limit_price: must be set for limit-type orders
        IF NEW.limit_price IS NOT NULL THEN
            SELECT code INTO ot_code FROM ref.order_type WHERE id = NEW.order_type_id;
            IF ot_code IS NULL OR ot_code != ANY(limit_order_codes) THEN
                RAISE EXCEPTION 'limit_price requires limit-type order_type (got %)', ot_code
                    USING ERRCODE = 'check_violation';
            END IF;
        END IF;
        -- Validate stop_price: must be set for stop-type orders
        IF NEW.stop_price IS NOT NULL THEN
            SELECT code INTO ot_code FROM ref.order_type WHERE id = NEW.order_type_id;
            IF ot_code IS NULL OR ot_code != ANY(stop_order_codes) THEN
                RAISE EXCEPTION 'stop_price requires stop-type order_type (got %)', ot_code
                    USING ERRCODE = 'check_violation';
            END IF;
        END IF;
    ELSIF TG_TABLE_NAME = 'order_slice' THEN
        IF NEW.status_id IS NULL THEN
            SELECT id INTO NEW.status_id FROM ref.order_status WHERE code = 'WORKING';
        END IF;
    ELSIF TG_TABLE_NAME = 'allocation' THEN
        IF NEW.status_id IS NULL THEN
            SELECT id INTO NEW.status_id FROM ref.allocation_status WHERE code = 'PENDING';
        END IF;
    ELSIF TG_TABLE_NAME = 'settlement' THEN
        IF NEW.status_id IS NULL THEN
            SELECT id INTO NEW.status_id FROM ref.settlement_status WHERE code = 'PENDING';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_default_status
    BEFORE INSERT ON oms.orders
    FOR EACH ROW EXECUTE FUNCTION oms.default_order_status();

CREATE TRIGGER trg_order_slice_default_status
    BEFORE INSERT ON oms.order_slice
    FOR EACH ROW EXECUTE FUNCTION oms.default_order_status();

COMMIT;
