ALTER TABLE public.users ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role VARCHAR(50); -- e.g. 'admin', 'steward'
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS organization VARCHAR(255);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_core_admin BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS salt VARCHAR(255);
