package migrations

import (
	"context"
	"database/sql"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/stretchr/testify/require"
)

// These guard the generated candidate tenant schema (db/tenant_migrations/_candidates/crims). The files are
// generated by scripts/gen-tenant-ddl.py and must never be edited by hand, so every property the generator
// promises is asserted here, on the files themselves, with no database needed.

const candidateDir = "../../db/tenant_migrations/_candidates/crims"

func readCandidate(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(candidateDir, name))
	require.NoError(t, err)
	return string(b)
}

func matches(re, s string) int { return len(regexp.MustCompile(re).FindAllString(s, -1)) }

// The gold-copy tenant's CRIMS datasource declares these schemas, and this is the order they are applied in.
var candidateFiles = []string{"01_ref.up.sql", "02_vend.up.sql", "03_wlth.up.sql", "04_cash_flow.up.sql", "05_orm.up.sql", "06_mdm.up.sql"}

func candidateSchema(f string) string {
	return strings.TrimSuffix(strings.SplitN(f, "_", 2)[1], ".up.sql")
}

func TestCandidateDDL_IsGeneratedSchemaOnlyAndFreeOfRowLevelSecurity(t *testing.T) {
	for _, f := range candidateFiles {
		s := readCandidate(t, f)
		require.True(t, strings.HasPrefix(s, "-- Generated by scripts/gen-tenant-ddl.py"), "%s must say it is generated", f)
		require.Zero(t, matches(`(?i)ROW LEVEL SECURITY`, s), "%s: a tenant database has no RLS (ADR-042)", f)
		require.Zero(t, matches(`(?m)^CREATE POLICY`, s), f)
		require.Zero(t, matches(`(?m)^\\`, s), "%s: psql meta-commands are not SQL", f)
		require.Zero(t, matches(`(?m)^(INSERT INTO|COPY) `, s), "%s: schema only, no data", f)
		require.Zero(t, matches(`(?m)^CREATE (OWNER|ROLE|USER)|OWNER TO|GRANT |REVOKE `, s), "%s: no ownership or grants", f)
	}
}

func TestCandidateDDL_TableCountsPerSchema(t *testing.T) {
	want := map[string]int{"ref": 0, "vend": 0, "wlth": 0, "cash_flow": 1, "orm": 80, "mdm": 441}
	for _, f := range candidateFiles {
		sc := candidateSchema(f)
		require.Equal(t, want[sc], matches(`(?m)^CREATE TABLE `+sc+`\.`, readCandidate(t, f)), sc)
		require.Equal(t, 1, matches(`(?m)^CREATE SCHEMA IF NOT EXISTS `+sc+`;`, readCandidate(t, f)), "each file creates exactly its own schema")
	}
}

// Every file may refer only to its own schema and to schemas applied before it, except that mdm and orm refer
// to each other, so the reference from orm into mdm lives in the mdm file.
func TestCandidateDDL_NoFileReferencesASchemaAppliedAfterIt(t *testing.T) {
	rank := map[string]int{}
	for i, f := range candidateFiles {
		rank[candidateSchema(f)] = i
	}
	for _, f := range candidateFiles {
		s := readCandidate(t, f)
		for _, m := range regexp.MustCompile(`REFERENCES ([a-z_]+)\.`).FindAllStringSubmatch(s, -1) {
			ref, ok := rank[m[1]]
			require.True(t, ok, "%s references %s, which is not part of the template", f, m[1])
			require.LessOrEqual(t, ref, rank[candidateSchema(f)], "%s references %s, which is applied after it", f, m[1])
		}
	}
	orm := readCandidate(t, "05_orm.up.sql")
	require.Zero(t, matches(`REFERENCES mdm\.`, orm), "orm is applied before mdm exists")
	require.Equal(t, 1, matches(`REFERENCES cash_flow\.settlement`, orm), "the cash_flow link is part of the template")
	require.Greater(t, matches(`REFERENCES orm\.`, readCandidate(t, "06_mdm.up.sql")), 0)
	require.Equal(t, 1, matches(`(?m)^ALTER TABLE ONLY orm\.account\n\s+ADD CONSTRAINT \w+ FOREIGN KEY \(party_id\) REFERENCES mdm\.party\(id\);`, readCandidate(t, "06_mdm.up.sql")),
		"the orm.account -> mdm.party link is added at the end of the mdm file")
}

func TestCandidateDDL_TheOnlyExtensionIsUuidOssp(t *testing.T) {
	all := ""
	for _, f := range candidateFiles {
		all += readCandidate(t, f)
	}
	require.Equal(t, 1, matches(`(?m)^CREATE EXTENSION`, all))
	require.Contains(t, readCandidate(t, "01_ref.up.sql"), `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`)
	require.Zero(t, matches(`(?i)\b(ltree|citext|vector\()`, all), "no other extension type is used")
}

// The candidate directory must never be selectable as an app.
func TestCandidateDirectoryCannotBeAnApp(t *testing.T) {
	require.False(t, appName.MatchString("_candidates"))
	require.False(t, appName.MatchString("crims"+"/orm"))
}

// Optional, against a real server: apply both files to an empty database and check what came out.
// TENANT_DDL_TEST_ADMIN_DSN must be a superuser-or-createdb DSN to a maintenance database; the test creates and
// drops its own database.
func TestCandidateDDL_AppliesToAnEmptyDatabase(t *testing.T) {
	dsn := os.Getenv("TENANT_DDL_TEST_ADMIN_DSN")
	if dsn == "" {
		t.Skip("TENANT_DDL_TEST_ADMIN_DSN not set")
	}
	ctx := context.Background()
	admin, err := sql.Open("pgx", dsn)
	require.NoError(t, err)
	name := "tenant_ddl_candidate_test"
	_, _ = admin.ExecContext(ctx, `DROP DATABASE IF EXISTS `+name)
	_, err = admin.ExecContext(ctx, `CREATE DATABASE `+name)
	require.NoError(t, err)
	// Registered before the connection to the new database, so it runs after that one is closed (cleanups run
	// last-in first-out), and it closes admin itself: a deferred admin.Close would run before it and make the drop fail.
	t.Cleanup(func() {
		_, _ = admin.Exec(`DROP DATABASE IF EXISTS ` + name)
		admin.Close()
	})

	u, err := url.Parse(dsn)
	require.NoError(t, err, "TENANT_DDL_TEST_ADMIN_DSN must be a postgres:// URL")
	u.Path = "/" + name
	tdsn := u.String()
	db, err := sql.Open("pgx", tdsn)
	require.NoError(t, err)
	t.Cleanup(func() { db.Close() })
	for _, f := range candidateFiles {
		tx, err := db.BeginTx(ctx, nil)
		require.NoError(t, err)
		_, err = tx.ExecContext(ctx, readCandidate(t, f))
		require.NoError(t, err, "applying %s", f)
		require.NoError(t, tx.Commit())
	}
	var orm, mdm, cf, rls int
	require.NoError(t, db.QueryRow(`SELECT count(*) FILTER (WHERE relnamespace='orm'::regnamespace), count(*) FILTER (WHERE relnamespace='mdm'::regnamespace), count(*) FILTER (WHERE relnamespace='cash_flow'::regnamespace) FROM pg_class WHERE relkind IN ('r','p')`).Scan(&orm, &mdm, &cf))
	require.Equal(t, 80, orm, "78 ordinary tables (partitions included) and 2 partitioned parents")
	require.Equal(t, 441, mdm)
	require.Equal(t, 1, cf)
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM pg_class WHERE relrowsecurity AND relnamespace IN ('orm'::regnamespace,'mdm'::regnamespace)`).Scan(&rls))
	require.Zero(t, rls)
}
