package migrations

import (
	"context"
	"database/sql"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/stretchr/testify/require"
)

// These guard the generated candidate tenant schema (db/tenant_migrations/_candidates/crims). The files are
// generated by scripts/gen-tenant-ddl.py and must never be edited by hand, so every property the generator
// promises is asserted here, on the files themselves, with no database needed.

const candidateDir = "../../db/tenant_migrations/_candidates/crims"

func readCandidate(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(candidateDir, name))
	require.NoError(t, err)
	return string(b)
}

func matches(re, s string) int { return len(regexp.MustCompile(re).FindAllString(s, -1)) }

func TestCandidateDDL_IsGeneratedSchemaOnlyAndFreeOfRowLevelSecurity(t *testing.T) {
	for _, f := range []string{"orm.up.sql", "mdm.up.sql"} {
		s := readCandidate(t, f)
		require.True(t, strings.HasPrefix(s, "-- Generated by scripts/gen-tenant-ddl.py"), "%s must say it is generated", f)
		require.Zero(t, matches(`(?i)ROW LEVEL SECURITY`, s), "%s: a tenant database has no RLS (ADR-042)", f)
		require.Zero(t, matches(`(?m)^CREATE POLICY`, s), f)
		require.Zero(t, matches(`(?m)^\\`, s), "%s: psql meta-commands are not SQL", f)
		require.Zero(t, matches(`(?m)^(INSERT INTO|COPY) `, s), "%s: schema only, no data", f)
		require.Zero(t, matches(`cash_flow\.`, s), "%s: cash_flow is not part of a tenant database", f)
		require.Zero(t, matches(`(?m)^CREATE (OWNER|ROLE|USER)|OWNER TO|GRANT |REVOKE `, s), "%s: no ownership or grants", f)
	}
}

func TestCandidateDDL_TableCounts(t *testing.T) {
	require.Equal(t, 80, matches(`(?m)^CREATE TABLE orm\.`, readCandidate(t, "orm.up.sql")))
	require.Equal(t, 441, matches(`(?m)^CREATE TABLE mdm\.`, readCandidate(t, "mdm.up.sql")))
}

// orm is applied first, so it must never refer to mdm; the reference back is added at the end of mdm.
func TestCandidateDDL_OrmNeverReferencesMdm_AndMdmCreatesItsOwnSchema(t *testing.T) {
	orm, mdm := readCandidate(t, "orm.up.sql"), readCandidate(t, "mdm.up.sql")
	require.Zero(t, matches(`REFERENCES mdm\.`, orm), "orm is applied before mdm exists")
	require.Zero(t, matches(`(?m)^CREATE SCHEMA IF NOT EXISTS mdm;`, orm))
	require.Equal(t, 1, matches(`(?m)^CREATE SCHEMA IF NOT EXISTS mdm;`, mdm))
	require.Equal(t, 1, matches(`(?m)^CREATE SCHEMA IF NOT EXISTS orm;`, orm))
	require.Zero(t, matches(`(?m)^CREATE SCHEMA IF NOT EXISTS orm;`, mdm))
	require.Greater(t, matches(`REFERENCES orm\.`, mdm), 0, "mdm refers to orm")
}

func TestCandidateDDL_TheOnlyExtensionIsUuidOssp(t *testing.T) {
	orm, mdm := readCandidate(t, "orm.up.sql"), readCandidate(t, "mdm.up.sql")
	require.Equal(t, 1, matches(`(?m)^CREATE EXTENSION`, orm))
	require.Contains(t, orm, `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`)
	require.Zero(t, matches(`(?i)\b(ltree|citext|vector\()`, orm+mdm), "no other extension type is used")
}

// The candidate directory must never be selectable as an app.
func TestCandidateDirectoryCannotBeAnApp(t *testing.T) {
	require.False(t, appName.MatchString("_candidates"))
	require.False(t, appName.MatchString("crims"+"/orm"))
}

// Optional, against a real server: apply both files to an empty database and check what came out.
// TENANT_DDL_TEST_ADMIN_DSN must be a superuser-or-createdb DSN to a maintenance database; the test creates and
// drops its own database.
func TestCandidateDDL_AppliesToAnEmptyDatabase(t *testing.T) {
	dsn := os.Getenv("TENANT_DDL_TEST_ADMIN_DSN")
	if dsn == "" {
		t.Skip("TENANT_DDL_TEST_ADMIN_DSN not set")
	}
	ctx := context.Background()
	admin, err := sql.Open("pgx", dsn)
	require.NoError(t, err)
	name := "tenant_ddl_candidate_test"
	_, _ = admin.ExecContext(ctx, `DROP DATABASE IF EXISTS `+name)
	_, err = admin.ExecContext(ctx, `CREATE DATABASE `+name)
	require.NoError(t, err)
	// Registered before the connection to the new database, so it runs after that one is closed (cleanups run
	// last-in first-out), and it closes admin itself: a deferred admin.Close would run before it and make the drop fail.
	t.Cleanup(func() {
		_, _ = admin.Exec(`DROP DATABASE IF EXISTS ` + name)
		admin.Close()
	})

	u, err := url.Parse(dsn)
	require.NoError(t, err, "TENANT_DDL_TEST_ADMIN_DSN must be a postgres:// URL")
	u.Path = "/" + name
	tdsn := u.String()
	db, err := sql.Open("pgx", tdsn)
	require.NoError(t, err)
	t.Cleanup(func() { db.Close() })
	for _, f := range []string{"orm.up.sql", "mdm.up.sql"} {
		tx, err := db.BeginTx(ctx, nil)
		require.NoError(t, err)
		_, err = tx.ExecContext(ctx, readCandidate(t, f))
		require.NoError(t, err, "applying %s", f)
		require.NoError(t, tx.Commit())
	}
	var orm, mdm, rls int
	require.NoError(t, db.QueryRow(`SELECT count(*) FILTER (WHERE relnamespace='orm'::regnamespace), count(*) FILTER (WHERE relnamespace='mdm'::regnamespace) FROM pg_class WHERE relkind IN ('r','p') AND relnamespace IN ('orm'::regnamespace,'mdm'::regnamespace)`).Scan(&orm, &mdm))
	require.Equal(t, 80, orm, "78 ordinary tables (partitions included) and 2 partitioned parents")
	require.Equal(t, 441, mdm)
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM pg_class WHERE relrowsecurity AND relnamespace IN ('orm'::regnamespace,'mdm'::regnamespace)`).Scan(&rls))
	require.Zero(t, rls)
}
