package api

import (
	"github.com/hondyman/semlayer/libs/jwt-middleware"
)
package api






































































































































































































































































}	})		"error": message,	h.respondJSON(w, statusCode, map[string]string{func (h *Handler) respondError(w http.ResponseWriter, statusCode int, message string) {}	json.NewEncoder(w).Encode(data)	w.WriteHeader(statusCode)	w.Header().Set("Content-Type", "application/json")func (h *Handler) respondJSON(w http.ResponseWriter, statusCode int, data interface{}) {// ============================================================================// Helper Methods// ============================================================================}	h.respondJSON(w, http.StatusOK, metrics)	}		return		h.respondError(w, http.StatusInternalServerError, fmt.Sprintf("calculation failed: %v", err))	if err != nil {	metrics, err := h.svc.GetHealthMetrics(ctx, tenantID)	// Calculate	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid tenant ID: %v", err))	if err != nil {	tenantID, err := uuid.Parse(tenantIDStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing X-Tenant-ID header")	if tenantIDStr == "" {	tenantIDStr := jwtmiddleware.GetClaimsFromContext(r).TenantID	// Extract tenant ID	ctx := r.Context()func (h *Handler) GetHealthMetrics(w http.ResponseWriter, r *http.Request) {// GetHealthMetrics handles GET /api/v1/mdm/calendar/health}	h.respondJSON(w, http.StatusOK, lineage)	}		return		h.respondError(w, http.StatusInternalServerError, fmt.Sprintf("fetch failed: %v", err))	if err != nil {	lineage, err := h.svc.GetLineageForRecord(ctx, tenantID, goldenID)	// Fetch	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid golden record ID: %v", err))	if err != nil {	goldenID, err := uuid.Parse(goldenIDStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing golden record ID")	if goldenIDStr == "" {	goldenIDStr := r.PathValue("id")	// Extract golden record ID from path	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid tenant ID: %v", err))	if err != nil {	tenantID, err := uuid.Parse(tenantIDStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing X-Tenant-ID header")	if tenantIDStr == "" {	tenantIDStr := jwtmiddleware.GetClaimsFromContext(r).TenantID	// Extract tenant ID	ctx := r.Context()func (h *Handler) GetLineage(w http.ResponseWriter, r *http.Request) {// GetLineage handles GET /api/v1/mdm/calendar/lineage/:id}	})		"is_business_day":   isBusinessDay,		"exchange":          exchange,		"region":            region,		"date":              date.Format("2006-01-02"),	h.respondJSON(w, http.StatusOK, map[string]interface{}{	}		return		h.respondError(w, http.StatusInternalServerError, fmt.Sprintf("check failed: %v", err))	if err != nil {	isBusinessDay, err := h.svc.IsBusinessDay(ctx, tenantID, date, region, exchangePtr)	// Check	}		exchangePtr = &exchange	if exchange != "" {	exchangePtr := (*string)(nil)	exchange := r.URL.Query().Get("exchange")	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid date format: %v", err))	if err != nil {	date, err := time.Parse("2006-01-02", dateStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing required query parameters: date, region")	if dateStr == "" || region == "" {	region := r.URL.Query().Get("region")	dateStr := r.URL.Query().Get("date")	// Parse query parameters	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid tenant ID: %v", err))	if err != nil {	tenantID, err := uuid.Parse(tenantIDStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing X-Tenant-ID header")	if tenantIDStr == "" {	tenantIDStr := jwtmiddleware.GetClaimsFromContext(r).TenantID	// Extract tenant ID	ctx := r.Context()func (h *Handler) IsBusinessDay(w http.ResponseWriter, r *http.Request) {// IsBusinessDay handles GET /api/v1/mdm/calendar/is-business-day}	h.respondJSON(w, http.StatusOK, response)	}		return		h.respondError(w, http.StatusInternalServerError, fmt.Sprintf("query failed: %v", err))	if err != nil {	response, err := h.svc.GetGoldenCalendar(ctx, tenantID, req)	// Fetch	}		req.Exchange = &exchange	if exchange != "" {	}		Exchange:  nil,		Region:    region,		EndDate:   endDate,		StartDate: startDate,	req := &domain.GetGoldenCalendarRequest{	// Build request	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid end_date format: %v", err))	if err != nil {	endDate, err := time.Parse("2006-01-02", endDateStr)	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid start_date format: %v", err))	if err != nil {	startDate, err := time.Parse("2006-01-02", startDateStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing required query parameters: start_date, end_date, region")	if startDateStr == "" || endDateStr == "" || region == "" {	exchange := r.URL.Query().Get("exchange")	region := r.URL.Query().Get("region")	endDateStr := r.URL.Query().Get("end_date")	startDateStr := r.URL.Query().Get("start_date")	// Parse query parameters	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid tenant ID: %v", err))	if err != nil {	tenantID, err := uuid.Parse(tenantIDStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing X-Tenant-ID header")	if tenantIDStr == "" {	tenantIDStr := jwtmiddleware.GetClaimsFromContext(r).TenantID	// Extract tenant ID	ctx := r.Context()func (h *Handler) GetGoldenCalendar(w http.ResponseWriter, r *http.Request) {// GetGoldenCalendar handles GET /api/v1/mdm/calendar/golden}	})		"ingested_at":       time.Now(),		"count":             len(goldenRecordIDs),		"golden_record_ids": goldenRecordIDs,	h.respondJSON(w, http.StatusAccepted, map[string]interface{}{	}		return		h.respondError(w, http.StatusInternalServerError, fmt.Sprintf("ingestion failed: %v", err))	if err != nil {	goldenRecordIDs, err := h.svc.IngestSource(ctx, tenantID, &req)	// Ingest	defer r.Body.Close()	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req domain.IngestRequest	// Parse request	}		return		h.respondError(w, http.StatusBadRequest, fmt.Sprintf("invalid tenant ID: %v", err))	if err != nil {	tenantID, err := uuid.Parse(tenantIDStr)	}		return		h.respondError(w, http.StatusBadRequest, "missing X-Tenant-ID header")	if tenantIDStr == "" {	tenantIDStr := jwtmiddleware.GetClaimsFromContext(r).TenantID	// Extract tenant ID from header	ctx := r.Context()func (h *Handler) IngestCalendarData(w http.ResponseWriter, r *http.Request) {// IngestCalendarData handles POST /api/v1/mdm/calendar/ingest}	}		logger: logger,		svc:    svc,	return &Handler{func NewHandler(svc *service.CalendarIngestionService, logger *zap.Logger) *Handler {// NewHandler creates a new API handler}	logger *zap.Logger	svc    *service.CalendarIngestionServicetype Handler struct {// Handler manages HTTP APIendpoints)	"go.uber.org/zap"	"github.com/hondyman/semlayer/mdm-service/internal/service"	"github.com/hondyman/semlayer/mdm-service/internal/domain"	"github.com/google/uuid"	"time"	"net/http"	"fmt"	"encoding/json"import (