import { useQuery } from '@tanstack/react-query';
import { useTenant } from '../../../contexts/TenantContext';
import apiClient from '../../../utils/apiClient';
import { devDebug } from '../../../utils/devLogger';
import type { CatalogEdge, CatalogNode } from '../../../api/glossary';

export type EntityType = 'business_term' | 'semantic_term' | 'business_object';

/**
 * Raw shape returned by `/api/glossary/node-graph?node_id=...` (terms).
 */
export interface EntityGraphResponse {
  node?: CatalogNode | Record<string, any>;
  edges?: CatalogEdge[];
  connected_nodes?: any[];
  nodes?: any[];
}

/**
 * Raw shape returned by `/api/business-objects/:id/relationships` (BOs).
 * Different shape — see backend/internal/metadata/businessobject_service.go.
 */
export interface BusinessObjectRelationships {
  relatedObjects?: Array<{
    relatedObjectName?: string;
    relatedObjectId?: string;
    id?: string;
    related_object_id?: string;
    relationshipType?: string;
    relationship_type?: string;
    description?: string;
  }>;
  semanticFields?: Array<{
    fieldName?: string;
    semanticTermName?: string;
    edgeTypeName?: string;
    edge_type_name?: string;
    semanticTermId?: string;
    semantic_term_id?: string;
  }>;
  availableTerms?: any[];
}

/**
 * Canonical, normalized shape every consumer can rely on regardless of
 * which backend endpoint the data came from.
 */
export interface NormalizedRelationships {
  edges: CatalogEdge[];
  nodes: CatalogNode[];
  source: 'node-graph' | 'business-object' | 'empty';
}

/**
 * Deterministic ID for synthetic edges generated by the normalizer.
 * Uses a separator that won't appear in real UUIDs so collisions are impossible.
 */
function hashSyntheticId(...parts: string[]): string {
  return ['synthetic', ...parts.filter(Boolean)].join('::');
}

function normalizeGraphResponse(res: EntityGraphResponse | undefined | null): NormalizedRelationships {
  if (!res) return { edges: [], nodes: [], source: 'empty' };
  const nodes = (res.connected_nodes ?? res.nodes ?? []) as CatalogNode[];
  const edges = Array.isArray(res.edges) ? res.edges : [];
  return { edges, nodes, source: 'node-graph' };
}

function normalizeBOResponse(
  boId: string,
  res: BusinessObjectRelationships | undefined | null
): NormalizedRelationships {
  if (!res) return { edges: [], nodes: [], source: 'empty' };

  const focalNode: CatalogNode = { id: boId, node_name: boId, catalog_type_name: 'business_object', created_at: '' };
  const nodes: CatalogNode[] = [focalNode];
  const edges: CatalogEdge[] = [];

  const pushNode = (id: string, name: string, typeName: string) => {
    if (!nodes.some((n) => n.id === id)) {
      nodes.push({ id, node_name: name, catalog_type_name: typeName, created_at: '' });
    }
  };

  for (const r of res.relatedObjects ?? []) {
    const remoteId = r.relatedObjectId ?? r.id ?? r.related_object_id;
    if (!remoteId) continue;
    const relType = r.relationshipType ?? r.relationship_type ?? 'BO_RELATIONSHIP';
    pushNode(remoteId, r.relatedObjectName ?? remoteId, 'business_object');
    edges.push({
      id: hashSyntheticId('bo-rel', boId, remoteId, relType),
      subject_node_id: boId,
      object_node_id: remoteId,
      source_node_id: boId,
      target_node_id: remoteId,
      edge_type_name: relType,
      relationship_type: relType,
      predicate: relType,
      description: r.description ?? '',
    });
  }

  for (const f of res.semanticFields ?? []) {
    const semId = f.semanticTermId ?? f.semantic_term_id ?? f.semanticTermName;
    if (!semId) continue;
    const edgeType = f.edgeTypeName ?? f.edge_type_name ?? 'HAS_BUSINESS_TERM';
    pushNode(semId, f.semanticTermName ?? semId, 'semantic_term');
    edges.push({
      id: hashSyntheticId('bo-sem', boId, semId, edgeType),
      subject_node_id: boId,
      object_node_id: semId,
      source_node_id: boId,
      target_node_id: semId,
      edge_type_name: edgeType,
      relationship_type: edgeType,
      predicate: edgeType,
      description: '',
    });
  }

  return { edges, nodes, source: 'business-object' };
}

export interface UseEntityRelationshipsResult {
  data: NormalizedRelationships | undefined;
  isLoading: boolean;
  error: Error | null;
  refetch: () => void;
}

/**
 * Centralized hook that fetches the relationship graph for any catalog node.
 * Routes to the right endpoint by entityType, then normalizes the response
 * to a canonical CatalogEdge[] + CatalogNode[] shape.
 */
export function useEntityRelationships(
  entityType: EntityType,
  entityId: string | null | undefined,
  opts?: { enabled?: boolean }
): UseEntityRelationshipsResult {
  const { tenant } = useTenant();
  const tenantId = tenant?.id;
  const enabled =
    (opts?.enabled ?? true) && Boolean(entityId) && Boolean(tenantId);

  const query = useQuery({
    queryKey: ['entity-relationships', entityType, entityId, tenantId],
    queryFn: async (): Promise<NormalizedRelationships> => {
      if (!entityId || !tenantId) {
        throw new Error('useEntityRelationships: entityId and tenantId are required');
      }

      if (entityType === 'business_object') {
        const url = `/api/business-objects/${encodeURIComponent(entityId)}/relationships`;
        devDebug('[useEntityRelationships] GET', url);
        const res = await apiClient<BusinessObjectRelationships>(url);
        return normalizeBOResponse(entityId, res);
      }

      const params = new URLSearchParams();
      params.append('node_id', entityId);
      params.append('tenant_id', tenantId);
      const url = `/api/glossary/node-graph?${params.toString()}`;
      devDebug('[useEntityRelationships] GET', url);
      const res = await apiClient<EntityGraphResponse>(url);
      return normalizeGraphResponse(res);
    },
    enabled,
    staleTime: 30_000,
  });

  return {
    data: query.data,
    isLoading: query.isLoading,
    error: query.error as Error | null,
    refetch: query.refetch,
  };
}
