name: E2E AMQP
on: [ push, pull_request ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Make e2e script executable
      run: chmod +x ./scripts/e2e_amqp.sh
    - name: Run E2E AMQP
      run: ./scripts/e2e_amqp.sh
